### ISSUE TITLE
Driver Name Exceeds OCI Max

### ISSUE THREAD

**Issue by jazzboME** [godror/godror#1]
I upgraded from goracle v2.24 to godror v0.0.1 and my code started to fail complaining about OCI_ATTR_DRIVER_NAME

Specifically trying to access the database results in
ORA-24960: the attribute  OCI_ATTR_DRIVER_NAME is greater than the maximum allowable length of 30

**To Reproduce**
```go
package main

import (
        "fmt"
        "database/sql"
        "log"

        _ "github.com/godror/godror"
)

const (
        dbname = "mydb"
        user   = "user"
        pass   = "pass"
)

func main() {
        db, err := sql.Open("godror", fmt.Sprintf("%s/%s@%s", user, pass, dbname))
        if err != nil {
                log.Fatal("Connect Error:\n" + err.Error())
        }
        if err = db.Ping(); err != nil {
                log.Fatal("Ping Error:\n" + err.Error())
        }
        defer db.Close()
        fmt.Println("Connected: ok")
}
```

Output:
`2019/12/13 19:47:51 Ping Error:
params=oracle://<sanitized>?connectionClass=GODROR&enableEvents=0&heterogeneousPool=0&poolIncrement=1&poolMaxSessions=1000&poolMinSessions=1&poolSessionMaxLifetime=1h0m0s&poolSessionTimeout=5m0s&poolWaitTimeout=30s&prelim=0&standaloneConnection=0&sysasm=0&sysdba=0&sysoper=0&timezone= extAuth=0: ORA-24960: the attribute  OCI_ATTR_DRIVER_NAME is greater than the maximum allowable length of 30`

I obviously removed some details of my system here and in the code.

**Your oracle client version**
12.1.0

**Your godror version**
v0.0.1

**Your go version**
go version go1.13.1 windows/amd64

**Your gcc version**
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

**Machine (please complete the following information):**
 - OS: Windows 10
 - Architecture 64 bit
 - Version: 1903

**Additional context**
https://docs.oracle.com/database/121/LNOCI/ociaahan.htm#LNOCI17759 seems to indicate that the 30 char limit is set by OCI.

I think this change is the cause of the problem: https://github.com/godror/godror/blob/446a29355d2967f04604e8e015a3343917860adf/drv.go#L90 

Not sure how you want to adjust the name, but if I shorten to just `"godror : " + Version` everything is groovy after that.

Also for reasons that aren't entirely clear to me, my Linux box didn't trigger this issue, it is using the 12.2 instantclient

**Comment by tgulacsi** [comment]
Thanks for the detailed bug report - I've fixed it in v0.9.1
