### ISSUE TITLE
How to use godror for logminer? It doesn't return any logmnr_contents query rows.

### ISSUE THREAD

**Issue by sagnol** [godror/godror#101]
**Describe the bug**
 It doesn't return any logmnr_contents query rows. `SELECT ... FROM v$logmnr_contents`

**To Reproduce**
```go
godror.ArraySize(1)
godror.FetchArraySize(1)
godror.FetchRowCount(1)

// already started logminer session with STARTSCN
sql := `SELECT ... 
FROM v$logmnr_contents 
WHERE 
    OPERATION_CODE IN (1, 2, 3, 5) 
    AND nvl(commit_scn, scn)>= 0
    AND (SEG_OWNER='TEST') `

prepared, err := l.db.Prepare(sql)
rows, err := prepared.Query(params...)
// cannot execute go code
if err != nil {
  // handle error
}

for rows.Next() {
   // scanning
}

```

**Expected behavior**
```go
for rows.Next() {
  // plz can scan rows when receive data
}
```

**Your oracle client version**
19.3 (instantclient version)
11g (database version)

**Your godror version**
0.20.0

**Your go version**
go 1.14

**Machine (please complete the following information):**
 - OS: MacOS

**Comment by tgulacsi** [comment]
What does `rows.Err()` say after the loop?
What if you 

    var n int
    err := QueryRowContext(ctx, `SELECT COUNT(0) FROM v$logmnr_contents`).Scan(&n)
    log.Println(n, err)

?

**Comment by sagnol** [comment]
doesn't logging.
```go
log.Println("before")
var n int
err := l.db.QueryRowContext(context.Background(), `SELECT COUNT(0) FROM v$logmnr_contents`).Scan(&n)
log.Println("After") // Logging is not working.
log.Println(n, err)
```

```
INFO[2020-09-23T08:37:27+09:00] logminer: start logminser session, SCN is 789549  SCN=789549
INFO[2020-09-23T08:37:27+09:00] Before     
```
end

**Comment by sagnol** [comment]
I got some errors while debugging. (But I'm not sure about the debugging point.)
```
dpiStmt_execute: ORA-01291: missing logfile
ORA-16241: Waiting for gap log file (thread# 1, sequence# 1)
```
It then ran INSERT, DELETE and UPDATE, but I didn't get anything from my application.

**Comment by tgulacsi** [comment]
Your logminer configuration is having issues.
First you have to fix that.
