### ISSUE TITLE
error： ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

### ISSUE THREAD

**Issue by FreshCoderM** [godror/godror#103]
This is code which connects oracle 

> `db, err := sql.Open("godror", `user="xxx" password="xxx" connectString="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=2xx.0x.x1.xxx)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=dlnxxx)))"
    poolSessionTimeout=42s 
    heterogeneousPool=false standaloneConnection=false`)`

**ORA-12514: TNS:listener does not currently know of service requested in connect descriptor**

**Comment by tgulacsi** [comment]
1. Please post text as text, not screenshot.
2. See https://godror.github.io/godror/doc/connection.html for the connection strings.

The `connectString` can be anything what OCI/ODPI-C understands (https://www.oracle.com/pls/topic/lookup?ctx=dblatest&id=GUID-B0437826-43C1-49EC-A94D-B650B6A4A6EE).

To test it, the easiest is to try that `sqlplus` can connect with that connection string.

**Comment by vgopher** [comment]
func dbConn(host string, port string, sid string, user string, password string) (*sql.DB, error) {
	conn, err := sql.Open("godror", "user="+user+" password="+password+
		" connectString="+host+":"+port+"/"+sid)
	if err != nil {
		return nil, err
	}
	return conn, nil
}
老兄看不到你的完整代码，不过你看下是不是这样的。

**Comment by FreshCoderM** [comment]
> func dbConn(host string, port string, sid string, user string, password string) (*sql.DB, error) {
> conn, err := sql.Open("godror", "user="+user+" password="+password+
> " connectString="+host+":"+port+"/"+sid)
> if err != nil {
> return nil, err
> }
> return conn, nil
> }
> 老兄看不到你的完整代码，不过你看下是不是这样的。

_**大哥！！我按照您的方法试着写了一下但是仍然报错，就是在 db.Ping()的时候报错**_
```
func dbConn(host string, port string, sid string, user string, password string) (*sql.DB, error) {
	conn, err := sql.Open("godror", "user="+user+" password="+password+
		" connectString="+host+":"+port+"/"+sid)
	if err != nil {
		return nil, err
	}
	return conn, nil
}

	db ,err = dbConn("远程ip地址","1521","xxx","xxx","12345678")
	beego.Info(db)
	beego.Info(err)
	//os.Setenv("NLS_LANG", "AMERICAN_AMERICA.AL32UTF8") //解决中文乱码
	if err := db.Ping(); err != nil {
		beego.Info(22)
		log.Fatal(err)
	}

```
**错误：ORA-12514: TNS:listener does not currently know of service requested in connect descriptor**

**Comment by vgopher** [comment]
建议你先用sqlplus命令行连接一下，看会不会有什么报错。

**Comment by sudarshan12s** [comment]
does it work from sqlplus?

is the service name matching with the one listed in v$services

SQL> select con_id, name from v$services order by 1;

or from the output of command for registered services with listener

lsnrctl services

**Comment by tgulacsi** [comment]
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor 

Is sth else. It means that there's a listener at host:port, but does not know about the sid.

**Comment by FreshCoderM** [comment]
> ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
> 
> Is sth else. It means that there's a listener at host:port, but does not know about the sid.


in  tnsnames.ora file i set sid dlnu10g
```
dlnu10g =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = 2xx.xx.xxxx )(PORT = 1521))
    (CONNECT_DATA =
     (SID =dlnu10g)
      (SERVER = DEDICATED)
    )
  )
```
but it doesn't work

**Comment by tgulacsi** [comment]
Your tnsnames.ora is only on client side, and defines only a "shortcut" or "alias": by using "dlnu10g" as the connectString, it translates to the specified `2xx.xx.xxxx:1521/dlnu10g`

So if it says the same, then it is the same: the database server's listener does not know about a "dlnu10g" service.
Try what @sudarshan12s suggested in https://github.com/godror/godror/issues/103#issuecomment-707592820 and check what's your service name.

**Comment by FreshCoderM** [comment]
> 您的tnsnames.ora仅在客户端，并且仅定义“快捷方式”或“别名”：通过使用“ dlnu10g”作为connectString，它将转换为指定的 `2xx.xx.xxxx:1521/dlnu10g`
> 
> 因此，如果说的相同，那么它是相同的：数据库服务器的侦听器不知道“ dlnu10g”服务。
> 尝试[＃103（注释）中](https://github.com/godror/godror/issues/103#issuecomment-707592820)建议的@ sudarshan12s，并检查您的服务名称是什么。[](https://github.com/godror/godror/issues/103#issuecomment-707592820)


i have solve this problem with this code
to set SID in connectString
```
db, err := sql.Open("godror", `user="jxxxxxx" password="xxxx" connectString="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=2xx.0xxxxxx)(PORT=1521)(SID=dlnu10g))(CONNECT_DATA=(SID=dlnu10g)))"
    poolSessionTimeout=42s
    heterogeneousPool=false standaloneConnection=false`)
```

**Comment by cjbj** [comment]
SIDs are _long_ obsolete and not the best, since ServiceNames let a lot of DB behaviors be configured, such as High Availability features.  Try and find the service name and use that.
