### ISSUE TITLE
Numbers are not godror.Number any more, strings instead, breaks compatibility

### ISSUE THREAD

**Issue by next-alfonsocantos** [godror/godror#106]
Hi!

We were using goracle.v2 to perform generic select statements designed in a declarative way, so we did not have information about the types at desing time, but at run time.

Because of that, out values were stored into an interface{} table, this way:

```
		rows, _ := conn.QueryContext(ctx, query)
		cols, _ := rows.Columns()
		valuePointers := make([]interface{}, len(cols))
		for i, _ := range valuePointers {
			valuePointers[i] = new(interface{})
		}
		for rows.Next() {
			if err := rows.Scan(valuePointers...); err != nil {
				return err
			}
			// convert value pointers, to the real valuePointers
			values := make([]interface{}, len(valuePointers))
			for i, _ := range valuePointers {
				values[i] = *valuePointers[i].(*interface{})
			}
			results = append(results, values)
		}
```

Then we serve the result as json, using this code to return NUMBERS as json numbers:

```
                                switch row[j].(type) {
				case bool, int, int64, int16, int8, int32, float32, float64, uint, uint64, uint16, uint8, uint32, goracle.Number:
					//// its a number
				case string:
					//// its a string, using godror v0.20 it is always a string
				default:
					span.Debugf("unknown object! %T", row[j])
				}
```

And that worked fine.

Now, we have updated to **godror**, and the same approach returns **all values always as strings** and we dont have a way to know if the columns in the database was defined as NUMBER or not.

Is there any way to do the same thing using godror?

Many thanks!!

**Comment by tgulacsi** [comment]
godror is simpler.
A more performant way is to check the column types with rows.ColumnTypes() once before the rows.Next() loop, and choose the destination type using that info.

So create an []interface{} slice and put the proper destination types in it, and another slice with pointers to those types. Then you can give this pointer-slice to Scan, and use the values from the first slice.

**Comment by next-alfonsocantos** [comment]
That make sense, many thanks for such a quick response.

**Comment by next-alfonsocantos** [comment]
It worked the way tgulacsi said!

Thanks!
