### ISSUE TITLE
Can't use Proxy Authentication without password

### ISSUE THREAD

**Issue by wwanderley** [godror/godror#108]
**Describe the bug**
I'm working in a project with N-tier authentication. The middle tier does not know the password of the proxy user.
Everything works as expected before godror v0.10.3.

**To Reproduce**
Add a new test case to z_heterogeneous_test.go
```go
//line 82
"proxyUser":       {In: godror.ContextWithUserPassw(ctx, proxyUser, proxyPassword, ""), Want: proxyUser},
"proxyUserNoPass": {In: godror.ContextWithUserPassw(ctx, proxyUser, "", ""), Want: proxyUser},
```

**Expected behavior**
Test PASS.

**Error output**

ORA-24419: Proxy sessions are not supported in this mode. 

```
TestHeterogeneousPoolIntegration/proxyUserNoPass: z_heterogeneous_test.go:81: user="test_proxyUserX" ConnectString="localhost:1521/xe" stats=busy=0 open=1 max=16 maxLifetime=5m0s timeout=1m0s waitTimeout=5s params={authMode:0 connectionClass:<nil> connectionClassLength:0 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:0 externalHandle:<nil> pool:0x7f91e8046eb0 tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-24419: Proxy sessions are not supported in this mode.
--- FAIL: TestHeterogeneousPoolIntegration (0.73s)
    --- PASS: TestHeterogeneousPoolIntegration/noContext (0.08s)
    --- PASS: TestHeterogeneousPoolIntegration/proxyUser (0.10s)
    --- FAIL: TestHeterogeneousPoolIntegration/proxyUserNoPass (0.00s)
```

**Your oracle client version**
19.3.0.0.0

**Your godror version**
v0.20.5

**Your go version**
1.14.3

**Your gcc version**
gcc version 10.2.0 (Debian 10.2.0-15)

**Machine (please complete the following information):**
 - OS: [Debian]
 - Architecture [x86_64]
 - Version: [10.2]

**Additional context**

**Comment by tgulacsi** [comment]
I'm not knowledgeable enough as an Oracle DBA - @cjbj, @anthony-tuininga  is it possible to use a heterogeneous session pool with external authentication? 
With external auth set, I get "DPI-1032: user name and password cannot be set when using external authentication" error when username/password is given.

Maybe only homogeneous pools can be used with external authentication, as that means all connections use the same username and auth data?

**Comment by anthony-tuininga** [comment]
@wwanderley, this [documentation](https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#connecting-using-proxy-authentication) is for cx_Oracle but should give you an idea of what you can do and what needs to be true.

If you can provide a standalone script that demonstrates the problem I can probably provide more applicable/pointed help. There are quite a few options that are available and I'm not sure which one you are attempting to use!

@tgulacsi, if you are using external authentication, you *must* use a heterogeneous session pool (when the pool is created). BUT, you can't use external authentication when acquiring a connection from that pool. Again, an example would be helpful. The example should acquire a connection from the pool at least twice. We built samples to demonstrate all of the possibilities for both cx_Oracle and node-oracledb, so they could be adjusted for godror. Let's see what @cjbj or @sudarshan12s says about that.

**Comment by wwanderley** [comment]
Thanks! I'll try to explain my scenario.

It's a legacy system with database accounts for all users (+10k accounts). All of the operations on the database must be executed with de correspondent account of the logged user. Exists one database superuser that can connect through any user:

```sql
ALTER USER mysuperuser GRANT CONNECT THROUGH user1;
ALTER USER mysuperuser GRANT CONNECT THROUGH user2....
```
Exists an heterogeneousPool for the 'mysuperuser':

```go
db, err := sql.Open("godror", "oracle://mysuperuser:secret@myserver:1521/db?heterogeneousPool=1")
```
A middleware that intercept all of the request, validate the logged user (jwt) and call godror.ContextWithUserPassw(ctx, loggedUser, "", ""). I don't no the password of the logged user.

```go
func handle(w http.ResponseWriter, r *http.Request) {
    ctx := r.Context()
    loggedUser := userFromContext(ctx)
    ctx = godror.ContextWithUserPassw(ctx, loggedUser, "", "") 
    doSomeDatabaseOperation(ctx, db)
    ...
}
```

**To reproduce**
Add a new test case to z_heterogeneous_test.go
```go
"proxyUserNoPass": {In: godror.ContextWithUserPassw(ctx, proxyUser, "", ""), Want: proxyUser},
```

Worked fine before godror v0.10.4

**Comment by cjbj** [comment]
I got around to publishing my 'notes': see https://blogs.oracle.com/opal/external-and-proxy-connection-syntax-examples-for-node-oracledb

@sudarshan12s is checking into godror

**Comment by sudarshan12s** [comment]
@wwanderley <https://github.com/wwanderley>,

Is your application handling multiple application users ; users, user1,
user2, ... to give access to same schema user mysuperuser or these multiple
users , user1, user2, ...
are having respective schemas. Is external authentication used by your
application ?



I am still working/reviewing on the changes to test other scenarios , looks
like patch is needed, shall update.  I modified test case to pass proxyuser
or appuser inside braces. we need to provide password of proxyuser, scott
in this case.


diff --git a/drv.go b/drv.go
index 2a28201..4240573 100644
--- a/drv.go
+++ b/drv.go
@@ -523,10 +523,6 @@ func (d *drv) getPool(P commonAndPoolParams)
(*connPool, error) {
                return nil, err
        }

-       if P.Heterogeneous {
-               P.Username = ""
-               P.Password.Reset()
-       }
        // determine key to use for pool
        poolKey := fmt.Sprintf("%s\t%s\t%d\t%d\t%d\t%s\t%s\t%s\t%t\t%t\t%t",
                P.Username, P.ConnectString, P.MinSessions, P.MaxSessions,
diff --git a/dsn/dsn.go b/dsn/dsn.go
index 7dc7221..396074c 100644
--- a/dsn/dsn.go
+++ b/dsn/dsn.go
@@ -242,6 +242,7 @@ func (P ConnectionParams) string(class, withPassword
bool) string {
        q.Add("standaloneConnection", B(P.StandaloneConnection))
        q.Add("enableEvents", B(P.EnableEvents))
        q.Add("heterogeneousPool", B(P.Heterogeneous))
+       q.Add("externalAuth", B(P.ExternalAuth))
        q.Add("prelim", B(P.IsPrelim))
        q.Add("poolWaitTimeout", P.WaitTimeout.String())
        q.Add("poolSessionMaxLifetime", P.MaxLifeTime.String())
@@ -378,6 +379,7 @@ func Parse(dataSourceName string) (ConnectionParams,
error) {

                {&P.EnableEvents, "enableEvents"},
                {&P.Heterogeneous, "heterogeneousPool"},
+               {&P.ExternalAuth, "externalAuth"},
                {&P.StandaloneConnection, "standaloneConnection"},
        } {
                s := q.Get(task.Key)

diff --git a/z_heterogeneous_test.go b/z_heterogeneous_test.go
index 53822e8..b55e767 100644
--- a/z_heterogeneous_test.go
+++ b/z_heterogeneous_test.go
@@ -66,18 +66,21 @@ func TestHeterogeneousPoolIntegration(t *testing.T) {

testHeterogeneousDB.ExecContext(testContext("HeterogeneousPoolIntegration-drop"),
"DROP USER "+proxyUser)
        }()

+       proxyuserwithbracket := "scott" + "[" + proxyUser + "]"
        for tName, tCase := range map[string]struct {
                In   context.Context
                Want string
        }{
-               "noContext": {In: ctx, Want: username},
-               "proxyUser": {In: godror.ContextWithUserPassw(ctx,
proxyUser, proxyPassword, ""), Want: proxyUser},
+               "noContext":       {In: ctx, Want: username},
+               "proxyUser":       {In: godror.ContextWithUserPassw(ctx,
proxyUser, proxyPassword, ""), Want: proxyUser},
+               "proxyUserNoPass": {In: godror.ContextWithUserPassw(ctx,
proxyuserwithbracket, "tiger", ""), Want: proxyUser},
        } {
                t.Run(tName, func(t *testing.T) {
                        var result string
                        if err =
testHeterogeneousDB.QueryRowContext(tCase.In, "SELECT user FROM
dual").Scan(&result); err != nil {
                                t.Fatal(err)
                        }
                        if !strings.EqualFold(tCase.Want, result) {
                                t.Errorf("%s: currentUser got %s, wanted
%s", tName, result, tCase.Want)
                        }

**Comment by wwanderley** [comment]
@sudarshan12s, just one schema for the entire application.

**Comment by sudarshan12s** [comment]
> Thanks! I'll try to explain my scenario.
> 
> It's a legacy system with database accounts for all users (+10k accounts). All of the operations on the database must be executed with de correspondent account of the logged user. Exists one database superuser that can connect through any user:
> 
> ```sql
> ALTER USER mysuperuser GRANT CONNECT THROUGH user1;
> ALTER USER mysuperuser GRANT CONNECT THROUGH user2....
> ```
> 
> Heterogeneous Pool for the 'mysuperuser':
> 
> ```go
> db, err := sql.Open("godror", "oracle://mysuperuser:secret@myserver:1521/db?heterogeneousPool=1")
> ```
> 
> A Function get logged user (jwt) and call godror.ContextWithUserPassw(ctx, loggedUser, "", ""). I don't know the logged user's password.
> 
> ```go
> func handle(w http.ResponseWriter, r *http.Request) {
>     loggedUser := userFromRequest(r)
>     ctx := godror.ContextWithUserPassw(r.Context(), loggedUser, "", "") 
>     doSomeDatabaseOperation(ctx, db)
>     ...
> }
> ```
> 
> **To reproduce**
> Add a new test case to z_heterogeneous_test.go
> 
> ```go
> "proxyUserNoPass": {In: godror.ContextWithUserPassw(ctx, proxyUser, "", ""), Want: proxyUser},
> ```
> 
> Worked fine before godror v0.10.4

I believe this is typo:
ALTER USER mysuperuser GRANT CONNECT THROUGH user1;
has to be 
ALTER USER  user1 GRANT CONNECT THROUGH mysuperuser;

**Comment by wwanderley** [comment]
Yes, that's a typo.

Thanks!
