### ISSUE TITLE
Implement NullTime

### ISSUE THREAD

**Issue by xhit** [godror/godror#11]
**Is your feature request related to a problem? Please describe.**
When a need to pass a date, timestamp, etc... from Oracle to other database, I need to check time.Time with `IsZero()` to pass nil to destination, but when Oracle date is `0001-01-01 00:00:00` in the table I need to pass the date but `IsZero()` is true and nil is assigned.

**Describe the solution you'd like**
Implementing NullTime can solve this.

**Describe alternatives you've considered**
IsZero() is a standard alternative but isn't perfect for all solutions like this.

Also, I saw that [this mssql driver](https://github.com/denisenkom/go-mssqldb/) can return nil when a column is NULL, but I think is better NullTime because this solution, although use your own solution I think can be better, need a lot of work and use NullTime is faster implementation.

**Comment by tgulacsi** [comment]
Can you try 089d2618862b4a4c0a0c3637dd315110acde0436 ?

You have to use godror.NullTime (maybe not - I don't know how type aliases work in Go 1.13),
if we want to keep the required version down to Go 1.11...

**Comment by xhit** [comment]
Tested.

I'm getting time.Time for DATE, TIMESTAMP, etc... instead NullTime.

Note that for NUMBER I get godror.Number and this is fine and I think that you proposal is return godror.NullTime. But doesn't work.

You can run this code for testing. The line with DEBUG comment is the important here.

```go
package main

import (
	"database/sql"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/godror/godror"
)

func main() {

	//connecto to Oracle
	db, err := connectORACLE("192.168.43.150", "XE", "system", "santiago", 1521)
	if err != nil {
		panic(err)
	}

	defer db.Close()

	//this table contains a column foreach Oracle datatype
	queryTypes := "select *from testtypes"

	/*
		CREATE TABLE TESTTYPES (
			A BFILE,
			B BINARY_DOUBLE,
			C BINARY_FLOAT,
			D BLOB,
			E CHAR(10),
			F CLOB,
			G DATE,
			H NUMBER(18 , 2),
			I FLOAT(126),
			J FLOAT(10),
			K NUMBER(38 , 0),
			L INTERVAL DAY TO SECOND(6),
			M INTERVAL YEAR TO MONTH,
			N LONG,
			P NCHAR(100),
			Q NCLOB,
			R NUMBER(18 , 2),
			S NUMBER(18 , 2),
			T NVARCHAR2(100),
			U RAW(100),
			V FLOAT(63),
			W NUMBER(38 , 0),
			X TIMESTAMP,
			Y TIMESTAMP WITH LOCAL TIME ZONE,
			Z TIMESTAMP WITH TIME ZONE,
			AA VARCHAR2(100),
			AB XMLTYPE
		);
	*/

	//get rows
	rows, err := db.Query(queryTypes)
	if err != nil {
		panic(err)
	}

	//get columns name
	colsName, err := rows.Columns()
	if err != nil {
		panic(err)
	}

	//get types of query columns
	types, err := rows.ColumnTypes()
	if err != nil {
		panic(err)
	}

	//total columns
	totalColumns := len(colsName)

	// create a slice of interface{}'s to represent each column,
	// and a second slice to contain pointers to each item in the columns slice
	columns := make([]interface{}, totalColumns)
	recordPointers := make([]interface{}, totalColumns)
	for i := range columns {
		recordPointers[i] = &columns[i]
	}

	//record destination
	record := make([]interface{}, totalColumns)

	for rows.Next() {

		// Scan the result into the record pointers...
		if err := rows.Scan(recordPointers...); err != nil {
			panic(err)
		}

		//Parse each field of recordPointers for get a custom field depending the type
		for idxCol := range recordPointers {
			record[idxCol] = oracleFieldParse(types[idxCol].DatabaseTypeName(), *recordPointers[idxCol].((*interface{})))
		}

		fmt.Println(record)

	}

}

//Parse each field
func oracleFieldParse(datatype string, field interface{}) interface{} {

	//DEBUG: print the type of field and datatype returned for the driver
	fmt.Printf("%T\t%s\n", field, datatype)

	if field != nil {
		switch field.(type) {
		case string:
			return field.(string)
		case godror.Number:
			return string(field.(godror.Number))
		case []uint8:
			switch datatype {
			case "LONG RAW":
				return hex.EncodeToString(field.([]uint8))
			default:
				return fmt.Sprintf("unsupported datatype %s", datatype)
			}
		case time.Time:
			/*in this case, time.Time is returned when IsZero() too.
			I think godror.NullTime need to be returned to know if Valid is true or false for return nil instead
			return a date parsed*/
			switch datatype {
			case "DATE":
				return field.(time.Time).Format("2006-01-02")
			case "TIMESTAMP":
				return field.(time.Time).Format("2006-01-02 15:04:05.000")
			case "TIMESTAMP WITH TIMEZONE":
				return field.(time.Time).Format("2006-01-02 15:04:05.0000000 -07:00")
			default:
				return fmt.Sprintf("%s", field)
			}
		default:
			return fmt.Sprintf("%s", field)
		}
	}
	return nil

}

//connect to oracle database
func connectORACLE(host, serviceName, user, password string, port int) (*sql.DB, error) {

	connString := fmt.Sprintf("%s/%s@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=%s)(PORT=%d)))(CONNECT_DATA=(SERVICE_NAME=%s)))", user, password, host, port, serviceName)

	db, err := sql.Open("godror", connString)

	if err != nil {
		return nil, err
	}

	err = db.Ping()

	if err != nil {
		return nil, err
	}

	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)

	return db, nil
}

```

**Comment by tgulacsi** [comment]
Ah, so you don't specify the destination type, just "interface{}", and want to change the default from time.Time to sql.NullTime. That's a breaking change, with "unsupported Scan, storing driver.Value type sql.NullTime into type *time.Time" everywhere.

See f3d3ce7

Test

**Comment by xhit** [comment]
Tested f3d3ce7.

NullTime always returns `true `for `Valid` 

struct returned for column DATE when is not null
`{2020-01-21 00:02:43 -0400 -04 true}`

struct returned for column DATE when is `NULL`
`{0001-01-01 00:00:00 +0000 UTC true}`

Also about this:
> That's a breaking change, with "unsupported Scan, storing driver.Value type sql.NullTime into type *time.Time" everywhere.

Yes, I am aware. The idea is to deal with NullTime instead of breaking the package. Your solution is good.

**Comment by tgulacsi** [comment]
PTAL, e99fcf2 should be better.

**Comment by xhit** [comment]
Tested and LGTM.

Thanks!
