### ISSUE TITLE
Release 0.20.6 requires Go 1.15 due to use of Int.FillBytes

### ISSUE THREAD

**Issue by atc0005** [godror/godror#110]
**Describe the bug**

This project indicates that Go 1.13 is supported. godror release 0.20.6 (specifically 2ba6aed687658a0da5fa6230aa828e93ffa9aaa9) introduces a dependency on `Int.FillBytes` which was released in Go 1.15. Test builds / CI based on Go 1.14 fail with this message:

```console
number.go:30:24: i.FillBytes undefined (type big.Int has no field or method FillBytes)
```

**To Reproduce**

- https://github.com/godror/godror/runs/1317417462?check_suite_focus=true#step:4:14
- https://github.com/godror/godror/commit/2ba6aed687658a0da5fa6230aa828e93ffa9aaa9#diff-8410264a2d3b5ab50e67d9a0dbbbb5d1df1e4089ade8e00413bb8a09f892caccR30

**Expected behavior**

Compatibility with Go 1.13, 1.14 to match the README

**Error output**

```console
number.go:30:24: i.FillBytes undefined (type big.Int has no field or method FillBytes)
```

**Your oracle client version**

N/A

**Your godror version**

v0.20.6

**Your go version**

- 1.15.4
  - builds without issue
- 1.14.11
  - fails with message noted earlier

**Your gcc version**

N/A

**Machine (please complete the following information):**

Pulled these details from the [GitHub Actions job](https://github.com/godror/godror/runs/1317417462?check_suite_focus=true#step:4:14)

 - OS: Ubuntu
 - Architecture: amd64
 - Version: 18.04.5

**Additional context**

First noticed this today when Dependabot offered a 0.20.5 to 0.20.6 upgrade and it failed a CI run for Go 1.14.

**Comment by tgulacsi** [comment]
v0.20.7 fixes this, sorry.
