### ISSUE TITLE
Mac build go for linux appear undefined error

### ISSUE THREAD

**Issue by avenCN** [godror/godror#115]
**Describe the bug**
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go // Also try CGO_ENABLED=1 and env CGO_ENABLED="1" 
OR
GOOS=linux GOARCH=amd64 go build main.go

**Error output**
# github.com/godror/godror
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:459:56: undefined: VersionInfo
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:468:56: undefined: VersionInfo
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:486:19: undefined: VersionInfo
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:487:19: undefined: VersionInfo
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:488:30: undefined: ObjectType
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:489:31: undefined: Event
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:489:42: undefined: SubscriptionOption
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:489:64: undefined: Subscription
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:490:10: undefined: StartupMode
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:491:11: undefined: ShutdownMode
../../../pkg/mod/github.com/godror/godror@v0.20.10/orahlp.go:491:11: too many errors

**Your oracle client version**
e.g. 12.2.0.1.0

**Your godror version**
e.g. v0.20.10

**Your go version**
e.g. 1.15.5

**Machine (please complete the following information):**
 - OS: macOS
 - Architecture: [e.g. x86_64]
 - Version: 11.0.1

**Comment by tgulacsi** [comment]
cgo is required, thus the proper C cross-compilers if you cross-compile.
You may use karalabe/xgo, but it's easier to compile on the target machine.

**Comment by tgulacsi** [comment]
See https://github.com/godror/godror/blob/master/doc/cross-compile.md

**Comment by gomurphyx** [comment]
Thanks @tgulacsi. I was able to get godror-linux-amd64 compiled using xgo. However, not sure which location should I place it for go to consider that during compilation and not get "too many errors" originally reported. Would appreciate any pointers.

**Comment by tgulacsi** [comment]
You have to build Your app with xgo, not just godror.

(I've stumled upon github.com/godror/go-grpc-sql, but its a work in progress...)

**Comment by tgulacsi** [comment]
Can you try `contrib/cross-compile.sh` at the current master?

It downloads zig, and tries to cross-compile with that.
