### ISSUE TITLE
table lock - concurrency problem

### ISSUE THREAD

**Issue by volker-raschek** [godror/godror#120]
Hello folks, 
I have written an oracle driver for https://github.com/golang-migrate/migrate using godror as the driver. To prevent multiple instances from migrating an oracle database the schema_lock table is locked and a row is inserted. Other instances should then not start the migration. 

Locally on my system and inside a container,  the tests run successfully. In our internal CI the test fails with the same container image.

Information:

- godror v0.22.2
- go version 1.15.6
- oracle client: 19.8.0.0.0
- oracle db version: 12c

Under the project https://github.com/volker-raschek/locker I have implemented everything to reproduce the error. Again, local on my system the test is successfully, but in our internal CI the test fails. 

Unfortunately I can't catch the error with an ORA error code, because it doesn't contain one. Sometimes I get an error message like this one `dpiStmt_execute(mode=0 arrLen=-1): ` or nothing. I am not sure if there is something wrong with my source code or the SQL statements or godror has a bug. 

Please have a look at my sample code and the logs and reproduce the error if necessary.

Volker

**To Reproduce**

```bash
git clone https://github.com/volker-raschek/locker
make start-oracle-xe
sleep 300 # wait until db is ready
make container-run/test/unit # maybe you must adapt DB_URL in Makefile
```

**Expected behavior**

The intergration tests are successfully on both systems (local and ci) 

**logs are attached as seperate files**

[ci.log](https://github.com/godror/godror/files/5716824/ci.log)
[local-system.log](https://github.com/godror/godror/files/5716829/test.log)

**Comment by tgulacsi** [comment]
```$ DB_URL=$GODROR_TEST_USERNAME/$GODROR_TEST_PASSWORD@$GODROR_TEST_DB go test
PASS
ok      github.com/volker-raschek/locker        1.479s
```

I'd use context.Context (for timeouts) and `defer tx.Rollback()`.

**Comment by tgulacsi** [comment]
What do you want to test?

In a Go program, you won't create more sql.DB pools per database, only one.
Here you create 25.

Maybe I've found a fix for the empty errors - see 9489b07

For your tests, I'd use context for timeouts: 
[x.patch.txt](https://github.com/godror/godror/files/5717582/x.patch.txt)

**Comment by volker-raschek** [comment]
Hey @tgulacsi , 

I should give you more information. I am writing a backend application in go
which will be packaged as container image. The container image is a base image
for other containerized applications which run in future in a kubernetes
cluster. One application, based on my container image, share the used database
scheme with other instances of the same application.

I don't know how ofter the application will be started in the cluster, but to
avoid that all instances of the application starts to migrate the database
scheme from one version to another an entry in table scheme_lock should avoid to
start the migration process multiple times.  

This is also the reason for 25 instances of the sql.DB pools. Each sql.DB pool
for one running application. It can be possible, that in a cluster more than 25
instances of an application is running. Maybe 100 or 1000. I just do not know it
at the moment.

I applied your patch into my example project. I saw you implemented a mutex. I
think the mutex makes no sense for the same reason. I have n applications and
the mutex limits only simultaneous access exclusively for one instance.

Next to the context. I try to change the code to use a context. I can pass the
context over the Config struct for the oracle driver of the go-migrate package.
Ofter the Lock() and Unlock() function it is not possible. It is an
implementation of the interface.

- [Config{} struct](https://github.com/golang-migrate/migrate/blob/a53e6fc425743533d66df19fcd275344cfeea6d5/database/driver.go#L29)
- [Driver{} interface](https://github.com/golang-migrate/migrate/blob/a53e6fc425743533d66df19fcd275344cfeea6d5/database/driver.go#L45) 

Now again to your patch. The test is successfully on my local system. On our
internal CI I received the following error message:

```txt
    locker_test.go:103: 
        	Error Trace:	locker_test.go:103
        	Error:      	Should be true
        	Test:       	TestLocker/Concurrency
        	Messages:   	Failed to create table schema_lock: dpiStmt_execute(mode=0 arrLen=-1): 
--- FAIL: TestLocker (0.79s)
    --- PASS: TestLocker/lock-unlock (0.57s)
    --- FAIL: TestLocker/Concurrency (0.22s)
```

[Complete CI-Log](https://github.com/godror/godror/files/5719122/ci.log)

**Comment by tgulacsi** [comment]
"Maybe I've found a fix for the empty errors - see 7c96931"

**Comment by sudarshan12s** [comment]
@voler-raschk, I am not recommending the below change, for my
understanding, can you add this and let me know your CI results.
             go func(index int, sqlDBO *sql.DB) {
 +                runtime.LockOSThread()

**Comment by volker-raschek** [comment]
@sudarshan12s , thanks a lot for the hint with `runtime.LockOSThread()`. I have updated godror to the latest version (currently v0.22.3) and the test is successfully on the CI. The logs are in the attachment - [ci.log](https://github.com/godror/godror/files/5755758/ci.log)

Since there is a dependency on a C library by godror it seems that it must be ensured that the C code runs in the same thread as the Go routines. Some additional links:

1. [benefits-of-runtime-lockosthread-in-golang](https://stackoverflow.com/questions/25361831/benefits-of-runtime-lockosthread-in-golang)
2. [LockOSThread - example](https://github.com/golang/go/wiki/LockOSThread)

Now I am wondering how far this could have implications on existing code where `runtime.LockOSThread()` is not called. 

I think this is only necessary when an application opens multiple DB pools or did I misunderstand something?

**Comment by tgulacsi** [comment]
I still does not understand what's happening.

@volker-raschek , can you post us a failing CI log of yout test using v0.22.3, but WITHOUT runtime.LockOSThread() ? That should not have empty error message. 
If it still does, than that suggests that the error-retrieving logic must be protected with LockOSThread(), which is more than a hundred places in the source, so I'd like to support this with evidence.

**Comment by tgulacsi** [comment]
@volker-raschek can you try 8411931 without runtime.LockOSThread ? 
I've tried encapsulating all OCI execution and error return in runtime.LockOSThread.

**Comment by volker-raschek** [comment]
@tgulacsi, I updated godror to  [8411931](https://github.com/godror/godror/commit/8411931c7261619b291ef633d5b5e731721b32b8) and removed `runtime.LockOSThread()` from my test - [commit](https://github.com/volker-raschek/locker/commit/54c2ebc477ea2e64845d3f1528789cf22b07b621)

The test is now successfully on the CI - [ci.log](https://github.com/godror/godror/files/5757160/ci.log). I would like to update all of our internal projects to the latest version of godror if we have fixed the error.

**Comment by sudarshan12s** [comment]
> @sudarshan12s , thanks a lot for the hint with `runtime.LockOSThread()`. I added `LockOSThread()` into my [test](https://github.com/volker-raschek/locker/blob/master/locker_test.go#L73) and I have updated godror to the latest version (currently v0.22.3). The test is than successfully on the CI. The logs are attached - [ci.log](https://github.com/godror/godror/files/5755758/ci.log)
> 
> Since there is a dependency on a C library by godror it seems that it must be ensured that the C code runs in the same thread as the Go routines. Some additional links:
> 
> 1. [benefits-of-runtime-lockosthread-in-golang](https://stackoverflow.com/questions/25361831/benefits-of-runtime-lockosthread-in-golang)
> 2. [LockOSThread - example](https://github.com/golang/go/wiki/LockOSThread)
> 
> Now I am wondering how far this could have implications on existing code where `runtime.LockOSThread()` is not called.
> 
> I think this is only necessary when an application opens multiple DB pools or did I misunderstand something?

Yes i was indicating TLS used for storing error context in C libs in this case.  other thing I wanted to clarify is on  application instance.   you mean a each application instance a seperate process , right which creates a pool. I got confused because in your test case, you  create multiple pools in a single process .
