### ISSUE TITLE
Insert data appear dpiStmt_execute(mode=32 arrLen=-1): ORA-01704 error

### ISSUE THREAD

**Issue by avenCN** [godror/godror#123]
**Describe the bug**
Oracle OUT_SYNC_DATA TABLE -> DATA used LONG

_, err = oracleDb.Exec("UPDATE OUT_SYNC_DATA SET DATA = '" + item["data"] + "' WHERE ID = '" + item["id"] + "'")
if err != nil {
logger.Printf(err.Error())
}

**Error output**
dpiStmt_execute(mode=32 arrLen=-1): ORA-01704: string literal too long

**Your oracle client version**
12.2.0.1.0

**Your godror version**
v0.20.4

**Your go version**
1.15.2

**Your gcc version**
4.8.3

**Machine (please complete the following information):**
 Linux 7.6

**Comment by tgulacsi** [comment]
NEVER assemble a query string from user input (See https://www.w3schools.com/sql/sql_injection.asp and https://en.wikipedia.org/wiki/SQL_injection#Incorrectly_filtered_escape_characters)!

ALWAYS use bind variables!

```
_, err = oracleDb.Exec("UPDATE OUT_SYNC_DATA SET data = :1 WHERE id = :2", item["data"], item["id"])
if err != nil {
logger.Println(err)
}
```
