### ISSUE TITLE
Expired password resetting is not working, dsn fields are lost while opening connection.

### ISSUE THREAD

**Issue by kurt-google** [godror/godror#124]
**Describe the bug**
Resetting an expired password fails, on failure you can see that newPassword  and standaloneConnection are defaults (verified by reviewing output of https://github.com/godror/godror/blob/master/drv.go#L518, I'm not sure why "standalone" is in the format string here.).

It looks due to struct member aliasing in `ConnectionParameters`, which has a Standalone and NewPassword field, but embeds `ConnParams` which defines a NewPassword field https://github.com/godror/godror/blob/master/dsn/dsn.go#L156. This prevents `ConnParams.NewPassword` from being promoted so `ConnParams` is not set by the direct access in https://github.com/godror/godror/blob/master/dsn/dsn.go#L484. Then these extra fields are dropped in `Open` because only the embedded structs are passed through https://github.com/godror/godror/blob/master/drv.go#L276

Example of the embedding/promotion issue https://play.golang.org/p/GOPzWGvNe-q

It seems both of these should live exclusively in the `ConnParams` struct?

**To Reproduce**
https://github.com/godror/godror/blob/master/z_test.go#L2907
Should be amended to actually initiate a connection, I used `db.Ping()`.

**Expected behavior**
db.Ping() should work and reset the password.

**Error output**
ORA-28001: the password has expired

**Your oracle client version**
e.g. 12.2.0.1.0

**Your godror version**
e.g. v0.9.0

**Your go version**
e.g. 1.15.6

**Your gcc version**
e.g. 10.2

**Machine (please complete the following information):**
 - OS: [e.g. win]
 - Architecture: [e.g. x86_64]
 - Version: [e.g. 10]

**Additional context**

**Comment by tgulacsi** [comment]
Thanks for the detailed, drill down!
Does 9e84a50 helps?

**Comment by kurt-google** [comment]
Testing to see if it works, but `ConnectionParams.Standalone` is still being dropped at https://github.com/godror/godror/blob/master/drv.go#L276 since only the embedded structs are passed so I expect it to still fail.

**Comment by kurt-google** [comment]
my internal testing everything is working even with standalone property being dropped. Perhaps documentation [1] is wrong and standalone is not needed to reset passwords? My testing doesnt connect as sysdba/oper/asm or prelim so I dont think it should be creating a standalone connection if standalone is being dropped.

https://oracle.github.io/odpi/doc/structs/dpiConnCreateParams.html#c.dpiConnCreateParams.newPassword

**Comment by tgulacsi** [comment]
Maybe we don't see something. But a96a354 should clarify the intentions.

**Comment by kurt-google** [comment]
Everything seems good to me, thanks again for your quick work as always!
