### ISSUE TITLE
COPY Command Syntax

### ISSUE THREAD

**Issue by mirecl** [godror/godror#125]
Hi guys, how to use command COPY from stdin (https://docs.oracle.com/cd/B10500_01/server.920/a90842/apb.htm#634269)
 for fast load large data.

**Comment by tgulacsi** [comment]
That's for Oracle DB v9.2. It says "The COPY command will be obsoleted in future releases of SQL*Plus."

OCI does not provide such command, so you have to implement it yourself.

For retrieving data, use a big enough buffer and godror.FetchArraySize and set the prefetch row count to a high enough value with godror.PrefetchCount.

For fast push of data, issue arrays.

For example, see https://github.com/UNO-SOFT/dbcsv/blob/master/tablecopy/tablecopy.go
or https://github.com/UNO-SOFT/dbcsv/blob/master/csvload/csvload.go and https://github.com/UNO-SOFT/dbcsv/blob/master/csvdump/csvdump.go

**Comment by tgulacsi** [comment]
For copying, use github.com/UNO-SOFT/dbcsv/tablecopy.

For loading csv (or odt, xlsx, xls), use github.com/UNO-SOFT/dbcsv/csvload.
