### ISSUE TITLE
getting memlock issue in 19C DB

### ISSUE THREAD

**Issue by ankurnigam** [godror/godror#138]
When we are running the our script using godror package to execute SQL ,we are getting below error :

Creation of an IPC port failed because of ENOMEM. Review the memlock limit for Oracle users. 
Also make sure that network driver settings are high enough to allow equal amount of memory registrations with network devicekgefec: fatal error 0

when we checked ulimit it is 32MB for root and unlimited for oracle user.

In Incident trace file limit is shown as 

----- Process Resource Limits -----
***************** Dumping Resource Limits(s/h) *****************
core file size                         0 KB/UNLIMITED
data seg size                     UNLIMITED/UNLIMITED
scheduling priority                    0 KB/0 KB
file size                         UNLIMITED/UNLIMITED
pending signals                     5471 KB/5471 KB
max locked memory                     64 KB/64 KB
max memory size                   UNLIMITED/UNLIMITED
open files                             4 KB/4 KB
POSIX message queues                 800 KB/800 KB
real-time priority                     0 KB/0 KB
stack size                            32 MB/UNLIMITED
cpu time                          UNLIMITED/UNLIMITED
max user processes                  5471 KB/5471 KB
virtual memory                    UNLIMITED/UNLIMITED

I am not sure from where this setting is coming.

**Comment by ankurnigam** [comment]
This is metalink we have :

https://mosemp.us.oracle.com/epmos/faces/DocumentDisplay?_afrLoop=141496266641033&id=2605233.1&_adf.ctrl-state=aasfhy9eu_77

**Comment by ankurnigam** [comment]
This was coming from our exporter setting .This is not package issue.

**Comment by tgulacsi** [comment]
Yup, "max locked memory" (ulimit -l) seems way low.
