### ISSUE TITLE
Passing NULL value to in parameter of function

### ISSUE THREAD

**Issue by MeBr0** [godror/godror#143]
Assume have some function in oracle with following signature
```oracle
FUNCTION getXml(
    pInDate IN DATE,
    pOutDate IN DATE,
    pAmount IN NUMBER DEFAULT NULL)
RETURN CLOB
```

I call this function from golang code like this

```golang
stmt, err := db.Prepare(`begin :xmlResponse := getXml(pindate => :startDate,
                                                      poutdate => :endDate,
                                                      pamount => :amount);end;`)

if err != nil {
    return err
}

var xmlResponse string

params := []interface{}{
    sql.Named("xmlResponse", sql.Out{Dest: &xmlResponse}),
    sql.Named("startDate", startDate),
    sql.Named("endDate", endDate),
    sql.Named("amount", nil),
}

 _, err = stmt.ExecContext(context.Background(), params...)
    
if err != nil {
    return err
}

// Logic for xmlResponse
fmt.Println(xmlResponse)
    
return nil
```

and got following error
```
ORA-06502: PL/SQL: numeric or value error\nORA-06512: at line 1
```

How to pass null value to parameter and what is exact problem? Please help me figure it out
Additionally, there is no problem with date parameters

Env information
```
go version: `go version go1.15 windows/amd64`
godror version: `v0.24.2`
```

**Comment by tgulacsi** [comment]
That `interface{}` in `sql.Named` should be a "typed nil".
For a NUMBER, you can use sql.NullInt64, sql.NullFloat, but the easiest is to give the number as string, and the NULL as an empty string ("").

**Comment by MeBr0** [comment]
@tgulacsi for both

```
sql.Named("amount", sql.NullInt64{Valid: false})
// and
sql.Named("amount", "")
```

gives same error `ORA-06502: PL/SQL: numeric or value error\nORA-06512: at line 1`

**Comment by tgulacsi** [comment]
@MeBr0 PTAL TestNullIssue143 in z_test.go at 1ca0042 - it passes.
I bet your getXml differ from the reported one.

**Comment by MeBr0** [comment]
@tgulacsi after your answer, I figured out that problem was not in 'amount' field, but in date fields. Before I was sending string with format "dd.MM.yyyy" and it causes before error. Sending `time.Now()` removes error, however I need to pass specific date. 

From PL/SQL client, passing string in format "dd.MM.yyyy" to date fields works well

```
stmt, err := db.Prepare(`begin :xmlResponse := getXml(pindate => :startDate,
                                                      poutdate => :endDate,
                                                      pamount => :amount);end;`)

if err != nil {
    return err
}

var xmlResponse string

startDateTime, _ := time.Parse("02.01.2006", "20.01.2020")
endDateTime, _ := time.Parse("02.01.2006", "22.01.2020")

params := []interface{} {
    sql.Named("xmlResponse", sql.Out{Dest: &xmlResponse}),
    sql.Named("startDate", startDateTime),
    sql.Named("endDate", endDateTime),
    sql.Named("amount", nil),
}

_, err = stmt.ExecContext(context.Background(), params...)

if err != nil {
    return err
}

// Logic for xmlResponse
fmt.Println(xmlResponse)
    
return nil
```

This code gives same error `ORA-06502: PL/SQL: numeric or value error\nORA-06512: at line 1`

Question is how to properly pass date field to function? Only thing that works is passing `time.Now()`
Also I think we can rename issue

**Comment by tgulacsi** [comment]
NEVER assume `NLS_DATE_FORMAT`, always give the used format to `TO_DATE` (and `TO_CHAR`): 

    TO_DATE('20.01.2020', 'DD.MM.YYYY')

"20.01.2020" is a string. Oracle will implicitly convert it to DATE if the receiving variable is a DATE - but it will use the session's NLS_DATE_FORMAT.
So be explicit - either give a DATE (time.Time), or the formatting mask to TO_DATE, or set the NLS_DATE_FORMAT yourself.
