### ISSUE TITLE
provide ability to override WALLET_LOCATION value in sqlnet.ora (to TNS_ADMIN)

### ISSUE THREAD

**Issue by paulparkinson** [godror/godror#147]
**Is your feature request related to a problem? Please describe.**
Unable to override WALLET_LOCATION in sqlnet.ora (to TNS_ADMIN) as is possible implicitly or explicitly in other languages/drivers.

**Describe the solution you'd like**
Allow TNS_ADMIN to be the value for WALLET_LOCATION or provide another way to override it (eg there is the default "oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=${TNS_ADMIN})))" value in ojdbc.properties,  dotnet has OracleConfiguration.WalletLocation in order to override, ...)

**Describe alternatives you've considered**
Unless I am missing something (in which case clarification is appreciated), it is necessary to edit sqlnet.ora to achieve this in Go driver.

**Additional context**
The default sqlnet.ora entry is "WALLET_LOCATION = (SOURCE = (METHOD = file) (METHOD_DATA = (DIRECTORY="?/network/admin")))" and thus an issue if the wallet is not in "?/network/admin" and is in TNS_ADMIN location by default for Oracle ADB (ATP, ...) .

**Comment by tgulacsi** [comment]
AFAIK OCI reads sqlnet.ora from under `$TNS_ADMIN`. You can override TNS_ADMIN environment variable with the `configDir` connection string parameter. See https://github.com/godror/godror/blob/master/doc/connection.md#-optional-oracle-net-configuration-files

You can use the same hack I'm using with Oracle Autonomous Database for testing: create a temporary directory, copy there the template sqlnet.ora, replacing the "?/network/admin" part with the proper path for the SSL wallet files. See https://github.com/godror/godror/blob/master/z_test.go#L106

**Comment by cjbj** [comment]
The wallet location can be specified in sqlnet.ora, tnsnames.ora or in an Easy Connect string (when using 19c Oracle Client).  This is all out of scope of godror IMHO.

**Comment by paulparkinson** [comment]
Thank you both. 

Indeed I have been using the hack of modifying the default sqlnet.ora/wallet_location value.

My point is that it should not be necessary to modify any files in order to set the wallet_location as this is not appropriate for containerized/kubernetes/microservices use cases where it should be possible to dynamically get necessary connection information from the environment.

Allowing override via the (easy connect) URL would be a good solution, however, this is not supported in instant client and the full client is heavy-weight, and again not suited for microservices (especially since this wallet_location override would be the only need for it). 

Oracle/ATP use via Java, dotnet, Python, and JS do not have this shortcoming/requirement (ie wallet_location can be dynamic there) and so it would be nice to have Go on par with that and remove the need to manually move or edit files/sqlnet.ora, etc.

**Comment by cjbj** [comment]
@paulparkinson ?? It already supports it, as I said above.  A reference is https://download.oracle.com/ocomdocs/global/Oracle-Net-19c-Easy-Connect-Plus.pdf

**Comment by paulparkinson** [comment]
@cjbj In instantclient as well or only the full client?  My attempt to  `db, err := sql.Open("godror", "myuser/mypw@myservice?wallet_location=/mywalletlocation")` was unsuccessful.

**Comment by cjbj** [comment]
Try the godror syntax shown in https://godror.github.io/godror/doc/connection.html#-godror-connection-handling

**Comment by anders-swanson** [comment]
To anyone else who finds this, what worked for me was adding the following snippet to my connection string in tnsnames.ora:

(security=(MY_WALLET_DIRECTORY=/path/to/this/database/wallet))
