### ISSUE TITLE
macos: <inline asm>:1:1: error: unknown directive 

### ISSUE THREAD

**Issue by Kaitou786** [godror/godror#148]
**Describe the bug**
Unable to install the module using `go get github.com/godror/godror`

**To Reproduce**
Just run `go get github.com/godror/godror`

**Expected behavior**

Module to be installed

**Error output**
```
# github.com/godror/godror
<inline asm>:1:1: error: unknown directive
```

**Your oracle client version**
e.g. 12.2.0.1.0

**Your godror version**
e.g. v0.20.4

**Your go version**

go version go1.16.3 darwin/arm64

**Your gcc version**

```
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: arm64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Machine (please complete the following information):**
 - OS: Darwin
 - Architecture: arm_64
 - Version: 11.2.3
**Additional context**

**Comment by tgulacsi** [comment]
Nice.
Nor MacOS, nor arm64 around, so I cannot test it.

What does it print with "-x" flag ?

**Comment by Kaitou786** [comment]
```
go  get -x github.com/godror/godror
# get https://proxy.golang.org/github.com/@v/list
# get https://proxy.golang.org/github.com/godror/godror/@v/list
# get https://proxy.golang.org/github.com/godror/@v/list
# get https://proxy.golang.org/github.com/godror/@v/list: 410 Gone (0.333s)
# get https://proxy.golang.org/github.com/@v/list: 410 Gone (0.333s)
# get https://proxy.golang.org/github.com/godror/godror/@v/list: 200 OK (0.333s)
# get https://proxy.golang.org/golang.org/x/xerrors/@v/list
# get https://proxy.golang.org/github.com/go-logfmt/logfmt/@v/list
# get https://proxy.golang.org/golang.org/x/xerrors/@v/list: 200 OK (0.031s)
# get https://proxy.golang.org/golang.org/x/xerrors/@latest
# get https://proxy.golang.org/github.com/go-logfmt/logfmt/@v/list: 200 OK (0.031s)
# get https://proxy.golang.org/golang.org/x/xerrors/@latest: 200 OK (0.033s)
WORK=/var/folders/lc/ptmb5b5d5r7965br73h76td80000gn/T/go-build2536101883
mkdir -p $WORK/b001/
cd /Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4
TERM='dumb' CGO_LDFLAGS='"-g" "-O2" "-ldl" "-lpthread"' /opt/homebrew/Cellar/go/1.16.3/libexec/pkg/tool/darwin_arm64/cgo -objdir $WORK/b001/ -importpath github.com/godror/godror -- -I $WORK/b001/ -g -O2 -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/include -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/src -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/embed ./conn.go ./data.go ./drv.go ./drv_posix.go ./lob.go ./obj.go ./queue.go ./rows.go ./stmt.go ./subscr.go
cd $WORK
clang -fno-caret-diagnostics -c -x c - -o /dev/null || true
clang -Qunused-arguments -c -x c - -o /dev/null || true
clang -fdebug-prefix-map=a=b -c -x c - -o /dev/null || true
clang -gno-record-gcc-switches -c -x c - -o /dev/null || true
cd $WORK/b001
TERM='dumb' clang -I /Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4 -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -fno-common -I ./ -g -O2 -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/include -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/src -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/embed -o ./_x001.o -c _cgo_export.c
TERM='dumb' clang -I /Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4 -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -fno-common -I ./ -g -O2 -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/include -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/src -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/embed -o ./_x002.o -c conn.cgo2.c
TERM='dumb' clang -I /Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4 -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -fno-common -I ./ -g -O2 -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/include -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/src -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/embed -o ./_x003.o -c data.cgo2.c
TERM='dumb' clang -I /Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4 -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -fno-common -I ./ -g -O2 -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/include -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/src -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/embed -o ./_x004.o -c drv.cgo2.c
TERM='dumb' clang -I /Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4 -fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -fno-common -I ./ -g -O2 -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/include -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/src -I/Users/tarunkhandelwal/go/pkg/mod/github.com/godror/godror@v0.24.4/odpi/embed -o ./_x005.o -c drv_posix.cgo2.c
# github.com/godror/godror
<inline asm>:1:1: error: unknown directive
```

**Comment by tgulacsi** [comment]
By reading https://github.com/williamslab/ped-sim/issues/1 it struck that maybe that glibc memcpy evading gcc-only.

Can you try with deleting the __asm__ line in drv_posix.go ?

If that helps, I'll try a better fix.

**Comment by Farmion** [comment]
By adding

// https://www.win.tue.nl/~aeb/linux/misc/gcc-semibug.html
#ifdef __linux__
__asm__(".symver memcpy,memcpy@GLIBC_2.2.5");
#endif
*/

it can get it to build.

**Comment by tgulacsi** [comment]
Thanks for the confirmation.
Can you check the asm branch? (go get github.com/godror/godror@asm)
I'll release it as v0.24.5 if it works.

**Comment by Farmion** [comment]
It complains: go: cannot use path@version syntax in GOPATH mode

**Comment by tgulacsi** [comment]
Thanks, I've released the fix as v0.24.5.

**Comment by oyb001** [comment]
szitdeMacBook-Pro-oyb:oracle-sql-run-agent ouyangbin$ go  get -x github.com/godror/godror
# get https://goproxy.cn/github.com/godror/godror/@v/list
# get https://goproxy.cn/github.com/godror/godror/@v/list: 200 OK (0.660s)
WORK=/var/folders/7y/26pq3xkj5j53nl4b5m85s76wzr8ttw/T/go-build084183653
mkdir -p $WORK/b001/
cd /Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3
CGO_LDFLAGS='"-g" "-O2" "-ldl" "-lpthread"' /usr/local/go_1.14.4/go/pkg/tool/darwin_amd64/cgo -objdir $WORK/b001/ -importpath github.com/godror/godror -- -I $WORK/b001/ -g -O2 -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/include -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/src -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/embed ./conn.go ./data.go ./drv.go ./drv_linux.go ./lob.go ./obj.go ./queue.go ./rows.go ./stmt.go ./subscr.go
cd $WORK
clang -fno-caret-diagnostics -c -x c - -o /dev/null || true
clang -Qunused-arguments -c -x c - -o /dev/null || true
clang -fdebug-prefix-map=a=b -c -x c - -o /dev/null || true
clang -gno-record-gcc-switches -c -x c - -o /dev/null || true
cd $WORK/b001
TERM='dumb' clang -I /Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/include -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/src -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/embed -o ./_x001.o -c _cgo_export.c
TERM='dumb' clang -I /Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/include -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/src -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/embed -o ./_x002.o -c conn.cgo2.c
TERM='dumb' clang -I /Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/include -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/src -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/embed -o ./_x003.o -c data.cgo2.c
TERM='dumb' clang -I /Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/include -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/src -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/embed -o ./_x004.o -c drv.cgo2.c
TERM='dumb' clang -I /Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3 -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=$WORK/b001=/tmp/go-build -gno-record-gcc-switches -I ./ -g -O2 -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/include -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/src -I/Users/ouyangbin/Workspace/dev/golang/pkg/mod/github.com/godror/godror@v0.25.3/odpi/embed -o ./_x005.o -c drv_linux.cgo2.c
# github.com/godror/godror
<inline asm>:1:1: error: unknown directive

#  The follow is drv_linux.go
```

package godror

/*
#cgo LDFLAGS: -ldl -lpthread

// https://github.com/godror/godror/issues/139
// https://www.win.tue.nl/~aeb/linux/misc/gcc-semibug.html
__asm__(".symver memcpy,memcpy@GLIBC_2.2.5");
*/
import "C"
```

**Comment by oyb001** [comment]
go env
```shell
szitdeMacBook-Pro-oyb:oracle-sql-run-agent ouyangbin$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/ouyangbin/go/bin:/usr/local/opt/inetutils/libexec/gnubin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/mysql-5.7.25-macos10.14-x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/go_1.14.4/go/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home//bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/opt/inetutils/libexec/gnubin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/mysql-5.7.25-macos10.14-x86_64/bin:/Users/ouyangbin/Workspace/dev/golang:/Users/ouyangbin/Workspace/dev/golang/bin:/usr/local/apache-maven-3.6.2/bin:/Users/ouyangbin/Workspace/dev/golang:/Users/ouyangbin/Workspace/dev/golang/bin"
GOCACHE="/Users/ouyangbin/Library/Caches/go-build"
GOENV="/Users/ouyangbin/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/Users/ouyangbin/Workspace/dev/golang:"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go_1.14.4/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go_1.14.4/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ouyangbin/Documents/001_work/01_git/oracle-sql-run-agent/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7y/26pq3xkj5j53nl4b5m85s76wzr8ttw/T/go-build725526773=/tmp/go-build -gno-record-gcc-switches"
szitdeMacBook-Pro-oyb:oracle-sql-run-agent ouyangbin$ 

```

**Comment by oyb001** [comment]
@tgulacsi  I install godror@v0.25.3 fail on mac

**Comment by tgulacsi** [comment]
What if you comment out the "__asm__(".symver memcpy,memcpy@GLIBC_2.2.5");" line?

**Comment by oyb001** [comment]
I have set GOOS="darwin", build succ,Thanks!
```shell
szitdeMacBook-Pro-oyb:oracle-sql-run-agent ouyangbin$ go env | grep GOOS
GOOS="darwin"
szitdeMacBook-Pro-oyb:oracle-sql-run-agent ouyangbin$ pwd
/Users/ouyangbin/Documents/001_work/01_git/oracle-sql-run-agent
szitdeMacBook-Pro-oyb:oracle-sql-run-agent ouyangbin$ ./control build
command-line-arguments
oracle-sql-run-agent-linunx build ok
szitdeMacBook-Pro-oyb:oracle-sql-run-agent ouyangbin$ file oracle-sql-run-agent 
oracle-sql-run-agent: Mach-O 64-bit executable x86_64
szitdeMacBook-Pro-oyb:oracle-sql-run-agent ouyangbin$ go  get -x github.com/godror/godror
# get https://goproxy.cn/github.com/godror/godror/@v/list
# get https://goproxy.cn/github.com/godror/godror/@v/list: 200 OK (0.594s)
WORK=/var/folders/7y/26pq3xkj5j53nl4b5m85s76wzr8ttw/T/go-build769481309
szitdeMacBook-Pro-oyb:oracle-sql-run-agent ouyangbin$
```
@tgulacsi
