### ISSUE TITLE
<inline asm>:1:1: error: unknown directive

### ISSUE THREAD

**Issue by Farmion** [godror/godror#149]
Thank you a lot for providing this library! It works very well on linux and windows, but I am having issues setting it up on a mac:

```
$ go get github.com/godror/godror
# github.com/godror/godror
<inline asm>:1:1: error: unknown directive
```

The thing is: other cgo packages work, do you have any hints on how to debug this issue?

-- 
Edit: perhaps the env info is useful

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/farmion/Library/Caches/go-build"
GOENV="/Users/farmion/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/farmion/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kg/n80sx2k56kn0brj1h2yzg2l80000gn/T/go-build339301231=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by tgulacsi** [comment]
See #148

**Comment by Farmion** [comment]
Sorry, now I feel stupid...
