### ISSUE TITLE
Unable to locate Oracle Client Library when run as a systemd service

### ISSUE THREAD

**Issue by AtakanColak** [godror/godror#15]
**Describe the bug**
I am using godror to get some views from an oracle database. When I run my program through commandline, it uses Oracle DB's own library files in $ORACLE_HOME environment variable. However when I run it as a service, it is unable to use ORACLE_HOME environment variable (which is expected behaviour of systemd) But after I explicitly set it as Environment=ORACLE_HOME=<...>, it still doesn't work. 

I'm out of ideas on how to make it find the oracle client files when run as a service.

**To Reproduce**
 Run a program that uses godror as a systemd service. 

**Expected behavior**
For it to work as it works when I run it through bash

**oracle client version** : 11.2.0.2.0
**godror version** : v0.11.1
**go version** : 1.13.3
**gcc version** : 4.8.5

**compiling machine**
 - OS: [centos]
 - Architecture [x86_64]
 - Version: [7]

**working machine**
 - OS: [ubuntu]
 - Architecture [x86_64]
 - Version: [16.04]

**Comment by tgulacsi** [comment]
As godror uses ODPI-C underneath, check their Install manual: https://oracle.github.io/odpi/doc/installation.html#linux

I think the relevant sentence is "ODPI-C first searches for a library called “libclntsh.so” using the standard library search order. If this is not found, it will then search for version specific files such as “libclntsh.so.19.1”. If no library is found, then $ORACLE_HOME/lib/libclntsh.so is checked. If no library is found there, then an error is returned."

So, put the proper path into LD_LIBRARY_PATH.
(AFAIK you have to use "Environment=ORACLE_HOME=\nEnvironment=ORACLE_HOME=/proper/path" to first erase the environment in the override config of systemd (systemctl edit my.service)).

To be sure, add something like 'ExecStartPre=/bin/sh -c "export -p"' to log the real environment.
Or make your program log os.Environ() BEFORE `sql.Open("godror",...)`.

**Comment by AtakanColak** [comment]
Thanks to your reply, I was able to figure out the solution. 

I created a new .conf file in /etc/ld.so.conf.d that included proper/path/to/ORACLE_HOME/lib and then ran ldconfig. Restarting the service, the program didnt show any errors.
