### ISSUE TITLE
Question: Proper way to configure the client

### ISSUE THREAD

**Issue by Kaitou786** [godror/godror#151]
Hi, just wanted to ask this quick question. Are we required to set the Client config(i.e. Setting `ORACLE_HOME` ORACLE_SID` creating tnsnames.ora ) on the node where this go code is running from?

**Comment by sudarshan12s** [comment]
yes for tnsnames.ora , env TNS_ADMIN should point to the location where it
is present.


Regards,

**Comment by cjbj** [comment]
If your DB is on a different machine you wouldn't set ORACLE_SID.  If your client libraries are from Oracle Instant Client you would not set ORACLE_HOME.  If you need a tnsnames.ora and/or sqlnet.ora file they should be on the machine running Go.  These files are optional.

**Comment by Kaitou786** [comment]
I am running oracle DB as a container image with PAT to the local host I have defined `TNS_ADMIN` and tnsnames.ora inside of it. But I get the error:
```
ORA-12162: TNS:net service name is incorrectly specified
```

**Comment by sudarshan12s** [comment]
can you check the servicename provided and verify if it works through
sqlplus .

on DB , you can check the registered services
SQL> select con_id, name from v$services order by 1;

**Comment by Kaitou786** [comment]
with sqlplus I am able to login after defining the TNS_ADMIN and tnsnames.ora. With the above content
 select con_id, name from v$services order by 1; => results in ORCLCDB
