### ISSUE TITLE
Unable to load location due to incorrect casing in timezone

### ISSUE THREAD

**Issue by enork** [godror/godror#153]
**Describe the bug**
in conn.go line 515 the following query is used:

SELECT DBTIMEZONE as dbTZ, NVL(TO_CHAR(SYSTIMESTAMP, 'TZR'), TO_CHAR(SYSTIMESTAMP, 'TZH:TZM')) AS dbOSTZ FROM DUAL

In our case we have the following trigger setting the session timezone to America/Chicago

create or replace trigger svccontract.date_translation_trigger
after logon on SVCCONTRACT.schema 
declare 
  v_timezone varchar2(200); 
begin 
  begin 
    select type_description 
    into v_timezone 
    from prod.types 
    where type_prefix = 'LOGONTRG' 
    and type_code = 'DBTIMEZONE'; 
  exception 
    when no_data_found then 
       v_timezone := 'America/Chicago'; 
  end; 
  execute immediate 'alter session set sql_translation_profile=ADMIN.DATE_TRANSLATION_PROFILE'; 
  begin
     execute immediate 'alter session set time_zone='''||v_timezone||''''; 
  exception
    when others then
      raise_application_error(-20000,'Timezone error');
  end;
end;

As the format in the above query is using 'TZR', the query is returning the timezone as AMERICA/CHICAGO and therefore causing a panic when trying to load the location (conn.go line 632) since that timezone does not exist on the system.

**To Reproduce**
Attempt to connect to database where the DBTIMEZONE is set to something like America/Chicago and not an offset.

**Expected behavior**
I think the correct format in this query should be 'tzr' to return the timezone correctly such as America/Chicago. 

Currently the only way I saw to work around this for now was to manually create that time zone in our alpine docker container by
RUN mkdir /usr/share/zoneinfo/AMERICA/
RUN cp /usr/share/zoneinfo/America/Chicago /usr/share/zoneinfo/AMERICA/
RUN mv /usr/share/zoneinfo/AMERICA/Chicago /usr/share/zoneinfo/AMERICA/CHICAGO

**Error output**
panic: AMERICA/CHICAGO: AMERICA/CHICAGO: unknown time zone AMERICA/CHICAGO

goroutine 1 [running]:
github.com/godror/godror.(*conn).initTZ(0xc000360000, 0x0, 0x0)
        /go/pkg/mod/github.com/godror/godror@v0.24.6/conn.go:562 +0x14e0
github.com/godror/godror.(*conn).init(0xc000360000, 0x0, 0xc000105300, 0xb)
        /go/pkg/mod/github.com/godror/godror@v0.24.6/conn.go:467 +0x40
github.com/godror/godror.(*drv).createConn(0x1b42f40, 0xc00035c000, 0xc000105300, 0xb, 0xc000105323, 0x15, 0xc00010530c, 0x16, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/godror/godror@v0.24.6/drv.go:372 +0x2e5
github.com/godror/godror.(*drv).createConnFromParams(0x1b42f40, 0xc000105300, 0xb, 0xc000105323, 0x15, 0xc00010530c, 0x16, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/godror/godror@v0.24.6/drv.go:567 +0x130
github.com/godror/godror.connector.Connect(0x1b42f40, 0xc000105300, 0xb, 0xc000105323, 0x15, 0xc00010530c, 0x16, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/godror/godror@v0.24.6/drv.go:1063 +0x5fc
database/sql.(*DB).conn(0xc00015e240, 0x1356960, 0xc0002ef200, 0x1, 0xc0001d9890, 0x4a206b, 0x1356920)
        /usr/local/go/src/database/sql/sql.go:1228 +0x201
database/sql.(*DB).Conn(0xc00015e240, 0x1356960, 0xc0002ef200, 0x1356960, 0xc0002ef200, 0xc00031b190)
        /usr/local/go/src/database/sql/sql.go:1747 +0x82

**Your oracle client version**
12.1.0.2.0

**Your godror version**
v0.24.6

**Your go version**
1.12

**Your gcc version**
e.g. 4.8.3

**Machine (please complete the following information):**
 - OS: Alpine linux
 - Architecture: [e.g. x86_64]
 - Version: [e.g. 10]

**Additional context**

**Comment by tgulacsi** [comment]
Do I understand correctly that you set AMERICA/CHICAGO instead of America/Chicago?
Can you set godror.Log to something that prints to stdout?
Can you try 982a95d?

**Comment by enork** [comment]
No, the time zone is set to America/Chicago per our db trigger. however if you see in the query for DBTIMEZONE the format used is 'TZR'. My suggestion is that the correct format is 'tzr'

Here are the following queries when I compare in sql developer on our database

SELECT DBTIMEZONE as dbTZ, NVL(TO_CHAR(SYSTIMESTAMP, 'TZR'), TO_CHAR(SYSTIMESTAMP, 'TZH:TZM')) AS dbOSTZ FROM DUAL;

DBTZ        DBOSTZ
+00:00     AMERICA/CHICAGO

SELECT DBTIMEZONE as dbTZ, NVL(TO_CHAR(SYSTIMESTAMP, 'tzr'), TO_CHAR(SYSTIMESTAMP, 'TZH:TZM')) AS dbOSTZ FROM DUAL;

DBTZ        DBOSTZ
+00:00     America/Chicago

**Comment by enork** [comment]
Also, worth noting is AMERICA/CHICAGO curiously seems to work on macOS but for our engineers running locally in windows and in our docker container which is on Alpine we run into this timezone error.

**Comment by enork** [comment]
[INFO]    2021-05-12 13:54:25 [internal/services/service.go] [services.Initialize: 82] - initializing service
[msg connect poolParams poolIncrement=1 poolMaxSessions=1000 poolMinSessions=1 poolSessionMaxLifetime=1h0m0s
poolSessionTimeout=5m0s poolWaitTimeout=30s connParams  common user=********** password="**********" connectString=**********
timezone=]
[msg dpiContext_createWithParams params 0xc0002e7260]
[msg getPool key **********    **********   1       1000    1       30s     1h0m0s  5m0s    false   false   false   UTC]
[C dpiPool_create user ********** ConnectString ********** common {1 0x1b694c0 0x1b694c0 <nil> 0 0x1b69540 16 0} pool godror._Ctype_struct_dpiPoolCreateParams{minSessions:0x1, maxSessions:0x3e8, sessionIncrement:0x1, pingInterval:60, pingTimeout:5000, homogeneous:1, externalAuth:0, getMode:0x3, outPoolName:(*godror._Ctype_char)(nil), outPoolNameLength:0x0, timeout:0x12c, waitTimeout:0x7530, maxLifetimeSession:0xe10, plsqlFixupCallback:(*godror._Ctype_char)(nil), plsqlFixupCallbackLength:0x0, maxSessionsPerShard:0x0}]
[msg acquireConn pool 0xc000360000 connParams user=********** password="**********" connectString=**********
timezone= ]
[msg init connection conn &user=********** password="**********" connectString=**********
configDir= connectionClass= enableEvents=0 externalAuth=0 heterogeneousPool=0
libDir= noTimezoneCheck=0 poolIncrement=1 poolMaxSessions=1000 poolMinSessions=1
poolSessionMaxLifetime=1h0m0s poolSessionTimeout=5m0s poolWaitTimeout=30s
prelim=0 standaloneConnection=0 sysasm=0 sysdba=0 sysoper=0 timezone=&serverVersion=0.0.0.0.0&tzOffSecs=0&new=true onInit <nil>]
[msg initTZ tzValid false paramsTZ UTC]
[msg initTZ key America/Chicago user=********** password="**********" connectString=**********
configDir= connectionClass= enableEvents=0 externalAuth=0 heterogeneousPool=0
libDir= noTimezoneCheck=0 poolIncrement=1 poolMaxSessions=1000 poolMinSessions=1
poolSessionMaxLifetime=1h0m0s poolSessionTimeout=5m0s poolWaitTimeout=30s
prelim=0 standaloneConnection=0 sysasm=0 sysdba=0 sysoper=0 timezone=local]
[enter bindVars st 0xc00037c000 args []]
[doManyCount 1 arrLen -1 doExecMany false minArrLen maxArrLen]
[msg openRows col 0 info {2001 3004 1 6 6 6 0 0 0 <nil>}]
[C dpiConn_newVar conn 0x1cc0c20 typ 2001 natTyp 3004 sliceLen 100 bufSize 6 isArray 0 objType <nil> v <nil>]
[msg openRows col 1 info {2001 3004 1 32 32 32 0 0 0 <nil>}]
[C dpiConn_newVar conn 0x1cc0c20 typ 2001 natTyp 3004 sliceLen 100 bufSize 32 isArray 0 objType <nil> v <nil>]
[msg fetched bri 0 fetched 1 moreRows 0 len(data) 2 cols 2]
[msg scanned row 1 dest [+00:00 AMERICA/CHICAGO]]
[msg calculateTZ sessionTZ +00:00 dbOSTZ AMERICA/CHICAGO]
[dbTZ +00:00 dbOSTZ AMERICA/CHICAGO]
[timezone AMERICA/CHICAGO tz UTC error AMERICA/CHICAGO: AMERICA/CHICAGO: unknown time zone AMERICA/CHICAGO]
[msg initTZ error AMERICA/CHICAGO: AMERICA/CHICAGO: unknown time zone AMERICA/CHICAGO]
[msg statement.closeNotLocking st 0xc00037c000 refCount 1]
panic: AMERICA/CHICAGO: AMERICA/CHICAGO: unknown time zone AMERICA/CHICAGO

**Comment by tgulacsi** [comment]
I've never seen 'tzr' as an approved format string for TO_CHAR.
Can you try 5651f92a8132efea6eec6276f55df78b9665ee72 ?

**Comment by enork** [comment]
That will work for our case since there is no underscore in the timezone but it will not work for others such as America/New_York since string.Title() will transform it into America/New_york and therefore cause the same issue in those cases.

Another option would be to wrap the query in INITCAP() which correctly transforms the upper case 'AMERICA/NEW_YORK' into 'America/New_York' e.g. SELECT INITCAP('AMERICA/NEW_YORK') AS dbOSTZ FROM DUAL;

However, I do see that the lower case format is called out in oracle's docs here. See 'Uppercase Letters in Date Format Elements'
https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements004.htm
