### ISSUE TITLE
I have a question about golang code and memory leak. 

### ISSUE THREAD

**Issue by marthcat** [godror/godror#154]
(first, i'm not good at english. excuse me.)
hello. i need a help

I build the code, run and i monitoring by `top -b -p {PID}`.
I think The memory (VIRT, RES) seems to increase non-aperiodically. 

Am I mistaken or is there a mistake in the code? thanks..

#### test code
```
package main

import (
	"database/sql"
	"time"
	"log"
	"os"
	"runtime"

	_ "github.com/godror/godror"
)

func main() {
	myLogger := log.New(os.Stdout, "INFO: ", log.LstdFlags)
	connStr := "~~~~"
	sqlQuery :=
	`
               ~~~~~
	`

	ticker := time.NewTicker(time.Second)
	for {
		select {
		case <-ticker.C:
		}

		myLogger.Print("Test")

		db, err := sql.Open("godror", connStr)
		if err != nil {
			if db != nil {
				db.Close()
				err = nil
				continue
			}
		}

		rows, _ := db.Query(sqlQuery)
		if rows != nil {
			rows.Close()
		}
		db.Close()
		err = nil

		runtime.GC()
	}
}
```

#### top -b -p {PID} 
- start+0 ~
  ![image](https://user-images.githubusercontent.com/51684485/118081681-ce55fa80-b3f6-11eb-8622-02a4a6ef2465.png)
  ![image](https://user-images.githubusercontent.com/51684485/118081982-5b994f00-b3f7-11eb-9d78-791331733b33.png)
- start+11m ~ start+25m 
  ![image](https://user-images.githubusercontent.com/51684485/118082032-74096980-b3f7-11eb-8383-fca7575f9346.png)
  ![image](https://user-images.githubusercontent.com/51684485/118082528-4cff6780-b3f8-11eb-8e3d-04d3299167a1.png)
- start+80m
  ![image](https://user-images.githubusercontent.com/51684485/118082818-d2831780-b3f8-11eb-86d5-ddf588c9b5da.png)
- start+150m
  ![image](https://user-images.githubusercontent.com/51684485/118084112-12e39500-b3fb-11eb-9667-6c90fc35a9ef.png)
   

**Your oracle client version**
21.1.0.0.0

**Your godror version**
 v0.24.6

**Your go version**
1.15.8 linux/amd64

**Your gcc version**
gcc version 8.3.0 (Debian 8.3.0-6) 

**Machine (please complete the following information):**
- Windows > WSL2 > Linux
Linux 2e56a21164a6 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux

**Additional context**

**Comment by tgulacsi** [comment]
That's not much increase.
In real programs you don't create the connection pool (sql.Open) and close it after a Query, but keep it open for the whole life of the application.

**Comment by marthcat** [comment]
I'm developing a program that won't be a problem if I keep running for more than a year.
so... I am concerned that "memory" is increasing non-periodically. (It only happened in the "godror" code on my program.)

hmm... Ok
I will modify the code as you said and continue monitoring.

Thank for your answer.

**Comment by marthcat** [comment]
Sorry. "Closed" by my fault.
