### ISSUE TITLE
How to read clob>32k in procedure with sql.Out?

### ISSUE THREAD

**Issue by kerokhin88** [godror/godror#156]
**Describe the bug**
Got oracle procedure with clob as out parameter.
myproc(in1,in2,out1,out2)
Calling it with tools like dbeaver:
```
declare
 out1 clob;
 out2 varchar(10);
begin
 myproc(:1,:2,out1,out2)
end;
```
I am able to get result with clob>32k, output via DBMS_OUTPUT.put_line + substr
In go code, using string as sql.Out{Dest: str} works fine for objects < 32k, but with objects >32k i got:
```
dpiStmt_execute(mode=0 arrLen=-1): ORA-06550: line 3, column 9:
PLS-00306:  wrong number or types of arguments in call to 'GET_MESSAGE'
ORA-06550: line 3, column 9:
PL/SQL: Statement ignored
```
As I see string got buffer https://github.com/godror/godror/blob/v0.24.7/stmt.go#L1077 wich works for most objects.
Tried changing out parameter to  gordor.Lob result in the same error message.
Adding LobAsReader() result in the same error message.
Read comment on LobAsReader, but cant figure out how to set DPI_ORACLE_TYPE_LONG_VARCHAR for out type.

**Expected behavior**
Able to read clob object > 32k.

**Error output**
https://pastebin.com/iU5L5Akt

**Your oracle client version**
12.2.0.1.0

**Your godror version**
v0.24.7

**Your go version**
v1.16.4

**Your gcc version**
9.3.0

**Machine (please complete the following information):**
Ubuntu 20.04 + updates

**Comment by tgulacsi** [comment]
PTAL TestReadLargeLOB in z_lob_test.go at 8047ec1.
It should just work.
(You haven't show your code, so cannot help more).

**Comment by kerokhin88** [comment]
OMG! The thing I was missing is `{IsClob: true}` in lob creation.
Now it works great.
