### ISSUE TITLE
 ORA-12154: TNS:could not resolve the connect identifier specified

### ISSUE THREAD

**Issue by freeman983** [godror/godror#159]
**Describe the bug**
I use SID connect to my database, but I always get same response,
but Use this connection method is successful

`
	P.ConnectString = fmt.Sprintf("%s:%s/%s", db.Ip,  db.Port,  db.Db)

`

**To Reproduce**
At least the offending source code;
the best is a minimal test case that reproduces the error.

`      name := "u_sqldev"
	pwd := "u_sqldev"
	service := "qianuc"

	var P godror.ConnectionParams
	
	P.Username = name
	P.Password = godror.NewPassword(pwd)
	P.ConnectString = fmt.Sprintf("%s", service)
	P.Timezone = time.Local
	P.StandaloneConnection = true
	

	db := sql.OpenDB(godror.NewConnector(P))

	err := db.Ping()
	if err != nil {
		fmt.Println("err：", err)
		return err
	}`

**Expected behavior**
Successfully connected to the database

**Error output**
err： user="u_sqldev" ConnectString="qianuc" standalone params={authMode:0 connectionClass:<nil> connectionClassLength:0 purity:0 newPassword:<nil> newPasswordLength:0 ppContext:<nil> numAppContext:0 externalAuth:0 externalHandle:<nil> pool:<nil> tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-12154: TNS:could not resolve the connect identifier specified

**Your oracle client version**
11.1

**Your godror version**
v 0.25.1

**Your go version**
go version go1.16.4 darwin/amd64

**Your gcc version**
e.g. 4.2.1

**Machine (please complete the following information):**
 - OS: macos 
 - Architecture:64
 - Version: 10.15.7 (19H524)

**Additional context**
tnsnames.ora 
`

qianuc =
     (DESCRIPTION =
       (ADDRESS_LIST =
         (ADDRESS = (PROTOCOL = TCP)(HOST = lin-21-4-253)(PORT = 1521))
       )
       (CONNECT_DATA =
         (SERVICE_NAME = ofdb)
       )
)

`

**Comment by tgulacsi** [comment]
Is TNS_ADMIN environment variable set to the directory of tnsnames.ora? sqlplus connects successfully?

**Comment by freeman983** [comment]
@tgulacsi  Yes,I can successfully connect using sqlplus,But I realized that it might be a problem with environment variables，The same code I tested on centos 7 can connect to the database through tns。It should be an environmental problem on the mac. I will find the reason for myself. Thank you very much for your reply.
