### ISSUE TITLE
Named Parameters?

### ISSUE THREAD

**Issue by travellingkiwi** [godror/godror#160]
I have several thousand existing SQL statements defined in a YAML document that consist of SQL statements that have named parameters. It's use day several different apps, all written in perl. And they use DBD::Oracle 

The statements are of the form 'select * from table where column1=:parm1 and column2=:param2' etc. i.e. Using Oracle :name format for named parameters

I'm trying to implement a small golang program that uses the same YAML definitions... However the documentation for gosql and godror aren't very clear on how to pass the parameters. I assumed that (Using prepared statements) I would pass the parameters as 'map[string]string', but gosql or godror apparently doesn't like this.. returning the error

'1. arg: unknown type map[string]string'

What format does stmt.Query expect the arguments to be in? There doesn't appear to be a separate stmt.Bind() call to set the parameters anywhere other than passing them to stmt.Query()

**Comment by tgulacsi** [comment]
Either use sql.NamedArg (https://pkg.go.dev/database/sql#Named), or convert them to positional parameters (https://pkg.go.dev/github.com/godror/godror#NamedToOrdered).

**Comment by travellingkiwi** [comment]
Thanks... I don't suppose you can pass an array of them to stmt.Query() can you? Rather than just discrete parameters? (Does gaoling expand arrays in parameters like perl? probably not).

It makes it awfully messy to wrap it.  Sorry, just learning golang now and using databases doesn't appear to be as rich and mature as things like Perls DBI

**Comment by tgulacsi** [comment]
You can pass an []interface{} with ... to expand:

    var rc int
    args := []interface{sql.Out{Dest:&rc}, "1", 2, nil}
    stmt.Query("BEGIN :1 := proc(:2, :3, :4); END;", args...)

**Comment by travellingkiwi** [comment]
Ah! brilliant. I hadn't noticed that yet in golang. Nice.
