### ISSUE TITLE
SIGSEGV during fetch stored procedure returning cursor (fetchRows)

### ISSUE THREAD

**Issue by rahmanme** [godror/godror#161]
When i tried to iterate on rowset with next randomly got SIGSEGV

godror version: v0.25.2
golang version: 1.16.5

#233		cols := outRecs.(driver.RowsColumnTypeScanType).Columns()
#234		dest := make([]driver.Value, len(cols))
#235		for {
#236			if err := outRecs.Next(dest); err != nil {
#237				if err == io.EOF {
#238					break
#239				}
#240				return 0
#241			}

			...

#274		}

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7fd3ef03253c]

runtime stack:
runtime.throw(0xb6d185, 0x2a)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 243 [syscall, locked to thread]:
runtime.cgocall(0xa09080, 0xc003d95ff0, 0x7bf)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc003d95fc0 sp=0xc003d95f88 pc=0x410bdb
github.com/godror/godror._Cfunc_dpiStmt_fetchRows(0x7fd3dc048650, 0x7fd300000064, 0xc004fc3d48, 0xc004fc3d4c, 0xc004cfbeec, 0x0)
	_cgo_gotypes.go:4409 +0x48 fp=0xc003d95ff0 sp=0xc003d95fc0 pc=0x60ac88
github.com/godror/godror.(*rows).Next.func2(0xc004fc3cc0, 0xc000000064, 0xc004cfbeec, 0x4ec52e)
	/var/jenkins_home/workspace/ussd_v4/src/ussd_v4/vendor/github.com/godror/godror/rows.go:323 +0x8e fp=0xc003d96038 sp=0xc003d95ff0 pc=0x64bf6e
github.com/godror/godror.(*rows).Next(0xc004fc3cc0, 0xc0064ea730, 0x5, 0x5, 0x0, 0x0)
	/var/jenkins_home/workspace/ussd_v4/src/ussd_v4/vendor/github.com/godror/godror/rows.go:323 +0x2a7a fp=0xc003d964e8 sp=0xc003d96038 pc=0x62c59a
ussd_v4/db.(*DbHandler).GetMobileList(0xc0000b9bc0, 0xc000b049f4, 0xa, 0x0, 0x0, 0xc002285340, 0x0)
	/var/jenkins_home/workspace/ussd_v4/src/ussd_v4/db/db_handler.go:236 +0xb50 fp=0xc003d96808 sp=0xc003d964e8 pc=0x949670
ussd_v4/session.(*Handler).ProcessMsg(0xc0001ef680, 0xc004cfb0f0, 0xc, 0xc004cfb100, 0xb, 0x1, 0x133aa4fe00000000, 0x0, 0x0, 0x0, ...)
	/var/jenkins_home/workspace/ussd_v4/src/ussd_v4/session/handler.go:724 +0x11a6 fp=0xc003d97278 sp=0xc003d96808 pc=0x9be326
ussd_v4/session.(*Handler).ProcessMsg(0xc0001ef680, 0xc004cfb0f0, 0xc, 0xc004cfb100, 0xb, 0x1, 0x133aa4fe00000000, 0x0, 0x0, 0x0, ...)
	/var/jenkins_home/workspace/ussd_v4/src/ussd_v4/session/handler.go:792 +0xf05 fp=0xc003d97ce8 sp=0xc003d97278 pc=0x9be085
ussd_v4/session.(*Handler).HandleRequest(0xc0001ef680, 0xc004cfb0f0, 0xc, 0xc004cfb100, 0xb, 0x1, 0x133aa4fe00000000, 0x0, 0x0, 0x0, ...)
	/var/jenkins_home/workspace/ussd_v4/src/ussd_v4/session/handler.go:404 +0x27d fp=0xc003d97de8 sp=0xc003d97ce8 pc=0x9bc85d
ussd_v4/session.Worker.Start.func1(0xc000020ba0, 0xc0018306c0, 0xc0018622a0, 0x53, 0xc0001ef680)
	/var/jenkins_home/workspace/ussd_v4/src/ussd_v4/session/worker.go:47 +0x1c5 fp=0xc003d97fb8 sp=0xc003d97de8 pc=0x9c72c5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc003d97fc0 sp=0xc003d97fb8 pc=0x47a781
created by ussd_v4/session.Worker.Start
	/var/jenkins_home/workspace/ussd_v4/src/ussd_v4/session/worker.go:39 +0x53

**Comment by rahmanme** [comment]
I use it same as your sample with PrepareContext, ExecContext and close statement with defer after prepare. It seems some times the statement has closed before first stmt.Next() and refCount doesn't increase.

followed log is generated by same code.

SIGSEGV case:

6:03PM DBG godrorLOG msg=["msg","openRows","col",1,"info",{}]
6:03PM DBG godrorLOG msg=["msg","statement.closeNotLocking","st","0xc00539a160","refCount",1]
6:03PM DBG godrorLOG msg=["C","dpiConn_newVar","conn",{},"typ",2001,"natTyp",3004,"sliceLen",100,"bufSize",508,"isArray",0,"objType",null,"v",null]
6:03PM DBG godrorLOG msg=["msg","openRows","col",2,"info",{}]
6:03PM DBG godrorLOG msg=["C","dpiConn_newVar","conn",{},"typ",2001,"natTyp",3004,"sliceLen",100,"bufSize",508,"isArray",0,"objType",null,"v",null]
6:03PM DBG godrorLOG msg=["msg","openRows","col",3,"info",{}]
6:03PM DBG godrorLOG msg=["C","dpiConn_newVar","conn",{},"typ",2003,"natTyp",3004,"sliceLen",100,"bufSize",0,"isArray",0,"objType",null,"v",null]
6:03PM DBG godrorLOG msg=["msg","openRows","col",4,"info",{}]
6:03PM DBG godrorLOG msg=["C","dpiConn_newVar","conn",{},"typ",2003,"natTyp",3004,"sliceLen",100,"bufSize",0,"isArray",0,"objType",null,"v",null]
6:03PM DBG godrorLOG msg=["msg","IsValid","connOK",true,"released",false,"pooled",true,"tzOK",true]
6:03PM DBG godrorLOG msg=["msg","statement.closeNotLocking","st","0xc005289b80","refCount",1]


normal case:

6:03PM DBG godrorLOG msg=["msg","openRows","col",0,"info",{}]
6:03PM DBG godrorLOG msg=["C","dpiConn_newVar","conn",{},"typ",2010,"natTyp",3004,"sliceLen",100,"bufSize",40,"isArray",0,"objType",null,"v",null]
6:03PM DBG godrorLOG msg=["msg","openRows","col",1,"info",{}]
6:03PM DBG godrorLOG msg=["C","dpiConn_newVar","conn",{},"typ",2001,"natTyp",3004,"sliceLen",100,"bufSize",508,"isArray",0,"objType",null,"v",null]
6:03PM DBG godrorLOG msg=["msg","openRows","col",2,"info",{}]
6:03PM DBG godrorLOG msg=["C","dpiConn_newVar","conn",{},"typ",2001,"natTyp",3004,"sliceLen",100,"bufSize",508,"isArray",0,"objType",null,"v",null]
6:03PM DBG godrorLOG msg=["msg","openRows","col",3,"info",{}]
6:03PM DBG godrorLOG msg=["C","dpiConn_newVar","conn",{},"typ",2003,"natTyp",3004,"sliceLen",100,"bufSize",0,"isArray",0,"objType",null,"v",null]
6:03PM DBG godrorLOG msg=["msg","openRows","col",4,"info",{}]
6:03PM DBG godrorLOG msg=["C","dpiConn_newVar","conn",{},"typ",2003,"natTyp",3004,"sliceLen",100,"bufSize",0,"isArray",0,"objType",null,"v",null]
6:03PM DBG godrorLOG msg=["msg","IsValid","connOK",true,"released",false,"pooled",true,"tzOK",true]
6:03PM DBG godrorLOG msg=["msg","fetched","bri",0,"fetched",1,"moreRows",0,"len(data)",5,"cols",5]
6:03PM DBG godrorLOG msg=["msg","scanned","row",1,"dest",["0","09132419480","09132419480","",""]]
6:03PM DBG godrorLOG msg=["msg","fetched","bri",0,"fetched",0,"moreRows",0,"len(data)",5,"cols",5]
6:03PM DBG godrorLOG msg=["msg","statement.closeNotLocking","st","0xc004a78160","refCount",2]
6:03PM DBG godrorLOG msg=["msg","statement.closeNotLocking","st","0xc004a2f760","refCount",1]

**Comment by tgulacsi** [comment]
Without code I can only guess, but what if you use strictly one connection - either by using the same *sql.Tx, or *sql.Conn ?

**Comment by rahmanme** [comment]
ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	stmtProcCall, err := db.dbConn.PrepareContext(ctx, query)
	if err != nil {
		if db.sys_log != nil {
			_ = db.sys_log.Alert("query statement problem: " + err.Error())
		}
		log.Error().Str("err", err.Error()).Msg("db")
		return -1
	}
	defer stmtProcCall.Close()

	var outRecs driver.Rows
	var itemPerPage int64 = 0
	var res int64
	_, err2 := stmtProcCall.ExecContext(ctx, sql.Out{Dest: &res},
		ses.MobileNo,
		ses.VarFind("account_id"),
		ses.MenuLangId,
		listName,
		sql.Out{Dest: &itemPerPage},
		listFilter,
		sql.Out{Dest: &outRecs},
		"")
	if err2 != nil {
		if db.sys_log != nil {
			_ = db.sys_log.Alert("query exec problem: " + err2.Error())
		}
		log.Error().Str("err", err2.Error()).Msg("db exec")
		return -1
	}

	defer outRecs.Close()
	ses.ListItemPerPage = int(itemPerPage)
	if res == 0 {

		ix := 0
		ses.LastListName = listName
		ses.ItemsList = nil
		cols := outRecs.(driver.RowsColumnTypeScanType).Columns()
		dest := make([]driver.Value, len(cols))
		for {
			if err := outRecs.Next(dest); err != nil {
				if err == io.EOF {
					break
				}
				return 0
			}

			tmp := dataTypes.ItemsStruct{}
			for k, v := range outRecs.Columns() {
				switch strings.ToLower(v) {
				case "item_name":
					if str, ok := dest[k].(string); ok {
						tmp.Name = str
					} else {
						tmp.Name = dest[k].(godror.Number).String()
					}
				case "item_value":
					if str, ok := dest[k].(string); ok {
						tmp.Value = str
					} else {
						tmp.Value = dest[k].(godror.Number).String()
					}
				case "item_add_value":
					if str, ok := dest[k].(string); ok {
						tmp.AddValue = str
					} else {
						tmp.AddValue = dest[k].(godror.Number).String()
					}
				case "item_add_value2":
					if str, ok := dest[k].(string); ok {
						tmp.AddValue2 = str
					} else {
						tmp.AddValue2 = dest[k].(godror.Number).String()
					}
				}
			}
			ses.ItemsList = append(ses.ItemsList, tmp)
			ix++
		}
	}

**Comment by tgulacsi** [comment]
What is `db.dbConn` ?

**Comment by tgulacsi** [comment]
You can try godror.WrapRows for easier Scanning.

**Comment by rahmanme** [comment]
> You can try godror.WrapRows for easier Scanning.

It works.

db.dbConn, err = sql.Open("godror", dbConf.StringWithPassword())

**Comment by tgulacsi** [comment]
Ok, what if you use an *sql.Tx instead of dbConn? You have to force the db connection pool to use one connection and do not close the stmt.
