### ISSUE TITLE
Shutdown broken on 0.25.2

### ISSUE THREAD

**Issue by kurt-google** [godror/godror#164]
**Describe the bug**
On 0.25.2 attempting to shutdown a database results in DPI errors about invalid connection: `Shutdown(3): ORA-00000: DPI-1002: invalid dpiConn handle`

**To Reproduce**
Run the shutdown example, but instead of using godror.raw use `driverConn, err := godror.DriverConn(ctx.TODO(), db)` (I havnt tested godror.raw yet but perhaps that will prevent the `dpiConn_release` in the dpi logs).

**Expected behavior**
That this would work (since it has worked in prior versions) or if the connection is invalid godror.DriverConn to return an error?

**Error output**
```
msg=PrepareContext shortcut=--GET_CONNECTION--
msg=IsValid connOK=true released=false pooled=true tzOK=false
ODPI [49435] 2021-06-30 12:11:57.139: fn start dpiConn_release(0x7f3f700b1730)
ODPI [49435] 2021-06-30 12:11:57.139: fn end dpiConn_release(0x7f3f700b1730) -> 0
ODPI [49435] 2021-06-30 12:11:57.140: fn start dpiConn_shutdownDatabase((nil))
ODPI [49435] 2021-06-30 12:11:57.140: internal error DPI-1002: invalid dpiConn handle (dpiConn_shutdownDatabase / check main handle)
ODPI [49435] 2021-06-30 12:11:57.140: fn end dpiConn_shutdownDatabase((nil)) -> -1
Shutdown(3): ORA-00000: DPI-1002: invalid dpiConn handle
```

**Your oracle client version**
12.2.0.1.0

**Your godror version**
v0.25.2

**Your go version**
1.15.X

**Your gcc version**
e.g. 4.8.3

**Machine (please complete the following information):**
 - OS: linux
 - Architecture: x86_64

**Additional context**
I havnt had time to bisect this and will provide that when I get time, and just saw the new godror.Raw function so I havnt tested that. If that works I think its probably fine, but since this worked earlier it would be nice if it could continue to work.

**Comment by nilabja-bhattacharya** [comment]
It could be because _standaloneConnection_ was 1 by default which is 0 now. We are investigating the fix.

**Comment by tgulacsi** [comment]
PTAL 217dfe7 - I cannot test it though...

**Comment by tgulacsi** [comment]
Sorry, dead-end. 

You have to pick a connection and stick to it - either by using an sql.Tx, or db.Conn - ExecContext will prepare and close the statement, and the connection if not kept alive.

**Comment by kurt-google** [comment]
I think something else may have fixed this as the issue is no longer appearing on 0.25.3. Sorry I havnt had time to really dig into this recently, my setup does not make it easy to bisect right now. I should have some time this week to dig in.

**Comment by kurt-google** [comment]
Bisected this and actually the issue was with one of our patches for https://github.com/godror/godror/issues/126 that had a bug in it and was carried through when we updated. At least from 0.25.0 things seem to be working.
