### ISSUE TITLE
Filtering by `time.Time` bind variable not working as expected

### ISSUE THREAD

**Issue by lukasbob** [godror/godror#165]
**Describe the bug**
Insertion of `time.Time` values into a `DATE` column and subsequently filtering by the same `time.Time` value returns no rows since v0.24.1. This is also the case for the latest versions.

I suspect the switch from `DPI_ORACLE_TYPE_DATE` to `DPI_ORACLE_TYPE_TIMESTAMP_TZ` from 0.24.0 to 0.24.1: https://github.com/godror/godror/compare/v0.24.0...v0.24.1

**To Reproduce**
```golang
func TestInsertFilterByTime(t *testing.T) {
    // [Connection code elided - ses is a database connection]

    dropTable := func() {
        if _, err := ses.ExecContext(ctx, "DROP TABLE lc999_test.testtime"); err != nil {
            t.Fatal(err)
        }
    }
    defer dropTable()

    if _, err := ses.ExecContext(ctx, `CREATE TABLE lc999_test.testtime (ID NUMBER, TIMESTAMP DATE)`); err != nil {
        return err
    }

    type scdRow struct {
        ID   int64
        Time time.Time
    }

    want := scdRow{ID: 1, Time: time.Now()}
    if _, err := ses.ExecContext(ctx,
        `insert into lc999_test.testtime (id, timestamp) values (:id, :ts)`,
        sql.Named("id", want.ID),
        sql.Named("ts", want.Time),
    ); err != nil {
        return err
    }

    cases := []struct {
        name, query string
        args        []interface{}
    }{
        { // This case fails
            "by timestamp",
            `select id, timestamp from lc999_test.testtime where timestamp = :ts`,
            []interface{}{sql.Named("ts", want.Time)},
        },
        { // As expected, this case passes
            "by ID",
            `select id, timestamp from lc999_test.testtime where id = :id`,
            []interface{}{sql.Named("id", want.ID)},
        },
    }

    for _, tt := range cases {
        t.Run(tt.name, func(t *testing.T) {
            var got scdRow
            if err := ses.QueryRowContext(ctx, tt.query, tt.args...).Scan(&got.ID, &got.Time); err != nil {
                t.Fatal(err)
            }
            if diff := cmp.Diff(want, got, cmpopts.EquateApproxTime(1*time.Second)); diff != "" {
                t.Error(diff)
            }
        })
    }
}
```

**Expected behavior**
Expected to be able to use a `time.Time` value as a bind varlable in a `where` clause and get rows containing that value.

**Error output**
No error output, but no rows returned.

**Your oracle client version**
12.2.0.1.0

**Your godror version**
v0.24.1 onwards

**Your go version**
1.16.4

**Your gcc version**
9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 

**Machine (please complete the following information):**
 - OS: linux
 - Architecture: x86_64
 - Version: Ubuntu 20.04

**Comment by tgulacsi** [comment]
Oracle's implicit type conversion strikes again!

You have to convert your TIMESTAMP WITH TZ data type to a DATE for comparison:

    select id, timestamp from lc999_test.testtime where timestamp = CAST(:ts AS DATE)

**Comment by lukasbob** [comment]
Nice, thanks you very much for the quick response!
