### ISSUE TITLE
Batch Insert

### ISSUE THREAD

**Issue by monirz** [godror/godror#166]
How do I make a batch insert using godror? 

I'm pretty new to Oracle and using Golang with it. And I usually do it something like  [this](https://stackoverflow.com/questions/12486436/how-do-i-batch-sql-statements-with-package-database-sql) with Postgres driver. But with Godror when I tried like that approach it'll throw me an error like: ```expected 3 arguments, got 6```. I also tried sqlx package with Godror, since it has batch insert option but it also doesn't work and will throw an error like this `could not find name 1 in ...` .
I have also gone through most of the issues if there's any discussion didn't find any.

So, how can I accomplish this with Golang and Oracle using this driver?

**Comment by tgulacsi** [comment]
Use arrays (slices) as argumenta. Each has to be the same lengths, and provide one for each parameter.

**Comment by monirz** [comment]
Oh okay, it works. Thanks for the direction!

**Comment by monirz** [comment]
Hi, another question regarding this. 
Is there a way that I can update on violating unique key constraint with this array/slices insert? Or if it's not possible, then I need  to execute a plain insert or update query, which I also couldn't find a way to do it with godror. So is there a way to do that?

**Comment by tgulacsi** [comment]
See MERGE INTO (https://docs.oracle.com/database/121/SQLRF/statements_9017.htm#SQLRF01606).
Neither easy nor fast for a few hundred inserts.

Better to create a stored procedure, or an anonymous block that receives your arrays as INDEX BY PLS_INTEGER tables, and does the looping and update/insert (IF SQL%ROWCOUNT=0) on the server side.

**Comment by monirz** [comment]
I'm pretty much new with Oracle database, but I think I got what you mean. Have to dig into that, thanks for giving me the idea!

**Comment by tgulacsi** [comment]
```
const qry = `
DECLARE
  TYPE num_tt IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
  TYPE date_tt IS TABLE OF DATE INDEX BY PLS_INTEGER;
  TYPE vc1000_tt IS TABLE OF VARCHAR2(1000) INDEX BY PLS_INTEGER;
  v_arg1 num_tt := :1;
  v_arg2 date_tt := :2;
  v_arg3 vc1000_tt := :3;
  v_idx PLS_INTEGER;
BEGIN
  v_idx := v_arg1.FIRST;
  WHILE v_idx IS NOT NULL LOOP
    UPDATE Table SET F_ield2 = v_arg2(v_idx), F_ield3 = v_arg3(v_idx) WHERE F_ield1 = v_arg1(v_idx);
    IF SQL%ROWCOUNT = 0 THEN
      INSERT INTO Table (F_ield1, F_ield2, F_ield3) VALUES (v_arg1(v_idx), v_arg2(v_idx), v_arg3(v_idx));
    END IF;
    v_idx := v_arg1.NEXT(v_idx);
  END LOOP;
END;
`
  arr1 := []string{"1", "2", "3"}
  arr2 := []time.Time{time.Now().Add(-1*time.Hour), time.Now(-1*time.Minute), time.Now()}
  arr3 := []string{"a", "B", ""}
  _, err := db.ExecContext(ctx, qry, godror.PlSSQLArrays, arr1, arr2, arr3)
```

**Comment by monirz** [comment]
That really looks nice, thank you so much for providing a complete example. How does that's gonna work performance-wise?  It's not gonna  slow down or anything, right?

**Comment by tgulacsi** [comment]
See https://oracle-base.com/articles/9i/merge-statement and https://asktom.oracle.com/pls/apex/f?p=100:11:0::::P11_QUESTION_ID:13401777766527

For a few hundred/thousand rows, this stored procedure will be the fastest.
If you can write your MERGE as a set operation (data is already in the DB), then MERGE INTO will be the fastest.

**Comment by monirz** [comment]
Okay, got it. Merge does seem to be what we need then because we need to insert more records than updating it. Also the request might hit  more than thousands though.  

What about looping through the list for insert and updating it when it gets an error?   Although, it will be mostly inserting new entries, and few cases for updating it.

**Comment by tgulacsi** [comment]
Them maybe the insert-then-update is better.
The best is to mrasure it.

**Comment by monirz** [comment]
Okay got it,  thanks for your suggestion!

**Comment by sudarshan12s** [comment]
not sure if it helps, something like this can be tried?. ( example taken from : https://github.com/godror/godror/discussions/133)
```
stmt, err := tx.PrepareContext(ctx, `MERGE /*+index(x)*/ INTO test_many_rows x 
			USING (select  :ID ID, :text text from dual) y 
			ON (x.id = y.id ) 
			WHEN MATCHED 
				THEN UPDATE SET  x.text = y.text 
			WHEN NOT MATCHED 
				THEN INSERT ( x.ID, x.TEXT) VALUES ( y.ID, y.TEXT)`)
```

**Comment by gyanpatel** [comment]
I was trying to copy bytea column from postgres into string and trying to convert into slice of bytes.
Fetching bytea column into []byte and appending to [][]byte worked for blob batch insert.
Basically I am copying date from Postgres to Oracle. Thanks a lot for you help.

**Comment by tgulacsi** [comment]
https://pkg.go.dev/github.com/godror/godror#Batch may help automate the accumulation.
