### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by Marvin-TMG** [godror/godror#169]
Hi all,

I am trying to create a go container which includes the oracle client and godror driver. The build process is fine, but the container crashes when trying to attempt to open the database connection.

Does anyone have a working example of a Dockerfile to create a container with godror and the oracle client? (size is not a concern)

Thank you in advance.

**Comment by cjbj** [comment]
Oracle has Dockerfiles for Instant Client at https://github.com/oracle/docker-images/tree/main/OracleInstantClient The README has links to pre-built images.  

Also see https://github.com/oracle/docker-images/tree/main/OracleLinuxDevelopers

Also see the blog series [https://blogs.oracle.com/opal/docker-for-oracle-database-applications-in-nodejs-and-python-part-1](https://blogs.oracle.com/opal/docker-for-oracle-database-applications-in-nodejs-and-python-part-1).

**Comment by Marvin-TMG** [comment]
Thanks, I have a working Python variant, so I know how to embed the oracle client.

The problem is related to godror crashing when I do a multi stage build, it works if I do not use static compilation:
```
FROM golang:latest as builder

# Install libraries: wget and unzip are needed to download and extract Oracle client
# Oracle client needs libaio1 as a dependency
RUN apt-get update && apt-get install -y libaio1 wget unzip

# Download and install Oracle client
WORKDIR /opt/oracle
RUN wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip && \
    unzip instantclient-basiclite-linuxx64.zip && rm -f instantclient-basiclite-linuxx64.zip && \
    cd /opt/oracle/instantclient* && rm -f *jdbc* *occi* *mysql* *README *jar uidrvci genezi adrci && \
    echo /opt/oracle/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf && ldconfig

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN GO111MODULE=on CGO_ENABLED=1 GOOS=linux go build -ldflags "-s -w" -o main ${MAIN_PATH}
#RUN GO111MODULE=on CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -ldflags '-linkmode external -extldflags "-static"' -o main ${MAIN_PATH}
```
The above is working (after some certificate magic, which I removed from clarity). However, when I try static compilation, godror crashes. Unfortunately, the latter is needed to create a small runtime container.

Does any of you have some ideas how to solve this?

**Comment by tgulacsi** [comment]
You cannot compile statically, as ODPI loads the OCI client dynamicalliy.

**Comment by Marvin-TMG** [comment]
I see, thanks. That makes sense. Do you have any good suggestions for a compact base image for a two stage build? The image from above will be quite substantial. Otherwise we can close this issue.

**Comment by tgulacsi** [comment]
Why?
You can compile godror with go and a c compiler, and the result will need some libc, that's all.
You can even compile it on the host, and copy that few ten megabytes into a container.

For runtime, a not-alpine base image with installed oracle client is enough.

**Comment by Marvin-TMG** [comment]
Thanks, it is working using the oraclelinux:7-slim image. I was using an alpine based version before.
