### ISSUE TITLE
How insert INTERVAL DAY TO SECOND?

### ISSUE THREAD

**Issue by xhit** [godror/godror#17]
I want to insert INTERVAL DAY TO SECOND using arguments but I can't and test lack of this. Is possible?

**Comment by tgulacsi** [comment]
It should work with time.Duration.
________________________________

**Comment by xhit** [comment]
The select returns a `time.Duration`. But when insert an argument `time.Duration` then this error is triggered:

`12. arg: unknown type time.Duration`

**Comment by xhit** [comment]
Works! Thanks. 

For documentation: Also I published a package to allow convert duration strings returned from time.Duration to time.Duration again for the insert if a user save the select result as is. https://github.com/xhit/go-str2duration
