### ISSUE TITLE
Question: array as nested table (user defined type) but not associative array

### ISSUE THREAD

**Issue by d1m1ch** [godror/godror#172]
**Is your feature request related to a problem? Please describe.**
I really frustrated that I can't implement a go custom type that implements 

database/sql/driver/types.go
```go
// Valuer is the interface providing the Value method.
//
// Types implementing Valuer interface are able to convert
// themselves to a driver Value.
type Valuer interface {
	// Value returns a driver Value.
	// Value must not panic.
	Value() (Value, error)
}
```
and 

database/sql/sql.go
```go
// Scanner is an interface used by Scan.
type Scanner interface {
	// Scan assigns a value from a database driver.
	//
	// The src value will be of one of the following types:
	//
	//    int64
	//    float64
	//    bool
	//    []byte
	//    string
	//    time.Time
	//    nil - for NULL values
	//
	// An error should be returned if the value cannot be stored
	// without loss of information.
	//
	// Reference types such as []byte are only valid until the next call to Scan
	// and should not be retained. Their underlying memory is owned by the driver.
	// If retention is necessary, copy their values before the next call to Scan.
	Scan(src interface{}) error
}

```
interfaces that will convert my custom type to nested table of some defined in the database type

it is possible to implement scanner interface, because inside you are getting a godror.Object and there is no much effort  to convert godror.Object to your custom type

you have an example here z_plsql_types_test.go

BUT for valuer it is much harder because you have to have a connection to get a godror.ObjectType type and then create a godror.Object 

and this objects hold a pointer to a connection in private variable 

and in example you provided you pass a global variable into the write method

**Describe the solution you'd like**
Ideally I wanted to see a standard solution via sql.Valuer sql.Scanner interfaces
but have no idea how

**Describe alternatives you've considered**
I think it is also possible to have your own Valuer interface that addtionaly provides a connection to `Value(conn *sql.Conn) (Value, error)` or context with connection inside

**Additional context**
The main question is: Is it possible to get rid of connection in godror.Object?
is it possible to serialize value somehow into some internal oracle format that oracle would interpret as nested table not associative array?

I am not so experienced with odpi-c and oracle, maybe you could suggest something else besides extracting connection from execer using godror.DriverConn(ctx, ex) because it doesn't look as clean solution

**Comment by tgulacsi** [comment]
For nested tables, godror.Object is the only way to go.
And Object must reside on its initial connection, so DriverConn is a must.

Thus I don't see a clean, database/sql - friendly way.

**Comment by d1m1ch** [comment]
hi, what about the case with additional interface similar to valuer but with additional conn parameter?

**Comment by d1m1ch** [comment]
you, may check inside in the driver that arg implements interface and if so call Value() method with current active connection

**Comment by tgulacsi** [comment]
> hi, what about the case with additional interface similar to valuer but with additional conn parameter?

It is possible, but who would call it? database/sql won't, so it wouldn't happen.
Nor would I pollute the API with such footgun.

If you really want, you can wrap your type with the concrete connection, and implement Valuer that calls your ValueConn with that embedded connection.

What kind of nested table,and how would you use it? You can SELECT from it with TABLE.

**Comment by d1m1ch** [comment]
I offered you add valuer inerface but I've found something similar to valuer interface - it is Writer interface

code below is taken from examples

and I am wondering why 

```
func (r MyTable) WriteObject() error {
	if len(r.Items) == 0 {
		return nil
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	conn, err := godror.DriverConn(ctx, testDb) // testDb is global variable
	if err != nil {
		return err
	}

	data, err := conn.NewData(r.Items[0], len(r.Items), 0)
	if err != nil {
		return err
	}

	for i, item := range r.Items {
		err = item.WriteObject()
		if err != nil {
			return err
		}
		d := data[i]
		d.SetObject(item.ObjectRef())
		r.Append(d)
	}
	return nil
}
```

better than modification I suggest
```
func (r MyTable) WriteObject(ctx context.Context, conn *Conn) error {
	if len(r.Items) == 0 {
		return nil
	}
	data, err := conn.NewData(r.Items[0], len(r.Items), 0)
	if err != nil {
		return err
	}

	for i, item := range r.Items {
		err = item.WriteObject(conn)
		if err != nil {
			return err
		}
		d := data[i]
		d.SetObject(item.ObjectRef())
		r.Append(d)
	}
	return nil
}
```

actually I have no idea why it is called writer because comment says it updates the object

```
// ObjectWriter update database object before binding
type ObjectWriter interface {
	WriteObject() error
	userType
}
```

**Comment by tgulacsi** [comment]
If you bind a godror.Object, and it implements godror.ObjectWriter, then WriteObject is called before sending the Object to Oracle.

See z_plsql_types_test.go TestPLSQLTypes.

**Comment by d1m1ch** [comment]
ok, but why cant you change 

```
// ObjectWriter update database object before binding
type ObjectWriter interface {
	WriteObject() error
	userType
}
```
to
```
// ObjectWriter update database object before binding
type ObjectWriter interface {
	WriteObject(ctx context.Context, conn *Conn) error
	userType
}
```

**Comment by tgulacsi** [comment]
What for? MyRecord/MyTable already contains an Object/ObjectCollection, thus it can read/write the object.

**Comment by d1m1ch** [comment]
to implement something like this
```
type Num9Table struct {
	Items []int64
}

func (t *Num9Table) Scan(src interface{}) error {
	//fmt.Printf("Scan(%T(%#v))\n", src, src)
	obj, ok := src.(*godror.Object)
	if !ok {
		return fmt.Errorf("cannot scan from type %T", src)
	}
	collection := obj.Collection()
	length, err := collection.Len()
	//fmt.Printf("Collection[%d] %#v: %+v\n", length, collection, err)
	if err != nil {
		return err
	}
	if length == 0 {
		return nil
	}
	t.Items = make([]int64, 0, length)
	var i int
	for i, err = collection.First(); err == nil; i, err = collection.Next(i) {
		//fmt.Printf("Scan[%d]: %+v\n", i, err)
		var data godror.Data
		err = collection.GetItem(&data, i)
		if err != nil {
			return err
		}

		t.Items = append(t.Items, data.GetInt64())
	}
	if err == godror.ErrNotExist {
		return nil
	}
	return err
}



func (t *Num9Table) WriteObject(ctx context.Context, conn godror.Conn) error {
	if len(t.Items) == 0 {
		return nil
	}

	ot, err := conn.GetObjectType("MySchema.Num9Table")
	if err != nil {
		return err
	}

	coll, err := ot.NewCollection()
	if err != nil {
		return err
	}

	for _, item := range t.Items {
		err = coll.Append(item)
		if err != nil {
			return err
		}
	}

	return nil
}
```

during implementation I've found one disadvantage, I can't close Object in Write method because I may suggest it will be used further and the only proper way to close it - after execer.ExecCtx method

**Comment by d1m1ch** [comment]
but originally I wanted something like this

**Comment by d1m1ch** [comment]
improved a bit
```
type Num9Table struct {
	Items []int64
	godror.ObjectCollection
}

func (t *Num9Table) Scan(src interface{}) error {
	//fmt.Printf("Scan(%T(%#v))\n", src, src)
	obj, ok := src.(*godror.Object)
	if !ok {
		return fmt.Errorf("cannot scan from type %T", src)
	}
	collection := obj.Collection()
	length, err := collection.Len()
	//fmt.Printf("Collection[%d] %#v: %+v\n", length, collection, err)
	if err != nil {
		return err
	}
	if length == 0 {
		return nil
	}
	t.Items = make([]int64, 0, length)
	var i int
	for i, err = collection.First(); err == nil; i, err = collection.Next(i) {
		//fmt.Printf("Scan[%d]: %+v\n", i, err)
		var data godror.Data
		err = collection.GetItem(&data, i)
		if err != nil {
			return err
		}

		t.Items = append(t.Items, data.GetInt64())
	}
	if err == godror.ErrNotExist {
		return nil
	}
	return err
}



func (t *Num9Table) WriteObject(ctx context.Context, conn godror.Conn) error {
	if len(t.Items) == 0 {
		return nil
	}

	ot, err := conn.GetObjectType("MySchema.Num9Table")
	if err != nil {
		return err
	}

	t.ObjectCollection, err = ot.NewCollection()
	if err != nil {
		return err
	}

	for _, item := range t.Items {
		err = t.ObjectCollection.Append(item)
		if err != nil {
			return err
		}
	}

	return nil
}

// this will be called by driver after execution to free resources
func (t *Num9Table) Close() error {
	return t.ObjectCollection.Close()
}

```

the main idea is to avoid hacks like godror.GetObjectType and godror.DriverConn

**Comment by tgulacsi** [comment]
I still doesn't get it.
How do you do it with the current API?
Why can't you do it with it?

**Comment by d1m1ch** [comment]
> How do you do it with the current API?

nohow
> Why can't you do it with it?

technically I may do something similar but I need additional initialization function for my type to initialize godror.ObjectCollection with ObjectType  and to initialize ObjectType  I need to call godror.GetObjectType or godror.DriverConn

and one more tricky moment that I use interface similar to sql.Execer but not compatible with it so I need one more hack like 

```
var getConnMu sync.Mutex
const getConnection = "--GET_CONNECTION--"

// getConn will acquire a separate connection to the same DB as what ex is connected to.
func getConn(ctx context.Context, ex Execer) (godror.Conn, error) {
	getConnMu.Lock()
	defer getConnMu.Unlock()
	var c interface{}
	if _, err := ex.ExecContext(ctx, getConnection, sql.Out{Dest: &c}); err != nil {
		return nil, fmt.Errorf("getConnection: %w", err)
	} else if c == nil {
		return nil, errors.New("nil connection")
	}
	return c.(godror.Conn), nil
}
```

**Comment by tgulacsi** [comment]
What's the matter with z_plsql_types_test.go line 395 ?

**Comment by d1m1ch** [comment]
what do you mean?

**Comment by tgulacsi** [comment]
As far as I see, it implements a type that is a table of sth, puts data to the db, anf retrieves it.

**Comment by d1m1ch** [comment]
yes, but in this example you already have connection
https://github.com/godror/godror/blob/main/z_plsql_types_test.go#L397

In my application I have no connection, only execer and it is not compatible with sql.Execer

**Comment by d1m1ch** [comment]
I also thought that I might scan godror object without holding and initializing godror.Object on my custom type but it doesn't work right now

**Comment by tgulacsi** [comment]
> yes, but in this example you already have connection
> https://github.com/godror/godror/blob/main/z_plsql_types_test.go#L397
> 
> In my application I have no connection, only execer and it is not compatible with sql.Execer

It must use an sql.DB/Tx/Stmt/Conn under the hood.
Unbury it first.

**Comment by d1m1ch** [comment]
hi, could you please explain why do you need connection stored on ObjectType?
for what purpose it is stored there?

**Comment by tgulacsi** [comment]
As you can see it in obj.go, an Object needs the dpiObject handle to be able to set/retriev attributes, values.
An ObjectType needs dpiObjectType for NewObject, NewCollection.
We can elminiate the latter by retrieving the type info fresh on each NewObject/NewCollection.

We also need dpiObjectType on user-defined type (with ObjectRef), and bind variables.

**Comment by d1m1ch** [comment]
I see several cases of using connection:
 - ```C.dpiConn_getObjectType(c.dpiConn, cName, C.uint32_t(len(name)), &objType)``` to retrieve object type info
 - ```v, dpiData, err := c.newVar(vi)``` to create new data

but I don't unerstand why you need connection in cases like these two:
 - ```
    O.conn.checkExec(func() C.int {
		return C.dpiObject_setElementValueByIndex(O.dpiObject, C.int32_t(i), data.NativeTypeNum, &data.dpiData)
	}
   ```
  - ```
     if C.dpiObject_setAttributeValue(O.dpiObject, attr.dpiObjectAttr, data.NativeTypeNum, &data.dpiData) == C.DPI_FAILURE {
			return O.conn.getError()
		}
  ```  
  could you please explain why do you wrap cgo call with  `O.conn.checkExec(func() C.int {` ? are they connected somehow?

**Comment by tgulacsi** [comment]
You do need the connecttion for every interaction with the database.
For example, the error retrieval needs the connecttion.

**Comment by tgulacsi** [comment]
A dpiObjectType is inherently tied to a dpiConn, and thus a dpiObject, too.
