### ISSUE TITLE
Configure hostname connection request

### ISSUE THREAD

**Issue by under0x** [godror/godror#175]
In the connection request, how can configurate this value

v$session.machine

Usually is the hostname, this because we gonna use go in openshift with quarkus

In java we use this:

quarkus.datasource."jdbc_name".jdbc.additional-jdbc-properties."v$session.machine"=${K8S_POD_NODENAME}

Where K8S_POD_NODENAME is the pod of execution.

So, where can we configurate that in the connection string in godror? Exist something like that?

Thanks a lot!

**Comment by cjbj** [comment]
I don't immediately see a way in OCI to set this.  A related question was https://github.com/oracle/node-oracledb/issues/1163 (node-oracledb and godor both use ODPI-C and OCI)

For us non-openshift users can you explain what this actually does and why there is no other workaround?

**Comment by tgulacsi** [comment]
action, module, clientinfo, clientidentifier and dbop are setable through godror.ContextWithTraceTag. But I see no way to set it with ODPI-C or OCI (https://docs.oracle.com/en/database/oracle/oracle-database/19/lnoci/handle-and-descriptor-attributes.html#GUID-580A7DB4-9B3E-47CF-B0E6-F5CF3C8AE48E).
