### ISSUE TITLE
Can't Read CLOB data 

### ISSUE THREAD

**Issue by monirz** [godror/godror#176]
Hi, I have column in a table with CLOB data type `jsonData   CLOB NULL` , and I inserted an array of struct using `json.Marshal` like this: 
```
	jsonData, err := json.Marshal(persons)
       ... 

      Exec(query,  jsonData) 

```

Now I'm tryin to read the data like this

```	
ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)

	defer cancel()

	rows, err := DB.QueryContext(ctx, "select jsonData from batches", godror.LobAsReader())

	for rows.Next() {
		var clob interface{}
		if err != nil {
			log.Println(err)
			continue
		}
		if err = rows.Scan(&clob); err != nil {
			rows.Close()

			log.Println("error scanning", err)
			continue
		}

		if clob, ok := clob.(*godror.Lob); !ok {
			log.Println("err ", clob)
		} else {
			var person []byte
			if person, err = ioutil.ReadAll(clob); err != nil {
				log.Println("err: ", err)
			}

			log.Println(string(person))
		}

	}

	rows.Close()


```
	

But I get :  
short buffer  error or  something like this once  5B7B226964223A322C226868644C697374223A5B7B226964223A332C

What I'm missing here?

**Comment by tgulacsi** [comment]
ioutil.ReadAll does not work for this. Use io Copy.

**Comment by monirz** [comment]
Hi, it did not work, With io.Copy() I get something like this

```
5B7B226964223A322C226868644C697374223A5B7B226964223A332C22756964223A2237353965303939632D393863632D346432342D623235642D336532623066656462306632222C22513135223A31352C22713136223A22746573742071313620616E7377657220616E6F74686572222C22713137223A31352C22713138223A322C22713230223A312C22713231223A392C22713232223A312C22713234223A312C22713236223A312C22713237223A312C22713238223A312C22713239223A322C22713330223A312C22713331223A312C22713332223A312C22713333223A317D2C7B226964223A332C22756964223A2239616331363234352D336633622D343465322D623761662D366337386562356562653165222C22513135223A332C22713136223A227465737420616E73776572222C22713137223A312C22713138223A322C22713230223A312C22713231223A392C22713232223A312C22713234223A312C22713236223A312C22713237223A312C22713238223A312C22713239223A322C22713330223A312C22713331223A312C22713332223A312C22713333223A317D5D2C22654964223A22222C22756964223A223131313131222C22624964223A22222C226D6F223A22303336222C22766C223A22303130222C226561223A22616E6F7468657220686F757365222C22626C736C223A31312C22666C72223A31302C227131223A312C22713241223A2271324120616E73776572222C22713242223A222071324220646966666572656E74222C227133223A35352C227134223A35352C227135223A35352C227136223A35352C227137223A36362C227138223A312C227139223A312C22713130223A312C22713131223A312C2271313241223A302C2271313242223A302C22713133223A312C22713134223A31302C226C6174223A33372E343231393938332C226C6F6E223A2D3132322E3038342C22636F6D6D656E74223A22222C22726563537461747573223A302C22697353796E63686564223A302C22697350223A322C22764964223A302C2276657273696F6E223A302C226D5F6164646564223A307D5D
```  

My example code: 

```

			var n int64
			var b bytes.Buffer

			if n, err = io.Copy(&b, clob); err != nil {
				log.Println("err: ", err)
			}

			buf := b.Bytes()

			log.Println(string(buf), n)
``` 

Thanks!

**Comment by monirz** [comment]
I have tried with your latest commit, now with `io.ReadAll()` does not give that error, but I'm still getting an string like this `5B7B226964223A322C226868644C697374223A5B7B226964223A332C22756964223A2264396462613831312D396237342D346466362D383766642D353433323334393933336232222C22513135223A31352C22713136223A22746573742071313620616E7377657220616E6F74686572222C22713137223A31352C22713138223A322C22713230223A312C22713231223A392C22713232223A312C22713234223A312C22713236223A312C22713237223A312C22713238223A312C22713239223A322C22713330223A312C22713331223A312C22713332223A312C22713333223A317D2C7B226964223A332C22756964223A2238623530373238322D376334`

The result is same with io.Copy() or io.ReadAll() 

Do you think my inserting is wrong, like inserting the byte array that comes from json.Marshal? That's how I did it with other databases.

**Comment by monirz** [comment]
If it is, then how can I reverse it to the byte array I have inserted? Is there a way?  Apparently inserting it as JSON string works fine.

**Comment by tgulacsi** [comment]
That is a HEX encoding of binary, as stored by Oracle RAWTOHEX.
```
echo 5B7B226964223A322C226868644C697374223A5B7B226964223A332C22756964223A2264396462613831312D396237342D346466362D383766642D353433323334393933336232222C22513135223A31352C22713136223A22746573742071313620616E7377657220616E6F74686572222C22713137223A31352C22713138223A322C22713230223A312C22713231223A392C22713232223A312C22713234223A312C22713236223A312C22713237223A312C22713238223A312C22713239223A322C22713330223A312C22713331223A312C22713332223A312C22713333223A317D2C7B226964223A332C22756964223A2238623530373238322D376334 | xxd -r -p

[{"id":2,"hhdList":[{"id":3,"uid":"d9dba811-9b74-4df6-87fd-5432349933b2","Q15":15,"q16":"test q16 answer another","q17":15,"q18":2,"q20":1,"q21":9,"q22":1,"q24":1,"q26":1,"q
27":1,"q28":1,"q29":2,"q30":1,"q31":1,"q32":1,"q33":1},{"id":3,"uid":"8b507282-7c4
```

For reading the JSON, what do you want?
If you want to retrieve the JSON into memory, don't use godror.LobAsReader, but plain []byte (fot BLOB) or string (for CLOB).
If you want to parse the JSON, then instead of io.ReadAll, `json.NewDecoder(lob).Decode(&v)`.

But I bet that you've stored that JSON corruptly, that's why it's encoded as HEX - maybe you've stored []byte in CLOB?

As JSON is UTF-8 encoded, and you don't want to let your DB's encoding mess with it, store the JSON in a BLOB!

**Comment by monirz** [comment]
Ah okay, got it. So it looks like all of them are missing half of the fields from  the struct when decoding from hex manually. But When I print the  json.Marshaled byte as a string where it is inserting the byte array into the table, it shows as a valid json and expected array of objects. 
Now what it could be the reason for those missing field?   

At first I tried JSON Unmarshal for that column data but it returned null, so wondered what I'm doing wrong. 

What I need is just the JSON string or anything I can decode to the struct or something.

**Comment by monirz** [comment]
Yes I have stored []byte in CLOB, like this: 
```
jsonData, err := json.Marshal(batch.HouseList)
Exec(query,  jsonData)
```

**Comment by monirz** [comment]
Yes I have stored []byte in CLOB, like this:

```
jsonData, err := json.Marshal(hList)
Exec(query,  jsonData)
```

I can change that column data type to blob and storing []byte would be fine, right? But can I read those already inserted []byte into CLOB as json string?

**Comment by tgulacsi** [comment]
See https://blogs.oracle.com/sql/post/how-to-store-query-and-create-json-documents-in-oracle-database why BLOB is better (till 21c, where JSON is a new database type).

You can use CLOB, but insert a string (`string(jsonData)`), not a []byte !
