### ISSUE TITLE
Default database/sql functions with context ignore context's timeout

### ISSUE THREAD

**Issue by tandem97** [godror/godror#178]
**Describe the bug**
functions using context ignore context's timeout

**To Reproduce**
```package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"time"

	_ "github.com/godror/godror"
)

func main() {
	db, err := sql.Open("godror", `user="scott" password="tiger" connectString="192.168.0.145:1521/orclpdb1"`)
	if err != nil {
		log.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	timestamp := time.Now()
	err = db.PingContext(ctx)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(time.Since(timestamp))
}
```

**Expected behavior**
error after 2 seconds

**Your oracle client version**
19.12.0.0.0

**Your godror version**
e.g. v0.25.4

**Your go version**
e.g. 1.17

**Machine (please complete the following information):**
win 10 x64

**Comment by tgulacsi** [comment]
Is OOB (out of bounds) signaling enabled?

**Comment by tandem97** [comment]
> Is OOB (out of bounds) signaling enabled?

how can i check or enable it?

**Comment by tandem97** [comment]
I need to add that this host is unreachable, may be this is important for you

**Comment by tgulacsi** [comment]
What is in `tnsnames.ora`, `sqlnet.ora` ?
OCI is a beast, it may or may not return in time.

If you se godror.Log to something that prints to stderr, what is printed with "setCallTimeout"?
What if you run it with DPI_DEBUG_LEVEL=92 enviroment variable set?
Where does it hang?

**Comment by tandem97** [comment]
> What is in `tnsnames.ora`, `sqlnet.ora` ?
> OCI is a beast, it may or may not return in time.
> 
> If you se godror.Log to something that prints to stderr, what is printed with "setCallTimeout"?
> What if you run it with DPI_DEBUG_LEVEL=92 enviroment variable set?
> Where does it hang?

This is output with DPI_DEBUG_LEVEL=92 

```
PS D:\go\src\Test> go run .\main.go
ODPI [02452] 2021-09-13 20:56:06.150: ODPI-C 4.2.1
ODPI [02452] 2021-09-13 20:56:06.155: debugging messages initialized at level 92
ODPI [02452] 2021-09-13 20:56:06.171: fn start dpiContext_createWithParams
ODPI [02452] 2021-09-13 20:56:06.177: Context Parameters:
ODPI [02452] 2021-09-13 20:56:06.182: Environment Variables:
ODPI [02452] 2021-09-13 20:56:06.187:     PATH => "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\msys64\mingw64\bin;C:\Program Files\Go\bin;C:\Users\└ыхъёхщ\AppData\Local\Microsoft\WindowsApps;;D:\Program Files (x86)\VS Code\Microsoft VS Code\bin;C:\Users\└ыхъёхщ\.dotnet\tools;C:\Users\└ыхъёхщ\go\bin"
ODPI [02452] 2021-09-13 20:56:06.252: check module directory
ODPI [02452] 2021-09-13 20:56:06.257: module name is C:\Users\CD86~1\AppData\Local\Temp\go-build2918066065\b001\exe\main.exe
ODPI [02452] 2021-09-13 20:56:06.268: load in dir C:\Users\CD86~1\AppData\Local\Temp\go-build2918066065\b001\exe
ODPI [02452] 2021-09-13 20:56:06.277: load with name C:\Users\CD86~1\AppData\Local\Temp\go-build2918066065\b001\exe/oci.dll
ODPI [02452] 2021-09-13 20:56:06.286: load by OS failure: The specified module could not be found
ODPI [02452] 2021-09-13 20:56:06.339: load with OS search heuristics
ODPI [02452] 2021-09-13 20:56:06.354: load with name oci.dll
ODPI [02452] 2021-09-13 20:56:06.360: load by OS successful
ODPI [02452] 2021-09-13 20:56:06.365: validating loaded library
ODPI [02452] 2021-09-13 20:56:06.389: fn end dpiContext_createWithParams -> 0
ODPI [02452] 2021-09-13 20:56:06.395: fn start dpiContext_getClientVersion(0000025ec8a61d80)
ODPI [02452] 2021-09-13 20:56:06.401: fn end dpiContext_getClientVersion(0000025ec8a61d80) -> 0
ODPI [02452] 2021-09-13 20:56:06.407: fn start dpiContext_initCommonCreateParams(0000025ec8a61d80)
ODPI [02452] 2021-09-13 20:56:06.413: fn end dpiContext_initCommonCreateParams(0000025ec8a61d80) -> 0
ODPI [02452] 2021-09-13 20:56:06.422: fn start dpiContext_initPoolCreateParams(0000025ec8a61d80)
ODPI [02452] 2021-09-13 20:56:06.428: fn end dpiContext_initPoolCreateParams(0000025ec8a61d80) -> 0
ODPI [02452] 2021-09-13 20:56:06.436: fn start dpiPool_create(0000025ec8a61d80)
ODPI [02452] 2021-09-13 20:56:27.724: OCI error ORA-12170: TNS:Connect timeout occurred (dpiPool_create / create pool)
ODPI [02452] 2021-09-13 20:56:27.735: fn end dpiPool_create(0000025ec8a61d80) -> -1
params=user=scott password="SECRET-4NMAKZqXbbo=" connectString=192.168.0.36:1521/orclpdb1
timezone= poolIncrement=1 poolMaxSessions=1000 poolMinSessions=1 poolSessionMaxLifetime=1h0m0s
poolSessionTimeout=5m0s poolWaitTimeout=30s extAuth=0: ORA-12170: TNS:Connect timeout occurred
21.5723404s
```

i dont have tnsnames.ora and sqlnet.ora, I use a connection string so i dont need them
How i can get godror logs?

**Comment by sudarshan12s** [comment]
The deadline mentioned in context is used after connection is established . In this case a connection could not be established . 

Can you try passing connect_timeout as arguments to connectstring like below in sql.open
connectString="ip:1521/svcname?connect_timeout=5

connect_timeout (and the related options like SQLNET.OUTBOUND_CONNECT_TIMEOUT) affect the time taken to open a connection to a DB.

The tech article https://download.oracle.com/ocomdocs/global/Oracle-Net-19c-Easy-Connect-Plus.pdf  shows options that might be usable, "mydbmachine.example.com/orclpdb1?connect_timeout=15"

**Comment by tandem97** [comment]
> ?connect_timeout=5

Thats works thanks! So is there any reason to use pingwithcontext if connection timeout we set in connection string. What  exactly Ping check?

**Comment by sudarshan12s** [comment]
Ping is another roundtrip call which sends dummy packet and wait for server response. 

> > The deadline mentioned in context is used after connection is established . In this case a connection could not be established .
> > Can you try passing connect_timeout as arguments to connectstring like below in sql.open
> > connectString="ip:1521/svcname?connect_timeout=5
> > connect_timeout (and the related options like SQLNET.OUTBOUND_CONNECT_TIMEOUT) affect the time taken to open a connection to a DB.
> > The tech article https://download.oracle.com/ocomdocs/global/Oracle-Net-19c-Easy-Connect-Plus.pdf shows options that might be usable, "mydbmachine.example.com/orclpdb1?connect_timeout=15"
> 
> That's works, thanks! So is there any reason to use pingwithcontext if connection timeout we set in connection string. What exactly Ping check?

Yes Ping involves a light weight call , sending some dummy packet to server and wait for response on established connection . so context can help breaking this active Ping function.

**Comment by tandem97** [comment]
> Ping is another roundtrip call which sends dummy packet and wait for server response.
> 
> > > The deadline mentioned in context is used after connection is established . In this case a connection could not be established .
> > > Can you try passing connect_timeout as arguments to connectstring like below in sql.open
> > > connectString="ip:1521/svcname?connect_timeout=5
> > > connect_timeout (and the related options like SQLNET.OUTBOUND_CONNECT_TIMEOUT) affect the time taken to open a connection to a DB.
> > > The tech article https://download.oracle.com/ocomdocs/global/Oracle-Net-19c-Easy-Connect-Plus.pdf shows options that might be usable, "mydbmachine.example.com/orclpdb1?connect_timeout=15"
> > 
> > 
> > That's works, thanks! So is there any reason to use pingwithcontext if connection timeout we set in connection string. What exactly Ping check?
> 
> Yes Ping involves a light weight call , sending some dummy packet to server and wait for response on established connection . so context can help breaking this active Ping function.

Thank everyone for help and answers!
