### ISSUE TITLE
Godror does not find the newly added column in the database with alter statement. 

### ISSUE THREAD

**Issue by monirz** [godror/godror#183]
Hi, so recently we had to add a new column to the existing database, and added the column with alter statement. And it works fine in the sqlplus, like with the select query it returns the column without any issues. But when I'm trying it with Golang using Godror, it does throw an error like this: `ORA-00904: "IMS_ID": invalid identifier`. Tried restarting the database, it did not work.  

To simply the test I have tried running the Golang code like this: 

```golang
package main

import (
	"context"
	"database/sql"
	"log"
	"time"

	"github.com/godror/godror"
	_ "github.com/godror/godror"
)

var DB *sql.DB

func main() {

	var P godror.ConnectionParams

	P.Username, P.Password = "username", godror.NewPassword("password")
	P.ConnectString = "host:1521/dbs:pooled?connect_timeout=5"
	P.SessionTimeout = 42 * time.Second

	// P.PoolParams.SessionIncrement = 30
	P.PoolParams.MaxSessions = 10

	DB = sql.OpenDB(godror.NewConnector(P))

	defer DB.Close()

	if err := DB.Ping(); err != nil {
		log.Fatal(err, " dsn: ")
	}

	//run the query
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)

	defer cancel()

	query := `
	select 
		ims_id
		from  users
	`

	rows, err := DB.QueryContext(ctx, query)

	imsID := ""

	if err != nil {
		log.Fatal(err)
	}

	for rows.Next() {
		rows.Scan(&imsID)
		log.Fatal(imsID)
	}

}

```

What am I missing here? Can you give me any idea?

**Comment by sudarshan12s** [comment]
can you add alter query cmd in the program along with select query and reproduce the issue, it gives complete standalone program to debug.

``` 
const qry = `alter table emp ADD newcol VARCHAR2(50)`
    if _, err := db.ExecContext(ctx, qry); err != nil {
        fmt.Printf("%s: %+v", qry, err)
    }
```

**Comment by monirz** [comment]
It actually works when the alter statement executed with the driver/code. But it's strange why didn't it work when it is executed with sqlplus. But it solves my problem eventually, I can add column through the code.

**Comment by tgulacsi** [comment]
As Oracle cannot rollback DDL operations (ALTER, CREATE, DROP...), they implicitly issue a COMMIT if in a transaction.
Also, Oracle uses READ COMMITED isolation level by default, the commited transaction's result will be seen in every other transaction after the commit.

So it cannot happen that your ALTER succeeded in sqlplus, but you cannot see it in Go.
Either you read/modified different databases, or the ALTER failed silently.
