### ISSUE TITLE
DB connection is not changing to other DB 

### ISSUE THREAD

**Issue by ankurnigam** [godror/godror#184]
Hi Team, 

I am trying to run one SQL on multiple databases on exadata sequentially, I have single variable "db" for connection and we are closing is exclusively as well.

Still what I can see db connection is still pointing to old database even though I have changed all variable.

I try to debug it and found as below :

Info: 2021/09/23 18:58:50 common.go:141: Collecting Resource status for ukljwusv2
Info: 2021/09/23 18:58:50 common.go:141: ORACLE_SID : ukljwusv2
Info: 2021/09/23 18:58:50 common.go:141: ORACLE_HOME : /u02/app/oracle/product/19.0.0.0/dbhome_1
Info: 2021/09/23 18:58:50 common.go:141: LD_LIBRARY_PATH : /u02/app/oracle/product/19.0.0.0/dbhome_1/lib
Info: 2021/09/23 18:58:50 common.go:141: PATH : /bin:/usr/bin:/u01/app/19.0.0.0/grid/bin:/u02/app/oracle/product/19.0.0.0/dbhome_1/bin
Info: 2021/09/23 18:58:50 common.go:141: Orapass : XXXXXXXX
Info: 2021/09/23 18:58:50 common.go:141: Orauser : XXXXXXX
Info: 2021/09/23 18:58:50 common.go:141: Quering ukljwusv2
Info: 2021/09/23 18:58:50 common.go:141: DB : UKLHPDFQ <= output of select dbname from v$database.

I have checked and didn't find anything wrong I am doing here as same code was working since long time , only changes I did is earlier I was using "/ as sysdba" now I am using different user.

I did check manually trying to login using same set of variable and able to login.

$ export ORACLE_SID=ukljwusv2
$ export ORACLE_HOME=/u02/app/oracle/product/19.0.0.0/dbhome_1
$ export LD_LIBRARY_PATH=/u02/app/oracle/product/19.0.0.0/dbhome_1/lib
$ export PATH=/bin:/usr/bin:/u01/app/19.0.0.0/grid/bin:/u02/app/oracle/product/19.0.0.0/dbhome_1/bin
$ sqlplus *****/*******

SQL*Plus: Release 19.0.0.0.0 - Production on Thu Sep 23 19:07:30 2021
Version 19.11.0.0.0

Copyright (c) 1982, 2020, Oracle.  All rights reserved.

Last Successful login time: Thu Sep 23 2021 18:20:38 +00:00

Connected to:
Oracle Database 19c EE Extreme Perf Release 19.0.0.0.0 - Production
Version 19.9.0.0.0

SQL> select name from v$database;

NAME
---------
UKLJWUSV

Code to make connection  : 

connect_string := ora_user + "/" + ora_pass
	db, err := sql.Open("godror", connect_string)
if err != nil {}
defer db.Close()

**Comment by tgulacsi** [comment]
Where do you change / specify the target database?
Be explicit, see README and docs/connection.md

**Comment by ankurnigam** [comment]
I am connecting locally on server and when you set all the variable you don't need to set DB name in connect string. Please let me know if you think it's incorrect ?

**Comment by ankurnigam** [comment]
This is snippet of the function I am calling by passing ORACLE_SID .Using ORACLE_SID I am updating complete env variable.

**Comment by ankurnigam** [comment]
I also don't get any error in this condition if err != nil {}. Please let me know if I can print db connection to validate if it's able to connect the DB or not as I don't see any error in error handling.

**Comment by ankurnigam** [comment]
OS user is different than Oracle .FYI

**Comment by ankurnigam** [comment]
The issue is that first database it was able connect but for next database it was not. When I exclusively provided connection string it was able to work.  We need to check on this that if we set complete environment and we doesn't require to setup complete connection string. 

working code  : 

connect_string := ora_user + "/" + ora_pass + "@hostname/" + oracleUniqueDBName
