### ISSUE TITLE
Proposal: cast bool type in arguments for insert

### ISSUE THREAD

**Issue by xhit** [godror/godror#19]
Oracle, like others RDBMS, don't have the boolean type, but normally the user use` CHAR(1)`, `VARCHAR(1)`, `NUMBER(1,0)` _(this case less efficient)_, and others golang sql drivers manage bool in arguments to cast to 1 or 0 depending the value of boolean.

I propose cast the bool type in the driver for avoid the error `ORA-00932: inconsistent datatypes: expected CHAR got BOOLEAN` when insert a bool.

**Comment by tgulacsi** [comment]
Ok, what is the proposal?

How to translate between true/false and its database representation?
For numbers, 0=false, 1=true is general enough; but for CHAR(1)/VARCHAR2(1), I use N/I, you N/Y or F/T, others something else...

So we can make a type that is a bool on the Go side, but translates (with Value method) to something on the DB side - and the same for the other way:

    type engBool bool
    func (b engBool) Value() interface{} { if b { return "Y" }; return "N"; }
    func (b *engBool) Scan(src interface{}) error { *b = src.(string) == "Y" }

This is a type that anybody can implement and tweak to their need, and will work.

From API side, if we could make a type creator that embeds what a true and what a false string value is, then that helper function would ease a lot. But now I cannot assemble such a generic function...

**Comment by xhit** [comment]
The proposal is only for insert. 

We can't assume with Scan that a value` if string == "Y"` is `true` or `false` because, is better leave this part to the programmers because their knows the table schema for data management. Oracle don't have `BOOL` so I think that returns a `bool` need an API like you say for the programmer send what is `true` or `false`, but this task is very simple to implement outside the driver.

For insert is different. You receive a `Value` for convert to a valid value in the destination column, but if you receive a `bool` this type is not managed.

Like you said, an API need to be created. So this implementation can works:

In the driver make a exported struct with default values (1 and 0 in this example, can be others)
```go
type CustomBool struct{
	TrueValue 		string
	FalseValue		string
}

var BoolValue = CustomBool{
	TrueValue:"1",
	FalseValue:"0",
}
```

And in `Value` for `CHAR`, `VARCHAR2` and `NUMBER` (others datatype can be added) in the switch type conversion if `bool` then `if true set TrueValue else set FalseValue`

And the programmer can set the value for `CustomBool` or `BoolValue`

```go
godror.BoolValue.TrueValue = "T"
godror.BoolValue.FalseValue = "F"

//or

var customBool godror.CustomBool 
customBool.TrueValue = "T"
customBool.FalseValue = "F"
godror.BoolValue = customBool
```

Note: This implementation is an example.

**Comment by tgulacsi** [comment]
Please take a look at booler in z_test.go at 109c805.

What's the matter providing a proper type that implements Scanner and Valuer?

**Comment by xhit** [comment]
> Please take a look at booler in z_test.go at 109c805.

I like it.

> What's the matter providing a proper type that implements Scanner and Valuer?

Nothing. I only document a little more about Valuer. It's a simple implementation that require the API for booler know what is true or false.

For Scan, if string, need to read the TrueValue of the API, not only Y.

For Valuer, return TrueValue and FalseValue depending the boolean. Like in proposal implementation example. the exported struct can works.

**Comment by tgulacsi** [comment]
PTAL 52e0c35 - it does only the bool->string route, but the other (string->bool) should not be automatic, only opt-in (by scanning into a bool that knows how to Scan into).

**Comment by xhit** [comment]
Tested.

Works like expected.

Is this a simple test before implementation right?

In this part, would be better always return the values in BoolString (and need to be part of the driver).

```go
type Booler bool

func (b *Booler) Scan(src interface{}) error {
	switch x := src.(type) {
	case int:
		*b = x == 1
	case string:
		*b = x == boolString.True
	default:
		return fmt.Errorf("unknown scanner source %T", src)
	}
	return nil
}
func (b Booler) Value() (driver.Value, error) {
	if b {
		return boolString.True, nil
	}
	return boolString.False, nil
}
```

I think this is goal. Thanks for that!

**Comment by cjbj** [comment]
Oracle PL/SQL does have a `BOOLEAN` type.  It can be bound to (in general), e.g. see https://github.com/oracle/python-cx_Oracle/blob/master/test/BooleanVar.py for Python.

**Comment by tgulacsi** [comment]
@cjbj - yes, godror allows bool/BOOLEAN, but here the question is that SQL and tables does not allow a BOOLEAN (only PL/SQL).
So this change allows a general converter to be specified - but only for DML statements! 

@xhit - yes, this is a first iteration. This only implements a bool -> string conversion for DML statements, when the user specifies the conversion.
Now I have an idea for the other way, but that needs a little investigation.
