### ISSUE TITLE
PingContext hang When connecting to the database concurrently

### ISSUE THREAD

**Issue by freeman983** [godror/godror#190]
**Describe the bug**
 upgrading to v0.25.4 v.28.0  
PingContext hang When connecting to the database concurrently
use  v0.25.3 no problems

**To Reproduce**
```
type OracleGoDrorExec struct {
}

func CreatAndPing(host, port, service, user, pwd string, index int, ch chan int) (error, *OracleGoDrorExec) {
	o := &OracleGoDrorExec{}
	var P godror.ConnectionParams
	var pp godror.PoolParams
	var cp godror.ConnParams
	pp.SessionTimeout = 15
	P.ConnectString = fmt.Sprintf("%s:%s/%s", host, port, service)
	P.Username = user
	P.Password = godror.NewPassword(pwd)
        P.SessionTimeout = 15 * time.Second
	P.Timezone = time.Local
	P.StandaloneConnection = true
	P.PoolParams = pp
	P.ConnParams = cp
	P.WaitTimeout = 10 * time.Second
	dd := sql.OpenDB(godror.NewConnector(P))
	ctx, cancel := context.WithTimeout(context.TODO(), 5*time.Second)
	defer cancel()
	//
	err := dd.PingContext(ctx)
	if err != nil {
		fmt.Println("index:", index, " err:", err)
		return err, nil
	}
	ch <- index
	return nil, o
}

func TestAll() error {
	sf := &engine.SQLExecFactory{}
	sf.RefreshAll()
	return nil
}

func Test0253After() error {
	var testCons [][]string

	n := 100
	i := 0
	ch := make(chan int, n)

	for i < n {
		i++
		//Available connection configurations
		data := []string{"172.21.4.253", "1521", "sadb", "root", "root"}
		if i <= 10 {
			/******
			A separate request for this configuration will return a timeout error, which is used here to reproduce the problem
			//error message
			user="exopen" ConnectString="192.168.
			66.100:6688/acdb"
			standalone params={authMode:0 connectionClass:<nil>
			connectionClassLength:0 purity:0 newPassword:<nil>
			newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:0 externalHandle:<nil> pool:<nil> tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}:
			ORA-12170: TNS:Connect timeout occurred
			*/
			data = []string{"192.168.66.100", "6688", "acdb", "exopen", "PpvClh"}
		}
		testCons = append(testCons, data)
	}

	for idx, con := range testCons {
		go CreatAndPing(con[0], con[1], con[2], con[3], con[4], idx, ch)
	}

	count := 0
	for {
		success_index := <-ch
		count = count + 1

		if count < 100 {
			fmt.Println("success:", success_index, count)
		} else {
			fmt.Println("all done", count)
		}
	}

	return nil
}

//main.go 
Test0253After();

for{

}


```
//Need to try a few more times, there is a certain probability that it will appear
//Did not return all the results
//Switching to v2.5.4 v.2.6.0  v.2.8.0 

success_index: 30 1
success_index: 29 2
success_index: 44 3
success_index: 69 4
success_index: 70 5
success_index: 88 6
success_index: 26 7
success_index: 9 8
success_index: 31 9
success_index: 48 10
success_index: 46 11

**Expected behavior**
//Switching to v2.5.3 is ok

....
success: 78 98
success: 23 99
all done 100

**Error output**
Copy the error output (panic, stack trace),
or the output of running with `DPI_DEBUG_LEVEL=92`.

**Your oracle client version**
e.g. 11.1

**Your godror version**
v0.28.0 v0.25.4 ...

**Your go version**
GOVERSION="go1.16.4"

**Your gcc version**
4.2.1

**Machine (please complete the following information):**
 - OS: [e.g. win]
 - Architecture: [e.g. x86_64]
 - Version: [e.g. 10]

**Additional context**

**Comment by tgulacsi** [comment]
You create a separate connection pool for each iteration, and keep it open. This is far from a real-world use case.

Regarding the timeout, run with godror.SetLogger set and see whether it calls Break (conn.go ociBreakDone and Break methods), and how long does it take for dpiConn_breakExecution to return.

I don't have a timeouting server or mock listener. How have you created yours?

**Comment by sudarshan12s** [comment]
The dpiConn_breakExecution will be used after the connection is established and queries are in progress. 
even for Ping , first connection is established and then a ping packet is sent over the established connection. dpiConn_breakExecution is applied after connection establishment and when the ping packet is transmitted. 

Here it looks the connection itself are not established , it could also be because of NET level parameter changes.

@freeman983 , are there any server/client side sqlnet.ora config changes after upgrading client godror version?
or application changes with respect to network timeouts.

**Comment by freeman983** [comment]
@sudarshan12s There is no configuration change, this problem will only occur after 0.25.3, and it will not hang if it is switched to 0.25.3 ，I guess the update in 0.25.4 caused the problem

**Comment by tgulacsi** [comment]
Now I'm a bit confused: if the connection establishment takes long, and not the Ping, then it should've timed out in v0.25.3, too.

@freeman983 can you bisect the bad commit?
(If you have a script that exits 0 on good commit and 1 on bad commit (say `test.sh`) then in `github.com/godror/godror`

    git bisect start v0.25.4 v0.25.3
    git bisect run test.sh

will automagically find the first bad commit.

**Comment by freeman983** [comment]
@tgulacsi 
I tested the submissions between 0.25.4 and 0.25.3, and finally found the problematic submission point.
first bad commit.  [Add setCallTimeout in ociBreakDone 505349a](https://github.com/godror/godror/commit/505349ad9c7175cda86800423405eb79c1660d95)

**Comment by freeman983** [comment]
I compared and tested the following codes, and the results were no difference. There is no hanging problem

```
conn.go

-       if hasDeadline {
+       if false && hasDeadline {
                c.mu.RLock()
                if func() bool {
                        c.drv.mu.RLock()
```
