### ISSUE TITLE
Godror failing to handle enough concurrent connections.

### ISSUE THREAD

**Issue by monirz** [godror/godror#192]
Hi, 

We have a server that can handle  `60,000+` concurrent request but that doesn't hit the database. But with an API that excepts JSON data and insert into database, that fails with `20,000` concurrent request. Although it works fine with 10k requests. I have also tried stop calling the db insert function with that API and it works fine. 

Now with around 20k request it throws an error like this, here is the stacktrace: 

```
goroutine 22214 [syscall, locked to thread]:
github.com/godror/godror._Cfunc_dpiConn_create(0x28e55a0, 0x0, 0x0, 0x0, 0xc000000000, 0x7fe1e9571430, 0x3f, 0x0, 0xc02d86b830, 0xc02dbaa068, ...)
	_cgo_gotypes.go:2273 +0x4b
github.com/godror/godror.(*drv).acquireConn.func8.1(0xb31aa0, 0xc02dbed6d0, 0x0, 0x0, 0xc02dbed6d8, 0x0, 0x0, 0xc02dbed6e8, 0xc02dbeda50, 0x0, ...)
	/home/monir/gocode/src/github.com/username/project/vendor/github.com/godror/godror/drv.go:559 +0x1a5
github.com/godror/godror.(*drv).acquireConn.func8(0x41b818)
	/home/monir/gocode/src/github.com/username/project/vendor/github.com/godror/godror/drv.go:559 +0x91
github.com/godror/godror.(*drv).checkExec(0xb31aa0, 0xc02dbed810, 0x0, 0x0)
	/home/monir/gocode/src/github.com/username/project/vendor/github.com/godror/godror/drv.go:258 +0x5a
github.com/godror/godror.(*drv).acquireConn(0xb31aa0, 0xc0001bee00, 0xc00030093c, 0x5, 0xc000398640, 0x3f, 0xc0003007c0, 0x8, 0x0, 0x0, ...)
	/home/monir/gocode/src/github.com/username/project/vendor/github.com/godror/godror/drv.go:552 +0x731
github.com/godror/godror.(*drv).createConn(0xb31aa0, 0xc0001bee00, 0xc00030093c, 0x5, 0xc000398640, 0x3f, 0xc0003007c0, 0x8, 0x0, 0x0, ...)
	/home/monir/gocode/src/github.com/username/project/vendor/github.com/godror/godror/drv.go:372 +0xd8
github.com/godror/godror.(*drv).createConnFromParams(0xb31aa0, 0xc00030093c, 0x5, 0xc000398640, 0x3f, 0xc0003007c0, 0x8, 0x0, 0x0, 0x0, ...)
	/home/monir/gocode/src/github.com/username/project/vendor/github.com/godror/godror/drv.go:589 +0x158
github.com/godror/godror.connector.Connect(0xb31aa0, 0xc00030093c, 0x5, 0xc000398640, 0x3f, 0xc0003007c0, 0x8, 0x0, 0x0, 0x0, ...)
	/home/monir/gocode/src/github.com/username/project/vendor/github.com/godror/godror/drv.go:1089 +0x6f8
database/sql.(*DB).conn(0xc000079e10, 0x8ff028, 0xc02dba2960, 0x7fe4080c1d01, 0x0, 0x1c0, 0x7ff2f74fb5b8)
	/usr/local/go/src/database/sql/sql.go:1301 +0x184
database/sql.(*DB).exec(0xc000079e10, 0x8ff028, 0xc02dba2960, 0x891998, 0x6f, 0xc02dbef0a8, 0x5, 0x5, 0x1, 0x10, ...)
	/usr/local/go/src/database/sql/sql.go:1553 +0x66
database/sql.(*DB).ExecContext(0xc000079e10, 0x8ff028, 0xc02dba2960, 0x891998, 0x6f, 0xc02dbef0a8, 0x5, 0x5, 0xc02dba8580, 0x0, ...)
	/usr/local/go/src/database/sql/sql.go:1535 +0xe5
phcgolang/orcl.(*HouseService).CreateHouse(0xc00000ec48, 0x8ff060, 0xc02dba2960, 0xc02dbb3500, 0x1, 0x4, 0xc02d9182a0, 0x0, 0x0)
	/home/monir/gocode/src/github.com/username/project/orcl/house.go:62 +0x3a5
phcgolang/handler.(*Server).CreateHouseholdsHandler(0xc00043d680, 0x8fe460, 0xc02d8567e0, 0xc02d779c00)
	/home/monir/gocode/src/github.com/username/project/handler/house_handler.go:47 +0x422
net/http.HandlerFunc.ServeHTTP(0xc0003ded60, 0x8fe460, 0xc02d8567e0, 0xc02d779c00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
phcgolang/handler.(*Server).JWT.func1(0x8fe460, 0xc02d8567e0, 0xc02d779c00)
	/home/monir/gocode/src/github.com/username/project/handler/middleware.go:43 +0x24c
net/http.HandlerFunc.ServeHTTP(0xc0003f3e60, 0x8fe460, 0xc02d8567e0, 0xc02d779c00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc000409bc0, 0x8fe460, 0xc02d8567e0, 0xc02d779c00)
	/home/monir/gocode/src/github.com/username/project/vendor/github.com/go-chi/chi/chain.go:31 +0x52
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0003f1920, 0x8fe460, 0xc02d8567e0, 0xc02d779c00)
	/home/monir/gocode/src/github.com/username/project/vendor/github.com/go-chi/chi/mux.go:436 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc0003decd0, 0x8fe460, 0xc02d8567e0, 0xc02d779c00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0003f1920, 0x8fe460, 0xc02d8567e0, 0xc02d779b00)
	/home/monir/gocode/src/github.com/username/project/vendor/github.com/go-chi/chi/mux.go:87 +0x331
net/http.serverHandler.ServeHTTP(0xc0000a8000, 0x8fe460, 0xc02d8567e0, 0xc02d779b00)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc02da49540, 0x8ff060, 0xc02d77f580)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```
From one of your suggestion I found I tried with `context.WithTimeout(ctx, 1*time.Minute)` and `db.ExecContext()` for executing the insert query.  The result is same. 

Here is my config for the Godror I'm using:  

```
configDir= connectionClass= enableEvents=0 externalAuth=0 heterogeneousPool=0
libDir= noTimezoneCheck=0 poolIncrement=30 poolMaxSessions=20000 poolMinSessions=0
poolSessionMaxLifetime=0s poolSessionTimeout=15s poolWaitTimeout=0s prelim=0
standaloneConnection=0 sysasm=0 sysdba=0 sysoper=0 timezone=

```

If you want to know a little bit of server config: 
```go 
	srv := &http.Server{
		Addr:         addr,
		ReadTimeout:  60 * time.Second,
		WriteTimeout: 60 * time.Second,
		Handler:      s.router,
	}
```
I'm currently trying with the client I have written in Golang, which has the http.Transport configuration like this: 

```go
tr = &http.Transport{
		Proxy: http.ProxyFromEnvironment,
		DialContext: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: 30 * time.Second,
		}).DialContext,
		MaxIdleConnsPerHost:   20000,
		MaxIdleConns:          100,
		IdleConnTimeout:       90 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
	}

```
I can show you the full client code if you want, but the thing is it successfully handles 10k+ requests, or I also tried tsung to generate the load, result is pretty much same. Our database is configured for 400k connections but the session is about 6k (Do we need to increase it?). Although no error from the database side.      

And about the house data I'm sending it could be an array of house but right now I'm just only sending one house that has around 34 fields, mostly 1/2 digit integer value except for the uid field. But the insert query inserts into two tables one with a very few fields. 

I have tried several ways to tweak the configuration and stuff and couldn't get it working. Our target is to reaching at least 60k concurrent requests. Is that a bug?  Or What I might be doing wrong here? Can you give me any direction? Any help is appreciated! 

Thank you!

**Comment by tgulacsi** [comment]
What is the error (that's been omitted) ?

What if `poolMinSessions=20000` (or something high enough to remove the churn)?
To have another limiter, use `db.SetMaxConns(20000)` (or less).

I don't know whether it's the pool session acquiring/releasing or something else causes the error.
but you can easily limit the concurrent database connection by  spawning some goroutines that does the INSERTs. Or even batch them (see https://pkg.go.dev/github.com/godror/godror#Batch) and flush peridocally.

Is that 20k concurrent connections really needed? 
Do they do really different things in really different transactions that must separately commit/rollback?
If you sacrifice latency or transactions, batching those inserts multiplies throughput.

**Comment by tgulacsi** [comment]
A little background:
db.ExecContext will acquire a Go connection object. If none exist, will acquire an Oracle session and create the Go object.
The caching/limiting is `db.SetMaxConns` (upper limit), and `db.SetMaxIdleConns`.
The next level is Oracle session pooling.

So best is to have `db.SetMaxConns < poolMaxSessions` and `db.SetMaxIdleConns >= (number of average concurrent requests)`.

**Comment by tgulacsi** [comment]
Sorry, but that's not an error message, just a stack trace.
Can you put a full log (which DPI_DEBUG_LEVEL=92) somewhere?

**Comment by monirz** [comment]
Also it don't show these in the output  `dpiStmt_execute` `dpiStmt_close` `dpiConn_close` before it showing it started to show the repeated stackstrace.

**Comment by monirz** [comment]
I was trying around 20k request mostly because that's where it fails and that log is so big I can't trace them all and with small request it does not create the problem but let me share the log for the 1/2 or few requests. Sequentially? I haven't tried for that many request, but will try that.

**Comment by monirz** [comment]
Even with 200 or 1000 request it shows the log as above. And it all get success response.

**Comment by monirz** [comment]
Okay, I'll have to dig down to it. I'll come back to you soon.

**Comment by monirz** [comment]
Are you just it running from the test or trying with a client code with similar approach? I have ran the test and passed but did not see any concurrency number: 

```
--- PASS: TestConcurrency (42.03s)
PASS
ok  	github.com/godror/godror	42.146s
```    

It's on my local machine though, I'm gonna try it on the vm now. Also will be trying those parameters accordingly. And see what happens.
