### ISSUE TITLE
Does this support secure connection?

### ISSUE THREAD

**Issue by svarkey** [godror/godror#2]
If yes, could you please provide an example

**Comment by tgulacsi** [comment]
Just as ODPI-C and Oracle OCI supports.

But see z_test.go and contrib/free.db : the default test DB is an Oracle Cloud Always Free Autonomous DB, with an SSL-secured connection.

TL;DR; you need a proper sqlnet.ora at where TNS_ADMIN points, and either a tnsnames.ora there too, or provide the connection string as SID (user/password@SID).
