### ISSUE TITLE
Debug problems in Visual Studio Code with godror dependency

### ISSUE THREAD

**Issue by SlavaUtesinov** [godror/godror#200]
Hello.

I've faced a problem that I am not able to debug a program in Visual Studio Code when there is a godror dependency. I set a breakpoint and it was shown at breakpoints window "could not find file ....\main.go" with a grey circle icon, but the file had existed, moreover the program worked properly with expected result fetched from oracle database, but without ability to catch/(stop at) the breakpoint. If I eliminate the godror dependency from the program everything will work as expected i.e. I can set and catch the breakpoint.

![Breakpoint](https://user-images.githubusercontent.com/12560600/144018305-2ae954e4-3449-4d19-9a38-785e4576d859.PNG)

UPD:
After I had updated all go tools I received new error after debug launch:
error layer=debugger error loading binary "...AppData\\Local\\Temp\\__debug_bin2193837120.exe": error reading debug_info: decoding dwarf section line_str at offset 0x0: underflow

Without godror dependency it still works.

oracle client 18.4.0.0.0
godror v0.28.1
Visual Studio Code 1.62.3
go 1.17.3
gcc 11.2.0
Windows 10 Enterprise 1903, 64

**Comment by sudarshan12s** [comment]
I often debug examples using godror on macos. plugins were automatically
detected and i installed them.
attached snapshot.

**Comment by tgulacsi** [comment]
Sorry, I don't use VSCode.
Can you reproduce it with calling delve directly?

**Comment by SlavaUtesinov** [comment]
Hi, Yes with delve debugging I have the same behavior:

![image](https://user-images.githubusercontent.com/12560600/144596614-32311b5b-8d37-49b7-a8c9-f4501114c395.png)

**Comment by sudarshan12s** [comment]
> Hi. Yes with delve debugging I have the same behavior:
> 
> ![image](https://user-images.githubusercontent.com/12560600/144596614-32311b5b-8d37-49b7-a8c9-f4501114c395.png)
> 
> Without godror dependency it works.

  Is this also seen with linux/mac?

**Comment by SlavaUtesinov** [comment]
Unfortunately, I don't have mac to check it.

**Comment by tgulacsi** [comment]
I can debug cgo programs - for example `go test -c github.com/godror/godror` on Linux.

Does your program have a "main" function - is it a standalone program, or just a library? In the latter case, you won't be able to debug it directly, only through another program or a Test.

**Comment by SlavaUtesinov** [comment]
Yes, it has a "main" function, moreover it also has a "main.go" file. It is a standalone program. It seems like you've accidentally closed the issue.
