### ISSUE TITLE
rows column Blob type return blob

### ISSUE THREAD

**Issue by travelliu** [godror/godror#202]
Now query the blob field, row columns return a type of long raw. 
Is it possible to also return blob in the case of ClobAsString().

![image](https://user-images.githubusercontent.com/7792329/145841268-5208f4ae-60c0-447d-b448-9ffa45855041.png)

**Comment by tgulacsi** [comment]
"From 2.9.0, LOBs are returned as string/[]byte by default (before it needed the ClobAsString() option). Now it's reversed, and the default is string, to get a Lob reader, give the LobAsReader() option."

So, use `godror.LobAsReader()` option to have the LOB as io.Reader.

**Comment by travelliu** [comment]
> "From 2.9.0, LOBs are returned as string/[]byte by default (before it needed the ClobAsString() option). Now it's reversed, and the default is string, to get a Lob reader, give the LobAsReader() option."
> 
> So, use `godror.LobAsReader()` option to have the LOB as io.Reader.

I was wrong. i mean rows.ColumnTypes reture blob. now return long raw 

```
db.Exec("create table test_blob(id number,col_blob blob)")
defer db.Exec("drop table test_blob")
db.Exec("insert into test_blob(id,col_blob) values (:1,:2)", 1, "aaaa")
rows, err := db.Query(
    "select id,col_blob from test_blob",
)
if err != nil {
    t.Error(err)
    return
}
cols, err := rows.ColumnTypes()
for _, c := range cols {
    fmt.Println(c.Name(), c.DatabaseTypeName())
}
ID NUMBER
COL_BLOB LONG RAW
```
