### ISSUE TITLE
AlterSession 'Current_Schema' is not honoured past first session

### ISSUE THREAD

**Issue by travellingkiwi** [godror/godror#218]
When creating a connection to an Oracle database (12c in case it matters) using godror (golang 1.17) the first query works fine. However subsequent queries result in 'ORA-00942 table or view does not exist' for a simple SQL query when the schema is not specified in the query

e.g.
select * from my_table;

works once and then fails. While
select * from my_schema.my_table;

continues to work

I have tried setting the current_schema via directly executing 'alter session set current_schema=my_schema' and also specifying the current_schema in the connection parameter AlterSession array. Both methods result in a single successful run of the query followed by continual failures with ORA-00942

**Comment by sudarshan12s** [comment]
> 

I don't see any such issues in my 12.1 setup. Can you share more details on test case with table , column types ,...  , preferably a minimal program, if possible.

**Comment by travellingkiwi** [comment]
I've narrowed it down slightly. It's actually the first query that only succeeds. It's that only statements prepared on the first connection succeed. Because only the first session in the pool gets the current_schema set to a non-default value.

When I connect I create the connection via

`
var P godror.ConnectionParams
P.username, P.Password="myuser", godror.NewPassword("mypass")
P.ConnectString="mydb"
P.AlterSession=[][2]string{{"CURRENT_schema", "my_schema_owner"}}

self.pool=sql.OpenDB(godror.NewConnector(P))
`

And then calling

`
self.pool.Prepare("some_sql")
`

works fine... For the first prepare... But subsequent prepares fail with ORA-00942 (The Sql doesn't refer to the table by schema.table_name, just by table_name and relying on the current_schema)

When I look at the v$session for the database after the failures start, I can see that I have 3-4 sessions. The first session lists the schemaname correctly as "my_schema_owner". The subsequent sessions for the pool (identified as being subsequent by them having a higher client port) have the connection user as the schemaname...
So it looks like only the first session of the pool is getting the AlterSession run...

Is there something special I should be doing to have all sessions in the pool execute the AlterSchema parameters?

(I've also tried leaving AlterSession empty. And just running 

`
self.pool.Exec("alter session set current_schema='my_schema_owner'" 
`

But it has exactly the same issue.

**Comment by travellingkiwi** [comment]
Edited the title as it appears the root cause is that only the first session of the pool has AlterSession run for it.

**Comment by tgulacsi** [comment]
PTAL e575822 with setting logger with `godror.SetLog` to see what and when is executed.
Or run with DPI_DEBUG_LEVEL=127.

**Comment by cartersz** [comment]
I setup Log. But get the following information
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/25973791/154948169-df07203a-9160-4a32-9050-0af5af0d2a99.png">

**Comment by tgulacsi** [comment]
Is that with e575822 ? What does godror log (SetLog), or ODPI?

**Comment by cartersz** [comment]
the following file is the log of my program
[output.log](https://github.com/godror/godror/files/8113440/output.log)

**Comment by cartersz** [comment]
the following is the output of my program.
[output.log](https://github.com/godror/godror/files/8113468/output.log)

**Comment by cartersz** [comment]
The following is the log of my program.
[output.log](https://github.com/godror/godror/files/8113957/output.log)
