### ISSUE TITLE
CQN subscription callback not working in Docker

### ISSUE THREAD

**Issue by dinvlad** [godror/godror#22]
**Describe the bug** [this might be a feature request after all, please see the next post]
When running inside Docker, CQN subscription query registration seems to crash when the first change is triggered (but before the callback has a chance to run).

**To Reproduce**
1. Register a QRCN query according to https://github.com/godror/godror/blob/master/z_qrcn_test.go
2. Build a Docker image using
```Dockerfile
FROM golang AS build
WORKDIR /build
COPY go.* *.go ./
RUN go build -o main

FROM oraclelinux:7-slim
RUN yum -y -q install oracle-release-el7 && \
    yum-config-manager --enable ol7_oracle_instantclient >/dev/null && \
    yum -y -q install oracle-instantclient19.5-basic
COPY --from=build /build/main /
ENTRYPOINT ["/main"]
```
3. Run the Docker image.
4. Observe that the subscription query is registered successfully (no errors returned):
```go
func printReg() {
	var regID, tableName string
	row := testDb.QueryRow("SELECT regid, table_name FROM USER_CHANGE_NOTIFICATION_REGS")
	row.Scan(&regID, &tableName)
	log.Println(regID, tableName)
}()
testDb.Exec("INSERT INTO test_subscr (i) VALUES (1)")
printReg()
```
5. Observe that registration params were printed before the insert, and are missing after. No events are logged either, despite having a log statement in the callback.
6. Compile and run the same code on **macOS** or **RHEL** (without Docker), observe that the events are received and the registration survives.

**Expected behavior**
Insertion event should be logged, and the registration should remain alive after the event is triggered.

**Screenshots**

**Your oracle client version**
19.5 (same issue with 18.3)

**Your godror version**
v0.9.1

**Your go version**
1.13.8

**Your gcc version**
8.3.0

**Machine (please complete the following information):**
 - OS: Oracle Linux 7 (same behavior on Debian) in a **Docker** on **macOS 10.14.6** and **Amazon Linux (AWS Fargate instance)**
 - Architecture: x86_64

**Additional context**
As mentioned, I tried other base images (Debian) but the same behavior is observed.

Additionally, I tried `CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build` but that didn't help.

Finally, I tried both `strace` and `DPI_DEBUG_LEVEL=100`, but they don't reveal any messages/calls after the change is triggered (or maybe I didn't run those with proper options?).

So it appears as if the registration is just dropped silently. Is there any way to diagnose that?

EDIT: `strace` does show a lot of `EAGAIN (Resource temporarily unavailable)` and `ETIMEDOUT (Connection timed out)` before the insert, perhaps those are somehow relevant?

EDIT2: Attempting to re-register after the crash (using the same subscription) leads to
```
executeStmt: ORA-29970: Specified registration id does not exist
```

EDIT3: I re-ran the same image with [Singularity](https://singularity.lbl.gov/docs-docker) on RHEL7 (i.e. not a "real" Docker), and to my surprise it worked! So this issue appears to be specific to Docker.

**Comment by dinvlad** [comment]
OK, it looks like this may have to do with the ability of the database to connect back to the client IP/port (I was not aware that this is normally a server-initiated connection). Since `19.4` release however, there's an additional option for `clientInitiated` connections, which do _not_ require to have an externally exposed port:
https://blogs.oracle.com/opal/python-cx_oracle-73-for-oracle-database-is-on-pypi
https://oracle.github.io/odpi/doc/structs/dpiSubscrCreateParams.html#c.dpiSubscrCreateParams.clientInitiated

We actually have 2 databases, one of which is old (11.2g) and one new (19+). I'd like to explore using `clientInitiated` option for the latter, particularly since it requires less configuration and greater security.

That being said, the orthodox solution of exposing a static port on the Docker container, should work as well. I think the options to set the client host/port (`dpiSubscrCreateParams.ipAddress`/`dpiSubscrCreateParams.portNumber`) aren't currently exposed in `NewSubscription()`, but it should be easy to add them (along with `dpiSubscrCreateParams.clientInitiated`). I can submit a PR if you'd like.

**Comment by tgulacsi** [comment]
That's what I wanted to write - for me this subscription has succeeded only on the same machine (through localhost) - and as it is totally black box (before 19.4), you does not see what's happening nor have any inluence on it.

I don't have a 19.4, so couldn't try it out yet. 

The PR is nice, though I have a question about it.

**Comment by dinvlad** [comment]
Surely! And I'm having trouble with the port setting unfortunately - whichever port I set as an option, ODPI complains with
```
ORA-24911: Cannot start listener thread at specified port
```
which according to the [doc](http://ora.codes/ora-24911) means
> Cause:
Thread already running at a different port.
Action:
Set the correct port in the environment handle or let the system choose the port.

**Comment by dinvlad** [comment]
This is really weird. It looks like `godror.DriverConn()` opens a random port, if we specify `enableEvents=1` (we have to). But then if _reuses_ that port after `conn.NewSubscription..`. And if we try to assign `portNumber` when creating the subscription, it complains that the port is already open (the one that was open by `godror.DriverConn()`).

So in a way, it appears ODPI-C prevents itself from assigning `portNumber` (unless this is caused by something else).

**Comment by tgulacsi** [comment]
DriverConn just connects to the database.
For a quick skim, I didn't find anything that could open a port in either godror, nor ODPI-C.
This suggests that the OCI level is opening a connection.

I've never been able to use CQN reliably, if at all...  
Maybe you should ask it on ODPI-C, @cjbj or @anthony-tunininga knows a lot more!

**Comment by dinvlad** [comment]
Thanks for checking! Opened it: https://github.com/oracle/odpi/issues/128

**Comment by dinvlad** [comment]
Looks like this might be specific to `godror` after all: https://github.com/oracle/odpi/issues/128#issuecomment-593146618

**Comment by dinvlad** [comment]
This is the example code I use for `cx_Oracle`, which works:
```python3

import cx_Oracle

connection = cx_Oracle.connect(
  'user', 'pass', 'test.example.org:1521/testdb',
  events=True,
)

def CQNCallback(msg):
  print("Notification:", msg)

subscr = connection.subscribe(
  namespace=cx_Oracle.SUBSCR_NAMESPACE_DBCHANGE,
  callback=CQNCallback,
  port=12345,
  operations=cx_Oracle.OPCODE_INSERT | cx_Oracle.OPCODE_UPDATE,
  qos = cx_Oracle.SUBSCR_QOS_QUERY | cx_Oracle.SUBSCR_QOS_ROWIDS | cx_Oracle.SUBSCR_QOS_BEST_EFFORT,
)

subscr.registerquery("select updated_at from subjects")

input("Hit enter to stop CQN demo\n")
```
When I make a change to `subjects` table (resulting in an update to the `updated_at` field), I receive a notification, _without_ `ORA-24911`

**Comment by tgulacsi** [comment]
I'm on vacation this week, sorry.

You can try to compare what cx_Oracle and godror does when DPI_DEBUG_LEVEL=28

**Comment by dinvlad** [comment]
Sounds good, thanks! I’ll explore

**Comment by dinvlad** [comment]
I'll go ahead and close this, as we didn't really have time to test, and the current setup (all ports open to the Oracle instance) is working well (happy to share the details, if you're interested). Thanks again for making CQN available to us!
