### ISSUE TITLE
OCISessionGet() timed out waiting for a free connection.

### ISSUE THREAD

**Issue by achyutarjunneupane** [godror/godror#220]
We are trying to connect to ATP :
connection String 

url="connectionClass=POOLED standaloneConnection=0 poolMinSessions=200 poolIncrement=0 poolMaxSessions=200 user= password="" connectString=\"spsdb_high\" libDir="" configDir="" "
We are using wallet to connect.

We have a test case that runs sequentially for couple of hours. The connections keep on increasing and we start getting.

level=error msg="error retrieving records" error="user=\"\" ConnectString=\"spsdb_high\" stats=busy=200 open=200 max=200 maxLifetime=1h0m0s timeout=5m0s waitTimeout=30s params={authMode:0 connectionClass:0x6000000a6710 connectionClassLength:6 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:0 externalHandle:<nil> pool:0x600001700780 tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-24496: OCISessionGet() timed out waiting for a free connection." 

My assumption was, should not the connection be limited as defined in connectionString:

url="connectionClass=POOLED standaloneConnection=0 poolMinSessions=200 poolIncrement=0 poolMaxSessions=200 user= password="" connectString=\"spsdb_high\" libDir="" configDir="" "

I changes poolMinSessions and poolMaxSessions still same

**Comment by achyutarjunneupane** [comment]
Connect code:


logger.Info(log.Fields{"user": config.Database.Username}, fmt.Sprintf("connection started for user %s", config.Database.Username))
	

	cs := fmt.Sprintf("connectionClass=POOLED standaloneConnection=0 poolMinSessions=2 poolIncrement=1 poolMaxSessions=200 user=\"%s\" password=\"%s\" connectString=\"%s\" libDir=\"%s\" configDir=\"%s\"",
		config.Database.Username,
		config.Database.Password,
		config.Database.ConnectString,
		config.Database.LibLocation,
		config.Database.ConfigLocation)

	db, err := connector.Connect(cs)

	logger.Error(log.Fields{"url": cs, "event": "db connect"}, nil, "")

	if err != nil {
		logger.Error(
			log.Fields{"user": config.Database.Username, "event": "db connect"},
			err, "db connection was unsuccessful")
		return nil, err
	}

	// Maximum Idle Connections
	db.SetMaxIdleConns(0)
	
	pingErr := db.Ping()

**Comment by tgulacsi** [comment]
See https://github.com/godror/godror/issues/221#issuecomment-1048192879

**Comment by achyutarjunneupane** [comment]
Thanks @tgulacsi 
 we were able to resolve. Our some transactions were not closed.
 
Thanks,
Achyut
