### ISSUE TITLE
connection reached max and stuck

### ISSUE THREAD

**Issue by achyutarjunneupane** [godror/godror#221]
We are trying to connect to ATP :
connection String

url="standaloneConnection=1 user=\"\" password=\"\" connectString=\"spsdb_high\" libDir=\"/Users/aneupane/Downloads/instantclient_19_8\" configDir=\"/Users/aneupane/Downloads/instantclient_19_8/network/admin\""

We are using wallet to connect.

We have a test case that runs sequentially for couple of hours. The connections keep on and its just stuck

I did print the DBStats
{MaxOpenConnections:100 OpenConnections:100 InUse:100 Idle:0 WaitCount:1 WaitDuration:0s MaxIdleClosed:0 MaxIdleTimeClosed:0 MaxLifetimeClosed:0}

My assumption was,  connection should increse/decrease.

I changes SetMaxIdleConns and SetMaxOpenConns still same

**Comment by achyutarjunneupane** [comment]
Connect Code:

	logger.Info(log.Fields{"user": config.Database.Username}, fmt.Sprintf("connection started for user %s", config.Database.Username))


	// connectionClass=POOLED standaloneConnection=0 poolMinSessions=2 poolIncrement=1 poolMaxSessions=200
	cs := fmt.Sprintf("standaloneConnection=1 user=\"%s\" password=\"%s\" connectString=\"%s\" libDir=\"%s\" configDir=\"%s\"",
		config.Database.Username,
		config.Database.Password,
		config.Database.ConnectString,
		config.Database.LibLocation,
		config.Database.ConfigLocation)

	db, err := connector.Connect(cs)

	logger.Error(log.Fields{"url": cs, "event": "db connect"}, nil, "")

	if err != nil {
		logger.Error(
			log.Fields{"user": config.Database.Username, "event": "db connect"},
			err, "db connection was unsuccessful")
		return nil, err
	}

	// Maximum Idle Connections
	// Maximum Idle Connections
	db.SetMaxIdleConns(50)
	// Maximum Open Connections
	db.SetMaxOpenConns(100)
	// Idle Connection Timeout
	db.SetConnMaxIdleTime(1 * time.Second)
	// Connection Lifetime
	db.SetConnMaxLifetime(30 * time.Second)

**Comment by tgulacsi** [comment]
You have a resource leak.
You have to close (probably with defer) ALL opened DB, Conn, Tx, Stmt, Rows ASAP!

**Comment by achyutarjunneupane** [comment]
Thanks @tgulacsi 
 we were able to resolve. Our some transactions were not closed.
 
Thanks,
Achyut
