### ISSUE TITLE
Next: ORA-01805: possible error in date/time operation

### ISSUE THREAD

**Issue by freeman983** [godror/godror#228]
**Describe the bug**

Hi, I am getting this error while querying the CORE_COMPANY_EN_MAINT_CHK table.But I can return data normally when I use navicat and razor sql to query. no errors

Below is the structure of this table
and data

```
-- ----------------------------
-- Table structure for CORE_COMPANY_EN_MAINT_CHK
-- ----------------------------
CREATE TABLE "CORE_COMPANY_EN_MAINT_CHK" (
  "COM_ID" NUMBER(10,0) NOT NULL,
  "REP_TIME" TIMESTAMP(6) WITH TIME ZONE DEFAULT TO_DATE('1900-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS')  NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CORE_COMPANY_EN_MAINT_CHK
-- ----------------------------
INSERT INTO "CORE_COMPANY_EN_MAINT_CHK" VALUES ('1746181652', TO_TIMESTAMP_TZ('2021-04-02 13:40:37.304143 ASIA/SHANGHAI', 'SYYYY-MM-DD HH24:MI:SS:FF6 TZR'));
COMMIT;

```
**To Reproduce**
At least the offending source code;
the best is a minimal test case that reproduces the error.

**Expected behavior**

**Error output**
Copy the error output (panic, stack trace),
or the output of running with `DPI_DEBUG_LEVEL=92`.

```
ODPI [9606789] 2022-03-11 17:53:30.262: SQL 
        /**sqldev_token16469924100317**/

        SELECT * FROM ( SELECT A.*, ROWNUM SQLDEV_RN FROM (  
                select 
        t.COM_ID, t.REP_TIME 
from 
        CORE_COMPANY_EN_MAINT_CHK t 
                 
                ) A WHERE ROWNUM <= 10 ) WHERE SQLDEV_RN > 0
ODPI [9606789] 2022-03-11 17:53:30.262: fn end dpiConn_prepareStmt(0xd60a730) -> 0
ODPI [9606789] 2022-03-11 17:53:30.262: fn start dpiStmt_getInfo(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.262: fn end dpiStmt_getInfo(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.263: fn start dpiStmt_getBindCount(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.263: fn end dpiStmt_getBindCount(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.263: fn start dpiStmt_setFetchArraySize(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.263: fn end dpiStmt_setFetchArraySize(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.263: fn start dpiStmt_setPrefetchRows(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.263: fn end dpiStmt_setPrefetchRows(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.263: fn start dpiStmt_execute(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiStmt_execute(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.280: fn start dpiStmt_getQueryInfo(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiStmt_getQueryInfo(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.280: fn start dpiConn_newVar(0xd60a730)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiConn_newVar(0xd60a730) -> 0
ODPI [9606789] 2022-03-11 17:53:30.280: fn start dpiStmt_define(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiStmt_define(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.280: fn start dpiStmt_getQueryInfo(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiStmt_getQueryInfo(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.280: fn start dpiConn_newVar(0xd60a730)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiConn_newVar(0xd60a730) -> 0
ODPI [9606789] 2022-03-11 17:53:30.280: fn start dpiStmt_define(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiStmt_define(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.280: fn start dpiStmt_getQueryInfo(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiStmt_getQueryInfo(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.280: fn start dpiConn_newVar(0xd60a730)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiConn_newVar(0xd60a730) -> 0
ODPI [9606789] 2022-03-11 17:53:30.280: fn start dpiStmt_define(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiStmt_define(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.280: fn start dpiStmt_addRef(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.280: fn end dpiStmt_addRef(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.281: fn start dpiStmt_fetchRows(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.281: OCI error ORA-01805: possible error in date/time operation (dpiStmt_fetchRows / get time zone portion)
ODPI [9606789] 2022-03-11 17:53:30.281: fn end dpiStmt_fetchRows(0xd60bbc0) -> -1
ODPI [9606789] 2022-03-11 17:53:30.281: fn start dpiVar_release(0xd60be10)
ODPI [9606789] 2022-03-11 17:53:30.281: fn end dpiVar_release(0xd60be10) -> 0
ODPI [9606789] 2022-03-11 17:53:30.281: fn start dpiVar_release(0xd60c260)
ODPI [9606789] 2022-03-11 17:53:30.281: fn end dpiVar_release(0xd60c260) -> 0
ODPI [9606789] 2022-03-11 17:53:30.281: fn start dpiVar_release(0xd60c7d0)
ODPI [9606789] 2022-03-11 17:53:30.281: fn end dpiVar_release(0xd60c7d0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.281: fn start dpiStmt_release(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.281: fn end dpiStmt_release(0xd60bbc0) -> 0
 resultErr1 token: 16469924100317     resultErr: Next: ORA-01805: possible error in date/time operation bk: true
ODPI [9606789] 2022-03-11 17:53:30.281: fn start dpiStmt_release(0xd60bbc0)
ODPI [9606789] 2022-03-11 17:53:30.281: fn end dpiStmt_release(0xd60bbc0) -> 0
ODPI [9606789] 2022-03-11 17:53:30.281: fn start dpiConn_getIsHealthy(0xd60a730)
ODPI [9606789] 2022-03-11 17:53:30.281: fn end dpiConn_getIsHealthy(0xd60a730) -> 0
ODPI [9606789] 2022-03-11 17:53:30.281: fn start dpiConn_release(0xd60a730)
ODPI [9606789] 2022-03-11 17:53:30.287: fn end dpiConn_release(0xd60a730) -> 0
===============sqlLog.count=============： 0

```

**Your oracle client version**
 Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production

**Your godror version**
 v0.31.0

**Your go version**
 go version go1.16.10 darwin/amd64

**Your gcc version**
~~
**Machine (please complete the following information):**
 - OS: mac 
 - Architecture: [e.g. x86_64]
 - Version:10.15.7 

**Additional context**
conn code 

```
var P godror.ConnectionParams
	var pp godror.PoolParams
	var cp godror.ConnParams

	pp.SessionTimeout = 30
	//cp.IsSysOper = true

	P.ConnectString = fmt.Sprintf("%s:%s/%s", db.Ip, db.Port, db.Db)

	if db.ConType == lib.CON_TYPE_TNS {
		P.ConnectString = fmt.Sprintf(
			"%s",
			db.Db)
	}

	P.Username = db.User
	P.Password = godror.NewPassword(db.Pass)

	//fmt.Println("constr:", P.ConnectString)
	P.SessionTimeout = 15 * time.Second
	P.Timezone = time.Local
	P.StandaloneConnection = true
	P.PoolParams = pp
	P.ConnParams = cp
	P.WaitTimeout = 30 * time.Second
	

	dd := sql.OpenDB(godror.NewConnector(P))
```

```
SELECT DBTIMEZONE FROM DUAL;
+00:00
```

```

select 
   CAST(systimestamp AS timestamp(0) with local time zone) as local_time,
   systimestamp as server_time
from dual;

local_time                         server_time
2022-03-11 17:55:49�	2022-03-11 17:55:49.234273 +08:00
```

**Comment by tgulacsi** [comment]
`ORA-01805: possible error in date/time operation (dpiStmt_fetchRows / get time zone portion)`

is returned by dpiOci__dateTimeGetTimeZoneOffset in `odpi/src/dpiOci.c`, and this means OCIDateTimeGetTimeZoneOffset returned an error.
It's documentation says this is the case when "datetime does not contain a time zone (SQLT_DATE, SQLT_TIMESTAMP)".

The only place calling this is in `odp/src/dpiData.c` dpiDataBuffer__fromOracleTimestamp, which is called in `odpi/src/dpiVar.c`:

```
 773         case DPI_NATIVE_TYPE_TIMESTAMP:
 774             if (oracleTypeNum == DPI_ORACLE_TYPE_DATE)
 775                 return dpiDataBuffer__fromOracleDate(&data->value,
 776                         &buffer->data.asDate[pos]);
 777             return dpiDataBuffer__fromOracleTimestamp(&data->value, var->env,
 778                     error, buffer->data.asTimestamp[pos],
 779                     oracleTypeNum != DPI_ORACLE_TYPE_TIMESTAMP);
 780             break;
 ```

I'd add some printfs to all places calling `dpiDataBuffer__fromOracleTimestamp` (or `dpiOci__dateTimeGetTimeZoneOffset`) or print the stack trace (or just trigger a SIGSEGV when the call errors), to see where it fails.

**Comment by anthony-tuininga** [comment]
That error frequently suggests that the timezone files are not synchronized on the client and server. Run the `genezi -v` command on both client and server and compare the results of the timezone information.

**Comment by tgulacsi** [comment]
Thanks @anthony-tuininga !

So, @freeman983 see https://cx-oracle.readthedocs.io/en/latest/user_guide/initialization.html#oracle-environment-variables and https://docs.oracle.com/en/database/oracle/oracle-database/21/nlspg/datetime-data-types-and-time-zone-support.html#GUID-AD9EFCFB-CBEA-4BE2-A91E-9CC2A28CB199 for details!

**Comment by freeman983** [comment]
@tgulacsi @anthony-tuininga Hi, thank you very much for your answers. I have also noticed the difference between the time zones of the client and the server. But what puzzles me is that using the same client and configuration, queries in razorsql and Navicat premium can return results without execution errors.


`
select 
	t.COM_ID, t.REP_TIME 
from 
	CORE_COMPANY_EN_MAINT_CHK t 

`

navicat  result:
`
COM_ID       |    REP_TIME
1746181652	2021-04-02 13:40:37.304143 ASIA/SHANGHAI

RazorSql
`
COM_ID   |    REP_TIME
1746181652 | 2021-04-02 13:40:37.304143 Asia/Shanghai
`


I was thinking, if this problem is caused by the time zone difference between the server and the client, can there be some parameter configurations to solve this problem?

Like: P. timezone = "Asia / Shanghai"

But I tried and it didn't work.

**Comment by cjbj** [comment]
I don't know how those tools are implemented, but even if they are C based (using Oracle Client libraries), they may be calling different functions to do conversions.

You could:

- Try upgrading Oracle Client.  Everything up to 19c will connect to 11.2 database.
- Try using the 'small' timezone file - but you'd need Oracle Client 12.2 or later to do this (and 12.2 or later may not even have an issue).  We did log a bug recently against the Oracle client libraries where the large file gave an error but the small file didn't for a particular time zone.
  On the machine where you run Go, execute `/whereeve/instantclient_xx_y/genezi -v` and find the timezone files installed (they are actually embedded in the client libraries).  Then set the TZ file environment variable like `export ORA_TZFILE=oracore/zoneinfo/timezone_36.dat`.  (This will only work with Oracle Client 12.2 or later.  Also in some future version you won't even need the virtual `oracore/zoneinfo/` prefix)
 - Try upgrading the client timezone file.  Just grab a later copy from your database installation.  This time create a physical  directory `/whereeve/instantclient_xx_y/oracore/zoneinfo/` and put the file in it.  Run genezi -v again to check it is being used - if not, then set ORA_SDTZ to it, as above.

Oracle DB 11.2 itself is in its last year of final, final formal support from Oracle Support, so it's time to upgrade!

**Comment by freeman983** [comment]
@cjbj  Ok, thank you very much, I will reply you after I try the method you gave.

**Comment by cjbj** [comment]
@freeman983 I had a glitch in my export command. I've corrected the earlier comment.

**Comment by freeman983** [comment]
@cjbj Hello, I upgraded the oracle client to the latest version (Version 19.8.0.0.0) but still got the same error ORA-01805 when i execute the query


 when I set:
`
export ORA_TZFILE=timezone_36.dat
`
I got the following error when starting the go application
`
ODPI [9899838] 2022-03-14 14:15:42.553: fn start dpiContext_createWithParams
ODPI [9899838] 2022-03-14 14:15:42.553: Context Parameters:
ODPI [9899838] 2022-03-14 14:15:42.553: Environment Variables:
ODPI [9899838] 2022-03-14 14:15:42.553:     ORACLE_HOME => "/Users/chengyong/Work/common/oracle/instantclient_19_8"
ODPI [9899838] 2022-03-14 14:15:42.553:     ORA_TZFILE => "timezone_32.dat"
ODPI [9899838] 2022-03-14 14:15:42.553:     TNS_ADMIN => "$ORACLE_HOME/network/admin"
ODPI [9899838] 2022-03-14 14:15:42.553:     DYLD_LIBRARY_PATH => "$ORACLE_HOME"
ODPI [9899838] 2022-03-14 14:15:42.553: check module directory
2022/03/14 14:15:42 [ SQL ] sql/Users/chengyong/Work/go/src/shuaninfo.com/sqldev/models/instance.go:203708.607µsUPDATE `safe_sql_instance` SET `con_state` = ?, `err_msg` = ?, `updated_at` = ?  WHERE `safe_sql_instance`.`id` = ?[3 ORA-01804: failure to initialize timezone information 2022-03-14 14:15:42.552265 +0800 CST m=+1.868856497 25323e112209114df33528e61896651f] 1
2022/03/14 14:15:42 [ SQL ] sql/Users/chengyong/Work/go/src/shuaninfo.com/sqldev/models/instance.go:203526.442µsUPDATE `safe_sql_instance` SET `con_state` = ?, `err_msg` = ?, `updated_at` = ?  WHERE `safe_sql_instance`.`id` = ?[3 ORA-01804: failure to initialize timezone information 2022-03-14 14:15:42.553314 +0800 CST m=+1.869905796 5d99121ae7cc4176509117d1a3e8eb0e] 1
ODPI [9899838] 2022-03-14 14:15:42.554: module name is /private/var/folders/8w/l425tlz104x_7xjd7jwp9pgr0000gn/T/GoLand/___11sqldev_run_
ODPI [9899838] 2022-03-14 14:15:42.554: load in dir /private/var/folders/8w/l425tlz104x_7xjd7jwp9pgr0000gn/T/GoLand
ODPI [9899838] 2022-03-14 14:15:42.554: load with name /private/var/folders/8w/l425tlz104x_7xjd7jwp9pgr0000gn/T/GoLand/libclntsh.dylib
ODPI [9899838] 2022-03-14 14:15:42.554: load by OS failure: dlopen(/private/var/folders/8w/l425tlz104x_7xjd7jwp9pgr0000gn/T/GoLand/libclntsh.dylib, 1): image not found
ODPI [9899838] 2022-03-14 14:15:42.554: load with OS search heuristics
ODPI [9899838] 2022-03-14 14:15:42.554: load with name libclntsh.dylib
ODPI [9899838] 2022-03-14 14:15:42.554: load by OS successful
ODPI [9899838] 2022-03-14 14:15:42.554: validating loaded library
ODPI [9899838] 2022-03-14 14:15:42.555: fn end dpiContext_createWithParams -> -1
NewOracleGoDror ping err: ORA-01804: failure to initialize timezone information 253-40 2409121ae7cc4176509117d1a3e8eb04
SafeSqlInstance SaveConErrMsg:  2409121ae7cc4176509117d1a3e8eb04 ORA-01804: failure to initialize timezone information

The following is the database time zone information in the docker environment

`
I guess there is no $ORACLE_HOME/oracore/zoneinfo directory and timezone file causing this error, but I can't find anywhere to get this file

There is this file directory in the oracle docker image I tested, but it cannot be used when I download it to macos


`
[root@b2056db82a67 bin]# ./genezi -v
Client Shared Library 64-bit - 11.2.0.1.0

System name:	Linux
Release:	5.10.25-linuxkit
Version:	#1 SMP Tue Mar 23 09:27:39 UTC 2021
Machine:	x86_64

Operating in ORACLE_HOME environment.
Small timezone file = /home/oracle/app/oracle/product/11.2.0/dbhome_2/oracore/zoneinfo/timezone_11.dat
Large timezone file = /home/oracle/app/oracle/product/11.2.0/dbhome_2/oracore/zoneinfo/timezlrg_11.dat

`

**Comment by anthony-tuininga** [comment]
I see from the logs that you are setting the environment variable ``$ORACLE_HOME`` when using instant client. Don't do that! That is the source of the``ORA-01804`` error.

**Comment by cjbj** [comment]
@freeman983 some info regarding the paths: in my original answer I'd tried to point out that they don't necessarily exist because they are virtual inside the client libraries.
