### ISSUE TITLE
Is there a proper way to get last insert id?

### ISSUE THREAD

**Issue by ko2start** [godror/godror#235]
the id is generated by a sequence in DB. such as:
id, err := result.LastInsertId() defined in sql package. 
but I‘ve tried .QueryRow(xxxx) and .Exec(xxxx), it doesn't work.

**Comment by tgulacsi** [comment]
What is the last inserted ID for an Oracle DB?

As there's no such thing defined in Oracle, use an explicit "RETURNING INTO" clause and an `sql.Out{Dest:&id}` argument with Exec.

**Comment by ko2start** [comment]
got it, thanks a lot.

**Comment by cjbj** [comment]
@tgulacsi we did come across a way to get the ROWID without a RETURNING INTO clause when the statement affects a single row, see dpiStmt_getLastRowid

Some doc is at https://oracle.github.io/node-oracledb/doc/api.html#execlastrowid and https://cx-oracle.readthedocs.io/en/latest/api_manual/cursor.html#Cursor.lastrowid

**Comment by tgulacsi** [comment]
I know about dpiStmt_getLastRowid, but the go std library defined that last ID as int64, and ROWID is 2 bytes wider AFAIK.

https://pkg.go.dev/database/sql#Result
