### ISSUE TITLE
how to show inserter quantity in godror

### ISSUE THREAD

**Issue by Juniornewxt** [godror/godror#236]
Hello friends, I am creating a program that performs several actions in the database, such as truncating, insert, delete, update .... I have already managed to create this application, but something catches my attention, I would like to know the result, for example, how many lines were inserted to put in the output of the program on the screen, I don't find out how to do it is it possible? can you give me an example? or if it is valid, can you add this to the project?

**Comment by tgulacsi** [comment]
ExecContext returns sql.Result (https://pkg.go.dev/database/sql#DB.ExecContext), and that has a RowsAffected method, ehich returns this information.
