### ISSUE TITLE
godror.NewQueue method giveing error: driver: bad connection

### ISSUE THREAD

**Issue by thandavakrishnach** [godror/godror#237]
**Describe the bug**
while creating a queue object with the below code\
queue, err = godror.NewQueue(ctx, db, "{{some queue name}}", "RAW")

**To Reproduce**
At least the offending source code;
the best is a minimal test case that reproduces the error.

**Expected behavior**
Queue object should be created

**Error output**
 driver: bad connection

**Your oracle client version**
e.g. 19c

**Your godror version**
e.g. v0.29.0

**Your go version**
e.g. go1.17.8  linux/amd64

**Machine (please complete the following information):**
 - OS: linux

**Additional context**

**Comment by sudarshan12s** [comment]
Can you skip passing  type for queues created with RAW payload type like
` godror.NewQueue(ctx, db, "{{some queue name}}", "")`

you can share the logs by setting this environment variable and run the Go pgm.

`export DPI_DEBUG_LEVEL=92`

**Comment by tgulacsi** [comment]
As @sudarshan12s suggested, use empty string as payloadObjectType, not "RAW".
