### ISSUE TITLE
godror libDir  parameter does not take effect

### ISSUE THREAD

**Issue by wentaojin** [godror/godror#238]
**Describe the bug**
godror libDir  parameter does not take effect，BUT set the environment variable LD_LIBRARY_PATH is OK
`user=xxxx password=xxx connectString=xxxx:1521/oracl configDir=
connectionClass= enableEvents=0 externalAuth=0 heterogeneousPool=0 libDir=/root/marvin/instantclient_19_14
newPassword= noTimezoneCheck=0 poolIncrement=10 poolMaxSessions=1000 poolMinSessions=10
poolSessionMaxLifetime=1h0m0s poolSessionTimeout=5m0s poolWaitTimeout=1m0s
prelim=0 standaloneConnection=0 sysasm=0 sysdba=0 sysoper=0 timezone=local`

openDB ping error：
`[2022/05/21 22:39:37.713 +08:00] [FATAL] [main.go:72] ["server run failed"] [error="error on ping oracle database connection:ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library: \"libnnz19.so: cannot open shared object file: No such file or directory\". See https://oracle.github.io/odpi/doc/installation.html#linux for help"] [stack="main.main\n\t/root/marvin/transferdb/cmd/main.go:72\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"]
`

**To Reproduce**
At least the offending source code;
the best is a minimal test case that reproduces the error.
```
func ORAEngine(oraCfg sourceConfig) (*sql.DB, error) {
	connString := fmt.Sprintf("oracle://%s:%s@%s/%s?%s",
		oraCfg.Username, oraCfg.Password, utils.StringsBuilder(oraCfg.Host, ":", strconv.Itoa(oraCfg.Port)),
		oraCfg.ServiceName, oraCfg.ConnectParams)

	oraDSN, err := godror.ParseDSN(connString)
	if err != nil {
		return nil, err
	}

	oraDSN.OnInitStmts = oraCfg.SessionParams
	oraDSN.LibDir = oraCfg.LibDir

	sqlDB := sql.OpenDB(godror.NewConnector(oraDSN))
	sqlDB.SetMaxIdleConns(0)
	sqlDB.SetMaxOpenConns(0)
	sqlDB.SetConnMaxLifetime(0)

	err = sqlDB.Ping()
	if err != nil {
		return sqlDB, fmt.Errorf("error on ping oracle database connection:%v", err)
	}
	return sqlDB, nil
}```

**Expected behavior**
 libDir  parameter take effect

**Your oracle client version**
instantclient-basic-linux.x64-19.14.0.0.0dbru.zip

19.14

**Your godror version**
v0.33.0

**Your go version**
v1.17.2

**Machine (please complete the following information):**
x86 Linux

**Comment by cjbj** [comment]
libDir won't have any effect on Linux for linking reasons to do with Oracle's libnnz library that are proving to be intractable.  You must set LD_LIBRARY_PATH or run ldconfig before your process starts. This is documented in various places for other drivers that use ODPI-C.  The parameter works on macOS and Windows.

**Comment by wentaojin** [comment]
> libDir won't have any effect on Linux for linking reasons to do with Oracle's libnnz library that are proving to be intractable. You must set LD_LIBRARY_PATH or run ldconfig before your process starts. This is documented in various places for other drivers that use ODPI-C. The parameter works on macOS and Windows.

thanks！
