### ISSUE TITLE
godror.NewQueue method giveing error: newQueue "jrcs_queue": ORA-00000: DPI-1002: invalid dpiConn handle

### ISSUE THREAD

**Issue by Chanduch1** [godror/godror#239]
**Describe the bug**
while creating a queue object with the below code
queue, err = godror.NewQueue(ctx, db, "{{some queue name}}", "")

**To Reproduce**
At least the offending source code;
the best is a minimal test case that reproduces the error.

**Expected behavior**
Queue object should be created

**Error output**
ODPI [166187] 2022-05-23 09:54:29.723: fn start dpiContext_initConnCreateParams(0x1ca6cc0)
ODPI [166187] 2022-05-23 09:54:29.723: fn end dpiContext_initConnCreateParams(0x1ca6cc0) -> 0
ODPI [166187] 2022-05-23 09:54:29.723: fn start dpiConn_create(0x1ca6cc0)
ODPI [166187] 2022-05-23 09:54:29.723: fn end dpiConn_create(0x1ca6cc0) -> 0
2022/05/23 09:54:29 queueName: jrcs_queue, c: &{db:0xc0003e3520 closemu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} dc:0xc0003b1b00 done:0}
ODPI [166187] 2022-05-23 09:54:29.723: fn start dpiContext_initConnCreateParams(0x1ca6cc0)
ODPI [166187] 2022-05-23 09:54:29.723: fn end dpiContext_initConnCreateParams(0x1ca6cc0) -> 0
ODPI [166187] 2022-05-23 09:54:29.723: fn start dpiConn_create(0x1ca6cc0)
ODPI [166187] 2022-05-23 09:54:29.872: fn end dpiConn_create(0x1ca6cc0) -> 0
ODPI [166187] 2022-05-23 09:54:29.872: fn start dpiConn_release(0x7f76640305b0)
ODPI [166187] 2022-05-23 09:54:29.872: fn end dpiConn_release(0x7f76640305b0) -> 0
ODPI [166187] 2022-05-23 09:54:29.872: fn start dpiContext_initConnCreateParams(0x1ca6cc0)
ODPI [166187] 2022-05-23 09:54:29.872: fn end dpiContext_initConnCreateParams(0x1ca6cc0) -> 0
ODPI [166187] 2022-05-23 09:54:29.872: fn start dpiConn_create(0x1ca6cc0)
ODPI [166187] 2022-05-23 09:54:29.872: fn end dpiConn_create(0x1ca6cc0) -> 0
ODPI [166187] 2022-05-23 09:54:29.872: fn start dpiConn_release(0x7f766405f340)
ODPI [166187] 2022-05-23 09:54:29.872: fn end dpiConn_release(0x7f766405f340) -> 0
ODPI [166187] 2022-05-23 09:54:29.872: fn start dpiConn_newQueue((nil))
ODPI [166187] 2022-05-23 09:54:29.872: internal error DPI-1002: invalid dpiConn handle (dpiConn_newQueue / check main handle)
ODPI [166187] 2022-05-23 09:54:29.872: fn end dpiConn_newQueue((nil)) -> -1
2022/05/23 09:54:29 queue: <nil> , error: newQueue "jrcs_queue": ORA-00000: DPI-1002: invalid dpiConn handle
ODPI [166187] 2022-05-23 09:54:29.872: fn start dpiConn_release(0x7f7664029ec0)
ODPI [166187] 2022-05-23 09:54:29.872: fn end dpiConn_release(0x7f7664029ec0) -> 0

**Your oracle client version**
19c

**Your godror version**
v0.29.0

**Your go version**
go1.17.8 linux/amd64

**Machine (please complete the following information):**
 - OS: linux

**Additional context**
This is continuation of the issue:
[godror.NewQueue method giveing error: driver: bad connection #237](https://github.com/godror/godror/issues/237)

**Comment by tgulacsi** [comment]
Please share some source code - you should create a connection with db.Conn or db.BeginTx, and use that for NewQueue and keep it open till you use the Queue!

**Comment by Chanduch1** [comment]
i have fixed the issue with you suggestion. thank you very much
