### ISSUE TITLE
SetTime is not working as expected

### ISSUE THREAD

**Issue by damikem** [godror/godror#24]
Calling SetTime (in data.go) with a non nil time value exit the function without setting the given value.

**Comment by damikem** [comment]
It's a very easy fix, I just can't perform push and merge request for some reason (failed login)
func (d *Data) SetTime(t time.Time) {
	d.dpiData.isNull = C.int(b2i(t.IsZero()))
***
        PUT THIS LINE INSTEAD OF THE CURRENT LINE (drop the == 0)
	if d.dpiData.isNull {
***
		return
	}
	_, z := t.Zone()
	C.dpiData_setTimestamp(&d.dpiData,
		C.int16_t(t.Year()), C.uint8_t(t.Month()), C.uint8_t(t.Day()),
		C.uint8_t(t.Hour()), C.uint8_t(t.Minute()), C.uint8_t(t.Second()), C.uint32_t(t.Nanosecond()),
		C.int8_t(z/3600), C.int8_t((z%3600)/60),
	)
}

**Comment by tgulacsi** [comment]
That won't compile, because dpiData.isNull is an int32, but anyway, you're right, thanks!
