### ISSUE TITLE
SQL Binding variable value passing type

### ISSUE THREAD

**Issue by 892294101** [godror/godror#241]
Example：
res, err := tx.ExecContext(utils.GetContextProName(), insertSql, rd.DBName, rd.EnterpriseID)
rd.DBName, rd.EnterpriseID Type can only be []string or []time etc

Can it be improved to []*string or []*time ？？？

**Comment by tgulacsi** [comment]
Could, but what for?
An empty string is just as NULL for the oracle db, as a nil, and the zero Time is the same.
The extra indirection means complexity allocation and copying.
________________________________
From: 892294101 ***@***.***>
Sent: Monday, June 13, 2022 12:28:44 PM
To: godror/godror ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [godror/godror] SQL Binding variable value passing type (Issue #241)


Example：
res, err := tx.ExecContext(utils.GetContextProName(), insertSql, rd.DBName, rd.EnterpriseID)
rd.DBName, rd.EnterpriseID Type can only be []string or []time etc

Can it be improved to []*string or []*time ？？？

―
