### ISSUE TITLE
Unable to pass parameters to a query

### ISSUE THREAD

**Issue by aleybovich** [godror/godror#248]
**Describe the bug**
I am trying to pass a parameter to the parametrized query: 

```
db.Query("SELECT BARCODE, CONCEPT, SAMPLE, AMOUNT, CONCENTRATION FROM T_CONTAINER WHERE TYPE=':CT' and rownum <= 20", "SOLUTION", ora.FetchArraySize(10))
```
And I get an error: `Error querying database: sql: expected 0 arguments, got 1`

**To Reproduce**
In description above

**Expected behavior**
The query should use the parameter

**Error output**
Error querying database: sql: expected 0 arguments, got 1

**Your oracle client version**
e.g. 19.8

**Your godror version**
 v0.34.0

**Your go version**
1.18.0

**Your gcc version**

```
> gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Machine (please complete the following information):**
 - OS: MacOS
 - Architecture: Intel 64
 - Version: 13

**Additional context**

**Comment by tgulacsi** [comment]
Where is your CT param ?

```db.Query("SELECT BARCODE, CONCEPT, SAMPLE, AMOUNT, CONCENTRATION FROM T_CONTAINER WHERE TYPE=':CT' and rownum <= 20", "SOLUTION", ora.FetchArraySize(10))```

```db.Query("SELECT BARCODE, CONCEPT, SAMPLE, AMOUNT, CONCENTRATION FROM T_CONTAINER WHERE TYPE=:1 and rownum <= 20", "SOLUTION", ora.FetchArraySize(10))```
Or
```db.Query("SELECT BARCODE, CONCEPT, SAMPLE, AMOUNT, CONCENTRATION FROM T_CONTAINER WHERE TYPE=:CT and rownum <= 20", sql.Named("CT","SOLUTION"), ora.FetchArraySize(10))```
Will work.

**Comment by aleybovich** [comment]
Ah, it was quotes around the parameter! Thank you.

**Comment by tgulacsi** [comment]
Not just the quotes, but you either used numbered params (:1,:2.. etc) or named (:ct, :ccc) with sql.Named.

**Comment by aleybovich** [comment]
Named params work without sql.Named as well. i just pass args and they get matched in order

**Comment by cjbj** [comment]
Whether the names of the variables in the SQL text are alphabetic or numeric doesn't determine whether the bind process is 'by position' or 'by name'.  It's how the driver does the mapping from the application data to the SQL statement that determines it.  There can be some traps for beginners with bind-by-position regarding duplicate names and with SQL vs PL/SQL differences, so it is generally recommended to use bind-by-name: see https://oracle.github.io/node-oracledb/doc/api.html#-bind-by-position
