### ISSUE TITLE
Query() returns only the 1st result for an input array

### ISSUE THREAD

**Issue by dinvlad** [godror/godror#25]
**Describe the bug**
ExecuteMany query returns only the 1st result for a named parameter of len > 1.

**To Reproduce**
1. Run a query like the following
```go
rows, err := db.QueryContext(
	godror.ContextWithLog(ctx, logger.Log),
	"SELECT id FROM subjects WHERE id = :id",
	sql.Named("id", []int{1, 2, 3}),
)
if err != nil {
	log.Fatal(err)
}
defer rows.Close()
count := 0
hasNextResult := true
for hasNextResult {
	for rows.Next() {
		var row int
		if err = rows.Scan(&row); err != nil {
			log.Fatal(err)
		}
		fmt.Println(row)
		count++
	}
	hasNextResult = rows.NextResultSet()
}
fmt.Println("count", count)
```
2. Observe that only the 1st result is returned:
```
enter=bindVars args="unsupported value type"
msg=bindVars i=0 in=true out=false value="[]int []int{1, 2, 3}"
doManyCount=3 arrLen=3 doExecMany=true minArrLen=maxArrLen
msg=newVar i=0 plSQLArrays=false typ=2010 natTyp=3000 sliceLen=3 bufSize=0 isSlice=true
1
count 1
```

**Expected behavior**
All results must be returned (corresponding to `count 3` in the above example).

**Your oracle client version**
`18.1.0.0.0`

**Your godror version**
`v0.9.1`

**Your go version**
`1.13.7`

**Your gcc version**
`Apple LLVM version 10.0.1 (clang-1001.0.46.4)`

**Machine (please complete the following information):**
 - OS: macOS
 - Architecture x86_64
 - Version: `10.14.6`

**Additional context**
Same result is observed when the array is passed as an unnamed parameter.

**Comment by dinvlad** [comment]
Looks like this might not be supported by Oracle atm: https://github.com/oracle/python-cx_Oracle/issues/232#issuecomment-432332718

**Comment by tgulacsi** [comment]
Yes, this is unsupported by Oracle.
BTW what would you expect for a 
```
rows, err := db.Query("SELECT id FROM subjects WHERE id = :1", []int{1, 2, 3})
```
query? What kind of set has elements where EACH row satisfies the WHERE clause?
Maybe you want a `WHERE id IN (:1)` ?
That's not supported by Oracle, either - but you can use a simple helper function that builds the `IN`.
But at most 1000 elements is supported in an `IN`, after that you have to use `UNION ALL` - so becomes complex fast...

**Comment by dinvlad** [comment]
> Maybe you want a WHERE id IN (:1) ?

Indeed! That was the goal, and the initial format. But then I found out that it would (counter-intuitively) run ExecuteMany in this case, so each step in the “parameter sweep” would be effectively rendered into `WHERE id IN (1)` etc., so I changed that to equality as an equivalent (but of course, that doesn’t work either).

> but you can use a simple helper function that builds the IN.

Could you elaborate please?

I also looked at PL/SQL as possibly more appropriate for this, but couldn’t figure out how to use it here..

> But at most 1000 elements is supported in an IN

Aware of this limit, but would prefer a more idiomatic solution of course. Another solution suggested on Oracle forums is to load all values into a temporary table, but then the question becomes “how do we efficiently pass an array into an INSERT statement” (sorry, grasping at strands here as I’m not really an Oracle guru..)

BTW, is there a more appropriate format to ask questions like these about the use of the library? I only saw Bug/Feature templates for the issues, so apologies if I marked it incorrectly).

**Comment by dinvlad** [comment]
OK, I found a reasonable workaround (thanks to https://stackoverflow.com/a/28176621/2962507).
I can pass the array as a CSV string, and then parse it into a column inside:
```sql
SELECT id
FROM subjects
WHERE
  id IN (SELECT TO_NUMBER(column_value) FROM xmltable(:ids))
```
This limits the total length of `ids` parameter to 4,000 bytes (so a potentially lower limit than the 1,000 elements `IN (..., ..., ...)`). But at least it enables using prepared statements instead of dynamic queries, and usually we don't deal with that many elements anyway.

If you have any other suggestions, I'd really appreciate it!

**Comment by tgulacsi** [comment]
With godror.PlSQLArrays option, you can inject a "PL/SQL TABLE INDEX BY PLS_INTEGER" into a stored procedure / anonymous block:
```
db.Exec(
`DECLARE
  TYPE pls_tt IS TABLE OF PLS_INTEGER INDEX BY PLS_INTEGER;
  v_tab pls_tt := :1;
BEGIN
  DBMS_OUTPUT.PUT_LINE(v_tab.COUNT);
END;
`,
godror.PlSQLArrays, []int{1,2,3})
```
but still you can't do anything with it - there's not transfer between SQL and PL/SQL (except using a PIPELINE function, but that's too complex).

With Oracle 19c you can use JSON_ARRAY_T for a more type safe, XML-less data transfer.

**Comment by dinvlad** [comment]
Alright, thanks for this! I'll go ahead and close the issue. Since one of our DBs is still on 11.2g, I'll most likely be using `xmltable` for now.

**Comment by cjbj** [comment]
Other general, Oracle suggestions for multiple values in IN binds can be found in https://cx-oracle.readthedocs.io/en/latest/user_guide/bind.html#binding-multiple-values-to-a-sql-where-in-clause  You should do some benchmarking to see what is most efficient.

**Comment by dinvlad** [comment]
Yep, just did some benchmarking today according to that guide. It turned out that `xmltable` performance is really poor - oftentimes taking ~4sec even with only a few elements. I've used multiple `IN`, as suggested in that guide, instead (seems to be working quite well, so far).
