### ISSUE TITLE
hi, How to use BulkInsert?

### ISSUE THREAD

**Issue by zhanghaiyang9999** [godror/godror#259]
HI, all
How to use BulkInsert function to insert hundreds of record one time? thanks!

**Comment by tgulacsi** [comment]
Either you present (same length) slices as a arguments to the statement, or use the godror.Batch helper for it.

**Comment by zhanghaiyang9999** [comment]
> Either you present (same length) slices as a arguments to the statement, or use the godror.Batch helper for it.

Thanks @tgulacsi Would you please give some example codes? thanks!

**Comment by tgulacsi** [comment]
For Batch, See TestBatch in z_batch_test.go
For the other solution, see TestExecuteMany in z_test.go.

**Comment by zhanghaiyang9999** [comment]
> For Batch, See TestBatch in z_batch_test.go For the other solution, see TestExecuteMany in z_test.go.

Thansk @tgulacsi it's great!!
