### ISSUE TITLE
Some connection errors are reported as blank

### ISSUE THREAD

**Issue by kurt-google** [godror/godror#26]
**Describe the bug**
`func fromErrorInfo(errInfo C.dpiErrorInfo) *OraErr` can return an empty string, making debugging difficult.

It assumes errors will be ORA-XXXXX errors but there are cases where it might also be DPI/TNS (I think, we have not captured the specific cause with a debugger yet). Specifically I have noticed it coming from this return statement (technically it's equivalent from goracle)
https://github.com/godror/godror/blob/master/drv.go#L467

Specifically if a dpi context fails to be created it may return a DPI-XXXXX error. If im reading 
https://github.com/oracle/odpi/blame/fce6e31a0d6673ad03ef10738f391ba063a9c046/src/dpiContext.c#L207
Correctly. When context is invalid it goes to `src/dpiGen.c:dpiGen__checkHandle` which creates DPI specific errors that look like they will trigger the blank error codepath.

**To Reproduce**
We see this when initiating connections while networking might be established to a proxy and the proxy accepts packets but the remote instance is never connected so will never respond with data, sometimes we get errors from other parts of the code like"ORA-12547: TNS: lost contact". But typically the error message from this specific return path is blank.

**Expected behavior**
I expect to see the elements of the error as it was populated at the DPI level. Whether it was a TNS/ORA/DPI error.

**Your oracle client version**
12.2.0.1.0

**Your godror version**
v2.23.6

**Your go version**
1.14

**Your gcc version**
unknown

**Machine (please complete the following information):**
 - OS: linux
 - Architecture x86_64
 - Version: EL 7

**Additional context**

**Comment by tgulacsi** [comment]
I'm on vacation now, will look into it next week.
________________________________

**Comment by tgulacsi** [comment]
Hmm,with a quick glance, I cannot see how could `fromErrorInfo` return an empty error - or an error that's Error() returns an empty string.
That'd require code==0 and message=="" - and message is from dpiErrorInfo.message, so that means ODPI returned an empty message...
What do I miss?

**Comment by tgulacsi** [comment]
Ok, I've found that I don't use dpiErrorInfo.messageLength, thus it is read only till '\0'.
000239d fixes this, but I'm not sure that this is the root cause.

**Comment by kurt-google** [comment]
Sorry this slipped through my email, Ill try and test this later this week. Thanks for taking a look.

**Comment by kurt-google** [comment]
I havnt been able to capture this again in a debugger and our networking is no longer as flakey so i'll close this out. If I can capture this issue again with more information ill reopen this.
