### ISSUE TITLE
Can support oracle logical replication?

### ISSUE THREAD

**Issue by zhanghaiyang9999** [godror/godror#260]
Hi All,
Can support Oracle logical replication based on redo log?
If support, we can use this to replicate oracle db from one Oracle instance(database) to another.

**Comment by tgulacsi** [comment]
Logical replication and redo log is totally different concepts.
Oracle does have both, for extra license costs.

Redo logs can be shipped, but it's not an online solution.

Logical replication can be simulated by adding a database trigger that fires on commit
(AFTER DDL and AFTER STATEMENT,  - see https://docs.oracle.com/en/database/oracle/oracle-database/19/lnpls/plsql-triggers.html#GUID-FE23FCE8-DE36-41EF-80A9-6B4B49E80E5B ) and pushes the statement to an AQ, which is transported to another instance and replicated.
Of course this is a very naive logical replication - SYSDATE, SYSTIMESTAMP, DBMS_RANDOM.VALUE, remote views/procedures cannot be used...
