### ISSUE TITLE
Support for querying with question mark placeholders

### ISSUE THREAD

**Issue by harryeti** [godror/godror#262]
**Is your feature request related to a problem? Please describe.**
When I query with question mark placeholder, it throws parameter error.
sql: 
`select {columns} from {table} where id=?`

codes:
`db.Select(sql, id)`

**Comment by tgulacsi** [comment]
No, Oracle does not support this.
But you can replace your question marks with proper placeholders with ReplaceQuestionPlaceholder of 8f41116.
