### ISSUE TITLE
Connecting to Oracle Database with password Containing "@"

### ISSUE THREAD

**Issue by EagleShare** [godror/godror#27]
### What version of Go are you using (`go version`)?

<pre>
1.13.4 

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
windows/amd64

</pre></details>

Connecting to oracle database using sql/database with Open function

Tried both possibilities which didn't work

db, err := sql.Open("goracle", "system/oracle@2019@localhost:1521/orcl")
db, err := sql.Open('goracle', 'system/"oracle@2019"@localhost:1521/orcl')

### What did you expect to see?

Successful connection to Database.

### What did you see instead?
params=oracle://sytem:SECRET-PfbiAOWC07c=@2019"%40localhost:1521/orcl?connectionClass=GORACLE&poolIncrement=1&poolMaxSessions=1000&poolMinSessions=1&sysdba=0&sysoper=0&sysasm=0&standaloneConnection=0&enableEvents=0&heterogeneousPool=0&prelim=0&poolWaitTimeout=3000&poolSessionMaxLifetime=3600&poolSessionTimeout=300 extAuth=0: ORA-12154: TNS:could not resolve the connect identifier specified

**Comment by tgulacsi** [comment]
Use the URL form: 

    db, err := sql.Open("goracle", "oracle://system:oracle%402019@localhost:1521/orcl")

**Comment by EagleShare** [comment]
The above suggested method worked out well. Thank you so much..
