### ISSUE TITLE
Cannot locate a 64-bit Oracle Client library and connect faild

### ISSUE THREAD

**Issue by madoleeee** [godror/godror#272]
**Describe the bug**
Error when connecting to database

**To Reproduce**
```
`package main

import (
	"database/sql"
	"fmt"

	_ "github.com/godror/godror"
)

func main() {

	db, err := sql.Open("godror", `user="temp" password="temp1!a" connectString="(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-seoul-1.oraclecloud.com))(connect_data=(service_name=gee9edfb93f3cf6_issuecon_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))"`)
	if err != nil {
		panic(err.Error())
	}
	defer db.Close()

	fmt.Print(db.Ping())

}
`
```

**Expected behavior**
Not sure if it's a driver issue

**Error output**
`ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 0x0001): tried: 'libclntsh.dylib' (no such file), '/usr/local/lib/libclntsh.dylib' (no such file), '/usr/lib/libclntsh.dylib' (no such file),`

**Your oracle client version**
oracle cloud autonomous 19c

**Your godror version**
github.com/sijms/go-ora/v2 v2.5.21

**Your go version**
go version go1.19.3 darwin/arm64

**Your gcc version**
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Machine (please complete the following information):**
macbook pro - apple m1 12.5.1

**Additional context**

I am using Oracle for the first time. When I try to connect with golang, the above error is returned. I have been struggling for several days.
What should I do to solve the above and use godror without problems?

**Comment by tgulacsi** [comment]
You must install Oracle Instant Client

**Comment by madoleeee** [comment]
it is possible in m1 mac ?

**Comment by madoleeee** [comment]
> You must install Oracle Instant Client
it is possible in m1 mac ?

**Comment by tgulacsi** [comment]
Natively  not, with "arch -x86_64" yes.

This may help: https://gist.github.com/wattry/5e5d917682c80b1834147ab5851dc92c
