### ISSUE TITLE
Bulk execute merge into with large CLOB column

### ISSUE THREAD

**Issue by freeNestor** [godror/godror#274]
I used bulk execute merge into and encountered CLOBs that failed to be stored, but other fields were successfully stored and no error returned. Is there any way to solve it?
My code like below：

```bindClob = append(bindClob, godror.Lob{Reader: strings.NewReader(datatodb.(string)), IsClob: true})```
...
```bindtailslice[i] = bindClob```

database code sinppet:
```
        ctxTimeout, cancel := context.WithTimeout(context.Background(), time.Second*time.Duration(cmercfg.WriteTimeout))
	defer cancel()
	getconn, err := dstconn.Conn(ctxTimeout)
	if err != nil {
		return fmt.Errorf("bulk merge into, getconn error: %v - sql: %s", err, sqlbufstr)
	}
	defer getconn.Close()
	var stmt *sql.Stmt
	stmt, err = getconn.PrepareContext(ctxTimeout, sqlbufstr)
	if err != nil {
		return fmt.Errorf("prepare merge into sql error: %v - sql: %s", err, sqlbufstr)
	}
	defer stmt.Close()
	_, err = stmt.ExecContext(ctxTimeout, bindslice...)
	if err != nil {
		// transx.Rollback()
		return fmt.Errorf("bulk merge into error: %v - sql: %s", err, sqlbufstr)
	}
	return nil
```
sqlbufstr is string for a merge into sql like: "MERGE INTO .... using ON ... WHEN MATCHED THEN ... WHEN NOT MATCHED THEN INSERT ..."

**Comment by tgulacsi** [comment]
What is the error?How many records?Try it with string, not godrorLob.

**Comment by freeNestor** [comment]
> What is the error?How many records?Try it with string, not godrorLob.

no error returned, ExecContext() executed successfully. I tested only one record, and clob column was larger than 1Mb.
With string is ok but will cause ora error. I tried to use godrorLob due to error "ORA-03146: invalid buffer length for TTC field" with string.

**Comment by sudarshan12s** [comment]
Can you share the Oracle instant client and server versions . 
For lob case on terminal , can you set this env and share the console logs:
`DPI_DEBUG_LEVEL=92`

For strings multi row insert, does it happen in initial ExecContext call or in subsequent batches . somewhat similar test is found here, z_issue133_test.go

**Comment by freeNestor** [comment]
> DPI_DEBUG_LEVEL

Client Shared Library 64-bit - 21.5.0.0.0
Oracle Database is 19.9

logs: 
[nohup.txt](https://github.com/godror/godror/files/10765097/nohup.txt)

**Comment by freeNestor** [comment]
Thx, I'll check z_issue133_test.go later.

**Comment by freeNestor** [comment]
> For strings multi row insert, does it happen in initial ExecContext call or in subsequent batches . somewhat similar test is found here, z_issue133_test.go
I have got info from DBA that ORA-03146 is a bug in oracle DB 19.9 when merged clob column with large strings, so I tried godrorLob as workaround, but failed like above. This DB bug can be solved after a patch, I just want to work on a workaround solution.

**Comment by sudarshan12s** [comment]
> > DPI_DEBUG_LEVEL
> 
> Client Shared Library 64-bit - 21.5.0.0.0 Oracle Database is 19.9
> 
> logs: [nohup.txt](https://github.com/godror/godror/files/10765097/nohup.txt)

Thanks for sharing the logs. logs abnormally terminated , was this complete logs of the application doing a lob write ?

**Comment by freeNestor** [comment]
> Thanks for sharing the logs. logs abnormally terminated , was this complete logs of the application doing a lob write ?

Sorry, I truncated it I think there's nothing useful for you after the truncation. I can confirm there's a lob write before truncation.
