### ISSUE TITLE
preferrably do not use a global logger but one per connection(pool)

### ISSUE THREAD

**Issue by jxsl13** [godror/godror#277]
**Is your feature request related to a problem? Please describe.**
It would be great if the connection pool defined either some option or a method or both to allow to change the underlying logger for a single instance of the connection pool.

It's a pretty rare use case if you want to connect to two or more oracle databases with two different loggers but it's imo cleaner to have a logger for each instance. 

It might make sense to have connections inherit the logger from their pool.

Just a suggestion.

**Comment by tgulacsi** [comment]
A Logger embedded in Context would be more go-like.
But what Logger? I'm waiting for golang.org/x/exp/slog to be accepted as log/slog to finally finish all logger migrations...

**Comment by jxsl13** [comment]
https://github.com/godror/godror/blob/c2f7bab525ee9294a1a2e3d3a01d47084ffa4d25/log.go#L19-L24
Isn't this the logger the library already uses?
So maybe just this one?
Long term it would be great to have slog, I guess.
Maybe just define a logger interface and some default logger that does nothing an dlet the user decide which logger to use.

**Comment by jxsl13** [comment]
I don't think that using the context for saving a logger is the best way to do that. 
Imo context.Context.WithValue is bad.
It's making the code worse in places where you do not have a context, imo, for example: getLogger(nil)
I would have a struct field for the logger.

Here is an example of how I (would) do it.
 Maybe more than my opinion would make this discussion better.

https://github.com/jxsl13/amqpx/blob/main/pool/pool.go#L37-L56
To be clear, I do borrow the interface from logrus because I do use logrus as my default logger.
You might want to use a different logger.

In the end if people want to use a different logger, they will define a wrapper struct that implements the interface.
When using for example pgx, I also define a wrapper for my logger, as pgx has a completely different logger interface.

**Comment by jxsl13** [comment]
Maybe it's necessary to propagate a logger through the driver:
https://github.com/godror/godror/blob/c2f7bab525ee9294a1a2e3d3a01d47084ffa4d25/drv.go#L184-L217

but that's again somewhat global state.
In the end it looks like you want to use the context.
Tricky one.

**Comment by jxsl13** [comment]
This wrapper also looks interesting:
https://github.com/jackc/pgx/tree/2cf1541bb90ae2244bfee2d5ec6511811425ed4a/stdlib
They define a global variable with a configurations map that is used to pass/register loggers and other config values.

**Comment by tgulacsi** [comment]
What's the goal?

Pool is used through database/sql.DB, which does it's own pooling.
So you may or may not get a new connection, may or may not see the logger change.

If you want to set the logger for a statement, that's easier (see FetchRowCount for example).

So, with what granularity do you want to set the logger?

**Comment by jxsl13** [comment]
a logger per connection pool.

**Comment by tgulacsi** [comment]
PTAL the "logger" branch (828f3ad).

**Comment by tgulacsi** [comment]
@jxsl13 could you vet/test it?

**Comment by jxsl13** [comment]
I'm not a big fan of forcing a specific.
I sadly currently don't have the time to test it. 
I think this needs a more in depth discussion before implementing a lot of stuff.
