### ISSUE TITLE
Fatal error when it runs as non-root user

### ISSUE THREAD

**Issue by chilingpan123** [godror/godror#280]
**Describe the bug**
When the package is run as root user, it works fine. Due to security requirement, we need to run it as non-root user. When running as non-root user, it failed.

**To Reproduce**
build a docker image, and run it using non-root user.

**Expected behavior**
It should work as non-root user the same as root user does.

**Error output**
Copy the error output (panic, stack trace),
double free or corruption (!prev)
SIGABRT: abort
PC=0x7fbefaaa200b m=52 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 345 [syscall, locked to thread]:
runtime.cgocall(0x82ded0, 0xc00053d700)
        /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc00053d6d8 sp=0xc00053d6a0 pc=0x410d3c
github.com/godror/godror._Cfunc_dpiConn_create(0x7fbeac08b5b0, 0x7fbecc003fc0, 0x5, 0x7fbde000c980, 0x8, 0x7fbde000c9a0, 0x7d, 0xc000a8c300, 0xc00062b0e0, 0xc0000140c8)
        _cgo_gotypes.go:2297 +0x4c fp=0xc00053d700 sp=0xc00053d6d8 pc=0x72c16c
github.com/godror/godror.(*drv).acquireConn.func8.1(0xc0003c4800?, 0xc00053d7d8?, {0xc000031430?, 0x5}, 0x7fbefaa251a0?, {0xc000031450?, 0x8}, 0x8?, 0xc0003c4800?, 0xc000a8c300, ...)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:538 +0x159 fp=0xc00053d790 sp=0xc00053d700 pc=0x73ad39
github.com/godror/godror.(*drv).acquireConn.func8()
        /go/xproxy/vendor/github.com/godror/godror/drv.go:538 +0x57 fp=0xc00053d800 sp=0xc00053d790 pc=0x73abb7
github.com/godror/godror.(*drv).checkExec(0xc000352300?, 0xc00053dae8)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:244 +0x59 fp=0xc00053d840 sp=0xc00053d800 pc=0x7386b9
github.com/godror/godror.(*drv).acquireConn(_, _, {{{0xc000031430, 0x5}, {0xc000352300, 0x7d}, {{0xc000031450, 0x8}}, {0x0, 0x0}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:530 +0x8a5 fp=0xc00053dce8 sp=0xc00053d840 pc=0x739f65
github.com/godror/godror.(*drv).createConn(_, _, {{{0xc000031430, 0x5}, {0xc000352300, 0x7d}, {{0xc000031450, 0x8}}, {0x0, 0x0}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:351 +0xa8 fp=0xc00053e030 sp=0xc00053dce8 pc=0x739248
github.com/godror/godror.(*drv).createConnFromParams(_, {{{0xc000031430, 0x5}, {0xc000352300, 0x7d}, {{0xc000031450, 0x8}}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:568 +0x25b fp=0xc00053e450 sp=0xc00053e030 pc=0x73b7db
github.com/godror/godror.connector.Connect({0xc3d880, {{{0xc000031430, 0x5}, {0xc000352300, 0x7d}, {{...}}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}}, ...)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:1063 +0x778 fp=0xc00053eb38 sp=0xc00053e450 pc=0x73f198
github.com/godror/godror.(*connector).Connect(0xc000210c40?, {0x9b28d8?, 0xc000210c40?})
        <autogenerated>:1 +0xbe fp=0xc00053edc8 sp=0xc00053eb38 pc=0x76249e
database/sql.(*DB).conn(0xc0001b7ee0, {0x9b28d8, 0xc000210c40}, 0x1)
        /usr/local/go/src/database/sql/sql.go:1393 +0x763 fp=0xc00053ef40 sp=0xc00053edc8 pc=0x71c923
database/sql.(*DB).query(0x0?, {0x9b28d8, 0xc000210c40}, {0x911de0, 0x8b}, {0x0, 0x0, 0x0}, 0xb1?)
        /usr/local/go/src/database/sql/sql.go:1730 +0x5d fp=0xc00053efc0 sp=0xc00053ef40 pc=0x71d69d
database/sql.(*DB).QueryContext(0x9b2948?, {0x9b28d8, 0xc000210c40}, {0x911de0, 0x8b}, {0x0, 0x0, 0x0})
        /usr/local/go/src/database/sql/sql.go:1708 +0xda fp=0xc00053f040 sp=0xc00053efc0 pc=0x71d51a
github.corp.ebay.com/montage/goproxy/cmd/xproxy/handlers.getState({0x9b2948, 0xc00060cfc0}, {0xc000642129, 0x18}, 0x8?, {0xc000642147, 0x5}, 0xc00053f568)
        /go/xproxy/cmd/xproxy/handlers/dbcheck.go:209 +0x357 fp=0xc00053f4e8 sp=0xc00053f040 pc=0x7fb077
github.corp.ebay.com/montage/goproxy/cmd/xproxy/handlers.DbCheck({0x9b2438, 0xc00061c380}, 0xc000270e00)
        /go/xproxy/cmd/xproxy/handlers/dbcheck.go:142 +0x4ba fp=0xc00053f878 sp=0xc00053f4e8 pc=0x7fa59a
net/http.HandlerFunc.ServeHTTP(0xc000242120?, {0x9b2438?, 0xc00061c380?}, 0xc00043a920?)
        /usr/local/go/src/net/http/server.go:2109 +0x2f fp=0xc00053f8a0 sp=0xc00053f878 pc=0x68ae4f
github.corp.ebay.com/montage/goproxy/handler.(*AuthHandler).Middleware.func1({0x9b2438, 0xc00061c380}, 0xc000270e00)
        /go/xproxy/handler/auth.go:86 +0x65a fp=0xc00053f978 sp=0xc00053f8a0 pc=0x80333a
net/http.HandlerFunc.ServeHTTP(0xc000270b00?, {0x9b2438?, 0xc00061c380?}, 0xc0004c69e0?)
        /usr/local/go/src/net/http/server.go:2109 +0x2f fp=0xc00053f9a0 sp=0xc00053f978 pc=0x68ae4f

**Your oracle client version**
e.g. 12.2.0.1.0

**Your godror version**
v0.24.6

**Your go version**
1.19.1

**Your gcc version**
Not sure gcc version

**Machine (please complete the following information):**
Ubuntu 20.04

**Additional context**
The same docker image works fine when run as root user, but not working as non-root user. They run with same OS and go version.

**Comment by tgulacsi** [comment]
v0.24.6 is two years old, please try with a never version (master or v0.37.0).

The user it is run should not matter - I bet it's a connection error that's handled badly.

**Comment by chilingpan123** [comment]
@tgulacsi Thanks for your reply.
I upgrade to use v0.37.0. But the issue still there. Here is the new stack trace:

malloc(): unsorted double linked list corrupted
SIGABRT: abort
PC=0x7f0c1f6e400b m=24 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 610 [syscall, locked to thread]:
runtime.cgocall(0x98b950, 0xc00074b3f0)
        /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc00074b3c8 sp=0xc00074b390 pc=0x4123bc
github.com/godror/godror._Cfunc_dpiConn_create(0x7f0bd008b5b0, 0x7f0b84078670, 0x5, 0x7f0b840c9330, 0x8, 0x7f0b840c7370, 0x7f, 0xc0004eca00, 0xc0002921b0, 0xc0004aa138)
        _cgo_gotypes.go:2592 +0x4c fp=0xc00074b3f0 sp=0xc00074b3c8 pc=0x83dd8c
github.com/godror/godror.(*drv).acquireConn.func8.1(0x41be3f?, 0x840c737000000000?, {0xc000210008?, 0x5}, 0x845389?, {0xc000210030?, 0x8}, 0x8?, 0x7f0c1f65e5b8?, 0xc0004eca00, ...)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:572 +0x159 fp=0xc00074b480 sp=0xc00074b3f0 pc=0x855db9
github.com/godror/godror.(*drv).acquireConn.func8()
        /go/xproxy/vendor/github.com/godror/godror/drv.go:572 +0x57 fp=0xc00074b4f0 sp=0xc00074b480 pc=0x855c37
github.com/godror/godror.(*drv).checkExecNoLOT(0x41c187?, 0x8?)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:254 +0x22 fp=0xc00074b510 sp=0xc00074b4f0 pc=0x853322
github.com/godror/godror.(*drv).checkExec(0xc000382480?, 0x7f?)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:248 +0x34 fp=0xc00074b540 sp=0xc00074b510 pc=0x853274
github.com/godror/godror.(*drv).acquireConn(_, _, {{{0xc000210008, 0x5}, {0xc000382480, 0x7f}, {{0xc000210030, 0x8}}, {0x0, 0x0}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:564 +0x8e5 fp=0xc00074b9f8 sp=0xc00074b540 pc=0x855045
github.com/godror/godror.(*drv).createConn(_, _, {{{0xc000210008, 0x5}, {0xc000382480, 0x7f}, {{0xc000210030, 0x8}}, {0x0, 0x0}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:379 +0xa8 fp=0xc00074bd80 sp=0xc00074b9f8 pc=0x854208
github.com/godror/godror.(*drv).createConnFromParams(_, {_, _}, {{{0xc000210008, 0x5}, {0xc000382480, 0x7f}, {{0xc000210030, 0x8}}, {0x0, ...}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:604 +0x27b fp=0xc00074c250 sp=0xc00074bd80 pc=0x85687b
github.com/godror/godror.connector.Connect({0xf14aa0, {{{0xc000210008, 0x5}, {0xc000382480, 0x7f}, {{...}}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}}, ...)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:1125 +0x7ea fp=0xc00074ca48 sp=0xc00074c250 pc=0x85a8ea
github.com/godror/godror.(*connector).Connect(0xc0004979c0?, {0xb85b38?, 0xc0004979c0?})
        <autogenerated>:1 +0xbe fp=0xc00074cd38 sp=0xc00074ca48 pc=0x8a6c5e
database/sql.(*DB).conn(0xc000a84750, {0xb85b38, 0xc0004979c0}, 0x1)
        /usr/local/go/src/database/sql/sql.go:1393 +0x763 fp=0xc00074ceb0 sp=0xc00074cd38 pc=0x771aa3
database/sql.(*DB).query(0x0?, {0xb85b38, 0xc0004979c0}, {0xabb443, 0x8b}, {0x0, 0x0, 0x0}, 0xf1?)
        /usr/local/go/src/database/sql/sql.go:1730 +0x5d fp=0xc00074cf30 sp=0xc00074ceb0 pc=0x7741bd
database/sql.(*DB).QueryContext(0xb85ba8?, {0xb85b38, 0xc0004979c0}, {0xabb443, 0x8b}, {0x0, 0x0, 0x0})
        /usr/local/go/src/database/sql/sql.go:1708 +0xda fp=0xc00074cfb0 sp=0xc00074cf30 pc=0x773f9a
github.corp.ebay.com/montage/goproxy/cmd/xproxy/handlers.getState({0xb85ba8, 0xc0005919e0}, {0xc00002af99, 0x1a}, 0x9?, {0xc00002afb9, 0x5}, 0xc00074d568)
        /go/xproxy/cmd/xproxy/handlers/dbcheck.go:209 +0x357 fp=0xc00074d4e8 sp=0xc00074cfb0 pc=0x9565d7
github.corp.ebay.com/montage/goproxy/cmd/xproxy/handlers.DbCheck({0xb855d0, 0xc0002dab60}, 0xc000375500)
        /go/xproxy/cmd/xproxy/handlers/dbcheck.go:142 +0x4ba fp=0xc00074d878 sp=0xc00074d4e8 pc=0x955afa
net/http.HandlerFunc.ServeHTTP(0xc0001ce2d0?, {0xb855d0?, 0xc0002dab60?}, 0xc00030b320?)
        /usr/local/go/src/net/http/server.go:2109 +0x2f fp=0xc00074d8a0 sp=0xc00074d878 pc=0x6d21af
github.corp.ebay.com/montage/goproxy/handler.(*AuthHandler).Middleware.func1({0xb855d0, 0xc0002dab60}, 0xc000375500)
        /go/xproxy/handler/auth.go:86 +0x65a fp=0xc00074d978 sp=0xc00074d8a0 pc=0x95e8fa
net/http.HandlerFunc.ServeHTTP(0xc000375400?, {0xb855d0?, 0xc0002dab60?}, 0xc0007629e0?)
        /usr/local/go/src/net/http/server.go:2109 +0x2f fp=0xc00074d9a0 sp=0xc00074d978 pc=0x6d21af
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000332300, {0xb855d0, 0xc0002dab60}, 0xc000375000)
        /go/xproxy/vendor/github.com/gorilla/mux/mux.go:210 +0x1cf fp=0xc00074dac8 sp=0xc00074d9a0 pc=0x8aa76f
net/http.serverHandler.ServeHTTP({0xc000346360?}, {0xb855d0, 0xc0002dab60}, 0xc000375000)
        /usr/local/go/src/net/http/server.go:2947 +0x30c fp=0xc00074db78 sp=0xc00074dac8 pc=0x6d55ac
net/http.(*conn).serve(0xc0003152c0, {0xb85be0, 0xc00037b5c0})
        /usr/local/go/src/net/http/server.go:1991 +0x607 fp=0xc00074dfb8 sp=0xc00074db78 pc=0x6d0c87
net/http.(*Server).Serve.func3()
        /usr/local/go/src/net/http/server.go:3102 +0x2e fp=0xc00074dfe0 sp=0xc00074dfb8 pc=0x6d5eee
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00074dfe8 sp=0xc00074dfe0 pc=0x4794e1
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3102 +0x4db

**Comment by chilingpan123** [comment]
You suspect connection issue.
But the same docker image run on 2 different kubenetes cluster and connect to same oracle DBs. What could be connection issue happen on one cluster, but not on the other?

**Comment by tgulacsi** [comment]
The error ("malloc(): unsorted double linked list corrupted") is thrown in "C.dpiConn_create", which is an ODPI-C function.

context is checked for non-nullness,

userName, userNameLength, password and passwordLength for constency between pointer and length,
commonParams and createParams is created if null,
conn is always created.

For following the code (dpiConn_create in odpi/src/dpiConn.c) please provide your connection string - password redacted.

(External auth may conflict with the running user, for example).


https://stackoverflow.com/a/18035797 and https://stackoverflow.com/a/28762523 suggests that Valgrind may be used to find the corrupting code.

**Comment by chilingpan123** [comment]
@tgulacsi 
The kubenetes pod got restarted again and again. It always succeeded querying DB data for some time and then failed with different message. There is an error shows password expired, which explains the first failure. But didn't happen for the second and third time. 

1. first error:
time="2023-
-01T18:47:35Z" level=info msg="user: xxx, pass: xxxx"
time="2023-05-01T18:47:35Z" level=info msg="ConnectString: (description=(address=(protocol=tcp)(host=host1)(port=1521))(connect_data=(sid=EOS))(connect_timeout=5))"
time="2023-05-01T18:47:35Z" level=error msg="fetch session fail, due to user=\"xxxx\" standalone params={authMode:0 connectionClass:<nil> connectionClassLength:0 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:0 externalHandle:<nil> pool:<nil> tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-28001: the password has expired" client="127.0.0.1:46732" unit=dbcheck uri="/db/sessions?endpoint=host1:1521:EOS"
godror WARNING: discrepancy between DBTIMEZONE ("+00:00"=0) and SYSTIMESTAMP ("-07:00"=-700) - set connection timezone, see https://github.com/godror/godror/blob/master/doc/timezone.md
time="2023-05-01T18:47:35Z" level=info msg="user: xxxx, pass: xxxx"
time="2023-05-01T18:47:35Z" level=info msg="ConnectString: (description=(address=(protocol=tcp)(host=host2)(port=1521))(connect_data=(sid=DDS))(connect_timeout=5))"
time="2023-05-01T18:47:35Z" level=info msg="user: xxxx, pass: xxxx"
time="2023-05-01T18:47:35Z" level=info msg="ConnectString: (description=(address=(protocol=tcp)(host=host3)(port=1521))(connect_data=(sid=DDS))(connect_timeout=5))"
time="2023-05-01T18:47:35Z" level=info msg="user: xxxx, pass: xxxx"
time="2023-05-01T18:47:35Z" level=info msg="ConnectString: (description=(address=(protocol=tcp)(host=host4)(port=1521))(connect_data=(sid=CHKOUT21))(connect_timeout=5))"
malloc(): unsorted double linked list corrupted
SIGABRT: abort
PC=0x7f6d077eb00b m=18 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 904 [syscall, locked to thread]:
runtime.cgocall(0x9875d0, 0xc000709398)
        /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc000709370 sp=0xc000709338 pc=0x4123bc
github.com/godror/godror._Cfunc_dpiConn_create(0x7f6cc808b700, 0x7f6c900b2910, 0x5, 0x7f6c900e47e0, 0x8, 0x7f6c900e4130, 0x7b, 0xc0005b94a0, 0xc000590120, 0xc0005ae238)
        _cgo_gotypes.go:2592 +0x4c fp=0xc000709398 sp=0xc000709370 pc=0x83992c
github.com/godror/godror.(*drv).acquireConn.func8.1(0x41be3f?, 0x900e413000000000?, {0xc000210000?, 0x5}, 0x840f29?, {0xc000210020?, 0x8}, 0x8?, 0x7f6d07765f18?, 0xc0005b94a0, ...)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:572 +0x159 fp=0xc000709428 sp=0xc000709398 pc=0x851959
github.com/godror/godror.(*drv).acquireConn.func8()
        /go/xproxy/vendor/github.com/godror/godror/drv.go:572 +0x57 fp=0xc000709498 sp=0xc000709428 pc=0x8517d7
github.com/godror/godror.(*drv).checkExecNoLOT(0x41c187?, 0x8?)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:254 +0x22 fp=0xc0007094b8 sp=0xc000709498 pc=0x84eec2
github.com/godror/godror.(*drv).checkExec(0xc0005be000?, 0x7b?)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:248 +0x34 fp=0xc0007094e8 sp=0xc0007094b8 pc=0x84ee14
github.com/godror/godror.(*drv).acquireConn(_, _, {{{0xc000210000, 0x5}, {0xc0005be000, 0x7b}, {{0xc000210020, 0x8}}, {0x0, 0x0}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:564 +0x8e5 fp=0xc0007099a0 sp=0xc0007094e8 pc=0x850be5
github.com/godror/godror.(*drv).createConn(_, _, {{{0xc000210000, 0x5}, {0xc0005be000, 0x7b}, {{0xc000210020, 0x8}}, {0x0, 0x0}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:379 +0xa8 fp=0xc000709d28 sp=0xc0007099a0 pc=0x84fda8
github.com/godror/godror.(*drv).createConnFromParams(_, {_, _}, {{{0xc000210000, 0x5}, {0xc0005be000, 0x7b}, {{0xc000210020, 0x8}}, {0x0, ...}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:604 +0x27b fp=0xc00070a1f8 sp=0xc000709d28 pc=0x85241b
github.com/godror/godror.connector.Connect({0xf0c9c0, {{{0xc000210000, 0x5}, {0xc0005be000, 0x7b}, {{...}}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}}, ...)


2. second error after kubnetes pod restarted:

time="2023-05-01T18:57:54Z" level=info msg="user: xxxx, pass: xxxx"
time="2023-05-01T18:57:54Z" level=info msg="ConnectString: (description=(address=(protocol=tcp)(host=host5)(port=1521))(connect_data=(sid=GBARC2))(connect_timeout=5))"
double free or corruption (top)
SIGABRT: abort
PC=0x7f7db5c6900b m=26 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 283 [syscall, locked to thread]:
runtime.cgocall(0x9875d0, 0xc00033f398)
        /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc00033f370 sp=0xc00033f338 pc=0x4123bc
github.com/godror/godror._Cfunc_dpiConn_create(0x2df9330, 0x7f7d300c9020, 0x5, 0x7f7d300c9160, 0x8, 0x7f7d3001ba80, 0x85, 0xc000338780, 0xc000560cf0, 0xc000014080)
        _cgo_gotypes.go:2592 +0x4c fp=0xc00033f398 sp=0xc00033f370 pc=0x83992c
github.com/godror/godror.(*drv).acquireConn.func8.1(0x41be3f?, 0x3001ba8000000000?, {0xc00024b450?, 0x5}, 0x840f29?, {0xc00024b470?, 0x8}, 0x8?, 0x7f7db5be35b8?, 0xc000338780, ...)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:572 +0x159 fp=0xc00033f428 sp=0xc00033f398 pc=0x851959
github.com/godror/godror.(*drv).acquireConn.func8()
        /go/xproxy/vendor/github.com/godror/godror/drv.go:572 +0x57 fp=0xc00033f498 sp=0xc00033f428 pc=0x8517d7
github.com/godror/godror.(*drv).checkExecNoLOT(0x41c187?, 0x8?)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:254 +0x22 fp=0xc00033f4b8 sp=0xc00033f498 pc=0x84eec2
github.com/godror/godror.(*drv).checkExec(0xc0003ca120?, 0x85?)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:248 +0x34 fp=0xc00033f4e8 sp=0xc00033f4b8 pc=0x84ee14
github.com/godror/godror.(*drv).acquireConn(_, _, {{{0xc00024b450, 0x5}, {0xc0003ca120, 0x85}, {{0xc00024b470, 0x8}}, {0x0, 0x0}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:564 +0x8e5 fp=0xc00033f9a0 sp=0xc00033f4e8 pc=0x850be5
github.com/godror/godror.(*drv).createConn(_, _, {{{0xc00024b450, 0x5}, {0xc0003ca120, 0x85}, {{0xc00024b470, 0x8}}, {0x0, 0x0}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:379 +0xa8 fp=0xc00033fd28 sp=0xc00033f9a0 pc=0x84fda8
github.com/godror/godror.(*drv).createConnFromParams(_, {_, _}, {{{0xc00024b450, 0x5}, {0xc0003ca120, 0x85}, {{0xc00024b470, 0x8}}, {0x0, ...}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:604 +0x27b fp=0xc0003401f8 sp=0xc00033fd28 pc=0x85241b
github.com/godror/godror.connector.Connect({0xf0c9c0, {{{0xc00024b450, 0x5}, {0xc0003ca120, 0x85}, {{...}}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}}, ...)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:1125 +0x7ea fp=0xc0003409f0 sp=0xc0003401f8 pc=0x85648a
github.com/godror/godror.(*connector).Connect(0xc000262b00?, {0xb80a58?, 0xc000262b00?})


3. third error after kubnetes pod restarted again:

time="2023-05-01T19:02:59Z" level=info msg="user: xxxx, pass: xxxx"
time="2023-05-01T19:02:59Z" level=info msg="ConnectString: (description=(address=(protocol=tcp)(host=host4)(port=1521))(connect_data=(sid=CATY21))(connect_timeout=5))"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f0ddc5d48c1]

runtime stack:
runtime.throw({0xaaba15?, 0x7f0d87069e22?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f0dad7f33f0 sp=0x7f0dad7f33c0 pc=0x445edd
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:819 +0x369 fp=0x7f0dad7f3440 sp=0x7f0dad7f33f0 pc=0x45c609

goroutine 86 [syscall, locked to thread]:
runtime.cgocall(0x9875d0, 0xc0003df398)
        /usr/local/go/src/runtime/cgocall.go:158 +0x5c fp=0xc0003df370 sp=0xc0003df338 pc=0x4123bc
github.com/godror/godror._Cfunc_dpiConn_create(0x131b5d0, 0x7f0d9014bc30, 0x5, 0x7f0d90169100, 0x8, 0x7f0d9000c9a0, 0x7d, 0xc0006448c0, 0xc00028a900, 0xc00057c0d8)
        _cgo_gotypes.go:2592 +0x4c fp=0xc0003df398 sp=0xc0003df370 pc=0x83992c
github.com/godror/godror.(*drv).acquireConn.func8.1(0x41be3f?, 0x9000c9a000000000?, {0xc000030048?, 0x5}, 0x840f29?, {0xc000030070?, 0x8}, 0x8?, 0x7f0ddc4fca68?, 0xc0006448c0, ...)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:572 +0x159 fp=0xc0003df428 sp=0xc0003df398 pc=0x851959
github.com/godror/godror.(*drv).acquireConn.func8()
        /go/xproxy/vendor/github.com/godror/godror/drv.go:572 +0x57 fp=0xc0003df498 sp=0xc0003df428 pc=0x8517d7
github.com/godror/godror.(*drv).checkExecNoLOT(0x41c187?, 0x8?)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:254 +0x22 fp=0xc0003df4b8 sp=0xc0003df498 pc=0x84eec2
github.com/godror/godror.(*drv).checkExec(0xc000350100?, 0x7d?)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:248 +0x34 fp=0xc0003df4e8 sp=0xc0003df4b8 pc=0x84ee14
github.com/godror/godror.(*drv).acquireConn(_, _, {{{0xc000030048, 0x5}, {0xc000350100, 0x7d}, {{0xc000030070, 0x8}}, {0x0, 0x0}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:564 +0x8e5 fp=0xc0003df9a0 sp=0xc0003df4e8 pc=0x850be5
github.com/godror/godror.(*drv).createConn(_, _, {{{0xc000030048, 0x5}, {0xc000350100, 0x7d}, {{0xc000030070, 0x8}}, {0x0, 0x0}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:379 +0xa8 fp=0xc0003dfd28 sp=0xc0003df9a0 pc=0x84fda8
github.com/godror/godror.(*drv).createConnFromParams(_, {_, _}, {{{0xc000030048, 0x5}, {0xc000350100, 0x7d}, {{0xc000030070, 0x8}}, {0x0, ...}, ...}, ...})
        /go/xproxy/vendor/github.com/godror/godror/drv.go:604 +0x27b fp=0xc0003e01f8 sp=0xc0003dfd28 pc=0x85241b
github.com/godror/godror.connector.Connect({0xf0c9c0, {{{0xc000030048, 0x5}, {0xc000350100, 0x7d}, {{...}}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}}, ...)
        /go/xproxy/vendor/github.com/godror/godror/drv.go:1125 +0x7ea fp=0xc0003e09f0 sp=0xc0003e01f8 pc=0x85648a
github.com/godror/godror.(*connector).Connect(0xc0002b8180?, {0xb80a58?, 0xc0002b8180?})

**Comment by tgulacsi** [comment]
It seems to connect to a lot of different databases (host and sid differs).

And the goroutine count is not low.

So, what is your program doing?
When do you close your DB? And all the opened resources?

**Comment by chilingpan123** [comment]
@tgulacsi The program is check DB access and get active/total session for all ebay oracle DB. So it makes a connection to one DB, run a SQL query, close the connection. Then go to another one.
The check is done every 1 minute.

**Comment by tgulacsi** [comment]
So, sth like
```
grp, grpCtx := errgroup.WithContext(ctx)
grp.SetLimit(16)
for _, connString := range connStrings {
grp.Go(func() error {
db, err := sql.Open("godror", connString)
if err != nil { return err }
defer db.Close()
rows, err := db.QueryContext(grpCtx, qry)
if err != nil { return err }
defer rows.Close()
for rows.Next() {
...
}
return rows.Err()
})
}
return grp.Wait()
```

?

(The main points is: close everything with defer, ASAP.


Or, do you keep the connection pools around?

That may work, if you severly limit the number of connection pools and their TCP connections,
by using `db.SetMaxOpenConns(1); db.SetMaxIdleConns(1); db.SetConnMaxLifetime(5*time.Minute)`,
and reusing the DB pools from a `map[string]*sql.DB`.

**Comment by tgulacsi** [comment]
TestOpenCloseDB in z_test.go seems to test the same scenario, and I cannot make it fail.

Maybe the other way (cache the connection pools in a map and reuse instead of create/close) may help.

**Comment by chilingpan123** [comment]
We don't want to cache connection since test connection is one of the monitoring goal. 
The program do 2 things every 1 minute:
1. test connection to DB works
2. when connection is OK, get active/inactive session

**Comment by chilingpan123** [comment]
Could you run TestOpenCloseDB in z_test.go in kubenetes docker as non-root user?
In our scenario, it works when run as root user in one cluster.
But due to security requirement, it failed to run as non-root user in a new cluster.

**Comment by tgulacsi** [comment]
648b3cd `contrib/container/docker-test.sh -test.run=OpenCloseDB`

runs the test in a container, as non-root user, and just works.
(The container is started as root - if you have some specific needs, please provide details!)
