### ISSUE TITLE
Prepared statement is closed on a generic error (table missing, for example)

### ISSUE THREAD

**Issue by minollo** [godror/godror#281]
A prepared statement is getting closed in ExecContext() (closeIfBadConn) when any generic error during its execution happens - for example, a "table missing" error; that prevents to re-execute the statement after the problem may have been corrected.
The "closeIfBadConn", as the name suggests, seems it should limit itself to close the statement only when the error in question may be a bad connection error.

To reproduce:

1. Create a prepared statement "SELECT * FROM newTable WHERE key = :1" - where "newTable" doesn't exist yet
2. Execute the statement; an error will be correctly reported
3. Create the missing "newTable"
4. Re-execute the same prepared statement; an error about "1 parameter specified, 0 expected" is reported

I would expect that step 4) succeeds. It does if I change the definition of "closeIfBadConn" into:
	closeIfBadConn := func(err error) error {
		closeDone()
		if err == nil {
			return nil
		}
		c := st.conn
		// wipe out st only if error may indeed be a bad connection error
		badConnErr := maybeBadConn(err, c)
		if badConnErr == driver.ErrBadConn {
			_ = st.closeNotLocking()
		}
		return badConnErr
	}

**Comment by tgulacsi** [comment]
PTAL 64ae0e7 (current main)
