### ISSUE TITLE
A numeric query result should be returned as a number. ,not as a string, when I pass an interface{}

### ISSUE THREAD

**Issue by minollo** [godror/godror#282]
I have a function which executes generic SQL queries, whose result may contain any database data type.
I use an array of interface{} objects to get the result back from rows.Scan(), and I expect to get back a set of strings, numbers and what else based on the data types returned by the query.
Other go drivers I use behave as expected here, but godror returns me string objects (well, godror.Number objects under the cover), which is not what I would expect - especially when not setting NumberAsString as true.

Is that the intended behavior? It seems somewhat limiting.
Let me know if you need any further details.

**Comment by tgulacsi** [comment]
What kind of number would you prefer?
Int, int64, float64?
Neither can represent precisely the 38 digits an Oracle NUMBER can.

**Comment by minollo** [comment]
float64 is likely the closest to cover the vast majority of usecases - isn't it?
If a user needs to deal with anything which cannot be represented with float64, they can just switch to NumberAsString...

**Comment by minollo** [comment]
Let me ask this - as a possible alternative: is there a way for me on the application side to detect that Scan() has returned a godror.Number and convert it myself - whenever possible?

**Comment by minollo** [comment]
To answer my own question, yes, I can trap the grodor.Number at scan time and convert it; I can live with that.

**Comment by tgulacsi** [comment]
We may introduce a NumberAsDouble option, but that's a very special case, as only 15 digits of int can be represented with that (int64: 19, Oracle NUMBER: 38).

The sql.Rows.ColumnTypes() returns []*sql.ColumnType, and it's DecimalSize() can be used to determine a fitting destination number type - if the query (DB) provides such information (a direct column SELECT will, a calculation won't).

godror.Number also implements https://golang.org/issue/30870 interface, which has a Decompose method, which allows you to use a big number type you wish.

**Comment by minollo** [comment]
>We may introduce a NumberAsDouble option
That would definitely be useful to cover the vast majority of usecases.

**Comment by tgulacsi** [comment]
PTAL 03dcd60

**Comment by minollo** [comment]
Nice!
