### ISSUE TITLE
Provide option to return string data types as nil when null in database

### ISSUE THREAD

**Issue by minollo** [godror/godror#283]
I'm sure this is a highly controversial topic which has already been discussed tons of times...
But it would be very useful (in my case necessary) to be able to distinguish from the application whether a character value returned by a query is an empty string or null. I do understand that returning nil makes Scan fail to assign the value to a go string; but it works as intended if you assign it to interface{} or []byte.
A "NullStringAsNil" option would be great to deal with this...

**Comment by tgulacsi** [comment]
Oracle does not distinguish NULL and empty string, so neither can you.

**Comment by minollo** [comment]
You are right, returning empty string or nil is semantically the same concept; but asking the driver to return nil rather than an empty string makes the application able to deal with the same code across different supported databases - where some of those other databases do support that distinction. But, yes, this can be dealt with at the application level as well.

**Comment by tgulacsi** [comment]
By returning empty string you acoid the need of using sql.NullString.
