### ISSUE TITLE
cannot access temporary LOB data

### ISSUE THREAD

**Issue by alishKK** [godror/godror#286]
**Here is code in go:**
resB := godror.Lob{IsClob: true}

stmt, err := db.Connection.PrepareContext(ctx, "call Z_077_PKGBONUSSTMT.pAccStatementXML(:1, :2, :3, :4)")
if err != nil {
return nil, err
}

_, err = stmt.ExecContext(ctx, "01-03-2023", "12-04-2023", "KZ108569202107703429", sql.Out{Dest: &resB})
if err != nil {
return nil, err
}

**Procedure in DB:**
procedure pAccStatementXML(pFromDate in date, pToDate in date, pAccCode in varchar2, pResult out clob);

**Error output**
readBytes: ORA-65502: cannot access temporary LOB data

**Versions:**
Oracle: 12.2.0.1.0
Godror: github.com/godror/godror v0.37.0
Go: go 1.19
GCC: gcc-10.3.0-2

**Machine:**
 - OS: Windows 10 Pro
 - Architecture: x64
 - Version: 21H1

**Comment by tgulacsi** [comment]
https://docs.oracle.com/en/database/oracle/oracle-database/21/adlob/temporary-LOBs-created-by-SQL-and-PLSQL-builtin-functions.html#GUID-46F77A28-E24F-486C-A556-652E671DA513
"The temporary LOB goes out of scope at the end of the program block at which time, the LOB is freed. "

So read all data you need - use a string, not a godror.Lob.

**Comment by tgulacsi** [comment]
Or to keep the stmt alive, do it on a transaction (*sql.Tx).
