### ISSUE TITLE
Error undefined orahlp.go

### ISSUE THREAD

**Issue by thaipd** [godror/godror#293]
I have error with connect DB Oracle 12c. Please support me fix this issuse
# github.com/godror/godror
C:\Users\thaipd\go\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:531:19: undefined: VersionInfo
C:\Users\thaipd\go\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:532:19: undefined: VersionInfo
C:\Users\thaipd\go\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:533:10: undefined: StartupMode
C:\Users\thaipd\go\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:534:11: undefined: ShutdownMode
C:\Users\thaipd\go\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:536:31: undefined: Event
C:\Users\thaipd\go\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:536:42: undefined: SubscriptionOption
C:\Users\thaipd\go\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:536:64: undefined: Subscription
C:\Users\thaipd\go\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:537:31: undefined: ObjectType
C:\Users\thaipd\go\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:538:59: undefined: Data
C:\Users\thaipd\go\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:539:28: undefined: DirectLob

**Comment by tgulacsi** [comment]
cgo and a working C compiler is required.

**Comment by Splashmou** [comment]
135

**Comment by zsy619** [comment]
如何解决？

**Comment by tgulacsi** [comment]
Install a C compiler (MinGW for Windows, clang for MacOS, GCC or clang for Linux).
