### ISSUE TITLE
how can I set a log level to enable the logs provided by godror, are their any additional logs that can be enabled

### ISSUE THREAD

**Issue by aashakabra** [godror/godror#298]
Hello,

I am using godror to connect to Oracle DB from my go code. I want to enable the logs so that I can get the detailed logs provided by godror.

I can see a log.go but no test file on how I can set the log level or enable the logs. I also took a look at logging.html but I am not able to understand the exact logging step that I need to add in my code to enable the logs .

Additionally, I wanted to get confirmation on one more information. I am trying to connect to Oracle RAC using the cluster ip. I wanted to know if their is any decision made at the godror level as if to connect to the available node (Scan VIP) or all godror does is will use the cluster ip only to connect to Oracle RAC?

Thanks in advance.

**Comment by tgulacsi** [comment]
Use `godror.SetLog` or `godror.SetLogger`.

**Comment by aashakabra** [comment]
Hello @tgulacsi , can you give the sample code on how I can use this in my code. I am already importing https://github.com/godror/godror but I am not getting these methods in suggestions.

Thanks in advance
