### ISSUE TITLE
Make `drv.go: drv` struct exported

### ISSUE THREAD

**Issue by Antonboom** [godror/godror#3]
Hello, thank u for lib!

We want to use [APM](https://github.com/elastic/apm-agent-go/) for receiving SQL execution spans and faced the following problems.

1) APM registers the driver of a specific library and wraps it in its "tracing driver". 
https://github.com/elastic/apm-agent-go/blob/master/module/apmsql/mysql/init.go
https://github.com/elastic/apm-agent-go/blob/master/module/apmsql/pq/init.go
https://github.com/elastic/apm-agent-go/blob/master/module/apmsql/mysql/init.go
But godror's driver is not exported :(

2) With each new connection, we need to do some work, so we use
```go
conn, _ := goracle.NewConnector(...)
db := sql.OpenDB(conn)
```
We could wrap the driver in a "tracer driver", but there is no way to change the driver for the connection:
```go
conn, _ := goracle.NewConnector(...)
wrappedDrv := apmsql.Wrap(drvConnector.Driver())
conn.d = wrappedDrv // Invalid
db := sql.OpenDB(conn)
```

Do u have any ideas? Thanks!

**Comment by tgulacsi** [comment]
Not nice, but works:
```
db := sql.OpenDB(connector)
apmsql.Register("godror", db.Driver())
db.Close()

apmsql.Open("godror", "tiger/scott")
```

You cannot use Wrap if you not directly use a Driver.

I'll see, maybe I can add a DefaultDriver() func to return the default *drv.

**Comment by tgulacsi** [comment]
Hmm... maybe I'm wrong.

That works only if you use sql.Open. That's what apmsql is about, too.

But we don't need a DefaultDriver() func, as the Connector has a Driver() method.
apmsql should have a WrapConnectior function:
```
func WrapConnector(c driver.Connector, opts ...apmsql.WrapOption) driver.Connector {
  return wrappedConnector{up:c, driver: apmsql.Wrap(c.Driver(), opts...)}
}
var _ = driver.Connector(wrappedConnector{})
type wrappedConnector struct {
  up driver.Connector
  driver driver.Driver
}
func (c wrappedConnector) Driver() driver.Driver { return c.driver }
func (c wrappedConnector) Connect(ctx context.Context) (driver.Conn, error) {
  return c.up.Connect(ctx)
}
```

though I'm not sure whether this works or not - it implements what you suggested in your last paragraph, but I'm not sure how is the Connector's Driver is  used.

**Comment by kepkin** [comment]
> apmsql should have a WrapConnectior function:
I thought about that too, but other drivers work through driver, so it would be nice to comply with them

**Comment by tgulacsi** [comment]
As I see, apmsql DOES use driver.DiverContext if driver implements it (*godror.drv does).
The problem is that I cannot see a way to inject onInit function int that connector - even if I add a SetOnInit method to the connector, apmsql hides it.

**Comment by tgulacsi** [comment]
A simple but little bit awkward solution - supposed that you only want to prepare the new connection with SQL statements - is to allow initialization statements url-encoded in the connection string.

This would be compatible both with sql.Open and sql.OpenDB.

Shall I implement it?

**Comment by Antonboom** [comment]
Our `onInit` func has ~150 lines of code :)

What is the problem of making the `drv` exportable,
as well as forwarding the driver as argument in `NewConnector`
(so that you can get rid of `defaultDrv`)? 

If we'll have `Drv`.

1) Easy to do
```golang
apmsql.Register("mysql", &godror.Drv{}, apmsql.WithDSNParser(ParseDSN))
```

2) And if it's not enough, we also can do
```golang
drv := apmql.Wrap(&godror.Drv{})
connector, _ := goracle.NewConnectorFromDriver(dsn, drv, func(...) error { ... })
```

Or I don’t see something?

**Comment by tgulacsi** [comment]
I don't see how will you add your onInit.

I can add a DefaultDriver() which you can use to apmsql.Register, but no, I don't want to add a NewConnectorFromDriver.

**Comment by Antonboom** [comment]
There is no point in the `DefaultDriver()`, since ampsql register new wrapped driver, but `goracle.NewConnector` will still use not wrapped `defaultDrv`.

We need a driver setter, not a getter :(

**Comment by Antonboom** [comment]
Just now I understand your option with `onInit` in the DSN line.

Indeed, without `NewConnectorFromDriver` you will have to make the `connector` exportable as well :(

```golang
d := &godror.Drv{}
wrapped := apmsql.Wrap(d)  // d lost `NewConnector()` :(

w, ok := wrapped.(driver.DriverContext)
if !ok {
    ...
}

cxr, err := w.OpenConnector(dsn)
if err != nil {
	panic(err)
}
cx := cxr.(connector) // Not exported
cx.onInit = onInit    // Invalid
```

**Comment by tgulacsi** [comment]
So, can I de-export Drv ?

Still you can include the statements in the DSN!

**Comment by Antonboom** [comment]
I'm sorry

We don't found the time to come up with an elegant solution for the library as a whole.
Locally we made a wrapper over your `driver.Connector` and this solved our problems.

**Comment by tgulacsi** [comment]
Try https://githu.com/ngrok/sqlmw to intercept the calls and do anything with them.

**Comment by alc-siteimprove** [comment]
@tgulacsi Did the change to export `drv` got reverted? It's not part of master. It looks like sqlmw would require `drv` to be exported as well.

**Comment by tgulacsi** [comment]
Yes, it got reverted as it did not solve the OP's issue, and you don't need godror.Drv to be exported:
```
db, err := sql.Open("godror", "connstr")
if err != nil {panic(err)}
sql.Register("godror-mw", sqlmw.Driver(db.Driver(), interceptor))
db.Close()
...
