### ISSUE TITLE
I prefer to transfer the result parameter and namesVals parameter of IN/OUT to the stored procedure more conveniently

### ISSUE THREAD

**Issue by nilin8** [godror/godror#300]
Hello godror developers, I have a good suggestion

I prefer to transfer the result parameter and namesVals parameter of IN/OUT to the stored procedure more conveniently
Corresponding to the input parameter type of IN or IN/OUT, especially the database we customize in the oracle database, the value passed in should be very simple. Either conforms to the JSON format, or conforms to the dictionary format, such as a Map or []Map format. For example, node-oracledb used in Nodejs, for their custom type, it is very simple to pass it into the stored procedure, as long as it is a type that conforms to the custom format.
However, if godror wants to import objects of custom types into the oracle database, it is very troublesome, and different enumerations need to be defined to implement different interfaces. Wouldn't it be more flexible to pass in JSON or Map or []Map data directly.

have a nice every day

create or replace package types is
subtype num38 is number(38);
subtype str16 is varchar2(16);
subtype str32 is varchar2(32);
subtype str64 is varchar2(64);
subtype str128 is varchar2(128);
subtype str256 is varchar2(256);
type arr_str256 is table of str256 index by simple_integer;
type nameValRecord is record ("name" str32,"val" str128);
type namesVals is table of nameValRecord index by simple_integer;

type result is record (
  "code" num38,
  "style" str16,
  "lang" str64,
  "params" arr_str256 
);
end types;

procedure test(
  params in out types.namesVals, 
  rst in out types.result
  ) as 
begin
  if params.count <= 0 then
    params(0)."name":='name0';
    params(0)."val":='val0';
  else
    for i in 1..params.count loop
      params(i)."name":='name0' || '--update';
      params(i)."val":='val0' || '--update';
    end loop;
  end if;
  if rst."code" is null then
    rst := types.result();
    rst."code":=100;
    rst."lang":='langkey100';
    rst."style":='fail';
    rst."params":= types.arr_str256();
    rst."params"(0):='langParams1';
    rst."params"(1):='langParams2';
  else
    rst."code":=rst."code"+100;
    rst."lang":=rst."lang" || '---update';
  end if;
end test;

	subObjectType, err := godror.GetObjectType(ctx, conn, param.SubType)
	if err != nil {
		return nil, err
	}
	defer subObjectType.Close()
	if param.SubDataType == 1 {// -------  PL/SQL RECORD
		subObject, err := subObjectType.NewObject()
		if err != nil {
			return nil, err
		}
		subObject.Close()
                var m map[string]interface{} = make(map[string]interface{})
		m["code"]=100
		// .........
		// Is it possible to pass the value directly into the stored procedure in the simplest and most convenient way like this
		subObject.setValue(m)
		val = sql.Named(param.Name, sql.Out{Dest: subObject, In: in})
	} else if param.SubDataType == 2 {// ---------- PL/SQL TABLE
		subCollection, err := subObjectType.NewCollection()
		if err != nil {
			return nil, err
		}
		subCollection.Close()
               var list []map[string]interface{} = make([]map[string]interface{},0)
		var m map[string]interface{}  = make(map[string]interface{})
		m["code"]=100
		// .........
		// Is it possible to pass the value directly into the stored procedure in the simplest and most convenient way like this
		list=append(list, m)
		subCollection.setValue(list)
		val = sql.Named(param.Name, sql.Out{Dest: &subCollection, In: in})
	}

**Comment by tgulacsi** [comment]
You already can, just embed the object's name into a struct that's given to ExecContext - see "oshStruct" in z_plsql_types_test.go and the "Osh" subtest.

**Comment by nilin8** [comment]
Thank you very much for your reply, I have solved it now. Contains the implementation of IN and IN OUT of Record, Object, Table and other types. The following is the demo I implemented

func setRecord(o *godror.Object, p paramInfo, v any) error {
	if p.Dir == 3003 || v == nil {
		return nil
	}
	if m, ok := v.(map[string]interface{}); ok {
		if err := o.ResetAttributes(); err != nil {
			return err
		}
		for n := range o.Attributes {
			val, ok := m[n]
			if !ok {
				if new, ok := m[strings.ToLower(n)]; ok {
					val = new
				} else {
					continue
				}
			}
			var data godror.Data
			if err := o.GetAttribute(&data, n); err != nil {
				return err
			}
			data.Set(val)
			if err := o.SetAttribute(n, &data); err != nil {
				return err
			}
		}
	}

	return nil
}
