### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by hanzhenbjm** [godror/godror#302]
go env
set GOMODCACHE=E:\tool\goalng\gopath\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\tool\goalng\gopath
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=E:\tool\goalng
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=E:\tool\goalng\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.20.2

# github.com/godror/godror
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:531:19: undefined: VersionInfo
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:532:19: undefined: VersionInfo
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:533:10: undefined: StartupMode
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:534:11: undefined: ShutdownMode
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:536:31: undefined: Event
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:536:42: undefined: SubscriptionOption
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:536:64: undefined: Subscription
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:537:31: undefined: ObjectType
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:538:59: undefined: Data
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:539:28: undefined: DirectLob
E:\tool\goalng\gopath\pkg\mod\github.com\godror\godror@v0.37.0\orahlp.go:539:28: too many errors

Compilation finished with exit code 1

Hi Does godror only support go 1.9?

**Comment by tgulacsi** [comment]
godror needs CGO, thus a working C compiler.
