### ISSUE TITLE
Trying to connect to OracleRAC using Godror via cloud

### ISSUE THREAD

**Issue by aashakabra** [godror/godror#303]
I am trying to connect to a OracleRAC instance using godror from an application hosted on cloud. 
Since OracleRAC is on another network we use a mechanism where a tunnel is created and the cluster ip that I use during connection is whitelisted.

We have observed that even if we are only using the cluster ip to connect to the db, the response received is from one of the node ips. and this is forcing us to whitelist the node ips as well. If node ips are whitelisted the connection is successful.

Our requirement is that we only want to whitelist cluster ip and not the node ips.

Is there anything handled at godror level explicitly for Oracle RAC db? Is there any way to achieve the requirement?

**Comment by tgulacsi** [comment]
Godror uses vanilla Oracle OCI through ODPI. The network connections are handled by Oracle Instant Client.
