### ISSUE TITLE
Problem at the expslog.go file

### ISSUE THREAD

**Issue by dyogocae** [godror/godror#308]
Bug:
..\..\pkg\mod\github.com\godror\godror@v0.39.0\slog\expslog.go:44:96: too many arguments in call to slog.NewTextHandler
        have (io.Writer, *"golang.org/x/exp/slog".HandlerOptions)
        want (io.Writer)

I Created a repo and I'm trying to connect the database and using the postman to insert a row into a table. I'm using net/http class 

**Your oracle client version**
Oracle Database 23c Free, Release 23.0.0.0.0 - Developer-Release
Version 23.2.0.0.0

**Your godror version**
v0.39.0

**Your go version**
go1.20.2

**Machine (please complete the following information):**
 - OS: Windows
 - Architecture: [x86_64]
 - Version: [10]

**Comment by tgulacsi** [comment]
See #306, try f6948719280ed8e2ea47c44a2e37f292bda85619 (update x/exp/slog)
