### ISSUE TITLE
No longer support for go 1.19 ? 

### ISSUE THREAD

**Issue by sergej-klimenko** [godror/godror#312]
**Describe the bug**
No longer compile on go 1.19 since v0.40.0 because of direct import "log/slog"
in drv.go and rows.go. 
Is that intended change?

**To Reproduce**
go test 

**Error output**
drv.go:85:2: package log/slog is not in GOROOT (/usr/local/Cellar/go/1.19.3/libexec/src/log/slog)

**Your go version**
1.19.3

**Comment by tgulacsi** [comment]
I'm open to support Go 1.19, but my earlier attempts failed (github.com/godror/godror/slog, 
build tags to select between golang.org/x/exp/slog and std lib log/slog : last time I checked, their API differed!).

**Comment by sergej-klimenko** [comment]
Thank you for clarifying, we are planning to upgrade Go version soon anyway.

**Comment by tgulacsi** [comment]
PTAL 284682c  (go get github.com/godror/godror@main) - if it works with both Go 1.19 and 1.2[01], then I'll tag it as v0.40.3.

**Comment by sergej-klimenko** [comment]
Thank you , it works with both 1.19 and 1.21 now

**Comment by tgulacsi** [comment]
Thanks for the test, I've tagged it as v0.40.3.
