### ISSUE TITLE
Can't parse oracle Date into struct's field

### ISSUE THREAD

**Issue by raydent** [godror/godror#314]
**Describe the bug**
When having a column of DATE type in a table, this table cannot be parsed to a struct due to `panic: reflect: reflect.Value.Set using unaddressable value`.

**To Reproduce**
"test_pkg" package in Oracle:

```
type my_test_table is RECORD(
	id INT,
	update_time DATE
);

PROCEDURE getTable(
    x in number,
    res out test_pkg.my_test_table
);

PROCEDURE getTable(
	x in number,
	res out test_pkg.my_test_table
) IS
	BEGIN
	res.id := x;
	res.update_time := TIMESTAMP '2023-10-21 02:21:54'; -- set some constant date here just for function example
	END getTable;
```

Go struct definition:
```go 
type TestTable struct {
	godror.ObjectTypeName `godror:"test_pkg.my_test_table" json:"-"`
	id                    int       `godror:"ID"`
	updateTime            time.Time `godror:"update_time"`
}
```

Go call of getTable procedure:
```go
tt := TestTable{}
_, err = tx.ExecContext(ctx, `CALL 
		test_pkg.getTable(
			:1,
			:2,
		)`,
	1,
	tt,
) // panic is encountered during this call
```
**Expected behavior**
DATE type being parsed into time.Time (*time.Time, sql.NullTime, *sql.NullTime or even string - I tried each of these options)

**Error output**
Stack trace except the private logs:
panic: reflect: reflect.Value.Set using unaddressable value [recovered]
	panic: reflect: reflect.Value.Set using unaddressable value

testing.tRunner.func1.2({0x27a380, 0xc00038e370})
	GOROOT/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	GOROOT/src/testing/testing.go:1548 +0x397
panic({0x27a380?, 0xc00038e370?})
	GOROOT/src/runtime/panic.go:914 +0x21f
reflect.flag.mustBeAssignableSlow(0x9?)
	GOROOT/src/reflect/value.go:272 +0x74
reflect.flag.mustBeAssignable(...)
	GOROOT/src/reflect/value.go:259
reflect.Value.Set({0x3f49c0?, 0xc0003a4318?, 0xc0c5a8?}, {0x3f49c0?, 0x16b8c00?, 0x2895c2?})
	GOROOT/src/reflect/value.go:2254 +0x65
github.com/godror/godror.(*conn).dataGetObjectStructObj(0x1686660?, {0x3f49c0?, 0xc0003a4318?, 0xc000218c48?}, 0x0)
	_main/external/com_github_godror_godror/stmt.go:2893 +0x53b
github.com/godror/godror.(*conn).dataGetObjectStruct(0x2c9080?, 0xc00039c5a0, {0x3f49c0, 0xc0003a4318}, {0xc000218e98, 0x1, 0x24fd3d?})
	_main/external/com_github_godror_godror/stmt.go:3079 +0x4bf
github.com/godror/godror.(*conn).dataGetObjectStructObj(0xc000384580?, {0x3b1680?, 0xc0003960e0?, 0xc0002191e8?}, 0xc00038e360)
	_main/external/com_github_godror_godror/stmt.go:3036 +0x18c9
github.com/godror/godror.(*conn).dataGetObjectStruct(0x1685480?, 0xc00039c240, {0x256ec0, 0xc0003960e0}, {0x32800f0, 0x1, 0xc0002195a0?})
	_main/external/com_github_godror_godror/stmt.go:3079 +0x4bf
github.com/godror/godror.(*statement).bindVarTypeSwitch.func3({0x256ec0?, 0xc0003960e0?}, {0x32800f0?, 0xc000380240?, 0x0?})
	_main/external/com_github_godror_godror/stmt.go:1259 +0x45
github.com/godror/godror.(*statement).ExecContext(0xc0003a2580, {0x5809a8, 0x16b6780}, {0xc00039e1e0?, 0x4, 0x4})
	_main/external/com_github_godror_godror/stmt.go:496 +0x11c3
database/sql.ctxDriverStmtExec({0x5809a8, 0x16b6780}, {0x580d00, 0xc0003a2580}, {0xc00039e1e0?, 0x4, 0x4})
	GOROOT/src/database/sql/ctxutil.go:65 +0xc4
database/sql.resultFromStatement({0x5809a8, 0x16b6780}, {0x57d3e0, 0xc0001d1400}, 0xc0002199d8, {0xc0003841c0, 0x4, 0x4})
	GOROOT/src/database/sql/sql.go:2642 +0x13a
database/sql.(*DB).execDC(0xc00029c820?, {0x5809a8, 0x16b6780}, 0xc00039c000, 0x27a380?, {0xc0003c0000, 0x97}, {0xc0003841c0, 0x4, 0x4})
	GOROOT/src/database/sql/sql.go:1694 +0x45f
database/sql.(*Tx).ExecContext(0xc0003a8000, {0x5809a8, 0x16b6780}, {0xc0003c0000, 0x97}, {0xc0003841c0, 0x4, 0x4})
	GOROOT/src/database/sql/sql.go:2478 +0xad

**Your oracle client version**
19.0.0.0.0

**Your godror version**
e.g. v0.36.0

**Your go version**
e.g. 1.21.1

**Your gcc version**
e.g. 13.0.1

**Machine (please complete the following information):**
 - OS: win
 - Architecture:  x86_64
 - Version: 10

**Additional context**

**Comment by raydent** [comment]
Also, I have a question: is it possible to parse table%rowtype, to avoid creation and conversion to additional type like my_test_table? I apologize if this question is not very bright, was not able to do so during tinkering and didn't find any examples.

**Comment by tgulacsi** [comment]
For table%rowtype, the easiest is to create a type alias:
TYPE my_table table%ROWTYPE;

As Oracle looks up the %TYPE, %ROWTYPE sugar at compile time, the compiled program DOES NOT contain such type, only the resulting record/type. (That's why you have to recompile your package after an ALTER touching that table).

**Comment by bikain** [comment]
@raydent, did you fix the date type field?
I have the same problem:
Type oracle:
```
create or replace type typeDate as object(
  id number,
  date_update date
);
```
GO code:
```
func testDate(db *sql.DB) {
	var dateI, dateO Date
	var result time.Time

	dateI.Id = 1
	dateI.DateUpdate = time.Now()

	// ITS WORK
	_, err := db.Exec(`
	declare
		v_date typeDate;
	begin
		v_date := :dateI;
		:result := v_date.date_update;
	end;
	`, sql.Named("dateI", dateI),
		sql.Named("result", sql.Out{In: false, Dest: &result}),
	)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("result:", result)

	// ITS NOT WORK
	_, err = db.Exec(`
	declare
		v_date typeDate := typeDate(null, null);
	begin
		v_date.id := 1;
		v_date.date_update := sysdate;
		:dateO := v_date;
	end;
	`, sql.Named("dateO", sql.Out{In: false, Dest: &dateO}),
	)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("dateO:", dateO)
}
```
If i use simple variable type = time.Time, all work. 
But if i use Struct with type field = time.Time, error:
Exception 0xc0000005 0x0 0xffffffffffffffff 0x7ff6961468d8
PC=0x7ff6961468d8
signal arrived during external code execution

runtime.cgocall(0x7ff696134e70, 0xc00006c8c0)
        C:/Program Files/Go/src/runtime/cgocall.go:158 +0x4a fp=0xc00006c898 sp=0xc00006c860 pc=0x7ff695eb4daa
github.com/godror/godror._Cfunc_dpiObject_addRef(0x23350e190a07e7)
        _cgo_gotypes.go:4304 +0x56 fp=0xc00006c8c0 sp=0xc00006c898 pc=0x7ff6960cbc96
github.com/godror/godror.(*Data).GetObject.func1.1(0x7ff695eb4e47?)
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/data.go:232 +0x3a fp=0xc00006c8f8 sp=0xc00006c8c0 pc=0x7ff6960daf7a
github.com/godror/godror.(*Data).GetObject.func1()
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/data.go:232 +0x1d fp=0xc00006c910 sp=0xc00006c8f8 pc=0x7ff6960daf1d
github.com/godror/godror.(*drv).checkExecNoLOT(0x7ff6960c9917?, 0x7ff696134cd0?)
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/drv.go:257 +0x22 fp=0xc00006c930 sp=0xc00006c910 pc=0x7ff6960de322
github.com/godror/godror.(*drv).checkExec(0xc000116688?, 0x23350e190a07e7?)
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/drv.go:251 +0x34 fp=0xc00006c960 sp=0xc00006c930 pc=0x7ff6960de274
github.com/godror/godror.(*Data).GetObject(0xc000116680)
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/data.go:231 +0xb2 fp=0xc00006c9a0 sp=0xc00006c960 pc=0x7ff6960dae32
github.com/godror/godror.(*conn).dataGetObjectStruct(0x7ff6961d2e40?, 0xc000074630, {0x7ff696213a80, 0xc000008300}, {0xc00006ccc0, 0x1, 0x7ff6961ac7cc?})
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/stmt.go:3092 +0x50c fp=0xc00006cb60 sp=0xc00006c9a0 pc=0x7ff696120f6c
github.com/godror/godror.(*conn).dataGetObjectStructObj(0xc0001165c0?, {0x7ff6961eca00?, 0xc0000245a0?, 0xc00006d110?}, 0xc0000408c0)
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/stmt.go:3049 +0x1817 fp=0xc00006d0d8 sp=0xc00006cb60 pc=0x7ff6961207f7
github.com/godror/godror.(*conn).dataGetObjectStruct(0x7ff69643fe40?, 0xc000074510, {0x7ff6961b7060, 0xc0000245a0}, {0x21eb3c417b0, 0x1, 0xc00006d530?})
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/stmt.go:3093 +0x530 fp=0xc00006d298 sp=0xc00006d0d8 pc=0x7ff696120f90
github.com/godror/godror.(*statement).bindVarTypeSwitch.func3({0x7ff6961b7060?, 0xc0000245a0?}, {0x21eb3c417b0?, 0x1?, 0x0?})
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/stmt.go:1270 +0x49 fp=0xc00006d2e0 sp=0xc00006d298 pc=0x7ff69610e949
github.com/godror/godror.(*statement).ExecContext(0xc000114840, {0x7ff6962884e8, 0xc000016050}, {0xc000064d50?, 0x1, 0x1})
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/stmt.go:503 +0x11c4 fp=0xc00006d930 sp=0xc00006d2e0 pc=0x7ff6961051c4
database/sql.ctxDriverStmtExec({0x7ff6962884e8, 0xc000016050}, {0x7ff6962885c8, 0xc000114840}, {0xc000064d50?, 0x1, 0x1})
        C:/Program Files/Go/src/database/sql/ctxutil.go:65 +0xcc fp=0xc00006d9b0 sp=0xc00006d930 pc=0x7ff695fa4e6c
database/sql.resultFromStatement({0x7ff6962884e8, 0xc000016050}, {0x7ff6962880d0, 0xc000110a00}, 0xc00006db58, {0xc00006ddd8, 0x1, 0x1})
        C:/Program Files/Go/src/database/sql/sql.go:2663 +0x145 fp=0xc00006da60 sp=0xc00006d9b0 pc=0x7ff695fb0aa5
database/sql.(*DB).execDC(0x21eb3bc1201?, {0x7ff6962884e8, 0xc000016050}, 0xc000074240, 0xc00006dc88?, {0x7ff69622b31b, 0x8a}, {0xc00006ddd8, 0x1, 0x1})
        C:/Program Files/Go/src/database/sql/sql.go:1698 +0x473 fp=0xc00006dc70 sp=0xc00006da60 pc=0x7ff695fabe53
database/sql.(*DB).exec(0x21eb3b69af8?, {0x7ff6962884e8, 0xc000016050}, {0x7ff69622b31b, 0x8a}, {0xc00006ddd8, 0x1, 0x1}, 0x60?)
        C:/Program Files/Go/src/database/sql/sql.go:1659 +0xe8 fp=0xc00006dce8 sp=0xc00006dc70 pc=0x7ff695fab968
database/sql.(*DB).ExecContext(0x7ff6961ea480?, {0x7ff6962884e8, 0xc000016050}, {0x7ff69622b31b, 0x8a}, {0xc00006ddd8, 0x1, 0x1})
        C:/Program Files/Go/src/database/sql/sql.go:1633 +0xe5 fp=0xc00006dd70 sp=0xc00006dce8 pc=0x7ff695fab6a5
database/sql.(*DB).Exec(...)
        C:/Program Files/Go/src/database/sql/sql.go:1651
main.testDate(0x7ff696219556?)
        C:/Temp_folder/golang/OracleNew/oracle.go:368 +0x3a5 fp=0xc00006def8 sp=0xc00006dd70 pc=0x7ff696134465
main.main()
        C:/Temp_folder/golang/OracleNew/oracle.go:394 +0xdf fp=0xc00006df80 sp=0xc00006def8 pc=0x7ff69613465f
runtime.main()
        C:/Program Files/Go/src/runtime/proc.go:250 +0x1fe fp=0xc00006dfe0 sp=0xc00006df80 pc=0x7ff695eec0fe
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00006dfe8 sp=0xc00006dfe0 pc=0x7ff695f16d01

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0xc000037fb0 sp=0xc000037f90 pc=0x7ff695eec496
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.forcegchelper()
        C:/Program Files/Go/src/runtime/proc.go:302 +0xb1 fp=0xc000037fe0 sp=0xc000037fb0 pc=0x7ff695eec331
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000037fe8 sp=0xc000037fe0 pc=0x7ff695f16d01
created by runtime.init.6
        C:/Program Files/Go/src/runtime/proc.go:290 +0x25

goroutine 18 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0xc00008ff90 sp=0xc00008ff70 pc=0x7ff695eec496
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.bgsweep(0x0?)
        C:/Program Files/Go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00008ffc8 sp=0xc00008ff90 pc=0x7ff695ed66ce
runtime.gcenable.func1()
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x26 fp=0xc00008ffe0 sp=0xc00008ffc8 pc=0x7ff695ecb266
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00008ffe8 sp=0xc00008ffe0 pc=0x7ff695f16d01
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:178 +0x6b

goroutine 19 [GC scavenge wait]:
runtime.gopark(0xc000086000?, 0x7ff696285920?, 0x1?, 0x0?, 0x0?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0xc000091f70 sp=0xc000091f50 pc=0x7ff695eec496
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.(*scavengerState).park(0x7ff69643ffe0)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:389 +0x53 fp=0xc000091fa0 sp=0xc000091f70 pc=0x7ff695ed4753
runtime.bgscavenge(0x0?)
        C:/Program Files/Go/src/runtime/mgcscavenge.go:617 +0x45 fp=0xc000091fc8 sp=0xc000091fa0 pc=0x7ff695ed4d45
runtime.gcenable.func2()
        C:/Program Files/Go/src/runtime/mgc.go:179 +0x26 fp=0xc000091fe0 sp=0xc000091fc8 pc=0x7ff695ecb206
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000091fe8 sp=0xc000091fe0 pc=0x7ff695f16d01
created by runtime.gcenable
        C:/Program Files/Go/src/runtime/mgc.go:179 +0xaa

goroutine 3 [finalizer wait]:
runtime.gopark(0x7ff6964403e0?, 0xc000034b60?, 0x0?, 0x0?, 0xc00003bf70?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0xc00003be28 sp=0xc00003be08 pc=0x7ff695eec496
runtime.goparkunlock(...)
        C:/Program Files/Go/src/runtime/proc.go:369
runtime.runfinq()
        C:/Program Files/Go/src/runtime/mfinal.go:180 +0x10f fp=0xc00003bfe0 sp=0xc00003be28 pc=0x7ff695eca36f
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00003bfe8 sp=0xc00003bfe0 pc=0x7ff695f16d01
created by runtime.createfing
        C:/Program Files/Go/src/runtime/mfinal.go:157 +0x45

goroutine 4 [select]:
runtime.gopark(0xc000039f88?, 0x2?, 0x11?, 0x0?, 0xc000039f84?)
        C:/Program Files/Go/src/runtime/proc.go:363 +0xd6 fp=0xc000039e10 sp=0xc000039df0 pc=0x7ff695eec496
runtime.selectgo(0xc000039f88, 0xc000039f80, 0x0?, 0x0, 0x0?, 0x1)
        C:/Program Files/Go/src/runtime/select.go:328 +0x7dc fp=0xc000039f50 sp=0xc000039e10 pc=0x7ff695efa83c
database/sql.(*DB).connectionOpener(0xc000020680, {0x7ff6962884b0, 0xc000116340})
        C:/Program Files/Go/src/database/sql/sql.go:1224 +0x8d fp=0xc000039fb8 sp=0xc000039f50 pc=0x7ff695fa92ad
database/sql.OpenDB.func1()
        C:/Program Files/Go/src/database/sql/sql.go:792 +0x2e fp=0xc000039fe0 sp=0xc000039fb8 pc=0x7ff695fa768e
runtime.goexit()
        C:/Program Files/Go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc000039fe8 sp=0xc000039fe0 pc=0x7ff695f16d01
created by database/sql.OpenDB
        C:/Program Files/Go/src/database/sql/sql.go:792 +0x18d

**Comment by tgulacsi** [comment]
PTAL https://github.com/godror/godror/issues/314#ref-commit-c1c9c84 and try. @main"

**Comment by raydent** [comment]
Tested last version, was able to parse time to struct and use rowtype, thank you very much!
However, I have a question: can you add support for sql.Null* types, please? And if you can, should I create a separate issue?
Problem description: when I change type of id in my example to sql.NullInt32, I get ```code panic: reflect: call of reflect.Value.SetInt on struct Value ```, if I change it to *int32, I get ```code panic: reflect: call of reflect.Value.SetInt on struct Value```. Stack traces are attached to this comment.
[struct_panic.txt](https://github.com/godror/godror/files/13177256/struct_panic.txt)
[ptr_panic.txt](https://github.com/godror/godror/files/13177257/ptr_panic.txt)

**Comment by tgulacsi** [comment]
PTAL 4d26b7f
