### ISSUE TITLE
sql.NullString testing support

### ISSUE THREAD

**Issue by freeNestor** [godror/godror#315]
Sorry to bother you again.
Our DBA complains recently that our merge sql in app causes too many child cursors, and the library cache memory is under pressure. We diagnosed the reason shows 'bind mismatch(19)', this issue on internet is little information. We suspect it's due to bind variable has NULL value, as we're using string in app to bind. So we have changed some bind variables from string to sql.NullTime, sql.NullInt64, sql.NullFloat64 etc. this reducing child cursors, seems better. I notice sql.NullString is not supported, I wanna if you could give us a test version support sql.NullString, for testing. I hope this could help. We use godror v0.40.2.
Thanks very much if you could support.

```
<Chi1dNode>
<ChildNumber>107</ChildNumber>
<ID>39</ID>
<reason>Bind mismatch(19)<reason>
<size>4x8</size>
<bind position>0000004700000000 </bind_position>
<original_oacflg>0000000700000000</original_oacflg>
<original_oacfl2>0100001000000000</oiginal_oacfl2>
<new_oacf12>0100000000000000 </new_oacf12></childNode>
```

**Comment by tgulacsi** [comment]
Oracle does not differentiate between the empty string and NULL, they're interchangeable, so sql.NullString has no relevance here.

**Comment by freeNestor** [comment]
We've tested it's different between using empty string and NULL in sql on oracle, it's not as simple as we imagined though the same writing result. Using sql.NullString solved our bind mismatch issue by another driver, but if use empty string with another driver, the same bind mismatch issue(cause many child cursors), so it's related to this.
