### ISSUE TITLE
Don't work EXEC with empty field type of object in variable PL/SQL obect type

### ISSUE THREAD

**Issue by bikain** [godror/godror#317]
**Describe the bug**
If object have empty variable type of other object then don't work **Exec**: `_panic: runtime error: invalid memory address or nil pointer dereference_`

**To Reproduce**
type 1 in oracle:

```
create or replace type typeChild as object(
	id number,
	name varchar2(100)
);
```

type 2 in oracle:
```
create or replace type typeParent as object(
  id number,
  child typeChild
);
```

code in GO:
```
type child struct {
	godror.ObjectTypeName `godror:"gin2.typeChild"`
	Id                    float64 `godror:"ID"`
	Name                  string  `godror:"NAME"`
}

type parent struct {
	godror.ObjectTypeName `godror:"gin2.typeParent"`
	Id                    float64 `godror:"ID"`
	Child                 child   `godror:"CHILD"`
}

func testObject(db *sql.DB) {
	var testChild child
	var testParent parent

	//testChild.Name = " "
	//testChild.Id = 1
	testChild.Id = 0

	//testParent.Child = testChild
	testParent.Id = 2

	_, err := db.Exec(`
	declare
		v_parent typeParent;
	begin
		v_parent := :p;
	end;
	`, sql.Named("p", testParent),
	)
	if err != nil {
		fmt.Println(err)
	}
}
```

**Expected behavior**
Work with empty value of field **CHILD** - without `testParent.Child = testChild`
If use `testChild.Id = 1` - all work. 
If use `testChild.Name = " "` - all work.
If use `testChild.Id = 0` -- not work.

If use `godror.Object` and `WriteObject` - all work:
```
type childTemp struct {
	*godror.Object
	Id   float64
	Name string
}

func (r childTemp) WriteObject() error {
	var data godror.Data
	if r.Id != 0 {
		data.SetFloat64(r.Id)
		err := r.SetAttribute("ID", &data)
		if err != nil {
			return err
		}
	}

	if r.Name != `` {
		data.SetBytes([]byte(r.Name))
		r.SetAttribute("NAME", &data)
	}
	return nil
}

type parentTemp struct {
	*godror.Object
	Id    float64
	Child childTemp
}

func (r parentTemp) WriteObject() error {
	var data godror.Data
	if r.Id != 0 {
		data.SetFloat64(r.Id)
		err := r.SetAttribute("ID", &data)
		if err != nil {
			return err
		}
	}

	if r.Child.Object != nil {
		err := r.Child.WriteObject()
		if err != nil {
			r.Set("CHILD", r.Child.ObjectRef())
		}
	}

	return nil
}

func testWriteObject(db *sql.DB) {

	context := godror.ContextWithTraceTag(context.Background(), godror.TraceTag{Module: "Golang.exe"})
	cx, err := db.Conn(context)
	if err != nil {
		fmt.Println(err)
	}
	defer cx.Close()
	conn, err := godror.DriverConn(context, cx)
	if err != nil {
		fmt.Println(err)
	}

	/*
		objTypeChild, err := conn.GetObjectType("typeChild")
		if err != nil {
			fmt.Println(err)
		}
		objChild, err := objTypeChild.NewObject()
		if err != nil {
			fmt.Println(err)
		}
		defer objChild.Close()
		var testChild childTemp
		//testChild.Name = " "
		//testChild.Id = 1
		//testChild.Id = 0
		testChild.Object = objChild
	*/

	objTypeParent, err := conn.GetObjectType("typeParent")
	if err != nil {
		fmt.Println(err)
	}
	objParent, err := objTypeParent.NewObject()
	if err != nil {
		fmt.Println(err)
	}
	defer objParent.Close()
	var testParent parentTemp
	//testParent.Child = testChild
	testParent.Id = 2
	testParent.Object = objParent

	cx.ExecContext(context, `
	declare
		v_parent typeParent;
	begin
		v_parent := :p;
	end;
	`, sql.Named("p", testParent),
	)
	if err != nil {
		fmt.Println(err)
	}
}
```

**Error output**
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7ff67025afdb]

goroutine 1 [running]:
github.com/godror/godror.(*Data).SetObject(0x7ff670352ee0?, 0xc0000422d0?)
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/data.go:247 +0x1b
github.com/godror/godror.(*conn).dataSetObjectStructObj(0x7ff67036cb60?, 0xc0000421b0, {0x7ff67036cb60?, 0xc0000a6560?, 0xc00000a058?})
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/stmt.go:2791 +0x10fe
github.com/godror/godror.(*conn).dataSetObjectStruct(0xc000044000, 0xc0000421b0, 0x1d175030560, 0x1d175030680, {0x7ff67036cb60?, 0xc0000a6560})
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/stmt.go:2828 +0x365
github.com/godror/godror.(*statement).bindVarTypeSwitch.func2(0xc000044000?, {0x1d175030680?, 0x1?, 0x0?}, {0x7ff67036cb60?, 0xc0000a6560?})
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/stmt.go:1266 +0x45
github.com/godror/godror.(*statement).bindVars(0xc000064160, {0xc00001e0f0?, 0x1, 0x1}, 0x0)
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/stmt.go:906 +0x1bfc
github.com/godror/godror.(*statement).ExecContext(0xc000064160, {0x7ff670408488, 0xc0000ae010}, {0xc00001e0f0?, 0x1, 0x1})
        C:/Users/***/go/pkg/mod/github.com/godror/godror@v0.40.3/stmt.go:443 +0x5aa
database/sql.ctxDriverStmtExec({0x7ff670408488, 0xc0000ae010}, {0x7ff670408568, 0xc000064160}, {0xc00001e0f0?, 0x1, 0x1})
        C:/Program Files/Go/src/database/sql/ctxutil.go:65 +0xcc
database/sql.resultFromStatement({0x7ff670408488, 0xc0000ae010}, {0x7ff670408070, 0xc000044000}, 0xc0000d7c18, {0xc0000d7e98, 0x1, 0x1})
        C:/Program Files/Go/src/database/sql/sql.go:2663 +0x145
database/sql.(*DB).execDC(0x1d16d955301?, {0x7ff670408488, 0xc0000ae010}, 0xc000042120, 0x7ff6700949d5?, {0x7ff6703aaa32, 0x41}, {0xc0000d7e98, 0x1, 0x1})
        C:/Program Files/Go/src/database/sql/sql.go:1698 +0x473
database/sql.(*DB).exec(0x1d16d990bd8?, {0x7ff670408488, 0xc0000ae010}, {0x7ff6703aaa32, 0x41}, {0xc0000d7e98, 0x1, 0x1}, 0x20?)
        C:/Program Files/Go/src/database/sql/sql.go:1659 +0xe8
database/sql.(*DB).ExecContext(0x7ff67036a520?, {0x7ff670408488, 0xc0000ae010}, {0x7ff6703aaa32, 0x41}, {0xc0000d7e98, 0x1, 0x1})
        C:/Program Files/Go/src/database/sql/sql.go:1633 +0xe5
database/sql.(*DB).Exec(...)
        C:/Program Files/Go/src/database/sql/sql.go:1651
main.testObject(0x7ff6703996b6?)
        C:/Temp_folder/golang/OracleNew/oracle.go:216 +0xee
main.main()
        C:/Temp_folder/golang/OracleNew/oracle.go:238 +0xdf
exit status 2

**Your oracle client version**
e.g. 12.2.0

**Your godror version**
e.g. v0.40.3

**Your go version**
e.g. 1.19.4

**Your gcc version**
e.g. 10.3.0

**Machine (please complete the following information):**
 - OS: windows 
 - Architecture: x86_64
 - Version: 10

**Comment by tgulacsi** [comment]
PTAL e774b9b
