### ISSUE TITLE
EXTRA string=time: missing Location in call to Date

### ISSUE THREAD

**Issue by ncduongg** [godror/godror#318]
Hello, I am having an orcal query problem

Error :(  tz := r.conn.Timezone() is null, But that doesn't happen with all requests, it only happens occasionally

func (rs *ResultSet) Next() error {
	return rs.rows.Next(rs.vals) -> error 
}
DATASRC : user="msp" password="msp" connectString="10.36.36.12:1521/orcl" timezone="UTC" :( 

2023-11-01 16:50:17     ERROR   middleware/middleware.go:161    [uH1nGp501q] :  MiddlewareError : %!(EXTRA string=time: missing Location in call to Date)
2023-11-01 16:50:17     ERROR   middleware/middleware.go:167    [uH1nGp501q] :  - /usr/local/go/src/time/time.go:1469 time.Date

2023-11-01 16:50:17     ERROR   middleware/middleware.go:167    [uH1nGp501q] :  - **_**/home/ncduong/go/pkg/mod/github.com/godror/godror@v0.40.3/**_**rows.go:543**_** github.com/godror/godror.(*rows).Next

-> tz is null  ->>> dest[i] = time.Date(int(ts.year), time.Month(ts.month), int(ts.day), int(ts.hour), int(ts.minute), int(ts.second), int(ts.fsecond), tz)

ORCAL : 
SELECT
    dbtimezone
FROM
    dual;
 OUT -> +00:00

SELECT
    systimestamp
FROM
    dual; 
OUT- >> 01-NOV-23 04.53.12.281979000 PM +07:00

**Comment by ncduongg** [comment]
prelim=0 standaloneConnection=0 sysasm=0 sysdba=0 sysoper=0 timezone=localDATE NE #LocalDATE OK = #LocalDATE Ok = #user=msp password=SECRET-*** connectString=10.36.36.12:1521/orcl configDir=
connectionClass= enableEvents=0 externalAuth=0 heterogeneousPool=0 initOnNewConnection=0
libDir= noTimezoneCheck=0 pingInterval=0s poolIncrement=1 poolMaxSessions=1000
poolMinSessions=1 poolSessionMaxLifetime=1h0m0s poolSessionTimeout=5m0s poolWaitTimeout=30s
prelim=0 standaloneConnection=0 sysasm=0 sysdba=0 sysoper=0 timezone=localDATE NE #UTCDATE LOIIIII = #UTCDATE LOIIIII = #user=msp password=SECRET-*** connectString=10.36.36.12:1521/orcl configDir=
connectionClass= enableEvents=0 externalAuth=0 heterogeneousPool=0 initOnNewConnection=0
libDir= noTimezoneCheck=0 pingInterval=0s poolIncrement=1 poolMaxSessions=1000
poolMinSessions=1 poolSessionMaxLifetime=1h0m0s poolSessionTimeout=5m0s poolWaitTimeout=30s

**Comment by tgulacsi** [comment]
If you enable logging in godror (godror.SetLogger), it will print such cases (when the time zone is nil).
After a quick look, I don't see how could this (r.conn.Timezone()) be nil.

Anyway, as your DB time zone (UTC), and DB OS' time zone (+07) differs, you should set the time zone in the connection parameter.
