### ISSUE TITLE
Can't work with Logminer

### ISSUE THREAD

**Issue by peihexian** [godror/godror#32]
**Describe the bug**
The current version can't use logminer technology. After opening the database archive, it failed to read redo log changes with logminer

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	conn, err := sourceOracleDb.Conn(ctx)
	if err != nil {
		logger.Logger.Error("err:" + err.Error())
	}
	defer conn.Close()

	if err := godror.EnableDbmsOutput(ctx, conn); err != nil {
		logger.Logger.Error("err:" + err.Error())
	}
	var minScnNumber int64
	row:= sourceOracleDb.QueryRow("select min(current_scn) CURRENT_SCN from gv$database")
	row.Scan(&minScnNumber)

	startLogminerCommand := `BEGIN DBMS_LOGMNR.START_LOGMNR(STARTSCN => ` + strconv.FormatInt(minScnNumber, 10) + `,OPTIONS =>  DBMS_LOGMNR.SKIP_CORRUPTION+DBMS_LOGMNR.NO_SQL_DELIMITER+DBMS_LOGMNR.NO_ROWID_IN_STMT+DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG + DBMS_LOGMNR.CONTINUOUS_MINE+DBMS_LOGMNR.COMMITTED_DATA_ONLY+dbms_logmnr.STRING_LITERALS_IN_STMT); END;`

	queryScnChangeSQL := "SELECT thread# as threadId, scn,start_scn,commit_scn,timestamp,operation_code,operation,status,SEG_TYPE_NAME,info,seg_owner,table_name,username,sql_redo,row_id,csf,TABLE_SPACE,SESSION_INFO,RS_ID,RBASQN,RBABLK,SEQUENCE#,TX_NAME,SEG_NAME,SEG_TYPE_NAME  FROM v$logmnr_contents WHERE OPERATION_CODE IN (1, 2, 3)"

	_, err = conn.ExecContext(ctx,startLogminerCommand)
	if err != nil {
		logger.Logger.Error("err:" + err.Error())
		os.Exit(-1)
	}

	defer func() {
		conn.ExecContext(ctx, "begin DBMS_LOGMNR.END_LOGMNR; end;")
	}()

	if _, err := conn.ExecContext(ctx, queryScnChangeSQL); err != nil {
		logger.Logger.Error("err:" + err.Error())
	}

	var buf bytes.Buffer
	if err := godror.ReadDbmsOutput(ctx, &buf, conn); err != nil {
		logger.Logger.Error("err:" + err.Error())
	}
	logger.Logger.Error(buf.String())
	if buf.String() != "\n" {
		logger.Logger.Error("err:" + err.Error())
	}

**Comment by cjbj** [comment]
Was there an error?  What versions of client & server were you using?

**Comment by tgulacsi** [comment]
What is the error?
What is the output?

Please check ALL your errors:
if err := sourceOracleDb.QueryRow("select min(current_scn) CURRENT_SCN from gv$database").Scan(&minScnNumber) ...

For queries, use QueryContext, NOT ExecContext! (queryScnChangeSQL).

**Comment by peihexian** [comment]
> What is the error?
> What is the output?
> 
> Please check ALL your errors:
> if err := sourceOracleDb.QueryRow("select min(current_scn) CURRENT_SCN from gv$database").Scan(&minScnNumber) ...
> 
> For queries, use QueryContext, NOT ExecContext! (queryScnChangeSQL).

thanks for the feedback,i modified the code, and now it will be stuck at:
rows, err: = conn.querycontext (ctx, queryscnchangesql)
-----------------------------------------------------------------------------------------
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	conn, err := sourceOracleDb.Conn(ctx)
	if err != nil {
		fmt.Println(err.Error())
	}
	defer conn.Close()

	if err := godror.EnableDbmsOutput(ctx, conn); err != nil {
		fmt.Println(err.Error())
	}

	var minScnNumber int64
	err= conn.QueryRowContext(ctx, "select min(current_scn) CURRENT_SCN from gv$database").Scan(&minScnNumber)
	if nil != err {
		fmt.Println(err.Error())
	}
	fmt.Println("scn start at:" + strconv.FormatInt(minScnNumber, 10))

	startLogminerCommand := `BEGIN DBMS_LOGMNR.START_LOGMNR(STARTSCN => ` + strconv.FormatInt(minScnNumber, 10) + `,OPTIONS =>  DBMS_LOGMNR.SKIP_CORRUPTION+DBMS_LOGMNR.NO_SQL_DELIMITER+DBMS_LOGMNR.NO_ROWID_IN_STMT+DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG + DBMS_LOGMNR.CONTINUOUS_MINE+DBMS_LOGMNR.COMMITTED_DATA_ONLY+dbms_logmnr.STRING_LITERALS_IN_STMT); END;`

	_, err = conn.ExecContext(ctx, startLogminerCommand)
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(-1)
	}

	fmt.Println("logminer started...")

	defer func() {
		conn.ExecContext(ctx, "begin DBMS_LOGMNR.END_LOGMNR; end;")
	}()

	queryScnChangeSQL := "SELECT thread# as threadId, scn,start_scn,commit_scn,timestamp,operation_code,operation,status,SEG_TYPE_NAME,info,seg_owner,table_name,username,sql_redo,row_id,csf,TABLE_SPACE,SESSION_INFO,RS_ID,RBASQN,RBABLK,SEQUENCE#,TX_NAME,SEG_NAME,SEG_TYPE_NAME  FROM v$logmnr_contents WHERE OPERATION_CODE IN (1, 2, 3)"
	rows, err:=conn.QueryContext(ctx, queryScnChangeSQL)
	if err != nil {
		fmt.Println(err.Error())
	}
	for {
		if rows.Next() {
                  fmt.Println("working....")
		}
	}
	rows.Close()


my oracle server is oracle 11.2,client same is oracle 11.2
my godror is 0.13.2 
there is no error number,no hint,no output

**Comment by tgulacsi** [comment]
So "logminer started..." is printed, but does the QueryContext(ctx, queryScnChangeSQL) succeed? (put a fmt.Println("scn", err) right after the call)

Another debug route is to put all this into a PL/SQL anonymous block, and call that.

**Comment by peihexian** [comment]
> So "logminer started..." is printed, but does the QueryContext(ctx, queryScnChangeSQL) succeed? (put a fmt.Println("scn", err) right after the call)
> 
> Another debug route is to put all this into a PL/SQL anonymous block, and call that.

there is no error output，it just won't work in that line

**Comment by tgulacsi** [comment]
If you don't understand what the code does, either debug it, or add println (or log.Println) BEFORE EACH ROW.

Reading your code, it stuck me that you have an infinite loop:
```
queryScnChangeSQL := "SELECT thread# as threadId, scn,start_scn,commit_scn,timestamp,operation_code,operation,status,SEG_TYPE_NAME,info,seg_owner,table_name,username,sql_redo,row_id,csf,TABLE_SPACE,SESSION_INFO,RS_ID,RBASQN,RBABLK,SEQUENCE#,TX_NAME,SEG_NAME,SEG_TYPE_NAME  FROM v$logmnr_contents WHERE OPERATION_CODE IN (1, 2, 3)"
rows, err:=conn.QueryContext(ctx, queryScnChangeSQL)
if err != nil {
	fmt.Println(err.Error())
}
for {
	if rows.Next() {
              fmt.Println("working....")
	}
}
rows.Close()
```

you should have

```
queryScnChangeSQL := "SELECT thread# as threadId, scn,start_scn,commit_scn,timestamp,operation_code,operation,status,SEG_TYPE_NAME,info,seg_owner,table_name,username,sql_redo,row_id,csf,TABLE_SPACE,SESSION_INFO,RS_ID,RBASQN,RBABLK,SEQUENCE#,TX_NAME,SEG_NAME,SEG_TYPE_NAME  FROM v$logmnr_contents WHERE OPERATION_CODE IN (1, 2, 3)"
rows, err:=conn.QueryContext(ctx, queryScnChangeSQL)
if err != nil {
	fmt.Println(err.Error())
}
for rows.Next() {
        fmt.Println("working....")
}
rows.Close()
```

or `break` when `rows.Next()` returns false!
