### ISSUE TITLE
Not able to create a temp lob and send it to a PLSQL procedure. 

### ISSUE THREAD

**Issue by shishir-mathur** [godror/godror#322]
I am trying to write to a lob and then use it in a procedure. I checked out z_lob_test.go which helped me in clearing out the initial issues but am not able to proceed beyond a certain point. The lob object that I get from one plsql call is not being used when I try to send it to another plsql call.

```

		ctx, cancel := context.WithTimeout(context.Background(), 600*time.Second)
    		defer cancel()
		tx, err := conn.BeginTx(ctx, nil)
		if err != nil {
			e.logger.Error("Error starting txn:"+ err.Error())
		}

		    defer tx.Rollback()
		
		fmt.Println(clobInput)
		//defer stmt.Close()
		var clobOutput string
		var status int 

		clobReader := strings.NewReader(clobInput)
		fmt.Println("SHISHIR Reader", clobReader)
		//lob := godror.Lob{Reader: clobReader, IsClob: true}

		var tmp godror.Lob
		tmp.IsClob = true
		
		var length int
		const qry = "DECLARE  BEGIN DBMS_LOB.createtemporary(:2, TRUE); dbms_lob.writeappend(:2, :3,:4); :5:= dbms_lob.getLength(:2); END;"
		stmt, err := conn.Prepare(qry)
		if err != nil {
			e.logger.Error("Error preparing statement:"+ err.Error())
		}

		_, err = stmt.Exec(
			godror.LobAsReader(),
			sql.Out{Dest: &tmp},
			len(clobInput),
			clobInput,
			sql.Out{Dest: &length},
		)
		if err != nil {
			e.logger.Error("Error executing statement:"+ err.Error())
		}
		fmt.Println("SHISHIR Lob len", length)
		
		query :=  "DECLARE status NUMBER; v_inp CLOB ;  BEGIN    :4:=dbms_lob.getLength(:1);  :3 := dbms_lob.substr(:1,2000,1); END;"

		fmt.Println("SHISHIR Lob", tmp)

		// Execute the function with CLOB input
		_, err = conn.Exec(query,
			godror.LobAsReader(),
			sql.Out{Dest: &tmp,In:true},
			sql.Out{Dest: &clobOutput},
			sql.Out{Dest: &status},
		)
		if err != nil {
			e.logger.Error("Error executing statement:"+ err.Error())
		}
		fmt.Println("SHISHIR Status", status)
		fmt.Println("SHISHIR CLOB Output:", clobOutput)
		defer stmt.Close()
```

When supplied with valid clobInput string I get the following error 

```
SHISHIR Lob len 809
SHISHIR Lob {0xc000c16de0 true}
2023-12-08T08:56:46.915Z	error	oracleexporter@v0.0.0/oracle_util.go:211	Error executing statement:ORA-06550: line 1, column 52:
PLS-00382: expression is of wrong type
ORA-06550: line 1, column 47:
PL/SQL: Statement ignored	
```

The tmp lob I am creating is not being transferred to the dbms_lob.getLength() procedure correctly. I am not sure what I am doing wrong here. If I set the v_inp as :1 I get the following error

`Error executing statement:ORA-22922: nonexistent LOB value`

I do not see any easy way to send the tmp lob to the procedure.

**Comment by tgulacsi** [comment]
I see several problems.

The first is that although you create a Tx, you don't use it. You have to call Prepare on the Tx, to bind the Stmt with the Tx - temporary LOBs are not portable between sessions (connections).

The second is that you pass a Reader to your procedure. You have to pass the original LOB, so you must Hijack it to have a DirectLob.

**Comment by shishir-mathur** [comment]
Thank you for the prompt reply. I realized the tx issue and made the changes earlier but that did not help. Let me try the Direct Lob approach. Thanks again!
