### ISSUE TITLE
OCI IAM Token Authentication support in ADB

### ISSUE THREAD

**Issue by shanu-gandhi-oracle** [godror/godror#328]
Hello everyone,

Can you please let me know if godror supports OCI IAM Token based authentication for oracle ADB ?

I am trying to add the configuration for OCI_TOKEN in JDBC String, but godror is not able to connect the db using it. I am adding the reference for the method of Token based authentication.

Ref:- https://docs.oracle.com/en/database/oracle/oracle-database/19/jjdbc/client-side-security.html#GUID-62AD3F23-21B5-49D3-8325-313267444ADD

Please let me know, if it is possible to connect to the ADB using any of the method under OCI IAM Token based auth, mentioned in the above doc.

Thank you

**Comment by tgulacsi** [comment]
What is OCI IAM Token?
Is https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_authentication_methods.htm relevant?

If ODPI-C supports it, then we can, too.

**Comment by sudarshan12s** [comment]
@shanu-gandhi-oracle ,
Can you try providing it in connect string as described [here](https://node-oracledb.readthedocs.io/en/latest/user_guide/connection_handling.html#iam-connection-strings
)

**Comment by tgulacsi** [comment]
What's the error for 
```db, err := sql.Open("godror", `/@(description=(retry_count=10)(retry_delay=3)(address=(protocol=tcps)(port=1521) (host=adb.###.oraclecloud.com)) (connect_data=(service_name=###.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)(TOKEN_AUTH=OCI_TOKEN)(TOKEN_LOCATION='/###/###/token')))`)```
?

You may try with DPI_DEBUG_LEVEL=92 env var.

**Comment by shanu-gandhi-oracle** [comment]
This is the error i am getting while using this
  db, err := sql.Open("godror", `/@(description= (retry_count=10)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.###.oraclecloud.com))(connect_data=(service_name=###.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)(TOKEN_AUTH=OCI_TOKEN)(TOKEN_LOCATION='/###/###/token')))`)


> bash-4.4$ go run godrortoken.go
> warning: GOPATH set to GOROOT (/scratch/go/go_20/go) has no effect
> ODPI [3128347] 2024-03-25 13:51:41.229: ODPI-C 5.2.0
> ODPI [3128347] 2024-03-25 13:51:41.229: debugging messages initialized at level 92
> ODPI [3128347] 2024-03-25 13:51:41.229: fn start dpiContext_createWithParams
> ODPI [3128347] 2024-03-25 13:51:41.229: Context Parameters:
> ODPI [3128347] 2024-03-25 13:51:41.229: Environment Variables:
> ODPI [3128347] 2024-03-25 13:51:41.229:     ORACLE_HOME => "/scratch/shangand/view_storage/shangand_torrv/oracle"
> ODPI [3128347] 2024-03-25 13:51:41.229:     TNS_ADMIN => "/scratch/keys"
> ODPI [3128347] 2024-03-25 13:51:41.229:     LD_LIBRARY_PATH => "/home/shangand/Downloads/instantclient_21_4:/scratch/instaclient/instantclient_21_13:/opt/oracle/instantclient_19_3:/scratch/instaclient/instantclient_21_13/:/scratch/instaclient/:/usr/lib"
> ODPI [3128347] 2024-03-25 13:51:41.229: check module directory
> ODPI [3128347] 2024-03-25 13:51:41.229: module name is /tmp/go-build1173155696/b001/exe/godrortoken
> ODPI [3128347] 2024-03-25 13:51:41.229: load in dir /tmp/go-build1173155696/b001/exe
> ODPI [3128347] 2024-03-25 13:51:41.229: load with name /tmp/go-build1173155696/b001/exe/libclntsh.so
> ODPI [3128347] 2024-03-25 13:51:41.229: load by OS failure: /tmp/go-build1173155696/b001/exe/libclntsh.so: cannot open shared object file: No such file or directory
> ODPI [3128347] 2024-03-25 13:51:41.229: load with OS search heuristics
> ODPI [3128347] 2024-03-25 13:51:41.229: load with name libclntsh.so
> ODPI [3128347] 2024-03-25 13:51:41.233: load by OS successful
> ODPI [3128347] 2024-03-25 13:51:41.233: validating loaded library
> ODPI [3128347] 2024-03-25 13:51:41.245: fn end dpiContext_createWithParams -> 0
> ODPI [3128347] 2024-03-25 13:51:41.245: fn start dpiContext_getClientVersion(0x29f5740)
> ODPI [3128347] 2024-03-25 13:51:41.245: fn end dpiContext_getClientVersion(0x29f5740) -> 0
> ODPI [3128347] 2024-03-25 13:51:41.245: fn start dpiContext_initCommonCreateParams(0x29f5740)
> ODPI [3128347] 2024-03-25 13:51:41.245: fn end dpiContext_initCommonCreateParams(0x29f5740) -> 0
> ODPI [3128347] 2024-03-25 13:51:41.245: fn start dpiContext_initPoolCreateParams(0x29f5740)
> ODPI [3128347] 2024-03-25 13:51:41.245: fn end dpiContext_initPoolCreateParams(0x29f5740) -> 0
> ODPI [3128347] 2024-03-25 13:51:41.245: fn start dpiPool_create(0x29f5740)
> ODPI [3128347] 2024-03-25 13:51:41.257: fn end dpiPool_create(0x29f5740) -> 0
> ODPI [3128347] 2024-03-25 13:51:41.257: fn start dpiPool_setStmtCacheSize(0x29f57d0)
> ODPI [3128347] 2024-03-25 13:51:41.257: fn end dpiPool_setStmtCacheSize(0x29f57d0) -> 0
> ODPI [3128347] 2024-03-25 13:51:41.257: fn start dpiContext_initConnCreateParams(0x29f5740)
> ODPI [3128347] 2024-03-25 13:51:41.257: fn end dpiContext_initConnCreateParams(0x29f5740) -> 0
> ODPI [3128347] 2024-03-25 13:51:41.257: fn start dpiConn_create(0x29f5740)
> ODPI [3128347] 2024-03-25 13:51:41.757: OCI error ORA-01017: invalid username/password; logon denied (dpiConn_create / get session)
> ODPI [3128347] 2024-03-25 13:51:41.757: fn end dpiConn_create(0x29f5740) -> -1
> ODPI [3128347] 2024-03-25 13:51:41.757: fn start dpiPool_getBusyCount(0x29f57d0)
> ODPI [3128347] 2024-03-25 13:51:41.757: fn end dpiPool_getBusyCount(0x29f57d0) -> 0
> ODPI [3128347] 2024-03-25 13:51:41.757: fn start dpiPool_getOpenCount(0x29f57d0)
> ODPI [3128347] 2024-03-25 13:51:41.757: fn end dpiPool_getOpenCount(0x29f57d0) -> 0
> ODPI [3128347] 2024-03-25 13:51:41.757: fn start dpiPool_getMaxLifetimeSession(0x29f57d0)
> ODPI [3128347] 2024-03-25 13:51:41.757: fn end dpiPool_getMaxLifetimeSession(0x29f57d0) -> 0
> ODPI [3128347] 2024-03-25 13:51:41.757: fn start dpiPool_getTimeout(0x29f57d0)
> ODPI [3128347] 2024-03-25 13:51:41.757: fn end dpiPool_getTimeout(0x29f57d0) -> 0
> ODPI [3128347] 2024-03-25 13:51:41.757: fn start dpiPool_getWaitTimeout(0x29f57d0)
> ODPI [3128347] 2024-03-25 13:51:41.757: fn end dpiPool_getWaitTimeout(0x29f57d0) -> 0
> connection fail: %v pool=0x18947d0 stats=busy=0 open=0 max=1000 maxLifetime=1h0m0s timeout=5m0s waitTimeout=30s params={authMode:0 connectionClass:<nil> connectionClassLength:0 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:0 externalHandle:<nil> pool:0x18947d0 tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-01017: invalid username/password; logon denied
> bash-4.4$ 
> bash-4.4$

**Comment by shanu-gandhi-oracle** [comment]
After trying it out for a while, the cause of the error was the use of inverted commas in token_location. While it was mentioned in the docs link of godror and node(https://node-oracledb.readthedocs.io/en/latest/user_guide/connection_handling.html#iam-connection-strings), the same was not running and giving an error in golang. When the inverted commas were removed, it started working. 

Also one of the important issues was the use of an older version of Oracle instant client library. The latest version of Oracle client library and the following alias worked for us.

db, err := sql.Open("godror", "/@(description= (retry_count=10)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=###.###.oraclecloud.com))(connect_data=(service_name=###.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)(TOKEN_AUTH=OCI_TOKEN)(TOKEN_LOCATION=/scratch/##/token)))")
