### ISSUE TITLE
SIGSEGV: segmentation violation when no internet connection or poolMinSessions > 0

### ISSUE THREAD

**Issue by gasperinn** [godror/godror#329]
**Describe the bug**

We have Golang Alpine image with Oracle InstantClient (V21.11), Golang (V1.21.2) and Godror (V0.40.3). If we run the image on docker container with parameter poolMinSessions > 0 (e.g. poolMinSessions=5) in oracle connection string and we do it without internet connection (so the godror can not access db) we get  "SIGSEGV: segmentation violation" error. 

Logs: 
[GodrorError.log](https://github.com/godror/godror/files/14663367/GodrorError.log)

If we have internet connection or we set the parameter poolMinSessions=0 then it works ok. 

**To Reproduce**

```
var db *sql.DB
var isConnected = false
var reconnectInProgress = false

func OpenDBConnection() {

	log.Println("Opening Oracle database connection")

	var err error
	db, err = sql.Open("godror", "user=\"XYZ\" password=\"123\" connectString=\"CONNECTIONSTRING\" poolMinSessions=5 poolIncrement=5 poolMaxSessions=1000")

	if err != nil {
		log.Println(e)
	}

	err = db.Ping()

	if err != nil {

		log.Println(err)
		tryToReconnect()

	} else {

		reconnectInProgress = false
		isConnected = true

		log.Println("Connection established")
	}

}

func CloseDBConnection() {
	db.Close()
	db = nil
}

func tryToReconnect() {

	if !reconnectInProgress {

		reconnectInProgress = true
		isConnected = false

		for !isConnected {

			log.Println("Reconnecting to database")

			CloseDBConnection()

			OpenDBConnection()

			time.Sleep(10 * time.Second)
		}
	}

}
```

**Expected behavior**

It should not throw "SIGSEGV: segmentation violation" regardless the internet connection or parameter poolMinSessions in oracle connection string

**Error output**

[GodrorError.log](https://github.com/godror/godror/files/14663367/GodrorError.log)

**Your oracle client version**
V21.11

**Your godror version**
V0.40.3

**Your go version**
V1.21.2

**Machine (please complete the following information):**
 - OS: linux (golang alpine image)
 - Architecture: x86_64

**Comment by tgulacsi** [comment]
This seems to be an Oracle OCI error - it cannot create the Pool.
You should raise this to Oracle.
