### ISSUE TITLE
switch off godror warnings

### ISSUE THREAD

**Issue by mhechthz** [godror/godror#330]
on connection to a database I get warning 

`godror WARNING: discrepancy between DBTIMEZONE ("+00:00"=0) and SYSTIMESTAMP ("+02:00"=200) - set connection timezone, see https://github.com/godror/godror/blob/master/doc/timezone.md`

how can I switch this off, since I get it on connect before I can correct the timezone of session?

I'm connectiong via `@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST= ...` so I cannot use the timezone specification - the other version from docs gives errors: 
```
db, err := sql.Open("godror", `user="scott" password="tiger"
    connectString="dbhost:1521/orclpdb1?connect_timeout=2"
    poolSessionTimeout=42s configDir="/opt/oracle/configdir"
    heterogeneousPool=false standaloneConnection=false
    timezone="Europe/Berlin"`)
```

`ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA`

**Comment by mhechthz** [comment]
This is the (obfuscated) connection string:

`myuser/mypass@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myhost)(PORT=myport))(CONNECT_DATA=(SID=mysid))) timezone="Europe/Berlin"`

and this is the error message:

`Failed to set session timezone to 'Europe/Berlin',  dpoPool_create user=myuser extAuth=0: ORA-12154: TNS:could not resolve the connect identifier specified`

Doing this works well:
`myuser/mypass@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myhost)(PORT=myport))(CONNECT_DATA=(SID=mysid)))`

**Comment by tgulacsi** [comment]
You cannot mix Oracle and godror connection parameters this way.

Try ```connectString="myuser/mypass@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myhost)(PORT=myport))(CONNECT_DATA=(SID=mysid)))" timezone="Europe/Berlin"```

**Comment by mhechthz** [comment]
Sorry, i'm slightly confused. This is my code:
```
	db, err := sql.Open(driverName, connString)
	if err != nil {
		msg := "GO ERROR: Failed to connect to database, " + err.Error()
		if verbose == 1 {
			fmt.Println(msg)
		}
		return C.CString(msg)
	}
```
where driverName is `"godror"` and connString is 
`"myuser/mypass@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myhost)(PORT=myport))(CONNECT_DATA=(SID=mysid)))"`

Where to add now the timezone in this call `db, err := sql.Open(driverName, connString)`?

**Comment by tgulacsi** [comment]
connString := `user="myuser" password="mypass" connectString="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myhost)(PORT=myport))(CONNECT_DATA=(SID=mysid)))" tmiezone="Europe/Berlin"`

**Comment by mhechthz** [comment]
Ok, works! Thank You very much.

But the question is still open: how to suppress warnings ;-)

**Comment by tgulacsi** [comment]
Add "noTimezoneCheck=1" to the connection params to forcefully turn this check ff.
