### ISSUE TITLE
unregister custom type: ANYDATA. call RegisterType first

### ISSUE THREAD

**Issue by freeman983** [godror/godror#332]
**Describe the bug**
oracle 19c 

select * from all_scheduler_program_args WHERE owner='SYSTEM'  and  program_name='PROGRAM1' ORDER BY argument_position

get error: 

unregister custom type: ANYDATA. call RegisterType first

**To Reproduce**
At least the offending source code;
the best is a minimal test case that reproduces the error.

**Expected behavior**

**Error output**
Copy the error output (panic, stack trace),
or the output of running with `DPI_DEBUG_LEVEL=92`.

**Your oracle client version**
19.8

**Your godror version**
e.g. v0.20.4

**Your go version**
e.g. 1.20.5

**Your gcc version**
e.g. 4.8.3

**Machine (please complete the following information):**
 - OS: mac os
 - Architecture: [e.g. x86_64]
 - Version: [e.g. 10]

**Additional context**

**Comment by tgulacsi** [comment]
ANYDATA type is not supported.
Convert those columns or leave them out
