### ISSUE TITLE
forall with save exceptions

### ISSUE THREAD

**Issue by VadimGossip** [godror/godror#336]
As I know oracle has an option to support saving rows that failed to insert when inserting a batch.
`FORALL index IN bounds_clause [ SAVE EXCEPTIONS ] dml_statement;`

Godror allows to use batch insert but there is no support for save exceptions. 
I found that technically there is such a feature(C.dpiStmt_getBatchErrors) and even built a custom version of the library with it. 
Is such an improvement planned?

**Comment by tgulacsi** [comment]
It is not planned (my use cases are usually either do everything or nothing at all),
but I accept PRs.

**Comment by tgulacsi** [comment]
Starting from

```
diff --git a/stmt.go b/stmt.go
index 76f5e45..27df975 100644
--- a/stmt.go
+++ b/stmt.go
@@ -500,6 +500,37 @@ func (st *statement) ExecContext(ctx context.Context, args []driver.NamedValue)
                return nil, closeIfBadConn(err) //fmt.Errorf("dpiStmt_execute(mode=%d arrLen=%d): %w", mode, arrLen, err))
        }
 
+       if many {
+               if err := func() error {
+                       var errInfos []C.dpiErrorInfo
+                       func() {
+                               runtime.LockOSThread()
+                               defer runtime.UnlockOSThread()
+                               var errCnt C.uint32_t
+                               if C.dpiStmt_getBatchErrorCount(st.dpiStmt, &errCnt) == C.DPI_FAILURE || errCnt == 0 {
+                                       return
+                               }
+                               errInfos = make([]C.dpiErrorInfo, int(errCnt))
+                               if C.dpiStmt_getBatchErrors(st.dpiStmt, errCnt, &errInfos[0]) == C.DPI_FAILURE {
+                                       errInfos = errInfos[:0]
+                                       return
+                               }
+                       }()
+                       if len(errInfos) == 0 {
+                               return nil
+                       }
+                       errs := make([]error, 0, len(errInfos))
+                       for _, ei := range errInfos {
+                               if e := fromErrorInfo(ei); e != nil {
+                                       errs = append(errs, e)
+                               }
+                       }
+                       return errors.Join(errs...)
+               }(); err != nil {
+                       return nil, err
+               }
+       }
+
        if logger != nil && logger.Enabled(ctx, slog.LevelDebug) {
                logger.Debug("get/set", "gets", st.gets, "dests", st.dests)
        }
```

collecting the errors is easy, but what should we do with them?
These are part-errors (not all statements failed), so a warning?

How do you handle this?

**Comment by tgulacsi** [comment]
Oh, and a test case would help a lot, too!

**Comment by VadimGossip** [comment]
In my case I need to insert a large number of rows into a database.
The rows contain information about phone calls.
The insertion is done in blocks. There may be a rare error in a block. I need to save error-free part to table and return error part to process it manually later all in one operation.
I can think of many workarounds but oracle allows to do this with forall save exceptions.

I don't quite understand how best to return slice with errors 
in (st *statement) ExecContext(ctx context.Context, args []driver.NamedValue) (driver.Result, error)

i made not good solution based on extending 
```
type stmtOptions struct {
 ...
	batchErrorCounter  *uint32
	batchErrorsArray   *[]BatchErrors
}

type BatchErrors = struct {
	RowNumber uint32
	ErrorCode int32
	ErrorMsg  string
}
```

**Comment by tgulacsi** [comment]
Ok, with 856775a I see that dpiStmt_getBatchErrorCount returns 0 for a simple INSERT with executeMany.

**Comment by tgulacsi** [comment]
Ok, it has needed DPI_MODE_EXEC_BATCH_ERRORS .
See f30651f.

Is this "half of it has been inserted" OK, or shall it be OPT-IN with some Option?
What should that Option's name be? With it, on batch error, a godror.ErrBatch will be returned.

**Comment by tgulacsi** [comment]
PTAL ace166b

Any better name for the option than PartialBatch ?

**Comment by VadimGossip** [comment]
> PTAL [ace166b](https://github.com/godror/godror/commit/ace166b47fa364431184d440fce65ec36fbfdaf6)
> 
> Any better name for the option than PartialBatch ?

I can't think of a better one)

**Comment by tgulacsi** [comment]
Can you try it for your use case? (go get github.com/godror/godror@ace166b should work)

**Comment by VadimGossip** [comment]
> Can you try it for your use case? (go get github.com/godror/godror@ace166b should work)

Seems all is perfect except some strange behavior.
1. RowAffected
     No Errors
      with option
           return correct RowAffected
       without option 
           don't return RowAffected     <- 
      Partial
          with option
           don't return RowAffected  <- 
          without option 
            don't return RowAffected         
on release version
  all rows inserted no error(option does not exist)
   return correct RowAffected  
  
  error
    don't return RowAffected         


2. Not connected to feature but found in process of testing it.
I managed to lock session, may be it's as designed and can't be solved. Create a big batch, start transaction and after some time kill internet connection.
Now every operation with table will be locked by hang session(after killing session all become ok). .

Reproduce stable on release version/new version

**Comment by VadimGossip** [comment]
> type BatchErrors struct {
  Errs []*OraErr
  Affected, Unaffected []int
}

It's a good solution, Affected contain error free offsets, right?!

one more thing
it seems that it's some kind of non-transparent behavior in  stmt.go: 510
```
if err != nil && !many ||
        (many && !st.PartialBatch()) ||
        closeIfBadConn(err) == driver.ErrBadConn {
        return nil, err
    }
```
we can received return nil, err in situation err == nil && many && !st.PartialBatch()
maybe 
 
```
if err != nil && (!many || !st.PartialBatch() || closeIfBadConn(err) == driver.ErrBadConn) {
        return nil, err
}
```

**Comment by tgulacsi** [comment]
Good catch, thanks!
