### ISSUE TITLE
seemingly weird function pointer values are being logged

### ISSUE THREAD

**Issue by john-behm-bertelsmann** [godror/godror#338]
I'm getting an error like this here:

```
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: func(context.Context, driver.ConnPrepareContext) error
```
Might be coming from here:
https://github.com/godror/godror/blob/e66819c88811007b34b3d3336d2ec0a708503b8b/conn.go#L153C38-L153C45

The log line that I get before my error is this one here: https://github.com/godror/godror/blob/e66819c88811007b34b3d3336d2ec0a708503b8b/conn.go#L1124

I cannot pin point where that one is coming from. exactly.

**Comment by tgulacsi** [comment]
Yup, either provide a logger that is able to handle logged messages, or don't provide a logger.

2024. jún. 25. 19:18:07 John Behm ***@***.***>:

**Comment by tgulacsi** [comment]
PTAL 5d2ccf8

**Comment by tgulacsi** [comment]
v0.44.1 skips these function fields from JSON marshaling.
