### ISSUE TITLE
`ParseDSN` unable to parse connection string with username with prefix `c##`

### ISSUE THREAD

**Issue by ZhouXing19** [godror/godror#340]
In a CDB, the name of a common user must begin with characters that are a case-insensitive match to the prefix specified by the COMMON_USER_PREFIX initialization parameter. By default, the prefix is C##.

When i try connection string `oracle://c##FETCH:password@127.0.0.1:1521/XE`, the user name is expected to be parsed as `c##FETCH`, while godror.ParseDSN() gives me empty string for the `dsn.CommonParams.Username`.

**Comment by tgulacsi** [comment]
Do you url.PathEscape that part?

2024. jún. 28. 18:33:54 Jane Xing ***@***.***>:

**Comment by ZhouXing19** [comment]
Oh yes, `oracle://c%23%23FETCHORACLEBASIC:password@127.0.0.1:1521/XE` works fine. Sorry for the noise!
