### ISSUE TITLE
Batch statements with nullable numbers

### ISSUE THREAD

**Issue by kongo2002** [godror/godror#341]
**Describe the bug**
When trying to insert multiple rows with one `Exec`/`ExecContext` statement it seems impossible to pass a nullable `NUMBER`  that is represented by a string (i.e. not a float).

In other words, I am trying to insert decimal-type numbers where I have to distinguish between `0` and `NULL`. Trying to use the [`Batch`](https://pkg.go.dev/github.com/godror/godror#Batch) fails as well.

**To Reproduce**

```go
type numbers struct {
	id      string
	decimal *string
}

func number(id, value string) numbers {
	if value == "" {
		return numbers{id: id}
	}
	return numbers{id: id, decimal: &value}
}

func numbersTest(ctx context.Context, db *sql.DB) error {
	defer func() {
		db.Exec("DROP TABLE numbers")
	}()

	_, err := db.ExecContext(ctx, `
	CREATE TABLE numbers (
		id VARCHAR(255) NOT NULL,
		value NUMERIC(10,4),
		PRIMARY KEY(id)
	)`)
	if err != nil {
		return err
	}

	values := []numbers{
		number("a", "0"),
		number("b", "234.5210"),
		number("c", ""),
	}

	/* inserting `*string` does work when inserting single rows:
	for _, value := range values {
		_, err := db.ExecContext(ctx, "INSERT INTO numbers (id,value) VALUES (:1, :2)", value.id, value.decimal)
		if err != nil {
			return err
		}
	}
	*/

	var ids []string
	var decimals []*string

	for idx := range values {
		ids = append(ids, values[idx].id)
		decimals = append(decimals, values[idx].decimal)
	}

	// this does NOT work:
	//   error: '2. arg: empty name'
	_, err = db.ExecContext(ctx, "INSERT INTO numbers (id,value) VALUES (:1, :2)", ids, decimals)

	// this does work though
        // (obviously without the decimals, just checking that the multi-insert works)
	//_, err = db.ExecContext(ctx, "INSERT INTO numbers (id) VALUES (:1)", ids)

	if err != nil {
		return err
	}

	rows, err := db.QueryContext(ctx, "SELECT id,value FROM numbers ORDER BY id ASC")
	if err != nil {
		return err
	}

	defer rows.Close()

	for rows.Next() {
		value := &numbers{}
		if err := rows.Scan(&value.id, &value.decimal); err != nil {
			return err
		}

		if value.decimal != nil {
			fmt.Printf("got [id: %q, decimal: %q]\n", value.id, *value.decimal)
		} else {
			fmt.Printf("got [id: %q, decimal: NULL]\n", value.id)
		}
	}

	return rows.Err()
}
```

**Expected behavior**
I expect to be able to insert the same data in a multi-row fashion as it is possible with multiple `Exec` statements, specifically for nullable numbers.

For above code example, I would expect an output of:
```
got [id: "a", decimal: "0"]
got [id: "b", decimal: "234.521"]
got [id: "c", decimal: NULL]
```

**Error output**

```
2. arg: empty name
```

**Your oracle client version**
21.0.0.0.0

**Your godror version**
v0.44.1

**Your go version**
1.22.5

**Your gcc version**
13.2.1

**Machine:**
 - OS: linux
 - Architecture: x86_64

**Comment by tgulacsi** [comment]
Use a string (or godror.Number), NEVER a *string - as Oracle does not distinguish between an empty string and NULL, use an empty string for NULL.

2024. júl. 16. 0:30:55 Gregor Uhlenheuer ***@***.***>:

**Comment by kongo2002** [comment]
Yes, that's true. However the representation in Oracle is a NUMBER which does indeed distinguish between NULL and 0.

I tried using *godror.Number and string as well, without success either.

**Comment by tgulacsi** [comment]
Use an empty string for NULL.
Use "0" for zero.

2024. júl. 16. 8:27:37 Gregor Uhlenheuer ***@***.***>:

**Comment by kongo2002** [comment]
That works indeed, thanks for the clarification!

Funnily enough, I knew about `"" == NULL` but was only expecting it to hold for actual "text" columns. Probably I was thrown off by the fact that using e.g. `*string` works just fine on a single statement and when reading, just not on the batched insert :thinking: 

One question on that topic: what is then the recommended way to select such a nullable NUMBER? `string`, `sql.NullString`, `godror.Number` ..?

**Comment by tgulacsi** [comment]
string or godror.Number, maybe sql.NullInt, NullFloat - it depends.on what kind of numbers are thesenand what are you want to do with them.

For example, for a NUMBER(9), an sql.NullInt32 is enough (esp. if you gonna calculate with it); for a NUMBER(15,*) an sql.NullFloat64 is needed.
