### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by Seelly** [godror/godror#344]
# github.com/godror/godror
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:563:19: undefined: VersionInfo
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:564:19: undefined: VersionInfo
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:565:10: undefined: StartupMode
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:566:11: undefined: ShutdownMode
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:568:31: undefined: Event
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:568:42: undefined: SubscriptionOption
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:568:64: undefined: Subscription
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:569:31: undefined: ObjectType
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:570:59: undefined: Data
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:571:28: undefined: DirectLob
D:\Application\Go\pkg\mod\github.com\godror\godror@v0.44.6\orahlp.go:571:28: too many errors

**Comment by tgulacsi** [comment]
See #302
