### ISSUE TITLE
Deadlock in InitTZ when failing the query

### ISSUE THREAD

**Issue by fdc-michael-grosshans** [godror/godror#345]
**Describe the bug**
We recently observed a deadlock of the driver that happens when initTZ is called but not finished successfully. In conn.go
```
	if !c.params.PerSessionTimezone {
		key = time.Local.String() + "\t" + c.params.ConnectString
		if c.params.Timezone != nil {
			key += "\t" + c.params.Timezone.String()
		}
		var ok bool
		c.drv.mu.RLock()
		tz, ok = c.drv.timezones[key]
		c.drv.mu.RUnlock()
		if !ok {
			c.drv.mu.Lock()
			//
			// This lock must be released before the query is executed
			// 
			defer c.drv.mu.Unlock()
			tz, ok = c.drv.timezones[key]
		}
		if ok {
			c.params.Timezone, c.tzOffSecs = tz.Location, tz.offSecs
			if c.params.Timezone == nil {
				c.params.Timezone = time.UTC
			}
			return nil
		}
	}
```

setting the sesstion timezone acquires a global write lock. However, when this statement is failing it calls `getError` which also tries to acquire a lock:
```
func (d *drv) getError() error {
	if d == nil {
		return &OraErr{code: 12153, message: "getError on nil drv: " + driver.ErrBadConn.Error()}
	}
	d.mu.RLock()
	dpiContext := d.dpiContext
	d.mu.RUnlock()

	if dpiContext == nil {
		return &OraErr{code: 12153, message: "getError on in dpiContext: " + driver.ErrBadConn.Error()}
	}
	var errInfo C.dpiErrorInfo
	C.dpiContext_getError(dpiContext, &errInfo)
	return fromErrorInfo(errInfo)
}
```

which leads to a deadlock.

Suggestion:
Release the timezone lock immediately after reading the values, Re-lock when the statement was executed succesfully.

**Your oracle client version**
19.22

**Your godror version**
v0.44.2, but still existing

**Your go version**
1.22.2

**Your gcc version**
doesn't matter

**Machine (please complete the following information):**
doesn't matter

**Comment by tgulacsi** [comment]
Can you help writing a test for it?
Or at least testing 60730c2 ?

**Comment by fdc-michael-grosshans** [comment]
Hello, i think the test setup is rather complicated and i cannot see how to do this actually. I found no example in your libraray that is close to what we actually need. Hwoever, we deploy the new version today, and will report back if this solved the issue.

Thank you very much for the quick fix

**Comment by fdc-michael-grosshans** [comment]
For now it looks good and therefore i will close the ticket. If we observe anything unwanted / unexpected we will come back.
