### ISSUE TITLE
error

### ISSUE THREAD

**Issue by drhvr** [godror/godror#348]
**Describe the bug**

**To Reproduce**
At least the offending source code;
the best is a minimal test case that reproduces the error.

**Expected behavior**

**Error output**
Copy the error output (panic, stack trace),
or the output of running with `DPI_DEBUG_LEVEL=92`.

**Your oracle client version**
e.g. 12.2.0.1.0

**Your godror version**
e.g. v0.20.4

**Your go version**
e.g. 1.15.2

**Your gcc version**
e.g. 4.8.3

**Machine (please complete the following information):**
 - OS: [e.g. win]
 - Architecture: [e.g. x86_64]
 - Version: [e.g. 10]

**Additional context**

**Comment by SoldierFace** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)
