### ISSUE TITLE
Cannot locate a 64-bit Oracle Client library: "libclntsh.so"

### ISSUE THREAD

**Issue by Mnemonics** [godror/godror#35]
For a while this issue went away when I followed the instructions on:  https://oracle.github.io/odpi/doc/installation.html#linux 
But now it is back with a vengeance.

I installed the Oracle Instant Client (19.6) and the lib is available in: /usr/lib/oracle/19.6/client64/lib 
I set the ldconfig, but still it remains.

**Comment by tgulacsi** [comment]
What does it print with DPI_DEBUG_LEVEL=38 environment variable?

**Comment by cjbj** [comment]
What does `ldconfig -p | grep libclntsh` show?

**Comment by Mnemonics** [comment]
Hi Christopher,

it Shows:
 libclntshcore.so.19.1 (libc6,x86-64) =>
/usr/lib/oracle/19.6/client64/lib/libclntshcore.so.19.1
libclntshcore.so (libc6,x86-64) =>
/usr/lib/oracle/19.6/client64/lib/libclntshcore.so
libclntsh.so.19.1 (libc6,x86-64) =>
/usr/lib/oracle/19.6/client64/lib/libclntsh.so.19.1
libclntsh.so (libc6,x86-64) =>
/usr/lib/oracle/19.6/client64/lib/libclntsh.so
libclntsh.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libclntsh.so

**Comment by Mnemonics** [comment]
Hi Tamás,

same output:
Fetching lambci/lambda:go1.x Docker container image......
2020-03-26 08:46:48 Mounting
/home/marcel/git/distr-partner-logistical-structure-service/ops/cdk.out as
/var/task:ro,delegated inside runtime container
2020-03-26T07:46:49Z [INFO] Emitter using address: 169.254.79.2:2000
panic: ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library:
"libclntsh.so: cannot open shared object file: No such file or directory".
See https://oracle.github.io/odpi/doc/installation.html#linux for help

goroutine 1 [running]:
main.init.0()
/home/marcel/git/distr-partner-logistical-structure-service/partner_logistical_structure/lambda/import/main.go:78
+0x2f2

**Comment by tgulacsi** [comment]
Try to add some debugging print to ODPI-C's dpiOci.c:
```
diff --git a/odpi/src/dpiOci.c b/odpi/src/dpiOci.c
index c731324..8d73fab 100644
--- a/odpi/src/dpiOci.c
+++ b/odpi/src/dpiOci.c
@@ -1786,9 +1786,12 @@ static int dpiOci__loadLib(dpiError *error)
                     sizeof(loadError));
 #else
         dpiOciLibHandle = dlopen(libName, RTLD_LAZY);
-        if (!dpiOciLibHandle && i == 0) {
+        if (dpiOciLibHandle) {
+                       dpiDebug__print("dlopen(%s): OK\n", libName);
+               } else {
             strncpy(loadError, dlerror(), sizeof(loadError) - 1);
             loadError[sizeof(loadError) - 1] = '\0';
+                       dpiDebug__print("dlopen(%s): %s\n", libName, loadError);
         }
 #endif

@@ -1807,6 +1810,13 @@ static int dpiOci__loadLib(dpiError *error)
                 (void) sprintf(oracleHomeLibName, "%s/lib/%s", oracleHome,
                         dpiOciLibNames[0]);
                 dpiOciLibHandle = dlopen(oracleHomeLibName, RTLD_LAZY);
+                               if (dpiOciLibHandle) {
+                                       dpiDebug__print("dlopen(%s): OK\n", oracleHomeLibName);
+                               } else {
+                                       strncpy(loadError, dlerror(), sizeof(loadError) - 1);
+                                       loadError[sizeof(loadError) - 1] = '\0';
+                                       dpiDebug__print("dlopen(%s): %s\n", oracleHomeLibName, loadError);
+                               }
                 free(oracleHomeLibName);
             }
         }
```

and then run with `DPI_DEBUG_LEVEL=38`.
(Don't forget to touch some go file to force the recompilation!)

**Comment by cjbj** [comment]
What's your (container?) OS distribution and version?

Was your ldconfig output from inside the container?

**Comment by Mnemonics** [comment]
Hi,

Thanks for your help. It looks like it is using some other environment.

I added the debug and get this:
ODPI [00020] 2020-03-27 07:52:25.287: oracleHome:(null)
ODPI [00020] 2020-03-27 07:52:25.288: oracleHome:(null)
ODPI [00020] 2020-03-27 07:52:25.288: oracleHome:(null)
ODPI [00020] 2020-03-27 07:52:25.289: oracleHome:(null)
ODPI [00020] 2020-03-27 07:52:25.289: oracleHome:(null)
2020-03-27T07:52:25Z [INFO] Emitter using address: 169.254.79.2:2000
panic: ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library:
"libclntsh.so: cannot open shared object file: No such file or directory".
See https://oracle.github.io/odpi/doc/installation.html#linux for help

Then I hardcoded my oracle lib and get:
ODPI [00022] 2020-03-27 07:55:22.115:
oracleHome:/usr/lib/oracle/19.6/client64
ODPI [00022] 2020-03-27 07:55:22.115:
oracleHomeLibName:/usr/lib/oracle/19.6/client64/lib/libclntsh.so
ODPI [00022] 2020-03-27 07:55:22.115:
oracleHome:/usr/lib/oracle/19.6/client64
ODPI [00022] 2020-03-27 07:55:22.115:
oracleHomeLibName:/usr/lib/oracle/19.6/client64/lib/libclntsh.so
ODPI [00022] 2020-03-27 07:55:22.115:
oracleHome:/usr/lib/oracle/19.6/client64
ODPI [00022] 2020-03-27 07:55:22.115:
oracleHomeLibName:/usr/lib/oracle/19.6/client64/lib/libclntsh.so
ODPI [00022] 2020-03-27 07:55:22.115:
oracleHome:/usr/lib/oracle/19.6/client64
ODPI [00022] 2020-03-27 07:55:22.115:
oracleHomeLibName:/usr/lib/oracle/19.6/client64/lib/libclntsh.so
ODPI [00022] 2020-03-27 07:55:22.116:
oracleHome:/usr/lib/oracle/19.6/client64
ODPI [00022] 2020-03-27 07:55:22.116:
oracleHomeLibName:/usr/lib/oracle/19.6/client64/lib/libclntsh.so
2020-03-27T07:55:22Z [INFO] Emitter using address: 169.254.79.2:2000
panic: ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library:
"libclntsh.so: cannot open shared object file: No such file or directory".
See https://oracle.github.io/odpi/doc/installation.html#linux for help

So it is not "looking" to the same environment.
I don't understand what environment it is looking to.

I'm running on Linux Mint (Mate) 19.1 Tessa on my laptop

I don't know which container, or how to check it (it would explain the
other environment)
Can I insert the oracle driver in that container?

Cheers,
Marcel

**Comment by cjbj** [comment]
Check you have libaio (it maybe called libaio1) installed.

**Comment by Mnemonics** [comment]
Yes installed

**Comment by cjbj** [comment]
Check whether SQL*Plus runs.

What Instant Client did you use before?

What glibc do you have?

Any issues with libnsl? https://github.com/oracle/node-oracledb/issues/892 ?

**Comment by cjbj** [comment]
@Mnemonics Any update?  What do you get when you run `ldd /usr/lib/oracle/19.6/client64/lib/libclntsh.so.19.1`?

**Comment by tgulacsi** [comment]
According to https://github.com/oracle/odpi/issues/131#issuecomment-637854431 ODPI-C v4.0.0 will have a debug option just for this!

**Comment by maverickVision** [comment]
I've had the same issue, this article solved the problem for me: http://oraontap.blogspot.com/2020/01/mac-os-x-catalina-and-oracle-instant.html

**Comment by tgulacsi** [comment]
As godror v0.17.0 uses ODPI v4.0.0, you can set ODPI_DEBUG_LEVEL=92 (at least 64) to see the dynamic library loading logic.

**Comment by phuwn** [comment]
Hi folks, for later readers like me, I think the solution is here: [quick start installation](https://oracle.github.io/node-oracledb/INSTALL.html#quickstart).

### tl:dr
- Install [Python 2.7](https://www.python.org/downloads/) (Note: recent Node.js tools should work with Python 3).
- Install a C Compiler such as Xcode, GCC, Visual Studio 2017, or similar.
- Install [Oracle Instant Client](https://www.oracle.com/database/technologies/instant-client.html) & add the LD_LIBRARY_PATH environment to your newly downloaded package.
```sh
export LD_LIBRARY_PATH=/dir/to/instantclient_version
```

**Comment by cjbj** [comment]
And always check the [latest installation instructions](https://oracle.github.io/node-oracledb/INSTALL.html) !
