### ISSUE TITLE
Cannot select column of type 'sys.xmltype'

### ISSUE THREAD

**Issue by rodgarrison** [godror/godror#36]
**Describe the bug**
I prepare a valid SQL statement string. I query. I attempt to read rows,

for rows.Next() {
  ...
}

However, the inside scope of the for loop never runs. Therefore the code never encounters the work of read+transform the sys.xmltype into GO's target type.

**To Reproduce**
// xmlColumn is of type 'sys.xmltype'
query := "select xmlColumn from xmlTable where id=123";
rows, err := oracle.Query(query)
if err!=nil {...}
// select xml column and cast to string
var xml string
for rows.Next() {
   err = rows.Scan(&xml)
   if err!=nil{...}
}
rows.Close()

**Expected behavior**
Either the xml column is selected as string, or Scan gives me an error. Neither happens now.

**Screenshots**
N/A

**Your oracle client version**
e.g. 12.2.0.1.0

**Your godror version**
e.g. v0.0.1

**Your go version**
e.g. 1.14.0

**Your gcc version**
e.g. 7.3.1

**Machine (please complete the following information):**
 - OS: Redhat Linux
 - Architecture amd x86_64
 - Version: 10

**Additional context**
I'm not sure if a Lob is needed here, however, as rows.Next() is always false, the inside of the loop is never encountered.

**Comment by tgulacsi** [comment]
You can try running with ODPI_DEBUG=28

Another solution may be to SELECT xmlColumn.getClobVal

**Comment by cjbj** [comment]
@rodgarrison use getClobVal, as mentioned.  Even if godror returned XMLTYPE directly from a query, it would be of limited size (the size of VARCHAR2) since XML support isn't good in the underlying Oracle client libraries.

**Comment by rodgarrison** [comment]
getClobVal works but weirdly not without a table alias. This works:

'select t.xmlColumn.getClobVal() from userTable t where x.id=123'
