### ISSUE TITLE
Add ability to set godror.NumberAsString(bool) as a global setting

### ISSUE THREAD

**Issue by omerkirk** [godror/godror#42]
Hi Tamas,

As discussed in #39 I was planning to use NumberAsString setting. However apparently that setting can be passed along with the new Query, Prepare and Open functions. The problem is I am using jmoiron/sqlx and that library didn't add support for the new db interfaces for the sake of compatibility.  Is it possible that you can make NumberAsString as a global setting that I can call directly instead of the driver interfaces. Like goracle.SetAutoCommit(true) as an example. 

I tried to use this setting as in the following test, but not only I don't have access to sql.DB type because I use the sqlx.DB wrapper, but I also couldn't find a function QueryContext that takes an Option as a third parameter in database/sql documentation. So I am confused as to how this setting is used.

```
func TestNumberBool(t *testing.T) {
	t.Parallel()
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	const qry = "SELECT 181 id, 1 status FROM DUAL"
	rows, err := testDb.QueryContext(ctx, qry, godror.NumberAsString())
	if err != nil {
		t.Fatal(errors.Errorf("%s: %w", qry, err))
	}

	for rows.Next() {
		var id int
		var status bool
		if err := rows.Scan(&id, &status); err != nil {
			t.Errorf("failed to scan data: %s\n", err)
		}
		t.Logf("Source id=%d, status=%t\n", id, status)
	}
}
```

**Comment by tgulacsi** [comment]
PTAL the "nonumber" branch!

**Comment by omerkirk** [comment]
it works thanks
