### ISSUE TITLE
Remove usage of _ORACLE_SCRIPT

### ISSUE THREAD

**Issue by anthony-tuininga** [godror/godror#43]
In the test case for heterogeneous pools a call is made to set the parameter _ORACLE_SCRIPT to the value true. See [here](https://github.com/godror/godror/blob/master/z_heterogeneous_test.go#L50). 

An explanation of why you don't want to use this parameter can be found here: https://mikedietrichde.com/2020/02/10/be-aware-when-you-use-_oracle_script-in-scripts/

Can this be removed?

**Comment by tgulacsi** [comment]
Sure, it's just a hack - but please fix the test, too!
It should also work with the default Autonomous Database.

**Comment by anthony-tuininga** [comment]
I have a bunch of tests that we did with session pools in the past. I'll look at integrating those in and also ensuring that they work with Autonomous Database.
