### ISSUE TITLE
IN OUT sql.NullString parameter returns []byte instead of sql.NullString

### ISSUE THREAD

**Issue by glebkin** [godror/godror#45]
**Describe the bug**
We have PL/SQL function with `IN OUT VARCHAR2` parameter.
In `ExecContext` we're sending it as 
`sql.Out{Dest: &sql.NullString{Valid:false, String:""}, In: true}`
and getting the following error:
`22. get[0]: awaited []byte/string/Number, got *sql.NullString (&sql.NullString{String:"", Valid:true})`
And we noticed that bindVarTypeSwitch function in stmt.go doesn't have any handler for sql.NullString type.

**To Reproduce**
Try to call PL/SQL function with VARCHAR2 IN OUT parameter.

**Expected behavior**
ExecContext executed without any errors.

**Your oracle client version**
19.6.0.0.0

**Your godror version**
e.g. v0.14.0

**Your go version**
e.g. 1.13.5

**Your gcc version**
e.g. 5.1.0

**Machine (please complete the following information):**
 - OS: Windows
 - Architecture: x64
 - Version: 10

**Comment by tgulacsi** [comment]
As Oracle does not differentiate between an empty string and a NULL, why do you want?
Just use an `var s string; sql.Out{Dest:&s, In:true}`.

**Comment by glebkin** [comment]
Thanks!

**Comment by tgulacsi** [comment]
Fun fact: lookup the difference between the SQL standard VARCHAR type and the Oracle-specific VARCHAR2!
https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/Data-Types.html#GUID-DF7E10FC-A461-4325-A295-3FD4D150809E
