### ISSUE TITLE
After failover, prepared statements stopped working

### ISSUE THREAD

**Issue by veqryn** [godror/godror#48]
**Describe the bug**
We run a multi-az AWS RDS with Oracle. This means it has 1 replica/clone, that can be failed over to at any time.
We tested a failover today, and a separate bunch of servers (a different application than my other ticket) began to encounter a very weird issue: It began claiming that a prepared statement that needs 1 argument, actually doesn't want any arguments.

**To Reproduce**
That might be tough...

**Expected behavior**
Program should continue without issues. If a statement needs to be re-prepared in the background due to connection issues, it should be.

**Screenshots**
`sql: expected 0 arguments, got 1`

**Your oracle client version**
e.g. 12.1.0.2.0

**Your godror version**
e.g. v0.13.4

**Your go version**
e.g. 1.14.1

**Your gcc version**
e.g. 7.3.0

**Machine (please complete the following information):**
 - OS: linux docker container for golang:1.14.1
 - Architecture x86_64
 - Version: debian buster

**Additional context**
Our code surrounding the call is pretty simple.
We have a prepared statement that looks roughly like this:
`select OTHER_ID from TABLE_OWNER.ID_TO_ID_T where ID = :1`

It gets prepared on startup, then the location of the error was here:
```go
sqlxConn.selectOtherIDFromIdStmt.GetContext(ctx, &otherID, id)
```

**Comment by tgulacsi** [comment]
In general, it seems that prepared statments won't work when failover.

**Comment by tgulacsi** [comment]
statement.NumInput will return -1 on error, but can't return the error - only a panic is possible, which is bad, too...

**Comment by tgulacsi** [comment]
I've tried to reproduce it with TestConnCut in 0c5cead without success.
Maybe a TCP dump on that AWS connection?

Or does that use SSL?

**Comment by veqryn** [comment]
I don't think it uses SSL, but not totally sure what oracle magic/voodoo is happening:
```
MY_SERVICE_NAME =
  (DESCRIPTION =
    (SDU=32767)
    (CONNECT_TIMEOUT = 10)
    (ENABLE = BROKEN)
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = prod1xxxx.us-east-1.rds.amazonaws.com)(PORT = 1521))
    )
    (CONNECT_DATA = (SERVICE_NAME = PROD1_SHARED.xxxx.net)(SERVER = SHARED))
  )
```

**Comment by tgulacsi** [comment]
If it does not have a "(SECURITY=(SSL...)" part, then it does not use SSL.
I was asking it only because my tcp proxy in TestConnCut does not work with SSL upstream.

Why don't you have FAILOVER and multiple ADDRESS in the ADDRESS_LIST (maybe even the same, twice?). 
@cjbj knows a lot more how the OCI / Orace SQL*Net works, but if the failover can be handled in the OCI, then don't pull it up to the application...
Maybe https://docs.oracle.com/cd/B28359_01/network.111/b28317/tnsnames.htm#NETRF279 helps, too.

**Comment by veqryn** [comment]
Our DBA's (I am definitely not an Oracle DBA) previously had multiple addresses listed back when we had Oracle running in our own data center.  But after we moved to AWS, there has only been one address listed, I assume because there is only 1 hostname now.

**Comment by tgulacsi** [comment]
PTAL the current master (or at least v0.15.0-pre3), w've rewritten the connection handling  and implemented SessionResetter, so every new connection (from the Go DB pool) is fresh from the underlying OCI session pool, so hopefully follows the failover.

**Comment by tgulacsi** [comment]
It should be better with v0.16.1 and enabling session poolin (standalone=0) and disablling Go connection pooling (db.SetMaxIdleConns(0), db.SetMaxOpenConns(0)).

**Comment by tgulacsi** [comment]
Go 1.14.6 gained proper session resetting (https://github.com/golang/go/commit/399ce807381f897d5ea7bdd3970017976d249738) and for #57 I've added a few missing releases, so you can use standalone=0 (Oracle session pooling) with `db.SetMaxIdleConns(0)` with confidence!

**Comment by veqryn** [comment]
Thank you @tgulacsi .
Quick request: could you clear up the language in the readme, as it appears to suggest that standaloneConnection=1 is the default behavior, when the code in the driver says otherwise:

> WARNING WARNING also, you MUST disable Go connection pooling if you're using Oracle Session pooling (standaloneConnection=0), that's why the default is standaloneConnection=1.
> Either use standaloneConnection=1 connection parameter, or disable Go connection pooling with

**Comment by tgulacsi** [comment]
Thanks @veqryn for pointing that out - I've eliminated that section in e033c73.
