### ISSUE TITLE
Avoid Go pooling or at least reaquire session when connection got from pool

### ISSUE THREAD

**Issue by tgulacsi** [godror/godror#49]
As discussed in mail and after at https://groups.google.com/forum/#!topic/golang-sql/VkjZeUVS0i4%5B1-25%5D Go's database pooling conflicts with some Oracle session pooling features (failover, for example).

ResetSession is called when the connection has been got freshly from the pool,
IsValid is called when the connections is being put back to the pool.

The idea is to release the session in IsValid,
and acquire a new one in ResetSession.

@anthony-tuininga I've started implementing this (in the "resetsession" branch, 6a95cb5), and seems to work (I don't know how effective is it regarding the OCI session pool), EXCEPT the TestObject test, which reliably (`go test -run=TestObject` with a poolable connection) fails, so this needs investigation.

**Comment by tgulacsi** [comment]
Ok, that error is because of my hack of getting the underlying connection from a Conn...

When I acquire a separate session, THAT works, but now queueing object fails:
```
gotip test -run=Queue
Using default database for tests:  /home/tgulacsi/src/github.com/godror/godror/contrib/free.db/env.sh
export TNS_ADMIN=/home/tgulacsi/src/github.com/godror/godror/contrib/free.db
export GODROR_TEST_USERNAME=test
export GODROR_TEST_DB=free_high
export GODROR_TEST_STANDALONE=1
Client: 19.3.0.0.0 Timezone: Local
Server: 18.4.0.0.0 [Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production; Version 18.4.0.0.0] Timezone: +00:00
--- FAIL: TestQueueObject (1.78s)
    queue_test.go:194: enqOpts: godror.EnqOptions{Transformation:"", Visibility:0x1, DeliveryMode:0x1}
    queue_test.go:199: deqOpts: godror.DeqOptions{Condition:"", Consumer:"", Correlation:"", MsgID:"", Transformation:"", Mode:0x3, DeliveryMode:0x1, Navigation:0x1, Visibility:0x1, Wait:0x1e}
    queue_test.go:224: obj: TEST.TEST_QOBJ_TYP
    queue_test.go:230: enqueue: enqueue []godror.Message{godror.Message{Correlation:"", ExceptionQ:"", Enqueued:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MsgID:[16]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, OriginalMsgID:[16]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, Raw:[]uint8(nil), Delay:0, Expiration:0, Priority:0, NumAttempts:0, Object:(*godror.Object)(0xc0000b61c0), DeliveryMode:0x0, State:0x0}}: ORA-00000: DPI-1056: found object of type TEST.TEST_QOBJ_TYP when expecting object of type TEST.TEST_QOBJ_TYP
```

@anthony-tuininga is there any requirement that the queue accepts an object only on the same session? Can the ObjectType and thus an Object acquired on a separate session?

**Comment by anthony-tuininga** [comment]
@tgulacsi, in ODPI-C, the object types and objects created from them are tied to a specific connection. So, if you create an object with one connection and then attempt to use it with another one, you *will* get errors! I'll take a closer look at the test and see if I can suggest a correction.

**Comment by tgulacsi** [comment]
Ok, I've reverted the change, now I get 
```
! gotip test -parallel=3
Using default database for tests:  /home/tgulacsi/src/github.com/godror/godror/contrib/free.db/env.sh
export TNS_ADMIN=/home/tgulacsi/src/github.com/godror/godror/contrib/free.db
export GODROR_TEST_USERNAME=test
export GODROR_TEST_DB=free_high
export GODROR_TEST_STANDALONE=1
Client: 19.3.0.0.0 Timezone: Local
Server: 18.4.0.0.0 [Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production; Version 18.4.0.0.0] Timezone: +00:00
--- FAIL: TestQueueObject (2.49s)
    queue_test.go:191: name: TEST_QOBJ
    queue_test.go:196: enqOpts: godror.EnqOptions{Transformation:"", Visibility:0x1, DeliveryMode:0x1}
    queue_test.go:201: deqOpts: godror.DeqOptions{Condition:"", Consumer:"", Correlation:"", MsgID:"", Transformation:"", Mode:0x3, DeliveryMode:0x1, Navigation:0x1, Visibility:0x1, Wait:0x1e}
    queue_test.go:221: obj: TEST.TEST_QOBJ_TYP
    queue_test.go:227: enqueue: enqueue []godror.Message{godror.Message{Correlation:"", ExceptionQ:"", Enqueued:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, MsgID:[16]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, OriginalMsgID:[16]uint8{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, Raw:[]uint8(nil), Delay:0, Expiration:0, Priority:0, NumAttempts:0, Object:(*godror.Object)(0xc000170380), DeliveryMode:0x0, State:0x0}}: ORA-00000: DPI-1056: found object of type TEST.TEST_QOBJ_TYP when expecting object of type TEST.TEST_QOBJ_TYP
```

? `DPI-1056: found object of type TEST.TEST_QOBJ_TYP when expecting object of type TEST.TEST_QOBJ_TYP` ?

and 

```
--- FAIL: TestPLSQLTypes (0.33s)
    z_plsql_types_test.go:326: dpiStmt_execute(mode=32 arrLen=-1): ORA-21522: attempted to use an invalid connection in OCI (object mode only)
```
escapes my understading...

**Comment by tgulacsi** [comment]
Ok, it was my fault, using a separate connection for the objects...
Going all the way back to the conn-fishing hack, everything seems to work,
and if I fix the tests, then even with Go 1.15, too!

This ResetSession reopens the session only if there is an underlying session pool,
so this cannot be used with my test Autonomous Database...

**Comment by anthony-tuininga** [comment]
Yes, I tried your branch and got the same error. I must admit it could be improved -- perhaps with something like "payload objects must be created with the same connection as the queue". I'll ask @cjbj for his opionion when he is available.

After your changes, the branch passes completely except for TestInputArray, which has always failed for me. That test appears to be assuming something about the time zone, but I haven't examined it closely yet.

**Comment by tgulacsi** [comment]
Hmm, what does dpiConn_release do vs. dpiConn_close?
If I only release the connection i ResetSession before acquiring a new one, the session pool gets exhausted fast. If I close the connection, then the Objects and Queues becomes invalid...

**Comment by anthony-tuininga** [comment]
`dpiConn_close()` actually closes the connection and anything that used it is no longer valid, as you discovered. `dpiConn_release()`, however, simply releases a reference. When the reference count reaches zero the connection will also be closed. But if there are other references (like the internal ones to Objects and Queues), the connection won't be closed until all of those refereences are released. I hope that explains the difference adequately!

**Comment by tgulacsi** [comment]
Thanks, that clarifies it.

Then somewhere I leak references - if I only dpiConn_release in ResetSession (before acquire), then the limited session pool gets full fast.

**Comment by anthony-tuininga** [comment]
You can use `DPI_DEBUG_LEVEL=2` to track references and see where your reference leak is taking place. I do that regularly enough for my own internal references. :-)

**Comment by tgulacsi** [comment]
Hmmm....

How to find that ref unrelease? I've severly simplified all Close code to just ..._release, but my tests still exhausts the pool: 

    $ DPI_DEBUG_LEVEL=30 gotip test -parallel=1 -v -count=1

[timeout-20200429_112822.log.gz](https://github.com/godror/godror/files/4550818/timeout-20200429_112822.log.gz)


I know this is too big - what shall I put in TestResetSession (z_test.go) to reproduce the error? Or do you see anything suspicious?
The pool size is set to 16.

**Comment by tgulacsi** [comment]
Maybe there's no error, just the `TestRanaIssue244` test exhausts all sessions (by design)...
Now only TestInputArray fails, and sometimes one or two with context timeout (which annoys me a little bit).

**Comment by tgulacsi** [comment]
Ok, I've finished it - all tests pass, if not too many runs in parallel.
The code is definitely better and simpler.

**Comment by anthony-tuininga** [comment]
All tests pass for me as well. :-)
