### ISSUE TITLE
scan error on timestamp column if data returns null from query for one of the columns

### ISSUE THREAD

**Issue by chris-0406** [godror/godror#52]
Hello @tgulacsi , thank you for looking into this. 

After we did a `-sed` of goracle to godror, we came across an issue in one of our API where It was throwing a scan error on one of the columns (expDate), which is a timestamp column and if the query is returning null value for that field then it is throwing an error 
>  **Error: unsupported Scan, storing driver.Value type <nil> into type *time.Time",**

Type struct for that field is defined as ` time.Time`, I changed it sql.NullTime but that didn't help and the error this time we got was 
> **Error - cannot use date.expDate (type sql.Nulltime) as type time.Time in argument to ptimes.TimestampProto.**

When we revert the changes back to goracle then we are not getting any errors.

Please let me know if I didn't explain the issue clearly or if I am missing anything to add, we are new to the Go and trying to understand our existing APIs
Thank you.

**Comment by tgulacsi** [comment]
Can't use date.expDate.Time ?
Please show some code for that unsupported scan.

**Comment by chris-0406** [comment]
Sorry, to respond back late. 

Here are my query results from DB
![ruH5pC8DFe](https://user-images.githubusercontent.com/65002841/81491753-4f643a00-9257-11ea-8c76-4840b72490fa.png)

This is how dates have been declared in the code 
![goland64_qS8ifQQwl7](https://user-images.githubusercontent.com/65002841/81491768-6d319f00-9257-11ea-93b1-74b565c56584.png)

When I was running in debug mode, I got an error message at scan 
![rhKf06Pydl](https://user-images.githubusercontent.com/65002841/81491782-a407b500-9257-11ea-8d59-439e44be2748.png)


Complete Error message :  

> Error: unsupported Scan, storing driver.Value type into type time.Time


Not sure if this helps you but please let me know if there is anything I need to do, but as I mentioned when i switched back to goracle then i am not getting any error on scan

**Comment by tgulacsi** [comment]
Please, always PRINT and copy the FULL error message, and don't believe to your IDE!.

Creating a simple test case, the full error message is:
```
--- FAIL: TestSelectNullTime (0.03s)
    z_test.go:3013: sql: Scan error on column index 1, name "SYSDATE+NULL": unsupported Scan, storing driver.Value type <nil> into type *time.Time
```

or maybe the `<nil>` is swallowed by GitHub ?

**Comment by chris-0406** [comment]
Sure, thank you.

**Comment by tgulacsi** [comment]
Why can't you use sql.NullTime for expDate?
