### ISSUE TITLE
How to connect as sysdba

### ISSUE THREAD

**Issue by ankurnigam** [godror/godror#54]
I want to connect as "/ as sysdba"

Can someone help me to draft the string.

I have already set ORACLE_SID and ORACLE_HOME

**Comment by tgulacsi** [comment]
Have you tried it? What was the error message?
When you can connect with sqlplus, you can connect with godror, too.

**Comment by ankurnigam** [comment]
I am getting error when I am putting ' / as sysdba' in connection string .


/u01/app/oracle/product/12.1.0.2/dbhome_fadbbp190901r
/u01/app/oracle/product/12.1.0.2/dbhome_fadbbp190901r/lib
/u01/app/oracle/product/12.1.0.2/dbhome_fadbbp190901r
/u01/app/oracle/product/12.1.0.2/dbhome_fadbbp190901r/lib
Error running query
params={{'  as sysdba'  false <nil> Local} {1 1000 1 30s 1h0m0s 5m0s false false}} extAuth=0: ORA-01017: invalid username/password; logon denied

**Comment by ankurnigam** [comment]
When I am putting connection as "/ as sysdba" ,I am getting error as below :

username="" dsn="" params={authMode:2 connectionClass:0x1602f90 connectionClassLength:6 purity:0 newPassword:<nil> newPasswordLength:0 appContext:<nil> numAppContext:0 externalAuth:1 externalHandle:<nil> pool:<nil> tag:<nil> tagLength:0 matchAnyTag:0 outTag:<nil> outTagLength:0 outTagFound:0 shardingKeyColumns:<nil> numShardingKeyColumns:0 superShardingKeyColumns:<nil> numSuperShardingKeyColumns:0 outNewSession:0}: ORA-01017: invalid username/password; logon denied

**Comment by ankurnigam** [comment]
Issue was with the syntax error which I have corrected and issue is resolved.

**Comment by ioanvapi** [comment]
But still, what is the right datasourceName for a connection as SYSDBA?
I have used: 

`datasourceName := "/ as sysdba"`
`db, err := sql.Open("godror", datasourceName)`

and I get the error:

`params=user= password="some-passwd" connectString= timezone=local poolIncrement=1 poolMaxSessions=1000 poolMinSessions=1 poolSessionMaxLifetime=1h0m0s
poolSessionTimeout=5m0s poolWaitTimeout=30s extAuth=0: ORA-24415: Missing or null username.
`

**Comment by ankurnigam** [comment]
You need to set variable to use this one.

os.Setenv("ORACLE_SID",<SID name>)
os.Setenv("ORACLE_HOME",<ORACLE_HOME>)
os.Setenv("PATH",PATH)
os.Setenv("LD_LIBRARY_PATH",LD_LIBRARY_PATH)

Once you set all these then run 

connectionStr := "/ as sysdba"
db, err := sql.Open("godror", connectionStr)

It will work.

**Comment by ioanvapi** [comment]
Looks like in my environment it work as:

`db, err := sql.Open("godror", "/")`

instead of 

`db, err := sql.Open("godror", "/ as sysdba")`

but I don't know why :(
I have set the previous environment variables.
