### ISSUE TITLE
How to print dbms_output.put_line data into a file using golang

### ISSUE THREAD

**Issue by vamshinandan** [godror/godror#56]
I have some dbms_output statements in my plsql package using which I write onto a file could you please give me a sample go program where I can call the package and create a file with data from dbms_output statements

**Comment by tgulacsi** [comment]
See https://godoc.org/github.com/godror/godror#ReadDbmsOutput and search for it in the tests for example.

**Comment by vamshinandan** [comment]
Thanks Tamas :)

**Comment by ankurnigam** [comment]
Hi Team, I don't see any example how to use dbms_output.put_line using that function.  

My problem is that I have PL/SQL block which I want to execute using golang and want to print the dbms_output.put_line output.

Please help.

**Comment by ankurnigam** [comment]
I only see below details :   
 func ReadDbmsOutput ¶
func ReadDbmsOutput(ctx context.Context, w io.Writer, conn preparer) error
ReadDbmsOutput copies the DBMS_OUTPUT buffer into the given io.Writer.

Be sure that you enable it beforehand (either with EnableDbmsOutput or with DBMS_OUTPUT.enable(NULL))

**Comment by tgulacsi** [comment]
Just as you stated (https://github.com/godror/godror/issues/56#issuecomment-854249587), you have to enable DBMS_OUTPUT with EnableDbmsOutput, when you can read the buffer with ReadDbmsOutput.

Just as in TestDbmsOutput (`z_test.go`) or  TestFuncBool (`z_plsql_types_test.go`).

**Comment by tgulacsi** [comment]
As always, watch out to use the same Oracle session for Enable, Execute and Read! The simplest solution for this is to use a *sql.Tx.

**Comment by ankurnigam** [comment]
Thanks Tamas :) 

I write below code but it's giving me error 

Code 
###########
	db, err := sql.Open("godror", connect_string)
    if err != nil {
	fmt.Println("Failed to connect DB")
    }
	defer db.Close()  
	ctx, cancel := context.WithTimeout(testContext("DbmsOutput"), 10*time.Second)
	defer cancel()
	if err := godror.EnableDbmsOutput(ctx, db); err != nil {
		fmt.Printf(err.Error())
	}
	q := "begin dbms_output.put_line ('Hello World..'); end;"
	if _, err := db.ExecContext(ctx, q); err != nil {
		fmt.Printf(err.Error())
	}
	var buf bytes.Buffer
	if err := godror.ReadDbmsOutput(ctx, &buf, db); err != nil {
		fmt.Printf(err.Error())
	}
  fmt.Println("Output:")
  fmt.Println(buf.String())
################
Error 
BEGIN DBMS_OUTPUT.enable(NULL); END;: ORA-01804: Error while trying to retrieve text for error ORA-01804ORA-01804: Error while trying to retrieve text for error ORA-01804BEGIN DBMS_OUTPUT.get_lines(:1, :2); END;: ORA-01804: Error while trying to retrieve text for error ORA-01804Output:

**Comment by tgulacsi** [comment]
ORA-01804 is something about DB time zones (https://support.oracle.com/knowledge/Oracle%20Database%20Products/365558_1.html).

Does a simple Ping succeeds?

And please take a look at https://github.com/godror/godror/issues/56#issuecomment-854502250 and use ONE connection with DBMS_OUTPUT!

And of course after some errors, you shouldn't proceed...

Sth. like 
```
    db, err := sql.Open("godror", connect_string)                                          
    if err != nil {                                                                            
        log.Fatalf("connect to %q: %+v", connect_string, err)                                                    
    }                                                                                          
    defer db.Close()                                                                       
    ctx, cancel := context.WithTimeout(testContext("DbmsOutput"), 10*time.Second)          
    defer cancel()
    tx, err := db.BeginTx(ctx, nil)
    if err != nil {
        log.Fatalf("BEGIN: %+v", err)
    }
    defer tx.Rollback()
    if err := tx.PingContext(ctx); err != nil {
        log.Fatalf("Ping: %+v", err)
    }
    if err := godror.EnableDbmsOutput(ctx, tx); err != nil {                               
        log.Fatalf("EnableDbmsOutput: %+v", err)
    }                                                                                      
    q := "begin dbms_output.put_line ('Hello World..'); end;"                              
    if _, err := tx.ExecContext(ctx, q); err != nil {                                      
        log.Fatalf("%s: %+v", q, err)
    }                                                                                      
    var buf bytes.Buffer                                                                   
    if err := godror.ReadDbmsOutput(ctx, &buf, tx); err != nil {                           
        log.Fatalf("ReadDbmsOutput: %+v", err)
    }                                                                                      
    fmt.Println("Output:")                                                                       
    fmt.Println(buf.String())       
```

**Comment by ankurnigam** [comment]
Thanks Tamas 👍  It worked ,the problem was that I was having typo in the code and setting wrong ORACLE_HOME.

**Comment by cjbj** [comment]
> setting wrong ORACLE_HOME.

A general FYI for other readers: don't set ORACLE_HOME if you are using Instant Client.
