### ISSUE TITLE
Error with new API for NewConnector at v0.16.0

### ISSUE THREAD

**Issue by tredoe** [godror/godror#59]
**Describe the bug**
After of update to v016.0, I get:

```
params={{  oracle://demo:***@127.0.0.1:1521/demo0 false 0x6e6eb0 UTC} {0 0 0 0s 0s 0s false false}} extAuth=0: ORA-24415: Missing or null username.
```

**To Reproduce**
I've updated my code to use the new API, just like:

```
import (
	"database/sql"
	"github.com/godror/godror"
)

func OpenDB(dsn string) (*sql.DB) {
	fmtTimeOracle := map[string]string{
		"NLS_DATE_FORMAT": "YYYY-MM-DD",
	}

	conn := godror.NewConnector(godror.ConnectionParams{
		CommonParams: godror.CommonParams{
			DSN:    dsn,
			OnInit: godror.NewSessionIniter(fmtTimeOracle),
		},
	})

	return sql.OpenDB(conn)
}
```

**Your godror version**
v0.16.0

**Your go version**
$ go version
go version go1.14.1 linux/amd64

**Your gcc version**
$ gcc --version
gcc (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4)

**Machine (please complete the following information):**
 - OS: CentOs
 - Architecture x86_64
 - Version: 8.1

**Additional context**
Like you can see, both username and password are passed via DSN.  
I'm supposed that the issue is because it expects to get them from [CommonParams](https://pkg.go.dev/github.com/godror/godror?tab=doc#CommonParams), but they should be get them from DSN when *Username* and/or *Password* are empty at *CommonParams*.

**Comment by tgulacsi** [comment]
If you provide ConnectionParams, then make it complete.
Or start from what ParseConnString returns.

**Comment by tredoe** [comment]
Finally I used *ParseConnString*, and it's working now.  
Thanks!
