### ISSUE TITLE
Issue with DRCP: connection class is not being used (and purity cannot be set)

### ISSUE THREAD

**Issue by olivierderuelle1977** [godror/godror#6]
Hi,

Firstly, thank you for your outstanding library!

I am trying to test using an Oracle DB which has DRCP enabled. The connections are created but Oracle DB does not create them effectively - There are too many connections being created (v$cpool_cc_stats) with a cclass_name similar to DMPSSDEV.OCI:SP:**mDy9YwLLADTgUwIAEawkuB** (note the random string at the end)
instead of the connection class being specified.

I think I have identified the problem in the file drv.go line 441:

`if err := c.acquireConn("", ""); err != nil {
	return nil, err
}`

The connCreateParams variable is not passed to **acquireConn** therefore empty values are passed down to the OCI wrapper. So, the connection class is never set!
Also, the purity parameter cannot be set and in the case of DRCP the correct value should be SELF  instead of NEW otherwise the num_hits will be 0.

`// purity values when acquiring a connection from a pool
typedef uint32_t dpiPurity;
#define DPI_PURITY_DEFAULT                          0
#define DPI_PURITY_NEW                              1
#define DPI_PURITY_SELF                             2
`

drv.go line 429:

`if P.ConnClass != "" {
		cConnClass := C.CString(P.ConnClass)
		defer C.free(unsafe.Pointer(cConnClass))
		connCreateParams.connectionClass = cConnClass
		connCreateParams.connectionClassLength = C.uint32_t(len(P.ConnClass))
		**connCreateParams.purity =2**
}`

Could you please let me know if my analysis is correct? If yes, could you please provide a fix?
Thank you,

**Comment by olivierderuelle1977** [comment]
I just realized you committed a fix after our emails exchange so I will test the latest code and let you know the result shortly. Thank you very much!
BTW, it would be nice if we could set the purity argument as well.

**Comment by tgulacsi** [comment]
I've found some issues with setting connection class, so please try the current master / v0.10.0 / at least 882a273d8b27b393cbb73fff9bc9de221301fd9b .

**Comment by olivierderuelle1977** [comment]
I have successfully tested v0.10.0 with connection class and DRCP - Thank you!
