### ISSUE TITLE
Error on prepareContext function

### ISSUE THREAD

**Issue by JaegerCaiser** [godror/godror#61]
In the function prepareContext line 290

With Error:  runtime error: cgo argument has Go pointer to Go pointer

**Comment by tgulacsi** [comment]
Can you share your test case?
The embedded test cases does not fire on v0.16.1, with Go 1.14.4, even with `GODEBUG=cgocheck=2`.

**Comment by JaegerCaiser** [comment]
go version go1.12.7 linux/amd64
godor version: latest

`//Testecase

conn := user + "/" + pass + "@" + "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=tcp)(HOST=" + server + ")(PORT=" + port + ")))(CONNECT_DATA=(SERVICE_NAME=" + sid + ")))"

	paramsConn, err := godror.ParseConnString(conn)

	if err != nil {
		log.Error(err.Error())
		return
	}

	sessionMap := map[string]string{"NLS_COMP": "LINGUISTIC", "NLS_SORT": "BINARY_CI"}

	for k, v := range sessionMap {
		paramsConn.SetSessionParamOnInit(k, v)
	}

	con := godror.NewConnector(paramsConn)
	sql.OpenDB(con)`

The connection works but in time the query statement fails.

**Comment by JaegerCaiser** [comment]
I will update my go and see wath happens.

**Comment by JaegerCaiser** [comment]
Is solved, new version of drive is imcompatible with go 1.12 version. Update version of golang and worked.
