### ISSUE TITLE
retrieve data from PLSql cursor

### ISSUE THREAD

**Issue by tcastelly** [godror/godror#62]
**Describe the bug**
I have a cursor returned by PLSql function. I would want to be able loop on the cursor and retrieve data.
Instead I have this error:
`column count mismatch: we have 10 columns, but given 0 destination`

**To Reproduce**
```golang
db, err := sql.Open("godror", "api/user@localhost/DEV")
if err != nil {
  fmt.Println(err)
  panic(err)
}
defer db.Close()

ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
defer cancel()

const query = `
DECLARE
BEGIN
:cursor := pkg_api.my_func(pstr_logn_nm => 'my_name');
END;
`
stmt, err := db.PrepareContext(ctx, query)
if err != nil {
  fmt.Println(err)
  panic(err)
}

var rows driver.Rows
_, err = stmt.ExecContext(ctx, sql.Out{Dest: &rows})
if err != nil {
  fmt.Println(err)
}

var r []driver.Value
err = rows.Next(r)
if err != nil {
  fmt.Println(err) // column count mismatch: we have 10 columns, but given 0 destination
}
defer rows.Close()

fmt.Println(rows.Columns()) // [COL_1 COL_2 COL_3 COL_4 COL_5 COL_6 COL_7 COL_8 COL_9 COL_10]
```

**Your oracle client version**
x64-19.3.0.0.0

**Your godror version**
v0.16.1

**Your go version**
1.13.3

**Your gcc version**
10.1.0 (GCC) 

**Machine**
 - OS: Gnu Linux / Archlinux
 - Architecture x86_64

**Additional context**
If I try to change `driver.Rows` by `sql.Rows` I have this error:
> arg: unknown type sql.Rows

If I try to create an interface I:

```golang
type I interface {
  NM() string
}

var r []I
err = rows.Next(r)
```

I have this error: 
> cannot use r (type []I) as type []driver.Value in argument to rows.Next

I'm also new in Golang, if someone has an idea :)

Thank you very much.

**Comment by tgulacsi** [comment]
```
r := make([]driver.Value, len(rows.Columns()))
err = rows.Next(r)
if err != nil {
  fmt.Println(err) // column count mismatch: we have 10 columns, but given 0 destination
}
defer rows.Close()
```

**Comment by tgulacsi** [comment]
For example see https://github.com/UNO-SOFT/dbcsv/blob/master/csvdump/csvdump.go

**Comment by tcastelly** [comment]
It works! Thank you so much!
