### ISSUE TITLE
lob as named param: dpiStmt_execute(mode=32 arrLen=-1): ORA-22922: nonexistent LOB value

### ISSUE THREAD

**Issue by tcastelly** [godror/godror#66]
**Describe the bug**
Hello,
I'm trying to send a blob as parameter in a query.

**To Reproduce**
```golang
  if _, err := stmt.ExecContext(
    ctx,
    params...,
  ); err != nil {
    return "", err
  }
```
![image](https://user-images.githubusercontent.com/37597737/86259782-bac5ea80-bbbc-11ea-8e99-0c9b2d8a4bb5.png)

**Your oracle client version**
x64-19.3.0.0.0

**Your godror version**
v0.17.0

**Your go version**
1.14.4

**Your gcc version**
e.g. 4.8.3

**Additional context**
If I try to send with a smaller file it works.

**Comment by tgulacsi** [comment]
What is in your params ? 
The LOB should be given as a `godror.Lob{Reader: ...}` or a LOB that has been received from the DB.

**Comment by tcastelly** [comment]
In my params I have few attributes:
- `id` as int
- `name` as string
- `fl` as []byte

And finally 
> sql.Named("res", sql.Out{Dest: &res})

About the file I tried both, send a []byte (it works only with small file) and `godror.Lob{Reader}` like this:
```golang
  // file is []byte
  lob := godror.Lob{
    Reader: bytes.NewReader(file[:]),
  }
```
Now small or bigger file I have this error
```
dpiStmt_execute(mode=32 arrLen=-1): ORA-22922: nonexistent LOB value
```

**Comment by tgulacsi** [comment]
See z_test.go line 1138. in TestReadWriteLob - can you provide such a small reproducing test case?

**Comment by tcastelly** [comment]
```sql
-- Create a table with an 'id' and a 'fl' (blob) into which records can be 
-- inserted directly with an INSERT statement or using the 'tmp_blob_ins'
-- function.
CREATE TABLE tmp_blob
( id               integer
, fl               blob
)
/

CREATE OR REPLACE 
FUNCTION tmp_blob_ins        ( pnum_id           IN tmp_blob.id%TYPE
                             , plob_fl           IN tmp_blob.fl%TYPE
                             ) RETURN varchar2
IS
BEGIN
   INSERT INTO tmp_blob
          ( id
          , fl
          )
   VALUES ( pnum_id 
          , plob_fl
          );
   RETURN 'SUCCESS';
EXCEPTION
   WHEN OTHERS THEN
      RETURN 'ERROR (' || SQLERRM || ')';
END tmp_blob_ins;
/
```

My query
```
DECLARE
BEGIN
:res := tmp_blob_ins(pnum_id => 1, plob_fl => :plob_fl);
END;
```

```golang
  stmt, err := connection.connection.PrepareContext(ctx, query.ToString())
  if err != nil {
    return nil, err
  }
  defer stmt.Close()


  var res string

  var params []interface{}

  params = append(params, map[string]interface{}{
    "plob_fl": godror.Lob{
      Reader: bytes.NewReader(file),
    },
  })

  params = append(params, sql.Named("res", sql.Out{Dest: &res}))

  if _, err := stmt.ExecContext(
    ctx,
    params...,
  ); err != nil {
    return "", err
  }
```

Thank a lot for your help

**Comment by tgulacsi** [comment]
Make sure that the lob and the prepared statement is on the same session (connection), by using an sql.Conn or a transaction (sql.Tx).

**Comment by tcastelly** [comment]
Thank you very much!

By creating a transaction it works. To be honest I don't understand ... My idea was to create once a connection and share it. But this "problem" show that there are multiple connections.

```golang
  ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
  defer cancel()

  tx, err := db.BeginTx(ctx, nil)
  if err != nil {
    return "", err
  }

  stmt, err := tx.PrepareContext(ctx, query.ToString())
  if err != nil {
    return "", err
  }
  defer stmt.Close()

 var params []interface{}

  params = append(params, map[string]interface{}{
    "plob_fl": godror.Lob{
      Reader: bytes.NewReader(file),
    },
  })

  params = append(params, sql.Named("res", sql.Out{Dest: &res}))

  if _, err := stmt.ExecContext(
    ctx,
    params...,
  ); err != nil {
    return "", err
  }
```

**Comment by tgulacsi** [comment]
Go's sql.DB is a connection pool, and a prepared statement is not bound to any connection, it may re-prepare itself on execution, on a different connection.

**Comment by tcastelly** [comment]
Understood
