### ISSUE TITLE
cannot reset password for DPI backed connection pool

### ISSUE THREAD

**Issue by obno** [godror/godror#67]
**Describe the bug**
The driver keys connection pools by `{P.Username, P.DSN, P.MinSessions, P.MaxSessions, P.SessionIncrement, P.WaitTimeout, P.MaxLifeTime, P.SessionTimeout, P.Heterogeneous, P.EnableEvents, P.ExternalAuth}`. I cannot see any way to re-initialize a pool if the user password changes. 

In my use case, I have an HTTP2-fonted gateway for executing SQL commands to various databases which makes it impractical to restart it whenever user credentials change. 

**To Reproduce**
1. create test user
2. open pool for user
3. ping
4. change user password
5. close pool
6. open pool with new password
7. ping fails

```golang
func TestDPIPools(t *testing.T) {

	// godror.Log = func(args ...interface{}) error {
	// 	lbuilder := &strings.Builder{}
	// 	for i, arg := range args {
	// 		if i > 0 {
	// 			lbuilder.WriteString("; ")
	// 		}
	// 		lbuilder.WriteString(fmt.Sprintf("%s", arg))
	// 	}
	// 	fmt.Println(lbuilder.String())
	// 	return nil
	// }

	sysPool, err := sql.Open("godror", "oracle://system:test123@192.168.200.61:1521/ORCL?poolMinSessions=0&poolMaxSessions=0&standaloneConnection=0")
	if err != nil {
		t.Error(err)
		return
	}
	sysPool.SetMaxIdleConns(0)
	sysPool.SetMaxOpenConns(0)
	defer sysPool.Close()
	if _, err := sysPool.Exec(`alter user c##test identified by "test123" container=all`); err != nil {
		t.Error(err)
		return
	}

	testPool, err := sql.Open("godror", "oracle://c%23%23test:test123@192.168.200.61:1521/ORCL?poolMinSessions=0&poolMaxSessions=0&poolSessionMaxLifetime=1s&poolSessionTimeout=1s&standaloneConnection=0")
	if err != nil {
		t.Error(err)
		return
	}
	defer testPool.Close()
	testPool.SetMaxIdleConns(0)
	testPool.SetMaxOpenConns(0)

	if err = testPool.Ping(); err != nil {
		t.Error(err)
		return
	}
	sessions, err := sysPool.Query(`select count(*) from v$session where username='C##TEST'`)
	if err != nil {
		t.Error(err)
		return
	}
	for sessions.Next() {
		var (
			count int
		)
		if err := sessions.Scan(&count); err != nil {
			t.Error(err)
			return
		}
		fmt.Println(fmt.Sprintf("c##test sessions: %d", count))
	}
	sessions.Close()

	if _, err := sysPool.Exec(`alter user c##test identified by "test1234" container=all`); err != nil {
		t.Error(err)
		return
	}
	testPool.Close()
	<-time.After(2 * time.Second)
	if testPool, err = sql.Open("godror", "oracle://c%23%23test:test1234@192.168.200.61:1521/ORCL?poolMinSessions=0&poolMaxSessions=0&poolSessionMaxLifetime=1s&poolSessionTimeout=1s&standaloneConnection=0"); err != nil {
		t.Error(err)
	}
	testPool.SetMaxIdleConns(0)
	testPool.SetMaxOpenConns(0)

        // THIS FAILS
	if err = testPool.Ping(); err != nil {
		t.Error(err)
	}
	testPool.Close()

}
```

**Expected behavior**
Should have some means to reset a DPI connection pool with similar semantics to `sql.DB.Close()`

**Screenshots**

**Your oracle client version**
19

**Your godror version**
v0.17.0

**Your go version**
1.14

**Your gcc version**
9.3

**Machine (please complete the following information):**
 - OS: linux
 - Architecture 86_64
 - Version:  Ubuntu 20.04 LTS

**Additional context**

**Comment by sudarshan12s** [comment]
Hi,
Does heterogeneous pool work for you.  you need not close the DB but update
the context with an updated password.

	if testPool, err = sql.Open("godror",
"oracle://c%23%23test:test1234@192.168.200.61:1521/ORCL?poolMinSessions=0&poolMaxSessions=0&poolSessionMaxLifetime=1s&poolSessionTimeout=1s&standaloneConnection=0&heterogeneousPool=1");
err != nil {

// update password to test1234

ctx = godror.ContextWithUserPassw(ctx, "ctest", "test1234", "")

db.PingContext(ctx) or db.QueryRowContext(ctx,query)


The old connections with old password will eventually be terminated to
accomodate subsequent new session requests.

Thanks

**Comment by obno** [comment]
@sudarshan12s - this works for me. Thanks for pointing it out.
