### ISSUE TITLE
Heterogeneous Pools are broken in v0.10.0

### ISSUE THREAD

**Issue by wwanderley** [godror/godror#7]
Heterogeneous Pools are broken in v1.10.0

**To Reproduce**

1. go test -v -count=1 -run TestHeterogeneousPoolIntegration
2. The test is blocked on 
    === RUN   TestHeterogeneousPoolIntegration/proxyUser

**Expected behavior**
Test pass

**Your oracle client version**
e.g. 18c-xe

**Your godror version**
e.g. v0.10.0

**Your go version**
e.g. 1.13.3

**Your gcc version**
e.g. 7.0.0

**Machine (please complete the following information):**
 - OS: Ubuntu
 - Architecture x86_64
 - Version: 18

**Comment by tgulacsi** [comment]
I've found the double lock, and fixed it in d1d68ad. Can you test, too?

**Comment by wwanderley** [comment]
Wow! That was fast.

https://github.com/godror/godror/commit/d1d68ad7cd911b656a695444a750815c1bcbb5f7 solved my problem.

Thank you
