### ISSUE TITLE
Are there any tutorials?

### ISSUE THREAD

**Issue by maverickVision** [godror/godror#71]
I'm sorry for creating this request here, but I searched all over the internet and couldn't find any beginner resources to godror. I've been able to install and make a simple `db.Query("select sysdate from dual")` request, but I don't know what to do from here. How can I create select statements or call stored procedures? I have to validate Go for an Oracle project and I really liked it, but I've found too few resources about it. Can anyone please point me some material, so I can read and try to figure out how to make godror work for real?

**Comment by tgulacsi** [comment]
This is just a Go database/sql driver for Oracle DB. So you need to know database/sql (pooling, transactions, contexts) and more about Oracle databases. I think node-oracle and cx_Oracle has more detailed docs (https://cx-oracle.readthedocs.io/en/latest/user_guide/plsql_execution.html), but I don't know about a tutorial.

What do you mean by "select statements" - db.QueryContext(ctx, "SELECT * FROM all_tables") ?
For  "*", you'll need to prepare an []interace{} slice with a proper size to `rows.Scan()` into  - for example with `make([]interface{}, len(rows.Columns()))`. See https://github.com/UNO-SOFT/dbcsv/csvdump for an example.

For stored procedures, you call them just as with other languages: 

    var rc int
     _, err := db.ExecContext(ctx, "BEGIN :1 := proc(:2, :3); END;", sql.Out{Dest: &rc}, "a", time.Now())

https://github.com/tgulacsi/oracall is a special project that generates gRPC server for stored procedures.

**Comment by cjbj** [comment]
@tgulacsi I don't know whether you consider https://static.rainfocus.com/oracle/oow19/sess/1567058525476001cK8G/PF/DEV6708-Using-the-Go-Language-for-Efficient-Oracle-Database-Applications_1568841171132001jI7d.pdf useful.

What's the simplest way to give you any doc content and tips - README PRs?

**Comment by tgulacsi** [comment]
Seems Just What The Doctor Ordered :)

Yes, PR is the easiest.

**Comment by maverickVision** [comment]
Thank you @tgulacsi and @cjbj, that's what I needed to continue studying. I'm pretty new to Go, and appreciate this help!

**Comment by tgulacsi** [comment]
@cjbj and @sudarshan12s presented some nice documentation revamps,
please check the current master!
