### ISSUE TITLE
*sql.Stmt.Query() hangs when connecting to an Oracle RDS instance from a docker container 

### ISSUE THREAD

**Issue by patilpankaj212** [godror/godror#73]
**Describe the bug**
When executing a prepared statement on an Oracle RDS instance from a docker container, I observed that it never completes. This issue is observed v0.15.0 and later (verified with v0.17.0 as well). Issue is not reproducible with v0.14.0.

**To Reproduce**
Below is a sample code that I am running in a docker container (base image: golang:1.14.1 "https://hub.docker.com/_/golang")

`package main

import (
	"fmt"
	"database/sql"
	_ "github.com/godror/godror"
)

func main() {
	user := "user"
	pass := "pass"
	host := "rdsinstnace"
	sid := "sid"
	loginInfo := fmt.Sprintf("%s/%s@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=%s)(PORT=%v))(CONNECT_DATA=(SID=%s)))", user, pass, host, "1521", sid)
	db, err := sql.Open("godror", loginInfo)
	// db.SetMaxIdleConns(0)

	if err != nil {
		fmt.Println("OracleDatabase Connection Failed due to error - ", err.Error())
	}

	err = db.Ping()
	if err != nil {
		fmt.Println("Failed to connect to Oracle Database due to error - ", err.Error())
	}

	insertTest(db, "insert into atable values ('test')")
}

func insertTest(db *sql.DB, query string) {
	stmt, err := db.Prepare(query)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("stmt query starting")
        //below doesn't execute successfully for RDS instance
	stmt.Query()
	fmt.Println("stmt query completed")
}
`

This sample code runs fine when connecting to an on premise db on same environment. Could you please let me know the probable reason for this issue?

**Expected behavior**
Query should execute successfully.

**Screenshots**
none

**Your oracle client version**
19.6.0

**Your godror version**
v0.15.0 (also tried with v0.17.0)

**Your go version**
go1.14.1 linux/amd64

**Your gcc version**
gcc version 8.3.0 (Debian 8.3.0-6)

**Machine (please complete the following information):**
 - linux(debian based) - 4.19.76-linuxkit
 - x86_64

**Additional context**

**Comment by tgulacsi** [comment]
Sorry, I don't know what Oracle RDS is or how to test one, so it's up to you.

Stat by using Go 1.14.6 and godror v0.17.1,
run with ODPI_DEBUG_LEVEL=92 and setting godror.Log to something that prints.

**Comment by patilpankaj212** [comment]
Sorry for the confusion @tgulacsi. I am connecting to a Amazon RDS for Oracle (https://aws.amazon.com/rds/oracle/).

Unfortunately the choice of go version is not up to me.

I will try out with v0.17.1

Thanks.

**Comment by tgulacsi** [comment]
If you cannot use Go 1.14.6, then either use `standaloneConnection=1` or disable Go connection pooling with `db.SetMaxIdleConns(0)` !

**Comment by patilpankaj212** [comment]
@tgulacsi existing code with godror v0.17.1 resolves the issue.

Also, with v.0.17.0, db.SetMaxIdleConns(0) resolves the issue.

Was there any fix made in v0.17.1 around this?

Just curious about the root cause of this issue. (because I observed this issue with AWS RDS instance only.)

**Comment by tgulacsi** [comment]
This should be #69 - interesting mix of locking error with caching error of DB timezone set to UTC.
