### ISSUE TITLE
OnInit function doesn't get invoked properly on DB switchover scenario

### ISSUE THREAD

**Issue by rjtsdl** [godror/godror#79]
**Describe the bug**
During a DB switchover event (the primary db will be changing), the CURRENT_SCHEMA which is set using `onInit` function is missing. Then with a working application, all of a sudden, you will see error like
```
dpiStmt_execute: ORA-00942: table or view does not exist
```

**To Reproduce**

The issue doesn't happen on a 100% repro scenario. From my observation, it happens 3 out of 20. We had 20 switchover activities, 3 of them manifest the above issue.

1. have a working application setup, and constant query to the database. 
2. the database is configured with primary and failover instances. AKA, the connection string has more than 1 database instance
3. do the switchover, by restart the primary db instance
4. watching the log for the query, the above error is likely to show up, if not, repeat 3 again.

**Expected behavior**
I expect no error during a switchover at all.

**Screenshots**

**Your oracle client version**
TBD

**Your godror version**
gopkg.in/goracle.v2 v2.16.3

**Your go version**
1.12.0

**Your gcc version**
TBD

**Machine (please complete the following information):**
 - OS: linux
 - Architecture x86_64
 - Version: TBD

**Additional context**

**Comment by tgulacsi** [comment]
What version of _godror_ are you using? 
'Cause you wrote "goracle v2.16.3"... Have you meant godror v0.16.3 ?

Can you try the current master? (`go get github.com/godror/godror@master`)

Can you help me how to test this? What is the test environment, how to do a switch?

Currently, OnInit is called when connCreateParams.outNewSession==1 in acquireConn in drv.go.
For testing, can you check out github.com/godror/godror, add some logging of connCreateParams.outNewSession and calling of OnInit (for example into getOnInit), `go mod edit -replace=github.com/godror/godror=$HOME/src/github.com/godror/godror`, and share the findings with us?
