### ISSUE TITLE
Cross compiling fails for 32bit architectures

### ISSUE THREAD

**Issue by Tommi2Day** [godror/godror#8]
**Describe the bug**
compiling for 32 bit architectures fails with folling error:
`# github.com/godror/godror
..\github.com\godror\godror\conn.go:380:13: type [214748363]_Ctype_struct_dpiData larger than address space
..\github.com\godror\godror\conn.go:380:13: type [214748363]_Ctype_struct_dpiData too large
..\github.com\godror\godror\rows.go:292:19: type [214748363]_Ctype_struct_dpiData larger than address space
..\github.com\godror\godror\rows.go:292:19: type [214748363]_Ctype_struct_dpiData too large
..\github.com\godror\godror\stmt.go:410:22: type [214748363]_Ctype_struct_dpiData larger than address space
..\github.com\godror\godror\stmt.go:410:22: type [214748363]_Ctype_struct_dpiData too large
..\github.com\godror\godror\subscr.go:49:16: type [214748363]_Ctype_struct_dpiSubscrMessageRow too large
..\github.com\godror\godror\subscr.go:63:17: type [214748363]_Ctype_struct_dpiSubscrMessageTable too large
..\github.com\godror\godror\subscr.go:78:17: type [214748363]_Ctype_struct_dpiSubscrMessageQuery larger than address space
..\github.com\godror\godror\subscr.go:78:17: type [214748363]_Ctype_struct_dpiSubscrMessageQuery too large
..\github.com\godror\godror\subscr.go:78:17: too many errors
`

**To Reproduce**
compile your demo program in an 32bit environment, in Windows10 using msys2
1. pacman -S mingw-w64-i686-toolchain
2. install 32bit go:  pacman -S mingw-w64-i686-go
3. in mingw32 environment go to your source: cd /e/Daten/go/src/oracletest
4. start build: go build 

**Expected behavior**
proper compiling

**Your oracle client version**
12.2.0.1.0

**Your godror version**
v0.10.2

**Your go version**
go version go1.13.5 windows/386

**Machine (please complete the following information):**
 - OS: Windows10 mit mingw32  
 - Architecture [64bit mit 32bit Wrapper]

**gcc version**
gcc -v
Using built-in specs.
COLLECT_GCC=E:\msys64\mingw32\bin\gcc.exe
COLLECT_LTO_WRAPPER=E:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/9.2.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../gcc-9.2.0/configure --prefix=/mingw32 --with-local-prefix=/mingw32/local --build=i686-w64-mingw32 --host=i686-w64-mingw32 --target=i686-w64-mingw32 --with-native-system-header-dir=/mingw32/i686-w64-mingw32/include --libexecdir=/mingw32/lib --enable-bootstrap --with-arch=i686 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --enable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw32 --with-mpfr=/mingw32 --with-mpc=/mingw32 --with-isl=/mingw32 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld --disable-sjlj-exceptions --with-dwarf2
Thread model: posix
gcc version 9.2.0 (Rev2, Built by MSYS2 project)

**Additional context**
None

**Comment by tgulacsi** [comment]
Please tweak line 36 of conn.go (maxArraySize) till it compiles && works.
My gut feeleing is that 1<<31 or 1<<30 should work (instead of 1<<32).

**Comment by Tommi2Day** [comment]
1<<31 reduced the error count, but there was remaining errors.
`# github.com/godror/godror
..\github.com\godror\godror\conn.go:380:13: type [107374181]_Ctype_struct_dpiData too large
..\github.com\godror\godror\rows.go:292:19: type [107374181]_Ctype_struct_dpiData too large
..\github.com\godror\godror\stmt.go:410:22: type [107374181]_Ctype_struct_dpiData too large
..\github.com\godror\godror\subscr.go:78:17: type [107374181]_Ctype_struct_dpiSubscrMessageQuery too large
`
with 1<<30 build was successfully.
Thanks!
