### ISSUE TITLE
EZ Connect parsing broke in 24cf984

### ISSUE THREAD

**Issue by cjbj** [godror/godror#81]
https://github.com/godror/godror/commit/24cf984c4c8efd047165dda361d693c3c408f603 broke basic connection.  The connect string is showing empty:

```  
      db, err := sql.Open("godror", `user="cj" password="cj"
                                       connectString="localhost/orclpdb1"
                                       libDir="/Users/cjones/instantclient_19_3"`)
```
gives:

```
2020/08/07 12:28:44 params=user=cj password="SECRET-CDJlB7TrNB4=" connectString= libDir=/Users/cjones/instantclient_19_3
timezone=local poolIncrement=1 poolMaxSessions=1000 poolMinSessions=1 poolSessionMaxLifetime=1h0m0s
poolSessionTimeout=5m0s poolWaitTimeout=30s extAuth=0: ORA-12162: TNS:net service name is incorrectly specified
```

**Comment by cjbj** [comment]
This is still not working

**Comment by tgulacsi** [comment]
What does `go test ./dsn` say?

If it passes, please add the failing test case.

**Comment by cjbj** [comment]
I get:
```
cjones@localhost:~/go/src/github.com/godror/godror$ echo $(git log --pretty=format:'%h ' -n 1)
ac04606
cjones@localhost:~/go/src/github.com/godror/godror$ go test ./dsn
--- FAIL: TestParse (0.00s)
    --- FAIL: TestParse/logfmt (0.00s)
        dsn_test.go:213: user=user password=pass connectString=localhost/sid heterogeneousPool=1
        dsn_test.go:220: parse of "user=user password=pass connectString=localhost/sid heterogeneousPool=1"
            got
            	dsn.ConnectionParams{CommonParams:dsn.CommonParams{Username:"user", ConnectString:"", Password:dsn.Password{secret:"pass"}, ConfigDir:"", LibDir:"", OnInit:(func(driver.Conn) error)(nil), OnInitStmts:[]string(nil), AlterSession:[][2]string(nil), Timezone:(*time.Location)(0x732ce0), EnableEvents:false}, ConnParams:dsn.ConnParams{NewPassword:dsn.Password{secret:""}, ConnClass:"", IsSysDBA:false, IsSysOper:false, IsSysASM:false, IsPrelim:false, ShardingKey:[]interface {}(nil), SuperShardingKey:[]interface {}(nil)}, PoolParams:dsn.PoolParams{MinSessions:1, MaxSessions:1000, SessionIncrement:1, WaitTimeout:30000000000, MaxLifeTime:3600000000000, SessionTimeout:300000000000, Heterogeneous:true, ExternalAuth:false}, NewPassword:dsn.Password{secret:""}, StandaloneConnection:false},
            wanted
            	dsn.ConnectionParams{CommonParams:dsn.CommonParams{Username:"user", ConnectString:"localhost/Sid", Password:dsn.Password{secret:"pass"}, ConfigDir:"", LibDir:"", OnInit:(func(driver.Conn) error)(nil), OnInitStmts:[]string(nil), AlterSession:[][2]string(nil), Timezone:(*time.Location)(0x732ce0), EnableEvents:false}, ConnParams:dsn.ConnParams{NewPassword:dsn.Password{secret:""}, ConnClass:"", IsSysDBA:false, IsSysOper:false, IsSysASM:false, IsPrelim:false, ShardingKey:[]interface {}(nil), SuperShardingKey:[]interface {}(nil)}, PoolParams:dsn.PoolParams{MinSessions:1, MaxSessions:1000, SessionIncrement:1, WaitTimeout:30000000000, MaxLifeTime:3600000000000, SessionTimeout:300000000000, Heterogeneous:true, ExternalAuth:false}, NewPassword:dsn.Password{secret:""}, StandaloneConnection:false}

. . .
````

See https://gist.github.com/cjbj/75c97fed20b052c0515a1439f4f95c2d for full log

**Comment by sudarshan12s** [comment]
looks like connectString is not set, in line 352, dsn.go, right?

 case "connectString":
347                     //fmt.Printf("connectString=%q\n", value)

348                     var user, passw string
349                     if user, passw, P.ConnectString =
parseUserPassw(value);     P.Username == "" && P.Password.IsZero() {
350                         P.Username, P.Password.secret = user, passw
351                     }
+                   P.ConnectString = <value>

**Comment by tgulacsi** [comment]
It is, on line 349.

**Comment by tgulacsi** [comment]
Ok, I've changed the previous behaviour, because it did not accept "user/pass", without service name.
But how to distinguish "user/pass" vs. "localhost/sid" ?

**Comment by tgulacsi** [comment]
What about f76e8f0 ? Can you test it?

**Comment by sudarshan12s** [comment]
Thanks Tamas.

I tested these 2 cases , work fine.

db, err := sql.Open("godror", `user="scott" password="tiger"
connectString="ip1521/demo.oracle.com"`)
    db, err := sql.Open("godror", `connectString="scott/tiger@ip:1521/
demo.oracle.com"`)

**Comment by tgulacsi** [comment]
The more I think about it, the more I convince myself that the logic if splitting the username/password from the connectString is unsolvable at this level, and for the new (logfmt) formatted dataSourceName we should require username= and password= to be specified separately.
And only keep the splitting for the old format.

@cjbj, @anthony-tuininga what do you think?

**Comment by cjbj** [comment]
Seems fair to me. You will want username & password to be optional so that external authentication can be used.

**Comment by cjbj** [comment]
@tgulacsi Does a test need updating? I still get a test failure with 352b0b9:

--- FAIL: TestParse (0.00s)
    --- FAIL: TestParse/logfmt_oldpw (0.00s)
        dsn_test.go:213: connectString=user/pass@localhost/sid heterogeneousPool=1
        dsn_test.go:220: parse of "connectString=user/pass@localhost/sid heterogeneousPool=1"
            got
            	dsn.ConnectionParams{CommonParams:dsn.CommonParams{Username:"", ConnectString:"user/pass@localhost/sid", Password:dsn.Password{secret:""}, ConfigDir:"", LibDir:"", OnInit:(func(driver.Conn) error)(nil), OnInitStmts:[]string(nil), AlterSession:[][2]string(nil), Timezone:(*time.Location)(0x733d00), EnableEvents:false}, ConnParams:dsn.ConnParams{NewPassword:dsn.Password{secret:""}, ConnClass:"", IsSysDBA:false, IsSysOper:false, IsSysASM:false, IsPrelim:false, ShardingKey:[]interface {}(nil), SuperShardingKey:[]interface {}(nil)}, PoolParams:dsn.PoolParams{MinSessions:1, MaxSessions:1000, SessionIncrement:1, WaitTimeout:30000000000, MaxLifeTime:3600000000000, SessionTimeout:300000000000, Heterogeneous:true, ExternalAuth:false}, NewPassword:dsn.Password{secret:""}, StandaloneConnection:false},
            wanted
            	dsn.ConnectionParams{CommonParams:dsn.CommonParams{Username:"user", ConnectString:"localhost/sid", Password:dsn.Password{secret:"pass"}, ConfigDir:"", LibDir:"", OnInit:(func(driver.Conn) error)(nil), OnInitStmts:[]string(nil), AlterSession:[][2]string(nil), Timezone:(*time.Location)(0x733d00), EnableEvents:false}, ConnParams:dsn.ConnParams{NewPassword:dsn.Password{secret:""}, ConnClass:"", IsSysDBA:false, IsSysOper:false, IsSysASM:false, IsPrelim:false, ShardingKey:[]interface {}(nil), SuperShardingKey:[]interface {}(nil)}, PoolParams:dsn.PoolParams{MinSessions:1, MaxSessions:1000, SessionIncrement:1, WaitTimeout:30000000000, MaxLifeTime:3600000000000, SessionTimeout:300000000000, Heterogeneous:true, ExternalAuth:false}, NewPassword:dsn.Password{secret:""}, StandaloneConnection:false}
              dsn.ConnectionParams{
              	CommonParams: dsn.CommonParams{
            - 		Username:      "user",
            + 		Username:      "",
            - 		ConnectString: "localhost/sid",
            + 		ConnectString: "user/pass@localhost/sid",
            - 		Password:      s"SECRET-rO3TfrHuUhY=",
            + 		Password:      s"",
              		ConfigDir:     "",
              		LibDir:        "",
              		... // 5 identical fields
              	},
              	ConnParams: dsn.ConnParams{},
              	PoolParams: dsn.PoolParams{MinSessions: 1, MaxSessions: 1000, SessionIncrement: 1, WaitTimeout: s"30s", MaxLifeTime: s"1h0m0s", SessionTimeout: s"5m0s", Heterogeneous: true},
              	... // 2 identical fields
              }
FAIL
FAIL	github.com/godror/godror/dsn	0.003s
FAIL

**Comment by tgulacsi** [comment]
Removed it, thanks.

**Comment by cjbj** [comment]
```
$  go test ./dsn

ok  	github.com/godror/godror/dsn	0.004s
```
