### ISSUE TITLE
Not Support Rowid 

### ISSUE THREAD

**Issue by travelliu** [godror/godror#83]
**Describe the bug**
select ccess column with rowid field type, return data is empty

**To Reproduce**
```
create table t1 (
        COL_RAW RAW(20),
        COL_ROWID ROWID
);

insert
    INTO t1 (
        col_raw,
        col_rowid
    )
SELECT
    hextoraw('aaaa') AS col_raw,
    ROWID AS col_rowid
FROM
    dual
CONNECT BY
    ROWNUM <= 10;

commit;
```

```
rows ,err := db.Query("select COL_RAW,COL_ROWID from t1")
if err != nil {
        t.Error(err)
}
for rows.Next() {
        var rowid,raw []byte
        err := rows.Scan(&raw,&rowid)
        if err != nil {
                return
        }
        fmt.Printf("%X %X\n",raw,rowid)
}
```
**Screenshots**
![image](https://user-images.githubusercontent.com/7792329/89747538-c7a9f800-daf1-11ea-958e-6d5dcd046988.png)

**Your oracle client version**
11.2.0.3.0

**Your godror version**
v0.19.0

**Your go version**
1.13.0

**Your gcc version**
Apple clang version 11.0.3 (clang-1103.0.32.62)

**Machine (please complete the following information):**
 - OS: MacOS
 - Architecture:
 - Version: 10.15

**Additional context**

**Comment by tgulacsi** [comment]
Convert it to string (''||ROWID) as a workaround.

**Comment by travelliu** [comment]
v0.19.1 not Contain this issue?

**Comment by tgulacsi** [comment]
No, it does not. And the current master is only for SELECTs, at the moment.
Do you want to use the retrieved rowid as a parameter to an sql statement or query?
That may require a special type, to differentiate between a []byte and a ROWID.
________________________________

**Comment by travelliu** [comment]
not use special type. rowid is string. like raw. 
select * from t1 where rowid='AAAYq2AAEAACosrAAA'
update t1 set COL_ROWID='AAAYq2AAEAACosvAAI';

**Comment by tgulacsi** [comment]
Neither RAW, not ROWID is a string :)
Both are byte slices, ROWID is 10 bytes.

The string format is the encoded variant, which is transparently converted by Oracle DB.

But OK, so the string format is enough.
I'll try that.
