### ISSUE TITLE
DPI-1072: the Oracle Client library version is unsupported

### ISSUE THREAD

**Issue by 5k3105** [godror/godror#9]
**Your oracle client version**
tried instaclient oci.dll 11_2, 12_2, 18_5, 19_5

windows 10
godror version 0.10.4 (master)
go version go1.13.5 windows/amd64
gcc (Rev2, Built by MSYS2 project) 9.2.0

```
func init() {
	var err error
	db, err = sql.Open("godror", dbhost)
	if err != nil {
		panic("open: " + err.Error())
	}
	err = db.Ping()
	if err != nil {
		panic("ping: " + err.Error())
	}
}
```

**Comment by tgulacsi** [comment]
Maybe you have another oci.dll somewhere in your PATH?

 See https://github.com/oracle/python-cx_Oracle/issues/384 and https://oracle.github.io/odpi/doc/installation.html

**Comment by 5k3105** [comment]
> which oci.dll
/c/Go/bin/oci.dll

**Comment by tgulacsi** [comment]
which is not part of Windows.
Please check on Windows side, or compile on Linux side (I suspect you use WSL).

**Comment by 5k3105** [comment]
I am not using WSL, I am using msys2. There is an mtxoci.dll in windows/syswow64

**Comment by tgulacsi** [comment]
Please uninstall any oracle client (mtxoci.dll is part of it: https://docs.oracle.com/health-sciences/cis/installation-guide/index.htm?toc.htm?213990.htm), then INSTALL an Oracle Instant Client, and then try again.

**Comment by 5k3105** [comment]
Ok - it needs more than the oci.dll, so adding the instaclient folder to the path ```C:\oracle\instantclient_19_5``` allowed it to run. Sorry :D Thank you!
