### ISSUE TITLE
Crush with alpine 3.12.0

### ISSUE THREAD

**Issue by mingxuechao** [godror/godror#96]
Crush with the list code in alpine 3.12.0
--------------------------------
package main

```
import (
	"database/sql"
	"fmt"
	"log"
	"net/url"
	"os"
	"os/signal"
	"syscall"
	"time"

	_ "github.com/godror/godror"
)

func CheckConnection() error {
	time.Sleep(5 * time.Second)
	host := "172.24.105.43"
	user := "m"
	sqlpassword := "m"
	port := "1521"
	dbname := "nsdc"
	var conn string

	//conn = fmt.Sprintf("oracle://%s:%s@%s:%s/%s?standaloneConnection=true", user, sqlpassword, host, port, dbname)
	conn = fmt.Sprintf("oracle://%s:%s@%s:%s/%s?standaloneConnection=true", url.QueryEscape(user), url.QueryEscape(sqlpassword), host, port, dbname)

	fmt.Println(conn)
	db, err := sql.Open("godror", conn)
	if err != nil {
		log.Printf("CheckConnection Opendb fail. err:[%v]", err)
		return fmt.Errorf("AUTHERROR")
	}
	defer db.Close()
	err = db.Ping()

	if err != nil {
		log.Printf("Ping fail. err:[%v]", err)
		return err
	}
	log.Println("Success")
	return nil
}

func main() {
	CheckConnection()
	c := MakeShutdownCh()
	<-c
	fmt.Println("quit!")
}

func MakeShutdownCh() chan struct{} {
	resultCh := make(chan struct{})

	shutdownCh := make(chan os.Signal)
	signal.Notify(shutdownCh)
	go func() {

		for s := range shutdownCh {
			switch s {
			case syscall.SIGINT, syscall.SIGTERM, syscall.SIGHUP, syscall.SIGQUIT:
				fmt.Println("got signal and try to exit: ", s)
				close(resultCh)
			case syscall.SIGUSR1:
				fmt.Println("usr1: ", s)
			case syscall.SIGUSR2:
				fmt.Println("usr2: ", s)
			default:
				fmt.Println("other: ", s)
			}
		}
	}()

	return resultCh
}
```
--------------------------------

**Your godror version**
latest

**Your go version**
1.14.6

**Your gcc version**
gcc version 9.3.0 (Alpine 9.3.0)

**Machine (please complete the following information):**
 - OS: alpine 
 - Architecture x86_64
 - Version: 3.12.0

**Comment by tgulacsi** [comment]
Sorry, but what is the error?
What does it print on crash?

**Comment by mingxuechao** [comment]
@tgulacsi 

runtime: unexpected return pc for runtime.sigpanic called from 0x0
stack: frame={sp:0xc0000345e8, fp:0xc000034618} stack=[0xc000034000,0xc000034800)
000000c0000344e8:  000000000043ccfb <runtime.addOneOpenDeferFrame+123>  000000c0000344f8 
000000c0000344f8:  00000000004696f0 <runtime.addOneOpenDeferFrame.func1+0>  000000000045325a <runtime.sigpanic+986> 
000000c000034508:  000000c0000345e8  000000c000186600 
000000c000034518:  0000000000000000  000000c0000345d8 
000000c000034528:  000000000043d38c <runtime.gopanic+252> other:  urgent I/O condition
 000000c000186600 
000000c000034538:  000000000045325a <runtime.sigpanic+986>  000000c0000345e8 
000000c000034548:  0000000000000000  0000000000000000 
000000c000034558:  0000000000000000  000000c000034590 
000000c000034568:  0000000000418d78 <runtime.newobject+56>  0000000000000060 
000000c000034578:  0000000000589580  000000c000186600 
000000c000034588:  000000c0000b4240  00000a8446505853 
000000c000034598:  00000000000000ff  0000000000000000 
000000c0000345a8:  000000000056a8e0  00000000006a7b70 
000000c0000345b8:  0000000000000000  0000000000000000 
000000c0000345c8:  0000000000000000  0000000000000000 
000000c0000345d8:  000000c000034608  000000000045325a <runtime.sigpanic+986> 
000000c0000345e8: <000000000056a8e0  00000000006a7b70 
000000c0000345f8:  0000000000000000  0000000000000000 
000000c000034608:  0000000000000000 !0000000000000000 
000000c000034618: >0000000000000000  0000000000000000 
000000c000034628:  0000000000000000  0000000000000000 
000000c000034638:  0000000000000000  0000000000000000 
000000c000034648:  0000000000000000  0000000000000000 
000000c000034658:  0000000000000000  0000000000000000 
000000c000034668:  0000000000000000  0000000000000000 
000000c000034678:  0000000000000000  0000000000000000 
000000c000034688:  0000000000000000  0000000000000000 
000000c000034698:  0000000000000000  0000000000000000 
000000c0000346a8:  0000000000000000  0000000000000000 
000000c0000346b8:  0000000000000000  0000000000000000 
000000c0000346c8:  0000000000000000  0000000000000000 
000000c0000346d8:  0000000000000000  0000000000000000 
000000c0000346e8:  0000000000000000  0000000000000000 
000000c0000346f8:  0000000000000000  000000000055e5e0 
000000c000034708:  0000000000000000  000000c00008e240 
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x5988b9, 0x11)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.gentraceback(0x45325a, 0xc0000345e8, 0x0, 0xc000186600, 0x0, 0x0, 0x7fffffff, 0x2ae8a665ca00, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:273 +0x19fb
runtime.addOneOpenDeferFrame.func1()
	/usr/local/go/src/runtime/panic.go:721 +0x91
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1041

goroutine 34 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0000344f0 sp=0xc0000344e8 pc=0x46b020
runtime.addOneOpenDeferFrame(0xc000186600, 0x45325a, 0xc0000345e8)
	/usr/local/go/src/runtime/panic.go:720 +0x7b fp=0xc000034530 sp=0xc0000344f0 pc=0x43ccfb
panic(0x56a8e0, 0x6a7b70)
	/usr/local/go/src/runtime/panic.go:929 +0xfc fp=0xc0000345e8 sp=0xc000034530 pc=0x43d38c
runtime: unexpected return pc for runtime.sigpanic called from 0x0
stack: frame={sp:0xc0000345e8, fp:0xc000034618} stack=[0xc000034000,0xc000034800)
000000c0000344e8:  000000000043ccfb <runtime.addOneOpenDeferFrame+123>  000000c0000344f8 
000000c0000344f8:  00000000004696f0 <runtime.addOneOpenDeferFrame.func1+0>  000000000045325a <runtime.sigpanic+986> 
000000c000034508:  000000c0000345e8  000000c000186600 
000000c000034518:  0000000000000000  000000c0000345d8 
000000c000034528:  000000000043d38c <runtime.gopanic+252>  000000c000186600 
000000c000034538:  000000000045325a <runtime.sigpanic+986>  000000c0000345e8 
000000c000034548:  0000000000000000  0000000000000000 
000000c000034558:  0000000000000000  000000c000034590 
000000c000034568:  0000000000418d78 <runtime.newobject+56>  0000000000000060 
000000c000034578:  0000000000589580  000000c000186600 
000000c000034588:  000000c0000b4240  00000a8446505853 
000000c000034598:  00000000000000ff  0000000000000000 
000000c0000345a8:  000000000056a8e0  00000000006a7b70 
000000c0000345b8:  0000000000000000  0000000000000000 
000000c0000345c8:  0000000000000000  0000000000000000 
000000c0000345d8:  000000c000034608  000000000045325a <runtime.sigpanic+986> 
000000c0000345e8: <000000000056a8e0  00000000006a7b70 
000000c0000345f8:  0000000000000000  0000000000000000 
000000c000034608:  0000000000000000 !0000000000000000 
000000c000034618: >0000000000000000  0000000000000000 
000000c000034628:  0000000000000000  0000000000000000 
000000c000034638:  0000000000000000  0000000000000000 
000000c000034648:  0000000000000000  0000000000000000 
000000c000034658:  0000000000000000  0000000000000000 
000000c000034668:  0000000000000000  0000000000000000 
000000c000034678:  0000000000000000  0000000000000000 
000000c000034688:  0000000000000000  0000000000000000 
000000c000034698:  0000000000000000  0000000000000000 
000000c0000346a8:  0000000000000000  0000000000000000 
000000c0000346b8:  0000000000000000  0000000000000000 
000000c0000346c8:  0000000000000000  0000000000000000 
000000c0000346d8:  0000000000000000  0000000000000000 
000000c0000346e8:  0000000000000000  0000000000000000 
000000c0000346f8:  0000000000000000  000000000055e5e0 
000000c000034708:  0000000000000000  000000c00008e240 
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:212
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:695 +0x3da fp=0xc000034618 sp=0xc0000345e8 pc=0x45325a
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:742 +0x12a

goroutine 1 [chan receive]:
main.main()
	/root/mxc/test.go:54 +0x4c

goroutine 20 [syscall]:
os/signal.signal_recv(0x5c8940)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	/usr/local/go/src/os/signal/signal.go:127 +0x44

goroutine 5 [chan receive]:
main.MakeShutdownCh.func1(0xc0000b4120, 0xc00008e0c0)
	/root/mxc/test.go:65 +0x52
created by main.MakeShutdownCh
	/root/mxc/test.go:63 +0xad
exit status 2

**Comment by tgulacsi** [comment]
Are you sure it has anything to do with godror? I don't see it's trace in the panic trace.
But see that it cannot really build a proper traceback...

Is this environment correct? Does Go's tests (all.bash) pass?

 Alpine is known to cause problems: see #30 and https://github.com/godror/godror/issues/69#issuecomment-660509201 .
