### ISSUE TITLE
Stored proc with multiple output ref cursor parameter.

### ISSUE THREAD

**Issue by vkarmendra** [godror/godror#97]
Hi there,

I need to call a stored proc having multiple output ref_cursor parameter. Was trying to find any code but had no luck. Is there any sample code that can point me in the right direction. 

I am using below code
```
var refCursor1 interface{}
var refCursor2 interface{}
var refCursor3 interface{}
	

query := `
  BEGIN
    Package.StoredProcA(123, :1, :2,:3);
  END;
 `
_, err = db.ExecContext(ctx, query, sql.Out{Dest: &refCursor1}, sql.Out{Dest: &refCursor2}, sql.Out{Dest: &refCursor3})
	
if err != nil {
	fmt.Println("Error running query")
	fmt.Println(err)
	return
}
```

But I am getting below error

dpiStmt_execute(mode=32 arrLen=-1): ORA-06550: line 3, column 5:
PLS-00306: wrong number or types of arguments in call to 'StoredProcA'

**Comment by tgulacsi** [comment]
See TestSelectRefCursor or TestSelectRefCursorWrap in z_test.go
